### ISSUE TITLE
Implement assets cache versioning system 

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/thirtybees#1002]
Thirtybees comes with multiple assets (javascript, css, font,... files). These are cached by browser, or any other intermediate caching systems (cloudflare). 

At the moment, asset urls don't contain any version control parameters (?v=whatever), which makes it very hard to release new version of the assets. Merchants usually encounter weird problems like this one: https://forum.thirtybees.com/topic/3326-editing-products/

We should come up with some fool-proof system to tackle this problem. The assets should contain some unique identifier that forces browser (or intermediate caches) to invalidate when the content change. We could use

1. md5 of the asset file. This would be most precise. But it would put additional pressure on server, as files md5 checksum would have to be calculated with every request
2. unique identifier or release. For example, git commit hash. Every release would have different commit, so every release would force invalidation of *all* resources. Also, this does not put any additional stress on server, as release identifier is constant
3. thirtybees version -- this would work similarly to #2. But it would not work properly for switching between bleeding edge commits

**Comment by Dh42** [comment]
What about the date? Like if the core updater just stored epoch time of the last run to the config table, then used that on these assets.

**Comment by Traumflug** [comment]
CCC does something like this already, so this looks like a good strategy: https://forum.thirtybees.com/topic/3326-editing-products/?do=findComment&comment=29457

**Comment by getdatakick** [comment]
I don't think CCC should be used in back office. In my experience CCC technology can very easily generate invalid javascript bundles. 

I have seen modules that contained bad javascript file with unclosed string, missing ending curly braces, or with unclosed comment. When such js file was included into CCC bundle, result was invalid javascript file, and non-functioning font-end site.

Obviously, this is the problem with individual module, and the easy fix is to uninstall such module. That might not be possible if we use CCC in the back office, though. Back office could be throwing thousands of javascript errors all over the place, rendering the whole administration unusable.
