### ISSUE TITLE
Configuration Information under Windows incorrect

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/thirtybees#1004]
When I choose Advanced Settings->Configuration Information under Windows I get a lot more files listed:
 - Under Updated Files I find all the subdirectories of Admin
 - Under Obsolete Files I find about everything. The picture below shows 3416 obsolete files. After I uploaded the shop to a Linux server that number changed to 82.

![adma](https://user-images.githubusercontent.com/13930107/62024961-fd29bf00-b1d6-11e9-8f65-5a05339afb0a.jpg)

**Comment by yaniv14** [comment]
TB is officially not supporting Windows, so I am doubt if this commit will be taken care of.
I'm sure that if you can come up with a proper fix it will be merged.

**Comment by Zengraph** [comment]
Windows server is really usefull, I like to install things locally on Wamp Server for exemple, so I understand your concern, there are few fixes that can help fix that on AdminInformationController, going to post them.

**Comment by Traumflug** [comment]
As long as such adjustments get provided and don't hobble operations on Linux they usually get accepted. Picked both of them to 1.1.x after fixing syntax errors.
