### ISSUE TITLE
TLS v1.2 check doesn't work anymore

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/thirtybees#1007]
[ConfigurationTest::testTlsv12](https://github.com/thirtybees/thirtybees/blob/e236ccfe7e4761803b88adbded7ce30a6e25c873/classes/ConfigurationTest.php#L324) uses `tlstest.paypal.com` to test if server supports tls1.2. It looks like this endpoint doesn't exists anymore, so the check returns false negative.

We could either find different service that checks tls version, or get rid of this check completely.

**Comment by Zengraph** [comment]
Here is a working code for that : 

```
    /**
     * @return 'ok' or nothing;
     *
     * @since 1.0.0
     */
    public static function testTlsv12()
    {
        $url = 'https://fancyssl.hboeck.de/';
	$protocol = 'CURL_SSLVERSION_TLSv1_2';

	$ch = curl_init();
	curl_setopt($ch, CURLOPT_URL, $url);
	curl_setopt($ch, CURLOPT_SSLVERSION, $protocol);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);	
	$response = curl_exec($ch) !== false;
	if ($response) return('ok');
    }
```

**Comment by Zengraph** [comment]
#1008

**Comment by Traumflug** [comment]
See comments to #1008, IMHO not an ideal solution.

For a better solution I sent a POST request to _api.paypal.com_. Without authentication one gets rejected, of course, but getting such a rejection already proves a working TLS v1.2. Demo on the command line:
```none
$ curl --tls-max 1.1 -X POST https://api.paypal.com/v1/oauth2/token 
curl: (35) error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure

$ curl -X POST https://api.paypal.com/v1/oauth2/token 
{"name":"AUTHENTICATION_FAILURE", ...
```
Accordingly I implemented this in PHP, but ... there it's hard to test, because PHP's cURL apparently tries the highest available TLS version, even if requested to not do so. See https://stackoverflow.com/questions/57297524/php-curl-enforce-low-tls-version

**Comment by Zengraph** [comment]
OK, what about this kind of solution that use SSLABS API for a proper server testing. 

https://github.com/bjoernr-de/php-ssllabs-api
https://github.com/andyftw/ssllabs-php

that might be a good solid and reliable way of testing TLS and SSL ?

**Comment by Traumflug** [comment]
This question on Stackoverflow turned out to be a lack of PHP's documentation, so I came up with bed542f211f6e5d6e41f3988e840cfc76ec1f565. Let's cross fingers PayPal doesn't block shops for an occasional unauthenticated request coming in.

What do you think?

**Comment by getdatakick** [comment]
Looks good. 

To be frank, I'm not sure if this check needs to be implemented at all. PCI DSS requirements stated that all payment systems must disable early TLS by 2018. PayPal disabled it on June 30, 2017, that's two years ago... I mean, are there really some production servers that don't support   TLS 1.2 in 2019? 

Maybe we should deprecate this check, and don't rely on any third-party services

**Comment by Zengraph** [comment]
I also think it's not needed anymore. It up to the sysop to manage that.
And it's not only about TLS 1.2 support, it should check if TLS 1.1 is disabled, SSL1, SSL2..etc.. and all cypher apache conf.. and now if TLS 1.3 is usable or not, etc... Let's manage that outside TB info page, just give the link for SSLLabs instead.

**Comment by Traumflug** [comment]
I have to admit I feel better with keeping such a test as I've seen quite old hosting, not even providing PHP 5.6 in 2019. The whole point of this back office page is to identify insufficient server capabilities, after all.
