### ISSUE TITLE
guest to customer email missing password

### ISSUE THREAD

**Issue by smarterweb** [thirtybees/thirtybees#1014]
in 
\mails\en\guest_to_customer.html
and
\mails\en\guest_to_customer.txt

the password is masked as ****** around line 92:
<span style="color:#333"><strong>Password:</strong></span> ******

however this password clearly needs to be visible.
even after changing the orig mails to use {passwd} , the password is still masked.

If one transforms a guest account into a real account, the user should get sent a password that he can then use to log in.Right now he only gets a masked password which is useless.

**Comment by getdatakick** [comment]
Let's track this in issue #1017 1017
