### ISSUE TITLE
Store URL in password mails not working (multistore)

### ISSUE THREAD

**Issue by smarterweb** [thirtybees/thirtybees#1016]
after upgrading to 1.10 all links from password mails won't work any longer.
I can revert back to 1.0.8 and it's all working fine.

instead of the shop URL we see this in the source of the mails: <a href=3D"https://"

and in the "New password" email the shore URL is missing too, so we see this in the source:
https://order-history instead of https://mydomain.com/order-history

**Comment by smarterweb** [comment]
I have just tested this in a Vanilla 1.10 install as well and the problem remains the same.
Here's some of the email source code:

You can review your order=
 and download your invoice from the
"Order history" [https://index.php?co=
ntroller=3Dhistory] section of
your customer account by clicking "My acco=
unt"
[https://index.php?controller=3Dmy-account] on our shop.=20

If yo=
u have a guest account, you can follow your order via the
"Guest Tracking=
"
[https://index.php?controller=3Dguest-tracking?id_order=3D{order_name}]=

section on our shop.=20

My Store [https://index.php] powered by thirt=
y
bees(tm) [https://thirtybees.com/]=20

**Comment by getdatakick** [comment]
Thanks for reporting this. I was able to reproduce and fix the issue
