### ISSUE TITLE
Can't add currencies with numeric ISO code larger than 3 digits

### ISSUE THREAD

**Issue by FreezeS** [thirtybees/thirtybees#1018]
![image](https://user-images.githubusercontent.com/2807003/63003990-10e54e80-be82-11e9-828c-efeb6f6d8dfa.png)

**Comment by getdatakick** [comment]
Metadata for this field in Currency object has indeed size 3, as does `iso_code_num` column in `tb_currency` table:

```sql
CREATE TABLE `tb_currency` (
  `id_currency` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `iso_code` varchar(3) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '0',
  `iso_code_num` varchar(3) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '0',
  `sign` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL,
  `blank` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `format` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `decimals` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `conversion_rate` decimal(13,6) NOT NULL,
  `deleted` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `active` tinyint(1) unsigned NOT NULL DEFAULT '1',
  PRIMARY KEY (`id_currency`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```

The question is, is this wrong? According to this [table](https://en.wikipedia.org/wiki/ISO_4217), all numerical currency codes has only 3 characters. 

You should use numerical code 978 for EUR, not 4217.

**Comment by FreezeS** [comment]
You are correct, ISO 4217 is the standard that describe the currency codes, not the code of Euro.
My mistake was to run a google search and not reading the answers thoroughly:

![image](https://user-images.githubusercontent.com/2807003/63007604-9f110300-be89-11e9-8500-d1354ba575dc.png)

**Comment by getdatakick** [comment]
:) good. I'm closing this one
