### ISSUE TITLE
Smarty error notice

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#1029]
Reported as a hidden comment here: https://github.com/thirtybees/thirtybees/commit/844f9ec4d028d385c90f192c6b14a020165d54b6, along with a fix:

https://github.com/Zengraph/thirtybees/commit/e10a0bca860383b5cecf83aa8a56be8dafc485dd

TODO: This fix might be the right spot, but it looks a bit like just hiding the problem by essentially disabling the conditioned code, not fixing the actual issue.

**Comment by Traumflug** [comment]
This looks like a pull request with the same commit: #1009

**Comment by ksimunovic** [comment]
Related commit with a more dynamic fix [f08ff0c](https://github.com/ksimunovic/thirtybees/commit/f08ff0c651a2b9211a8bba67cbb491e8180762cc)

**Comment by Traumflug** [comment]
Yes, this one looks better. Picked to 1.1.x as 5a29c2447f8b4d29d5f5eaded47bee081b56c062.

Thank you very much!
