### ISSUE TITLE
backoffice translations mostly english

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#1031]
See https://forum.thirtybees.com/topic/3429-backoffice-partially-in-english-after-update-to-110/

> after updating a shop to 1.1.0 parts of the backoffice now only appear in English despite all the expressions are filled in the translations section (and have the translations in there). For example the order page and the translations page itself are only shown in English.

> No fix, but a bypass:
>
>    If bigger than 49 Bytes save file /translations/<yourlanguage>/admin.php
> - Import the English language
> - Go to Employees
> - Change BO language to English and save
> - Change BO language back to your language and save
> - Clear cache and recompile
> - If this does not help, check length of /translations/<yourlanguage>/admin.php
> - If it is now (emptied to) 49 bytes, replace it with the formerly saved file

**Comment by Nobodaddy** [comment]
And please keep in mind while trying to fix this bug: I made the experience that after importing the English language and switching the employee's language to and fro the employee's language _admin.php_ (In this case German) was emptied.

**Comment by Traumflug** [comment]
Excellent work! Picked to 1.1.x as 6910e0159a0a5a62d5576a93b31663c2db706c9d, thank you very much.
