### ISSUE TITLE
Color picker squares disappeared after some time  on product lists

### ISSUE THREAD

**Issue by Websprint** [thirtybees/thirtybees#1033]
In product lists (category pages, best sales, etc.) colors pickers squares disappeared after some time. It happens randomly or after page re-loading, or after visiting into product page and then go back to category.

Colors pickers can disappear in few products in category, or in all together. After clearing cache color pickers appear again but only up to re-load category page. Then - disappearing again. Total disabling cache do not change this behavior. 

This issue we can also see on official demo store on category page -https://front.thirtybees.com/Coffee  - product "Mug" have 3 available colors on product card, but now is not shown as colorpickers on product list. 
Product Tin Cup - the same - https://front.thirtybees.com/tea - same situation.

In fresh installation - same behaviour - colorpickers disappearing randomly after some time and can appear back after cache cleaning.

This issue look like knowing issue PSCSX-6778 in Prestashop. I tried to fix it like in Prestashop but this way do not working in Thirtybees.﻿

Anybody know how to fix this issue?

**Comment by Dh42** [comment]
This should be the fix for this issue as well, https://github.com/thirtybees/thirtybees/issues/861

**Comment by getdatakick** [comment]
No, this is not related to #861. This issue is related to bad usage of smarty cache in `FrontController::addColorsToProductList`

**Comment by Dh42** [comment]
Oh nice, good pickup. I was wrong. from my testing I thought it was an ajax request cached.

**Comment by Websprint** [comment]
[SOLVED] Yes - is bug of front controller of "addColorsToProductList" function. As I see - is continued from fork point. In current version of Prestashop (1.6.1.24) is fixed well. So fastest method to fix this issue - just making override with this function from original Prestashop core.
How to:
1. Create file FrontController.php in /override/classes/controller/ and insert this code in to this file:
`
<?php
class FrontController extends FrontControllerCore
{
	/**
	* Fix Issue #1033 - color pickers on products lists
	* (part of Prestashop 1.6.1.24 code)
	*/
	
    public function addColorsToProductList(&$products)
    {
        if (!is_array($products) || !count($products) || !file_exists(_PS_THEME_DIR_.'product-list-colors.tpl')) {
            return;
        }

        $products_need_cache = array();
        foreach ($products as &$product) {
            if (!$this->isCached(_PS_THEME_DIR_.'product-list-colors.tpl', $this->getColorsListCacheId($product['id_product']))) {
                $products_need_cache[] = (int)$product['id_product'];
            }
        }

        unset($product);

        $colors = false;
        if (count($products_need_cache)) {
            $colors = Product::getAttributesColorList($products_need_cache);
        }

        Tools::enableCache();
        foreach ($products as &$product) {
            $tpl = $this->context->smarty->createTemplate(_PS_THEME_DIR_.'product-list-colors.tpl', $this->getColorsListCacheId($product['id_product']));
            if (isset($colors[$product['id_product']])) {
                $tpl->assign(array(
                    'id_product'  => $product['id_product'],
                    'colors_list' => $colors[$product['id_product']],
                    'link'        => Context::getContext()->link,
                    'img_col_dir' => _THEME_COL_DIR_,
                    'col_img_dir' => _PS_COL_IMG_DIR_
                ));
            }

            if (!in_array($product['id_product'], $products_need_cache) || isset($colors[$product['id_product']])) {
                $product['color_list'] = $tpl->fetch(_PS_THEME_DIR_.'product-list-colors.tpl', $this->getColorsListCacheId($product['id_product']));
            } else {
                $product['color_list'] = '';
            }
        }
        Tools::restoreCacheSettings();
    }

}

`
2. Go to /cache/ folder and delete class_index.php file
3. Also I recommend to clear cache in Prestashop asdmin panel

Now is working well. Is a good idea - to fix this function in thirtybees core in next release.

**Comment by mke-tb** [comment]
@Traumflug So do we add this to core?

**Comment by Websprint** [comment]
Yes. Please.

**Comment by Websprint** [comment]
> @Traumflug So do we add this to core?

Yes. Please.

**Comment by getdatakick** [comment]
Note:
In order to reproduce this on `niara` theme, it is necessary to fix `css/product_list.css` first

```diff
 .color-list-container {
-  display: none;
   margin-bottom: 10px;
 }

```
