### ISSUE TITLE
Specific Prices: fixed price not displayed in list

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/thirtybees#1040]
Reported on [forum](https://forum.thirtybees.com/topic/3448-specific-prices-bug/)
Injected by commit 8601c27fbba84d72a1724f253b446c665b988579

-----

I dont know if it's a bug, or I have something else going on, but I seem to have an issue with my Specific Prices.   I have a 1.1.0 live site, then I have other copies of it I test with.  Well in 1.0.8 my Specific Prices for this particular product looks like the 108.png file below, and my 1.1.0 site is the other pic.  Notice on the Fixed Price line, the info is missing on the 1.1.0 site, but on the 1.0.8 site it shows.  Also, if I use the core updater on my 1.1.0 site, and bring it back to 1.0.8, when I goto the Prices tab on the product, the tb's busy dealie on the upper left of the screen, will just spin, not letting me into the Prices tab at all.  It looks like this with all my products like that one below, not just this one product....

**1.0.8**
![1](https://forum.thirtybees.com/uploads/monthly_2019_09/108.thumb.PNG.6dae1a2da1cf886ff2ac217ba23fc0d2.PNG)

**1.1.0**
![2](https://forum.thirtybees.com/uploads/monthly_2019_09/110.thumb.PNG.2d7f070d1335cb92e231d954038e9a70.PNG)

**Comment by Traumflug** [comment]
Should be fixed by applying pull request #1041. Thank you!
