### ISSUE TITLE
Product variant radio buttons don't work in Niara

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#1047]
See https://forum.thirtybees.com/topic/3449-artikelvarianten-optionsfelder/ (German)

Demo see https://steine.a2hosted.com/demo/de/coffee-and-tea/tea/tea-cans#/13-flavor-turning_leaf. It works in the old theme: https://steine.a2hosted.com/demotbacht/coffee-and-tea/tea/tea-cans

As this demo probably goes away before too long, it's about these radios:

![grafik](https://user-images.githubusercontent.com/318581/64412259-49e29e80-d08f-11e9-9b67-af47cf5a9290.png)

Old theme:
![grafik](https://user-images.githubusercontent.com/318581/64412310-6aaaf400-d08f-11e9-9941-a0eb9d24b016.png)

In the old theme it works, but one has to click the small radio directly. Clicking label text isn't sufficient ... which probably explains why it doesn't work with the hidden radio button in Niara.

**Comment by ksimunovic** [comment]
@Traumflug In new theme radios are completely hidden as you said and radio circle is done through CSS and ::before on .label-text. This made it easier to make the whole thing clickable, radio and label, and I also added curser:pointer to make it more clear for users.

**Comment by Zengraph** [comment]
Just gave you another way of fixing that, without need of more JS script; hope you'll like it
