### ISSUE TITLE
Minor issue with Invalid Characters in Back Office Product "Name" field

### ISSUE THREAD

**Issue by techjp** [thirtybees/thirtybees#1048]
In the back office when creating a new product, hovering over the "Name" field brings up this text:

![image](https://user-images.githubusercontent.com/7457115/64562880-ec00d000-d388-11e9-902d-7e5032f1fb03.png)

"The public name for this product. Invalid characters < > ; = # { }"

This is the same text that was displayed in PS and earlier version of TB. Thankfully TB now supports # and = characters in product names (thank you!!) but the warning text still shows them as invalid. Other characters are still invalid and are correctly listed.

**Comment by Traumflug** [comment]
Nice catch!

**Comment by Traumflug** [comment]
Fixed with 6358c7842e5463b2e9ad4575d48bb38ac8f385a5. Thanks for the report!
