### ISSUE TITLE
Remove customer id from page cache key

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/thirtybees#1049]
Because FPC is now completely bypassed for logged in customers, customer id is not needed to be part of key dimensions.

Related to issue #295

**Comment by Traumflug** [comment]
We can just as well remove this bypass again. Branch _issue-295_ was open for testing for a while, apparently nobody noticed it being pointless.

**Comment by Traumflug** [comment]
If I follow history, I see this:

- July 2017: a user noticed Full Page Cache (FPC) to work not correctly for logged in users and reported it as #295.
- September 2018: @getdatakick committed a customer key for FPC with f6ec4bd997af7ca042142d131b95f63d4b38f859 and solved the problem this way. However, #295 remained open.
- September 2019: @mke-tb found issue #295 open and implemented the suggestion there. Neither him nor me were aware of it already being fixed.

Is this correct? Then I'd suggest reverting this recent "fix" for #295 and keeping #295 closed.

**Comment by getdatakick** [comment]
Not sure. With customer being part of the key dimension the number of cache entries is much higher. And most of these entries will probably expire, because how often the customer looks at the same page, right?

So maybe it would be a good thing to have this removed.

**Comment by Traumflug** [comment]
Sounds plausible.

**Comment by mke-tb** [comment]
So we don't revert #295 but revert f6ec4bd?
