### ISSUE TITLE
Missing new category in Associations

### ISSUE THREAD

**Issue by MockoB** [thirtybees/thirtybees#105]
When creating new category and than new product, the new created category is not in the category tree in Associations. It could be found and appears in the tree after search and hit in the search field for it.

**Comment by Traumflug** [comment]
Hmm. Can't reproduce this with 1.0.1-beta.2. The only thing I can see is that when creating a new product, categories on the association page are initially collapsed. Not expanded like when viewing an existing product. Expanding this shows all categories as expected, even ones created just a minute before.

@MockoB, can you still reproduce this?

**Comment by MockoB** [comment]
I just tried it on beta 1 and can't reproduce it anymore.
And one question, am I the only one who can close the issue? Because the other one I opened about the new top menu needs to be closed also.

**Comment by firstred** [comment]
Nope, we can close them, too.

**Comment by MockoB** [comment]
Thanks!
