### ISSUE TITLE
Adding product to order in BO is broken

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/thirtybees#1050]
It's no more possible to add a product to an order in BO. I get the following console error:

```
Uncaught ReferenceError: priceDatabasePrecision is not defined
    at displayPriceValue (admin.js?v=1.1.0-1.1.x:1393)
    at HTMLInputElement.<anonymous> (orders.js:430)
    at HTMLInputElement.dispatch (jquery-1.11.0.min.js:3)
    at HTMLInputElement.r.handle (jquery-1.11.0.min.js:3)
    at Object.trigger (jquery-1.11.0.min.js:3)
    at Object.e.event.trigger (jquery-migrate-1.2.1.min.js:2)
    at HTMLInputElement.<anonymous> (jquery-1.11.0.min.js:3)
    at Function.each (jquery-1.11.0.min.js:2)
    at e.fn.init.each (jquery-1.11.0.min.js:2)
    at e.fn.init.trigger (jquery-1.11.0.min.js:3)
```

Strangely I get this error also when I downgrade to an older tb version. But it was working in older versions :S

**Comment by Zengraph** [comment]
I just test to add a product in BO on an old order (on a fresh TB 1.1.0 installation on wamp) and  it works, no error shown.
What is your procedure for that and did you try it on a fresh install ? if not please give us more details to track this bug.
thank you :)

**Comment by Traumflug** [comment]
Some custom template involved, perhaps? It should get defined here: https://github.com/thirtybees/thirtybees/blob/1.1.x/admin-dev/themes/default/template/controllers/orders/form.tpl#L46

A couple of other templates have a likewise definition, try `grep -rn priceDatabasePrecision admin-dev/`

**Comment by Traumflug** [comment]
P.S.: as templates are involved, don't forget to clear the cache after an update/downdate.

**Comment by eschiendorfer** [comment]
Thanks for your help. I could solve the issue. Ofc @Traumflug was right. It was an override. But not the one you mentioned. It was https://github.com/thirtybees/thirtybees/commits/1.1.x/admin-dev/themes/default/template/controllers/orders/helpers/view/view.tpl. 

As I need to use a few overrides. I wonder, if it's possible to implement an override feature in the core updater? Obviously every merchant/dev need to handle is override personally. But would it be possible to show a warning, if an overriden file was changed in the core?

Example I update from 1.0.8 to 1.1.0. It says: "Warning: you override orders/helpers/view/view.tpl this file has been changed in this update".
