### ISSUE TITLE
Inactive "Save" buttons for product quantity (only multistore).

### ISSUE THREAD

**Issue by e-com-presta** [thirtybees/thirtybees#1051]
Thirty Bees version: 1.1.0
Server information: FreeBSD 11.2-RELEASE-p4 #7: Wed Nov 14 21:16:41 CET 2018
Server software version: Apache/N-G-I-N-X-htaccess-support
PHP version: 7.3.5
Memory limit: 512M
Max execution time: 300 
MySQL version: 5.7.21-20-log

Javascript error: "TypeError: this.current_request.complete is not a function" in file: /js/admin/products.js

This error occurs only in the multistore option, in the single store save buttons are active.

![Zaznaczenie_009](https://user-images.githubusercontent.com/20421361/64668290-5e42e480-d45d-11e9-8eed-22011755b30f.png)

**Comment by Zengraph** [comment]
I do use 1.1.0 on a live store upgraded from ps 1.6 in a multishop context, and the buttons work good.. do you have any override maybe on your install ?

**Comment by ksimunovic** [comment]
This is fixed with commits: [5394781](https://github.com/ksimunovic/thirtybees/commit/5394781376e23b3cec919b6ebcd3dc8ae5664d83) and [f2edc90](https://github.com/ksimunovic/thirtybees/commit/f2edc90ee7bc2780aa2d9675446d379ceb041a63)

**Comment by Zengraph** [comment]
Excellent, thank you ksimunovic

**Comment by Traumflug** [comment]
Thanks. Picked to _1.1.x_.

@e-com-presta, in case it doesn't work for you, please don't hesitate to re-open this issue.
