### ISSUE TITLE
Filemanager

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/thirtybees#1055]
Below the Admin directory you find the directory Filemanager.

Filemanager is an external plugin to TinyMCE. The original can be found here (https://github.com/Tsubashi/TinyMCE-FileManager). The inclusion happens in /js/admin/tinymce.inc.js where you find the following code 
`external_plugins: { "filemanager": ad + "/filemanager/plugin.min.js" },`

Filemanager adds a file browser to a.o. the image window. See image:
![selector](https://user-images.githubusercontent.com/13930107/64917807-b26b0300-d794-11e9-8c42-1cc2cfc8f951.jpg)

It looks like Michael thought that Filemanager was part of the Prestashop code. As a consequence he added a Prestashop/Thirty Bees copyright notice to each of its php files. Such notices are not present in Prestashop and  should be removed.

**Comment by Traumflug** [comment]
These copyright notices are likely a result of some sed script. Michael wasn't exactly the type of person opening 1000+ files and editing each manually.

That said, moving such external libraries into Composer or NPM dependencies would be likely the best solution for this.

**Comment by Traumflug** [comment]
Removed these copyright notices anyways, claiming copyright on vendor files isn't nice. Should be solved with e15fcbdc67bd34a20974422498e5cd9075466855.

Thanks for the hint!
