### ISSUE TITLE
Length problems with ip_registration_newsletter

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/thirtybees#1056]
Since using 1.1.0 I have had two complaints, that customers can not add orders to my shop. As you know: customers can never be precise about their report. It's just like: "I didn't work.".

I couldn't reproduce it myself, but I am quite sure, that it's about ip_registration_newsletter value, which is fixed to the size of 15: https://github.com/thirtybees/thirtybees/blob/1.1.x/classes/Customer.php#L63

If sombody has a longer IP address (maybe IPv6), it fails: Property Customer->ip_registration_newsletter length (39) must be between 0 and 15

**Comment by getdatakick** [comment]
This problem is not in 1.1.0 but in 1.1.x. 

In 1.1.0 the ipv6 address is silently truncated during save. In 1.1.x error is displayed instead of truncating value.

The fix is to simply change definition to `'size'=>39`

**Comment by eschiendorfer** [comment]
Ok thanks a lot. You are right about 1.1.x Is it save to just make 39 or can there appear even bigger lengths?

**Comment by getdatakick** [comment]
An IPv6 address, at its longest, would be 8 sets of 4 characters (32 total), each set separated by a colon. That makes 39 characters.

**Comment by eschiendorfer** [comment]
Thanks for explanation. I have now created a new branch and a PR :)

**Comment by Traumflug** [comment]
This should be fixed with e0f00a0011db33acb195b361e584236de5bbf872.
