### ISSUE TITLE
Danish alphabet special characters (ÆØÅ) does not get ordered correctly in Manufacturers and Suppliers page

### ISSUE THREAD

**Issue by bullmade** [thirtybees/thirtybees#1061]
If a manufacturer or a supplier has a name that starts with Æ, Ø or Å, they do not get sorted alphabetically. 

https://en.wikipedia.org/wiki/Danish_and_Norwegian_alphabet

They are supposed to be ordered after Z in the following order:
Æ
Ø
Å

They are part of DS 2089 and ISO 646 coding standards.

**Comment by getdatakick** [comment]
Database collation issue. Use core updater to migrate all database tables to correct encoding
