### ISSUE TITLE
AdminProductsController Add webp support 

### ISSUE THREAD

**Issue by Pierrox15** [thirtybees/thirtybees#1062]
Hello,

The webp support is missing when adding product img

https://github.com/thirtybees/thirtybees/blob/fd48f9e91cb4ed617a08ab284abafa1ab3ce0232/controllers/admin/AdminProductsController.php#L4825

is it possible to use CopyImage function into the  ajaxProcessAddProductImage?

I'm not a pro bu the code seem a bit duplicate for many ajax Process.

**Comment by Traumflug** [comment]
Duplicate code for regular and Ajax requests isn't much of a surprise, this usually exists for historical reasons.

**Comment by Traumflug** [comment]
I've picked this pull request of yours to branch _issue-1062_, which should appear in a couple of minutes in Core Updater. It'd be nice if you could confirm it still works for you as well.

Nice work, BTW.

**Comment by Traumflug** [comment]
Nah, didn't mean to close this ... yet.

**Comment by Pierrox15** [comment]
Nice Thx, I will test.
I think I found a new issue in admin-dev/index.php?controller=AdminImages.
HighDpi Images seem not been generated when Regenerate thumbnails.
It appear on a fresh tb11x install. I will go on forum to have more feedback

**Comment by Traumflug** [comment]
Assuming this works for everybody. If not, please don't hesitate to re-open this issue. Moved these four commits to 1.1.x.

Regarding the 'new issue' (distinct issues should go into another Github issue anyways), see #129.

**Comment by Pierrox15** [comment]
No time to test this week, I will test this soon.
