### ISSUE TITLE
Monaco Postcodes

### ISSUE THREAD

**Issue by graphskill** [thirtybees/thirtybees#1065]
Not sure if this is actually in 30bees fresh install or not as we migrated from Prestashop and I have not checked the 30bees raw files

Monaco postcodes have the format of 980NN
This works for most but for some reason does not work for 98000
changing the format to NNNNN works fine

**Comment by Traumflug** [comment]
Maybe there's some room for improvement, but NNNNN is the supported format. Also supporting a number of fixed digits would be an enhancement.

**Comment by Traumflug** [comment]
BTW., I looked up the validation function (`Country->checkZipCode()`), fixed digits are indeed supported. Wasn't aware of this.

Lo and behold, a format of _980NN_, actually the default format, works fine as well:

![grafik](https://user-images.githubusercontent.com/318581/65771499-9bcf8f00-e138-11e9-981d-431fa77fa833.png)

Apparently there's a distinction between your and my setup, so we have to find out what this distinction is. Which version of thirty bees are you running?

**Comment by graphskill** [comment]
We are still on 1.08 merged from Prestashop 1.6. I dare not upgrade to 1.10 yet as everything is working very sweetly at the moment :)

**Comment by Traumflug** [comment]
Doesn't look like here's a need to fix something. In case this can be reproduced on 1.1.0, please don't hesitate to re-open this issue.
