### ISSUE TITLE
Can't open products after some time

### ISSUE THREAD

**Issue by MockoB** [thirtybees/ThirtyBees#107]
After some time usage I can't open products. Those which are associated with some categories redirect me at home page. And products which are associated on home page just shows me that the page is not available. I saw that the link of that product associated with homepage is mysite.com//productname here is screenshot [http://i63.tinypic.com/24ow0f9.jpg](url)
I tried clearing cache, restart all services on WAMP but nothing changes.

**Comment by MockoB** [comment]
Just saw that the last added product shows that the page is not available and all others no matter which category they are associated with redirect me at homepage.

**Comment by firstred** [comment]
Caused by URL clearing in pre-beta-3 versions. Therefore closed.
