### ISSUE TITLE
Debugging Ajax

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/thirtybees#1071]
Ajax errors are notoriously hard to solve. The user gets at best a some message about a JqHxr error what is of course useless.

I believe such errors could be made easier to handle by creating the option to log those errors. That would be another menu option in the backoffice.

When an ajax error happens the following should happen:
 - the code that handles the return values of the ajax call makes another call to another file. Lets call it LogJqhrError.php
 - the call gets three arguments: which ajax call it was, the arguments that went with the call and the complete returned data.
 - LogJqhrError.php stores these returned values in a file under the log directory of the shop. As in some circumstances the size of the returned data can be quite big a separate file will be created for each incident.
 - optionally the backoffice could contain a page where you could access and delete those logfiles.

**Comment by Traumflug** [comment]
Ajax errors happen in the browser, so PHP can't do much about it, unless the browser would send another Ajax request for logging the error. In case PHP is already aware of an error before returning the request, it also logs errors already, just like any other PHP failure.

For debugging Ajax errors, most browsers have a developer console. These feature pretty much all you want here, except writing a log file.

**Comment by Traumflug** [comment]
I think we can close this, because there is no technical solution possible.

**Comment by musicpanda** [comment]
I proposed a technical solution - but you don't want it. That is something a bit different than "not possible".

The developer console is for experts. Finding the PHP error log often takes quite some effort - not to mention that the person may be looking in the wrong log file. What I propose is understandable for non-programmers and could improve the error reports on the forum. In addition the proposed log file would include the calling parameters - what the PHP error log is missing.

Yes, it takes another Ajax call. But one that doesn't need an answer and that can only go wrong when a file is missing or the log directory is not writable.
