### ISSUE TITLE
installationCheck() in OrderReturnState fails with DebugMode

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/thirtybees#1072]
OrderReturnState class has a method called installationCheck(). It checks, if there is an 'active' column. When it's missing, it should be created. 

But this won't work when you are in debug mode. Then you will see an exceptional error:
![debug-mode](https://user-images.githubusercontent.com/15154932/66411892-c8b35a00-e9f4-11e9-9e68-89c518831299.JPG)

**Comment by Traumflug** [comment]
There was a very similar issue recently, if not the same. I just can't find it anymore ...

**Comment by eschiendorfer** [comment]
I dont know about that. But tbh: I haven't searched long, if there is already a bug report on this.

**Comment by ksimunovic** [comment]
Could thirtybees/psonesixmigrator#23 be the one?

**Comment by Traumflug** [comment]
Searching another time I think I had this one in mind, in the forum: https://forum.thirtybees.com/topic/3335-x 

Good to have this issue here now, here it doesn't get forgotten after a while.

**Comment by Traumflug** [comment]
Steps to reproduce:
- Turn on debug mode.
- Delete column `active` in table `PREFIX_order_state`.
- List orders in back office.

This gives an exception similar to the above. Same applies to table `PREFIX_order_state_return`, trigger unknown here.

**Comment by Traumflug** [comment]
This should do it and works for me: 317895ff858ae3bc67fbf3386e8b90aa1ce0a76f

Available in a couple of minutes in Core Updater -> Bleeding Edge as _issue-1072_.

**Comment by getdatakick** [comment]
I'm afraid this fix will not work in production mode. Invalid queries throw exception only in DEBUG mode.

**Comment by getdatakick** [comment]
BTW, this is another candidate for unification. I think exception should be thrown even in production mode. Otherwise, it's just *error masking*

**Comment by Traumflug** [comment]
Fix of the fix: cdfa069be29879a2708f28418d1dcdea7aae8547
