### ISSUE TITLE
Partial refunds don't work/calculate incorrectly

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#1077]
See https://forum.thirtybees.com/topic/3428-x

> I have an order which has already been refunded. The partial refund of the products worked but the shop manager forgot to put in the value for the shipping costs I suppose. If we now want to do partial refund again (1 product in the order already completely refunded) and only put in the value in the shipping field and try to save it, we always get the error "The partial refund data is incorrect.". 

> Installed TB 1.1.0 with demo data and tried to refund the first demo order.
>
> Also added a new order manually, set it to payment received and tried to refund all products and shipping via partial refund
>
> -> refunded product and shipping prices get rounded down
> -> prices and taxes on order slip are not congruent

**Comment by getdatakick** [comment]
Not reproducible.
