### ISSUE TITLE
Admin menu: display default language name if translation is missing

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/thirtybees#1081]
### Enhancement request

If translation for back office menu item is missing, thirtybees displays controller name. This missing translation can happen easily, for example when new language is added or when language was marked as inactive during module installation. I suggest we display menu item in shop primary language instead

![image](https://user-images.githubusercontent.com/34651851/67265025-fa282d00-f4ac-11e9-8fe2-ec4bb74033e3.png)

![image](https://user-images.githubusercontent.com/34651851/67265186-6c990d00-f4ad-11e9-929f-945b4535f5b2.png)

**Comment by Traumflug** [comment]
Looks like an issue similar to #928.

- coalesce is a SQL function, so it should be uppercase.
- Preferable would be to use the translation always and drop name stored in the database.

**Comment by getdatakick** [comment]
All right, I've fixed the uppercase for COALESCE.
