### ISSUE TITLE
BO page not translated.

### ISSUE THREAD

**Issue by SLiCK-303** [thirtybees/thirtybees#1085]
This is from a conversation I was having with Led24ee on the forums.....

Ok. Try this.

Go to translation page (Localization - Translations), choose Type of translation -> Back office translations (Theme tab must be gone after this), language -> English and press Modify button. Now find tab ADMINTRANSLATIONS, expand this, find sentence " Here you can modify translations for every line of text inside thirty bees. " and change this . You can put there some letter in the end or in beginning, but please remember how this must be look. Now scroll to the end of this tab (ADMINTRANSLATIONS) and press Save. (The "funny" (actually it is very depressive)  thing is that in PS there wasn't any difference which Save button was pressed on page, the whole page was included. Now is included only this section which Save button You pressed, other sections are just ignored. This is only not with translation, but everywhere.)

This changed text must appear right there, this blue text which has header MODIFY TRANSLATIONS. 

Thank You

this is english
![tb-en](https://user-images.githubusercontent.com/763426/67634894-35e93b00-f88f-11e9-810f-325162fec22c.PNG)

this is spanish
![tb-es](https://user-images.githubusercontent.com/763426/67634898-400b3980-f88f-11e9-8fe9-53298c7061f7.PNG)

notice most of the text, especially the stuff in blue, but really most of this page, is not translated.

**Comment by SLiCK-303** [comment]
The translations are available in the BO, but they dont seem to be working

**Comment by getdatakick** [comment]
I can't reproduce this. For me, the translated text changed immediately:

![image](https://user-images.githubusercontent.com/34651851/67635378-a3fd2480-f8c6-11e9-804a-a279d1d1ce33.png)

Maybe caching issue? What is your cache settings?

**Comment by getdatakick** [comment]
I was able to reproduce this issue in 1.1.0. But it seems to be solved in 1.1.x

That's a good news. Wait for the next release, or upgrade to bleeding edge

**Comment by SLiCK-303** [comment]
I cleared my sites cache, cleared my browser cache, and still had the same problem.  I tested this on 1.1.x bleeding edge

**Comment by SLiCK-303** [comment]
yup, works on bleeding edge.....sorry i thought my test site was on bleeding edge, i was wrong....

**Comment by ilyasovivan** [comment]
I dont understand. How to fix it? I have the same issure.

**Comment by getdatakick** [comment]
> I dont understand. How to fix it? I have the same issure.

It's already fixed. Forward your tb to bleeding edge.
