### ISSUE TITLE
Blog widget modules installed twice

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/thirtybees#1087]
For some reason, blog widgets modules are installed twice during system installation:

```
mysql> select name, count(1) from tb_module group by name having count(1) > 1;
+-------------------------+----------+
| name                    | count(1) |
+-------------------------+----------+
| beesblogcategories      |        2 |
| beesblogpopularposts    |        2 |
| beesblogrecentposts     |        2 |
| beesblogrelatedproducts |        2 |
+-------------------------+----------+
4 rows in set (0.00 sec)
```

This is probably releated to the [hack](https://github.com/thirtybees/beesblog/blob/master/widgets/autoload.php) used to synchronize `/modules/beesblog/widget` subfolder into `/modules` directory.

**Comment by getdatakick** [comment]
related to this [forum thread](https://forum.thirtybees.com/topic/3624-duplicate-blog-settings-in-groups/?tab=comments#comment-31820)

**Comment by Traumflug** [comment]
This whole idea of one module installing kind of children modules is IHMO pretty borked. Michael once told me the reason for this strategy, but I forgot what it was. Something like having independent sets of hooks.

Having distinguished modules would likely be a better idea. On installation, parent modules can check whether required children are already installed.

**Comment by getdatakick** [comment]
Totally agree, these *widgets* should really be implemented as standalone modules.
