### ISSUE TITLE
Advanced settings

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#1091]
In Preferences => Themes the "Advanced settings" appear in three places LOGO, INVOICE & EMAIL LOGOS and ICONS. 

I think the "Advanced settings" shouldn’t be in three places but maybe one folder beside the folder LOGO, INVOICE & EMAIL LOGOS and ICONS.

**Comment by SLiCK-303** [comment]
It does not actually show in all those places, it shows in one place, beside the theme you are using.  You are just seeing that part of the setup, below those other tabs

**Comment by getdatakick** [comment]
As @SLiCK-303 wrote -- advanced settings button is outside of the top tabs
