### ISSUE TITLE
Theme Configurator

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#1093]
Modules and Services => Theme Configurator => Configure

If Enable we can configure and the theme Niara display:
![image](https://user-images.githubusercontent.com/38436949/68165362-2769e600-ff57-11e9-8bf6-7d447ea4fa6b.png)

If Disable we can configure and the theme Niara display:
![image](https://user-images.githubusercontent.com/38436949/68165406-3fda0080-ff57-11e9-9895-e34d681400bb.png)

When we configure the “Theme Configurator” we have the second folder “THEME CONFIGURATOR (V.3.0.9)” who is different for configuration in “Enable” and “Disable”.

If Enable:
![image](https://user-images.githubusercontent.com/38436949/68165439-61d38300-ff57-11e9-9fc6-d4906588137c.png)

If Disable:
![image](https://user-images.githubusercontent.com/38436949/68165454-67c96400-ff57-11e9-9a89-6b0b3a2181ab.png)

**Comment by getdatakick** [comment]
Please clarify what does it mean

>When we configure the “Theme Configurator” we have the second folder “THEME CONFIGURATOR (V.3.0.9)” who is different for configuration in “Enable” and “Disable”.

**Comment by Jorgemgm** [comment]
Check the images:

Theme Configurator Enable
![image](https://user-images.githubusercontent.com/38436949/68214656-c3d2cd80-ffd5-11e9-88a8-59bb531d6b86.png)

Theme Configurator Disable
![image](https://user-images.githubusercontent.com/38436949/68214679-cc2b0880-ffd5-11e9-9ac4-5c7bcd52f443.png)

**Comment by getdatakick** [comment]
This is not how it looks like in vanilla installation.

Based on your other issue you filed recently, I assume you have introduced some bug into your back-office theme.
