### ISSUE TITLE
Debuggability problem

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/thirtybees#1099]
Jquery has the infamous property that it triggers exceptions in the javascript console when nothing is wrong. 

This means for example that when you scroll when the console is open you get such an exception. 

My problem is that you get such an exception also when you move your mouse over the menu in the backoffice. That makes it very hard when selecting a page in the menu gives problems (I had a probably cache related problem where clicking the Modules entry in the menu logged me out). 

This is not a problem in Prestashop (I tested in 1.7.6) so I  hope this situation can be restored in Thirty Bees too.

**Comment by getdatakick** [comment]
I can't reproduce this behavior. Could you please explain more in depth the reprosteps? Also

- what browser do you use
- can you reproduce this on vanilla tb installation, without any additional modules
- please provide some screenshot or copy of an error / exception

**Comment by musicpanda** [comment]
I work in Chrome. I tested it on a freshly installed Bleeding Edge shop and I still see it.
Just open the console when you are in the backoffice. Then move the mouse towards the menu part of the screen.
![upgrade7](https://user-images.githubusercontent.com/13930107/68583444-6d560b00-047d-11ea-9a28-a3b7ea1b4972.jpg)

**Comment by getdatakick** [comment]
I still can't reproduce this. I'm on chrome as well: Version 78.0.3904.97 (Official Build) (64-bit)

Can you copy the exception stack trace, please

**Comment by musicpanda** [comment]
I was on 77. I just updated and got exactly the same version as you have (although you may not be on Windows). The problem still is there.
![upgrade8](https://user-images.githubusercontent.com/13930107/68584910-1fdb9d00-0481-11ea-948d-9a472877679f.jpg)

**Comment by getdatakick** [comment]
I'm sorry, I still can't reproduce. And the stack track don't help at all - it all comes down to 

`admin-theme.js:325` which contains

```
if ($('#footer').is(':visible')) {
```

That's definitely a valid code. So, I guess this is bug in jquery lib itself

**Comment by getdatakick** [comment]
Related to #602

**Comment by musicpanda** [comment]
I remember to have read once that jquery has some bugs that only happen when the console is open. I cannot scroll a page or refresh a page with the console open because of jquery. But I can live with that. In contrast this problem handicaps me.

You may like to see the full message that you see when the mouse is moved over the message under "pause on exception". 
![upgrade9](https://user-images.githubusercontent.com/13930107/68588846-c2e4e480-048a-11ea-9e5e-7385a666192e.jpg)

**Comment by getdatakick** [comment]
@musicpanda are you sure you don't have some browser extension installed that caused this? Because I look into jquery code, and there's a `try {...} catch` block that encapsulates this `webkitMatcherSelector` call. No exception should be reported at all.

Unless you have some extension that do some additional logging, or installs some polyfill, or whatnot.

**Comment by musicpanda** [comment]
I checked for that and I deleted two extensions that I wasn't sure of ever to have installed. But now I have only Ublock - an ad blocker that is disabled for localhost - and some Chrome applications.
Yet the problem remains.
![upgrade10](https://user-images.githubusercontent.com/13930107/68592705-f8420000-0493-11ea-82f0-ff560e3b312b.jpg)

**Comment by musicpanda** [comment]
Solved. It was uBlock - an ad blocker.
