### ISSUE TITLE
Bankwire module refuses line breaks

### ISSUE THREAD

**Issue by Skinperforator** [thirtybees/thirtybees#1106]
If you put in your bank account details in with line breaks, those get deleted after saving and all ends up in one line. When you put in html tags, those get stripped off when you save.

**Comment by getdatakick** [comment]
The fix in bankwire module fixes both issues for this particular case - storing html tags and retaining new lines at the same time. 

However, there is still bug in core regarding new lines disappearance. Tracked in issue #1107
