### ISSUE TITLE
Hard to add free-form fields to a product with stock control

### ISSUE THREAD

**Issue by veganline** [thirtybees/thirtybees#1113]
Enhancement suggestion.

BO>Catalog>Product>[...]>quantities
When out of stock: Deny orders

...applies to all attributes or none for the product; it cannot be limited to some.

BO>Catalog>Product>[...}>customization

...is an exception, almost useful for people with a partly-stock-controlled product, but it requires an extra order button. Otherwise, shopkeepers like me could adapt it easily.

Any custom field that is not stock-controlled like attributes, and on the product.tpl page would be an enhancement. For example a field for leaving a message in the customization text field that already exists in the database and shows on the shopping cart.

**Comment by getdatakick** [comment]
I'm not sure I understand this request. This is what customization is for, isn't it?

**Comment by veganline** [comment]
I just meant that the "save" button to press before the "order" button is unlikely to work for all customers.

One solution would be to allow a product to have a stock-controlled attribute and a not-stock-controlled-attribute.

Another solution would be customization and ordering with the same button

(There is one thirtybees module for customized fields on product pages - I have just bought it but think it does something slightly different. And there is a nemops page on
http://nemops.com/save-prestashop-custom-fields-add-to-cart/#.XdVFlVf7S1v that I am working-through but might not apply to thirtybees.)




![2nd-button-unlikely-to-be-pressed]

(https://user-images.githubusercontent.com/3786599/69247839-0504d900-0ba3-11ea-975d-c64b70650c20.jpg)

**Comment by getdatakick** [comment]
I don't understand how attribute could work without impacting stock. Say we have combinations create by 3 attributes

```
Size = (S, M)
Color = (Black, White)
Custom = (X, Y)
```

These three attributes could generate these combinations:
```
S, Black, X,
S, Black, Y,
S, White, X,
S, White, Y
M, Black, X
M, Black, Y
M, White, X,
M, White, Y
```

We obviously want to keep stock leves for (S, Black), (S, White), (M, Black), (M, White) -- but where should this value be store, in the database? There is no combination (S, Black), there are only (S, Black, X) and (S, Black, Y) 

The only proper solution is to use product customization. This is definitaly what you want. Then only reason you don't like it is the extra button -- but nobody forces you to have it. You can remove it / hide it, and adjust javascript function that is called when you click on 'Add to cart' to first save the customization and only then add product to cart. This is just small theme modification.
