### ISSUE TITLE
Customer message: increase length of user_agent property 

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/thirtybees#1115]
`user_agent` property of `CustomerMessage` has length 128 characters. It's not enough to save all user agents strings. 

For more info, see this [forum thread](https://forum.thirtybees.com/topic/3574-server-error-on-contact-us-submit-need-help/)

**Comment by veganline** [comment]
thanks for workaround on 11.11.2019
https://forum.thirtybees.com/topic/2455-free-theme-niara-thirty-bees-theme/?do=findComment&comment=32114
