### ISSUE TITLE
Dispatcher calls to deprecated function UrlRewrite::reverseLookup()

### ISSUE THREAD

**Issue by twentybugs** [thirtybees/thirtybees#1123]
At around line 977 you will find this:

> 
            if ($routeId === 'product_rule') {
                $url = UrlRewrite::reverseLookup($params['id'], UrlRewrite::ENTITY_PRODUCT, $idLang, $idShop, UrlRewrite::CANONICAL);
            } elseif ($routeId === 'category_rule') {
                $url = UrlRewrite::reverseLookup($params['id'], UrlRewrite::ENTITY_CATEGORY, $idLang, $idShop, UrlRewrite::CANONICAL);
            } elseif ($routeId === 'supplier_rule') {
                $url = UrlRewrite::reverseLookup($params['id'], UrlRewrite::ENTITY_SUPPLIER, $idLang, $idShop, UrlRewrite::CANONICAL);
            } elseif ($routeId === 'manufacturer_rule') {
                $url = UrlRewrite::reverseLookup($params['id'], UrlRewrite::ENTITY_MANUFACTURER, $idLang, $idShop, UrlRewrite::CANONICAL);
            } elseif ($routeId === 'cms_rule') {
                $url = UrlRewrite::reverseLookup($params['id'], UrlRewrite::ENTITY_CMS, $idLang, $idShop, UrlRewrite::CANONICAL);
            } elseif ($routeId === 'cms_category_rule') {
                $url = UrlRewrite::reverseLookup($params['id'], UrlRewrite::ENTITY_CMS_CATEGORY, $idLang, $idShop, UrlRewrite::CANONICAL);
            }

**Comment by getdatakick** [comment]
It does not. There is no mention of UrlRewrite in [Dispatcher](https://github.com/thirtybees/thirtybees/blob/1.1.x/classes/Dispatcher.php) class at all.

Dispatcher class in tbupdater module call this function, but this module is going to be removed soon anyway. No need for any action
