### ISSUE TITLE
Changed theme installer causes re-activation problem

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/thirtybees#1126]
I recently had to conclude that I couldn't re-activate my Panda theme. Activating it a first time went ok. But when I then activated another theme and went back to Panda my webshop became a white page with only a shop logo.

After a complaint I was told that Thirty Bees had changed the theme installer and I received a new version of the config.xml.

How many other themes will be affected by this change?

**Comment by musicpanda** [comment]
The problem is very easy to reproduce:

 - install TB 1.1
 - install Panda 1.5.2 on it and activate it
 - activate the Niara theme again
 - activate Panda again

When you now look at the front side you see your webshop reduced to just the logo.

I told SunnyToo about the problem and received an modified config.xml from them. They told me the problem was caused by changes in the theme installer. 

I am afraid this will happen with all themes.

**Comment by getdatakick** [comment]
Already fixed in bleeding edge
