### ISSUE TITLE
cache problems

### ISSUE THREAD

**Issue by Rubben1985** [thirtybees/thirtybees#1128]
After updating to 1.1.x it seems there are cache and performance issues.
A cache example would be how VC (aka visual composer) breaks its compatibility when activating cache. 
I recorded a video:
https://www.loom.com/share/d39ec5a60b2541d388e29b2038ea108a

No idea how to debug it... sorry.

Also gtmetrix put a lower punctuation with 1.1.x than 1.0.x

I know this may not help a lot to discover, but I do no know how to give a better description.

**Comment by Rubben1985** [comment]
at, the picture problem it happens with backgrounds only.

**Comment by getdatakick** [comment]
@Rubben1985 maybe this is the same issue as we discussed and fixed on forum? Shall we close this one?

**Comment by Rubben1985** [comment]
It could be, yes. I think I solve this deactivating some cache options but now I do not find it so I am not sure. But if anything arises again, I will post it here
