### ISSUE TITLE
Rewrite issue on the copy of the shop.

### ISSUE THREAD

**Issue by bovario** [thirtybees/thirtybees#1144]
I copied products, attributes, categories and language from the old shop database to new shop database. In BO I can see all the products and pictures but there is a problem with extra-long URL generated by shop.  
The product link will look like this
http://wall-decor.graphics/index.php?controller=product_rule&id=1297&rewrite=%5BREWRITE%5D&ean13=0&meta_keywords=kitchen-backsplashkitchen-sheetkitchen-wall-sticker&meta_title=i-love-coffee-wall-decal-self-adhesive-kitchen-wall-art-stickeri-love-coffee-wall-decal
Route to products: {category:/}{id}-{rewrite}{-:ean13}.html
On the SEO page can see error:
Keyword "{rewrite}" required for route "product_rule" (rule: "")
Keyword "{rewrite}" required for route "category_rule" (rule: "")
Keyword "{selected_filters}" required for route "layered_rule" (rule: "")
Keyword "{rewrite}" required for route "layered_rule" (rule: "")
Keyword "{rewrite}" required for route "supplier_rule" (rule: "")
Keyword "{rewrite}" required for route "manufacturer_rule" (rule: "")
Keyword "{rewrite}" required for route "cms_rule" (rule: "")
Keyword "{rewrite}" required for route "cms_category_rule" (rule: "")
When disable everything in SET UP URLS error disappear.
There is nothing on the front page.
Can you advise, please.

**Comment by getdatakick** [comment]
Do tou have routes defined for all languages?

**Comment by bovario** [comment]
I have 2 languages only, English GB and English US. Not sure what is means routes for all languages, I am not a programmer and if can ask for an answer like for newbie. The error above got somehow fixed but the category links are still broken (for me it is not a normal way to display categories, had only option to display in the module top menu). I would like to have categories displayed like on this page https://www.bargains-zone.co.uk/ where all was copied from.  This website is running on thirty bees 1.0.8 and Leo template (I do not recommend any products from this company, the theme often crashing, support is crap). I am trying to have products copied to new instal as the old shop has many issues and even can't be upgraded as many errors crashing this process. In wall-decor.graphics website could not find home text editor. In back office to any record on the left side, the word Admin is added, and example looks like AdminProducts, AdminCategories etc.
The domain which I am working on is wall-decor.graphics
Help is much appreciated.

**Comment by Zengraph** [comment]
Seems like you solved your problem alone, isn't it ? Please update it here if it's the case.

**Comment by bovario** [comment]
It is not solved, categories not working (broken links). There is no grid categories etc.

**Comment by Zengraph** [comment]
In order to help you on this particular problem, I need to be able to look in the back office, please provide credentials. I think it does not come from TB ... But from the way you set it up and how you did duplicate the shop.

**Comment by bovario** [comment]
https://wall-decor.graphics/admin1
mirokiciak@googlemail.com
PaTrYk.2002

I made a new installation of thirty bees. Copied from bargains-zone.co.uk
(it is my website was running on Prestashop version 1.6.0.9 then changed to
thirty bees).
I was unable to upgrade that shop as always go into the server error but
was able to transfer to TB. Now the layout of the product of the
bargains-zone.co.uk is weird, the text covers other text. In that shop have
many problems and errors during work decided to have clean new installation
free of errors. I copied from bargains website all tables: categories,
products, attributes, lang, then changed prefix from ps to tb.

**Comment by Zengraph** [comment]
OK, first of all there is a problem with root ids of category , to help for that I need acces to the database with phpmyadmin, don't post it on the public message system, send pm.

**Comment by bovario** [comment]
I do not see any way to send you PM. Do you need access to Cpanel (only
this way can phpAdmin be accessed)?

**Comment by Zengraph** [comment]
After having received the infos by mail, I could get into your DB and files system and I have to say that was a long time I didn't see such a mess ! Congrats :) :) 🥇 
I spend few hours to fix it all.. that was not nice... a rip off database and I had to do surgery in a hugly way, but the patient survived and is in a good shape now.. please backup this DB wich is now TB1.1.0 compliant and everything works good again... I wish you good luck  with your shop !! 👍
