### ISSUE TITLE
"An account using this email address has already been registered" preventing purchase where there is only guest orders with that email

### ISSUE THREAD

**Issue by gingerling** [thirtybees/thirtybees#1150]
I am having complaints come in from customers who chose to order (regularly) as guests. They are finding when they come to order again as a guest they get the following error

An account using this email address has already been registered

The only solution I can find is to set them up an account, which many are unhappy about (In the UK and "account" can be associated with credit/store-cards in people of a certain generation)

**Comment by getdatakick** [comment]
This looks like a bug. It should be possible to create guest account even if customer account exists for the same email address.

**Comment by gingerling** [comment]
Hi, is this fixed then? (Also note that in all of the situations, a guest account did not exist, but at the back end in the guest orders it said there is already an account)

**Comment by getdatakick** [comment]
> is this fixed then?
Yes, it should be. 
 
>Also note that in all of the situations, a guest account did not exist, but at the back end in the guest orders it said there is already an account

This message was never related to existing guest account, but to existing customer account with the same email. The reasoning behind this was that once customer account exists it should be used for all purchases...

**Comment by gingerling** [comment]
Yes but the account did NOT exist, there was not account for the two customers who mentioned ir, I double checked. That's my point, sorry if I wasn't clear.

**Comment by getdatakick** [comment]
That would be very strange. The code is very clear here - this error message is thrown only when customer account with the same email already exists.

**Comment by gingerling** [comment]
Iv'e had several instances now of this same issue. I can't make head nor tail of it, it's very odd indeed! Each time they are someone who has placed 5/6 orders as a guest over several years, with no account. I will report here if/when it happens again and can grant some access to my store to examine the issue if you like, or if you like I can give access and you can look at an existing case (however I have made an account for these people as a solution to the issue)
