### ISSUE TITLE
Backoffice order edit - add discount and add product buttons disappear after one edit - back in 1.1.0

### ISSUE THREAD

**Issue by NaturePinks** [thirtybees/thirtybees#1151]
Once an order is edited in backoffice - i.e., a product or discount is added or removed - the 'Add a product' and 'Add a new discount' buttons don't show up anymore.

One has to go back to orders screen and select the order again to open it. The buttons show up again on a fresh opening of the order details screen.

Thirty bees 1.1.0

Was #824 in earlier versions and was fixed.

**Comment by getdatakick** [comment]
Have you checked on bleeding edge?

**Comment by getdatakick** [comment]
I can't reproduce this problem on bleeding edge. Please update to latest version and retest again
