### ISSUE TITLE
All items show price as zero when Bulgarian language is used

### ISSUE THREAD

**Issue by martimarkov** [thirtybees/thirtybees#1157]
On a fresh TB installation if the store is set to be based in Bulgaria (default currency is Lev) and language is selected to be Bulgarian all prices are displayed as 0 in the products listing, cart and checkout. 

I found this on the forum: https://forum.thirtybees.com/topic/2670-bulgarian/

I'll look more into this issue.

**Comment by martimarkov** [comment]
Also, I added Russian to check if it's all Cyrillic languages and it's fine with Russian and the price shows.

**Comment by martimarkov** [comment]
Okay so the bug is in `commerceguys/intl`

The file `resources/number_format/bg.json` has the wrong currency definition for the language:

Original:
```json
{
	"numbering_system": "latn",
	"decimal_pattern": "#,##0.###",
	"percent_pattern": "#,##0%",
	"currency_pattern": "0.00 ¤",
	"accounting_currency_pattern": "0.00 ¤;(0.00 ¤)",
	"decimal_separator": ",",
	"grouping_separator": " "
}
```
Fixed:
```json
{
	"numbering_system": "latn",
	"decimal_pattern": "#,##0.###",
	"percent_pattern": "#,##0%",
	"currency_pattern": "#,##0.00 ¤",
	"accounting_currency_pattern": "#,##0.00 ¤;(#,##0.00 ¤)",
	"decimal_separator": ",",
	"grouping_separator": " "
}
```


I can't see any composer patching system supported in this project so I'm not sure how to push a fix for this?

**Comment by getdatakick** [comment]
This problem is already fixed with by commerceguys/intl/issues/64. 

We should update library dependency to newest version

**Comment by martimarkov** [comment]
I didn't know if upgrading to a more major version of intl will not have breaking changes.

**Comment by getdatakick** [comment]
Of course it needs to be tested. But the dependency on this library is minimal
