### ISSUE TITLE
maintenance mode not shown in some pages

### ISSUE THREAD

**Issue by PeterPano** [thirtybees/thirtybees#1162]
tb Version 1.1.0 

when the shop is in maintenance mode and you go to csv-import or sql-query (and maybe some more), the text in the upper right of the backend, wich says that the shop is in maintenance mode, is not shown. 

Is not a big issue but maybe interesting for getting tb more and more better...

**Comment by toplakd** [comment]
Sigi mentioned in forum, that csv-import or sql-query pages are not showing "maintenance text" if shop is in maintenance mode.

However looking further, there are much more pages missing that text.
Tested on 1.1.0 stable and, latest bleeding edge

Catalog tab: Monitoring, Atributes, Features, Manufacturers
Orders tab: Invoices, Delivery slips, Credit slips,
Modules tab: Positions
Localization tab: Localization, translations
Preferences tab: CMS, 
Advanced tab: Performance, CSV Import, SQL manager,
Administration tab: Permissions
Stats tab: Stats,
