### ISSUE TITLE
Upgrade jQuery

### ISSUE THREAD

**Issue by acs-ferreira** [thirtybees/ThirtyBees#118]
What about upgrading global jQuery (and plugins) versions used?
Actually PS stills on `v1.11.0`.

https://github.com/thirtybees/ThirtyBees/blob/03bd6325a217d84afc2452639d6806fff6e56a34/config/defines.inc.php#L223

**Comment by firstred** [comment]
It will stay like that until we are allowed to upgrade/break compatibility according to SemVer
