### ISSUE TITLE
SMTP username

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#1180]
The SMTP username need be fill with the same email of Shop email.

Advanced Parameters => Email => EMAIL   => SMTP username | Preferences => Store Contacts =>   Shop email
-- | --
  |  
![image](https://user-images.githubusercontent.com/38436949/79691298-95c90900-8256-11ea-9dd2-e56487b0cf55.png)  | ![image](https://user-images.githubusercontent.com/38436949/79691302-9bbeea00-8256-11ea-8f9a-d5fe62c990c7.png)

It’s good idea if we give this information on BO.

![image](https://user-images.githubusercontent.com/38436949/79691315-b729f500-8256-11ea-969a-4c1e77c8c685.png)

**Comment by Dh42** [comment]
I disagree, I cannot think of any mail service other than using your own that uses the mail address for the user name. I just checked my mailgun, it uses a different email address, amazon snes uses api keys not tied to email addresses, and mandrill uses keys as well.

**Comment by Jorgemgm** [comment]
In amazon snes, mailgun and mandril we don´t know. We use IRedMail and Yahoo.

Our experience is:

IRedMail:
SMTP server:	mail. example.com
SMTP username:	example@example.com
SMTP password:	XXXXXX
Encryption:	TLS
Port:		587

YAHOO EMAIL:
SMTP server:	smtp.mail.yahoo.com
SMTP username:	example@yahoo.com
SMTP password:	XXXXXX
Encryption:	TLS
Port:		587

**Comment by romaric33** [comment]
Same as @Dh42 
I am using elasticemail and the smtp account email is not necessarily the sender email, especially since i'm using the same elasticemail account for several domains.
