### ISSUE TITLE
500 server error after switching language

### ISSUE THREAD

**Issue by GrandM1961** [thirtybees/thirtybees#1182]
Hello, I am making a website for a Chinese customer and I have 4 languages installed. Dutch, English, simplified Chinese and traditional Chinese. All the languages work with the exception of the traditional Chinese, it gives me a 500 server error. Although I can change the translation in the backend, I cannot change into it on the frontend.Any suggestions????

**Comment by getdatakick** [comment]
I can't reproduce this problem, on 1.1.x both languages are working correctly.

Please reopen if you still have this error, with more details
