### ISSUE TITLE
MaxMind Geolocation needs update

### ISSUE THREAD

**Issue by Tcoton** [thirtybees/thirtybees#1183]
The module MaxMind Geolocation is not working anymore on new installation since December 2019. 

Please check: https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

The database is not available anymore at the link provided to configure the module and configuring it has become cumbersome.

**Comment by toplakd** [comment]
Since maxmind now offer databases only to registered users the only way currently is to register and download the database on its own and upload it.
Other than that it works just fine once uploaded.

**Comment by Tcoton** [comment]
Maybe the current module should reflect this process instead of pointing to a broken link. I really had to dig in to find the information I sent to you so I cannot imagine newbies trying to adopt your E-commerce solution.

**Comment by Tcoton** [comment]
I just noticed that in the admin console in preferences/geolocation you need to download a file which does not exists anymore too: GeoLiteCity.dat.gz.

**Comment by toplakd** [comment]
Read the steps 1-6 above. That will help.
Old geolocation file is deprecated -GeoLiteCity.dat.gz
Module is replacement, however maxmind stopped offering databases without user account.
So again, steps 1-6

**Comment by Tcoton** [comment]
Except that you still have to rename the new file to the old name in order to not get an error in the config page and then, it does not work at all. When trying to access the shop when Geolocation is enabled I get this even if connecting from an authorized country: 

500 Server Error
Oops, something went wrong. You can try to refresh this page

If the problem persists please feel free to contact us. Make sure to download encrypted error message and attach it to your email. That will help our engineers to solve this problem quickly.

**Comment by getdatakick** [comment]
This module can be used on tb 1.1.x only. If you are running on older tb version 1.1.0, then this modules has no effect at all, and you need to use old maxmind database (which is no longer supported :)

The best solution is to upgrade your store to bleeding edge, and then active the module.

**Comment by Tcoton** [comment]
Well.. I have updated to bleeding edge and now, I get this error when I enable the module and try to access my shop whether or not I am access it from an authorized country:

503 OVERLOADED You cannot access this store from your country. We apologize for the inconvenience.

**Comment by toplakd** [comment]
You can join thirty bees forum and discuss it there.
