### ISSUE TITLE
Wrong base price displayed in FE productview when using attributes and QTY discount

### ISSUE THREAD

**Issue by Dauphin-Peter** [thirtybees/thirtybees#1201]
There is a problem with the calculation of the baseprice when a customer wants to order a product in quantity, and there is a quantity discount, and he can choose an article attribute that changes the base price.  In my scenario it goes as follows.

- I have an article which comes in 3 options (one attribute with three values). The options change the base price (in my case the price increases significantly, but that is slightly off topic). The default option does not have an impact on the base price.

- I have a discount rule for customers if they order 5 articles or more. And another one for quantities of more then 10 (but that also does not matter, the problem already starts with the first discount rule).

If a customer sticks to the default option. Every works as expected, including the discounting rules.

However, if the customer chooses an option which has a price increasing effect. The following happens:

- For quantities lower then the quantity discount rule threshold (5 in my case), the correct increased base price is displayed.

- For quantities higher then the price discount threshold, the default option base price is displayed instead of the one linked to the option chosen. Although it then correctly applies the qty discount to this base price, it is completely wrong.

If we the proceed to the check out, everything is well again. All prices and calculations turn to be ok. But I discovered that customers get in confusion and most of the time stop the order process. In most cases, they contact me through email but this is not the way to go.

You can find screens shots in the forum : 
https://forum.thirtybees.com/topic/4169-wrong-base-price-displayed-in-fe-productview-when-using-attributes-and-qty-discount/?tab=comments#comment-35831

If you somebody needs some more info or action, please feel free to ask!

**Comment by getdatakick** [comment]
I can't reproduce this on 1.1.x / latest niara.

Please ensure you have updated both your theme, and core, and check again.

If you can still reproduce the issue, please let us know
