### ISSUE TITLE
webservice with json output format giving error

### ISSUE THREAD

**Issue by pks891618** [thirtybees/thirtybees#1210]
version 1.1.0

if using the API for listing products with special character for dutch language its giving the error

/api/products/?output_format=JSON&ws_key=WQTFCEIP13ZAFZMZ951GFX5M4GSWIHWU&display=full&sort=id_desc

SyntaxError: JSON.parse: bad control character in string literal at line 1 column 13214 of the JSON data

In prestahop 1.7 its working fine

**Comment by getdatakick** [comment]
upgrade to bleeding edge 1.1.x

**Comment by getdatakick** [comment]
Fix as part of issue #1249
