### ISSUE TITLE
warehouse API

### ISSUE THREAD

**Issue by aykou** [thirtybees/thirtybees#1219]
![Captura de tela de 2020-06-28 11-28-21](https://user-images.githubusercontent.com/11906530/85950365-b090bb80-b932-11ea-8e8d-6751632075ef.png)

**Comment by getdatakick** [comment]
This should be fixed in bleeding edge. Please use core updater and update to latest 1.1.x version

**Comment by getdatakick** [comment]
I take it back, looks like this issue is still present in tb code base. Will look into that
