### ISSUE TITLE
An error occurred while updating an object. manufacturer ()

### ISSUE THREAD

**Issue by Vegaanders** [thirtybees/ThirtyBees#122]
Not possible to update manufacturer. You get the "An error occurred while updating an object. manufacturer ()"

**Comment by firstred** [comment]
Indeed. The error message here is: `The lastname field is invalid.`

**Comment by firstred** [comment]
Fixed after applying these commits: https://github.com/thirtybees/ThirtyBees/compare/48003a812e1ca6b4dcdd2531bc05eff6c73f3e14...111ffc9059adba2ff9d5cb0860cd1f197f8b0413

If it doesn't work for you, feel free to open a new issue, but please provide more details.
