### ISSUE TITLE
Call to undefined method RuntimeException::getRequest() in file classes/Language.php at line 499

### ISSUE THREAD

**Issue by oliversiegel** [thirtybees/thirtybees#1220]
I created a simple, empty module, and installation throws an exception.

I determined it failed to install without errors because in `classes/Module.php` on line 1653 it will attempt to do the following:
`            // @codingStandardsIgnoreStart`
`            if (Module::$update_translations_after_install) {`
`                $this->updateModuleTranslations();`
`            }`
`            // @codingStandardsIgnoreEnd`

This then ends up going through `Language::updateModulesTranslations();` to `Language::downloadAndInstallLanguagePack();`
Where it will throw an exception. 
To me, it looks like whatever remote HTTP request it's making, doesn't return the expected parameters:

`        $guzzle = new GuzzleHttp\Client([`
`            'base_uri' => "https://translations.thirtybees.com/packs/{$version}/",`
`            'timeout'  => 20,`
`            'verify'   => _PS_TOOL_DIR_.'cacert.pem',`
`        ]);`
` `
`        try {`
`            $langPackLink = (string) $guzzle->get("{$iso}.json")->getBody();`
`        } catch (Exception $e) {`
`            $langPackLink = false;`
`            $errors[] = Tools::displayError('Language pack cannot be downloaded from thirtybees.com.');`
`            $errors[] = sprintf(Tools::displayError('Downloading %s failed (PHP message: %s).'), $e->getRequest()->getUri(), $e->getMessage());`
`        }`

The final exception then is 

**Call to undefined method RuntimeException::getRequest() in file classes/Language.php at line 499**

Details: 
https://forum.thirtybees.com/topic/4367-exception-on-installation-of-basic-module/

I circumvented the problem by calling this `parent::updateTranslationsAfterInstall(false);` before I call `parent::install();`

I hope I explained it well, it's a bit convoluted...

Two things about that:

1. Is it intended behavior that we're making this remote http request for updating translations by default? Seems as if this should be a feature to be requested by the module on demand, rather than by default IMO

2. Is there a bug in the Language class, since it doesn't even handle it's own exception the right way?

**Comment by getdatakick** [comment]
There's is definitely bug in exception handling. The code expects that guzzle always throws subclass of Guzzle exception, and that's not true. 

The fix for this issue would be either to change exception signature (make it more specific), or to change exception handler to not depend on data stored inside exception. Later seems to be more appropriate solution

**Comment by oliversiegel** [comment]
What are your thoughts about this function being run unsolicited?

I mean exception well handled or not - why did my blank module cause an exception?

Is it a requirement to specifically turn off this "update languages" feature in every module?
