### ISSUE TITLE
Update all

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#1221]
Fresh installation with 1.1.0.

Modules and Services => Modules and Services => Update all, didn’t update the module “Block Banner”.

![image](https://user-images.githubusercontent.com/38436949/86497459-ae3ac100-bd79-11ea-8377-773a4997f855.png)

**Comment by getdatakick** [comment]
Resolved by commit d0698868cf8d73996f681c7a3e793b6630bc62a8
