### ISSUE TITLE
Admin not translating in files starting with 'helpers'

### ISSUE THREAD

**Issue by akuehnis** [thirtybees/thirtybees#1223]
Some admin translations are not executed, for example the button 'Resend email' is never translated.

I found a workaround editing this file:
/config/smartyadmin.config.inc.php

Replace line 65:
```
if (strpos($filename, 'helpers') === 0) {
```
by this:
```
if (false) {
```

This is nor the final solution but I could not find the right one.

The problem seems to be caused by the value  $smarty->template_resource (line 52 in /config/smartyadmin.config.inc.php). All helper files, even those assigned to a controller, start with 'helpers'. Therefore, all translations are related to the class 'Helper' - but this is wrong because 'Resend email' translation is assigned to the AdminOrders controller.

/translations/en/admin.php
```
$_LANGADM['AdminOrdersd71940f24ee38ee09f6e06b908480bcf'] = 'Resend email';
```

Again: This is only a workaround, not the propper solution.

**Comment by getdatakick** [comment]
This has been fixed by commit 6910e0159a0a5a62d5576a93b31663c2db706c9d.

Please update your tb version
