### ISSUE TITLE
Configuring the theme with the module “Theme configurator” disabled

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#1227]
With the module “Theme configurator” “Disable” change the “SETTINGS” shouldn’t be affect the website.

Home page on fresh installation:

![image](https://user-images.githubusercontent.com/38436949/86695181-37fdbf00-c004-11ea-893c-63bcdd95e0a2.png)

The “Disable” on the “Theme configurator” are not working.

If is set on disable on module "Theme configurator" is possible keep doing configurations on “Configure”.

As we can see with this example I put here:

SETTINGS on Theme configurator | Website
-- | --
 
![image](https://user-images.githubusercontent.com/38436949/86695312-55328d80-c004-11ea-83f1-5700c9a1fff1.png)  | ![image](https://user-images.githubusercontent.com/38436949/86695332-58c61480-c004-11ea-940d-31d718d81e4a.png)   |

**Comment by getdatakick** [comment]
This is fact of life. The only way module can provide configuration to store is via hook system, an hooks are (must be) disabled together with module.

**Comment by Jorgemgm** [comment]
The module “Theme configurator” have two blocks, “SETTINGS” and “THEME CONFIGURATOR (V.3.0.9)”.


SETTINGS | THEME   CONFIGURATOR (V.3.0.9)
-- | --
![image](https://user-images.githubusercontent.com/38436949/87294515-cfc74580-c4fb-11ea-9a57-1998c1ea38b3.png)  | ![image](https://user-images.githubusercontent.com/38436949/87294541-d48bf980-c4fb-11ea-9875-304f14c648e7.png)


**1. Block “SETTINGS”**

Disable the module didn’t disable the configuration on block “SETTINGS” and the configuration affects the site.


**2. Block “THEME CONFIGURATOR (V.3.0.9)”.**

Disable the module disable the configuration on block “THEME CONFIGURATOR (V.3.0.9)” and the configuration didn’t affect the site.
