### ISSUE TITLE
Error UPDATING or ADDING manufacturer

### ISSUE THREAD

**Issue by Vegaanders** [thirtybees/ThirtyBees#123]
After implementing the changes in the files by replacing them with the changed from the master I now get another error. See attached screenshots

Anders
![screenshot 2017-02-26 08 22 40](https://cloud.githubusercontent.com/assets/25871096/23337628/f3ffc3b2-fbfc-11e6-8706-88b1ef3ea8b5.png)
![screenshot 2017-02-26 08 23 01](https://cloud.githubusercontent.com/assets/25871096/23337629/f4009aee-fbfc-11e6-86c3-8fd58732d1eb.png)

**Comment by firstred** [comment]
Can you find anything in your log files? I couldn't reproduce the issue on
both a clean test environment and on production.

**Comment by Vegaanders** [comment]
There is no info in the logs at all. Either in the shop log or in the server log. Can this somehow be theme related? I dont use the community theme

**Comment by Vegaanders** [comment]
I rolled back and are now back to the original error

**Comment by Vegaanders** [comment]
As said I rolled back and did the changes one more time but the result is the same. I also tested with PHP 5.6 instead of 7.1 but no change. So I roll back again

**Comment by firstred** [comment]
Able to reproduce now.

**Comment by firstred** [comment]
https://github.com/thirtybees/ThirtyBees/commit/dc42ab7f68a7652a6693d4106777402ccf7366a0

**Comment by firstred** [comment]
Original code had some wierd mix between `@return void` and `@return string`. Finding the right balance restored the page.
