### ISSUE TITLE
AdminStockManagementController::renderDetails - physical and usable quantity must be summarized

### ISSUE THREAD

**Issue by akuehnis** [thirtybees/thirtybees#1231]
The details list should summarize physical and usable quantities of all stocks for an id_product_attribute.

Line 130 (current in branch 1.1.x):
```
$this->_select = 'a.id_product_attribute as id, a.id_product, a.reference, a.ean13, a.upc, s.physical_quantity, s.usable_quantity';
```
Should be:
```
$this->_select = 'a.id_product_attribute as id, a.id_product, a.reference, a.ean13, a.upc, SUM(s.physical_quantity) AS physical_quantity, SUM(s.usable_quantity) AS usable_quantity';
```

**Comment by getdatakick** [comment]
It's strange that in detail view is used group by sql query. Maybe the summarization is not needed here -- we could remove group by, and include some additional dimension fields into the select clause.

**Comment by akuehnis** [comment]
@getdatakick,  my understanding is, that the user has no possibility to remove items from a specific stock row. I think it is First-in-First-Out (not sure). 
When adding products, additional stock rows are added if required (e.g. different price_te).

Therefore I think a separation of all stock rows would increase complexity.

**Comment by getdatakick** [comment]
@akuehnis you are absolutely right. I've checked, and indeed in this context it doesn't make sense to split the rows according to warehouse locations

**Comment by akuehnis** [comment]
@getdatakick , hmm - i was not even thinking about a warehouse separation. But there can be multiple lines for the very same (id_warehouse - id_product - id_product_attribute)-combination

**Comment by akuehnis** [comment]
@getdatakick , sorry - clicked wrong button. Thank's for reopening.
