### ISSUE TITLE
OrderDetail::tax_name should be VARCHAR(32) instead of VARCHAR(16)

### ISSUE THREAD

**Issue by akuehnis** [thirtybees/thirtybees#1232]
I have experienced a ThirtyBeesException when ordering from the backend:

```
Property OrderDetail->tax_name length (17) must be between 0 and 16
```
Obviously, my tax Name 'Warenumsatzsteuer' was too long.

The field order_detail.tax_name is filled with the content of tax_lang.name. Therefore, the size must match. I do recommend to set it to VARCHAR(32).

Suggested changes:

/classes/OrderDetail.php, row 73:
```
'tax_name'                      => ['type' => self::TYPE_STRING, 'validate' => 'isGenericName', 'size' => 32, 'dbNullable' => false],
```

SQL 
```
ALTER TABLE ps_order_detail MODIFY tax_name VARCHAR(32) NOT NULL;
```

**Comment by getdatakick** [comment]
Note: there's no need for sql update, as core updater contains this functionality
