### ISSUE TITLE
Hook displaypayment missing from hooksList

### ISSUE THREAD

**Issue by CoiledString** [thirtybees/thirtybees#1240]
HTML block doesn't display on payment page.

I believe 'displayPayment', needs to be added at line 79.
https://github.com/thirtybees/tbhtmlblock/blob/master/tbhtmlblock.php

**Comment by getdatakick** [comment]
displayPayment hook has very specific purpose. It is often queried for other reasons than to display content on front end. For example, it is used by back office order creation, or by some OPC modules to find all payment modules.

It's best not to mess with this hook. If you need to display something on payment page, use `displayPaymentTop` hook. If that's not enough, I suggest you adjust your theme and directly add content to the template
