### ISSUE TITLE
Supply Orders discount errors

### ISSUE THREAD

**Issue by antonio-m** [thirtybees/thirtybees#1244]
I have some troubles filling Suplpy Orders, I did some different things trying to work this out, this is what I found:

### Steps to reproduce it:

    Go to Warehouses > Supply Orders
    Add new order, fill some lines and save it
    Fill the discount rate at any line with some value
    Save it

### Expected behavior:

To have that line with the discount, new price, etc.

### Actual behavior

That line is with the original price and discount at 0 (zero), no matter what line was or discount.

### Steps to reproduce it:
    Start from Case 1
    Fill the global discount rate

### Expected behavior:

To have the final price with that discount

### Actual behavior

In the Supply Order Overview page Summary block, the first line "total price" have the discount already there and not the original amount. On the folowing lines, it calculate another discount on that price, which is incorrect, so the "Total to pay" shows a discount over discount price.

### Steps to reproduce it:

    ... from the Case 2
    Set the global discount rate at 0%

### Expected behavior:

To have the original price without the discount

### Actual behavior

In the same Supply Order Overview page Summary block, the first line "total price" stays with the original discount. The folling lines shows a 0 discount and the "Total to pay" shows an incorrect price (one discount).

### Steps to reproduce it:

    ... from the Case 3
    Set the global discount rate to a negative value (I just put -20%)

### Expected behavior:

To show an error for the negative value

### Actual behavior

Sure it shows the error, but it duplicates every line in the Supply Order, one instance with 0% discount and another instance with +20% discount. In the Supply Order Overview page Summary block shows the price calculation with all the (duplicated) lines.

My TB version is 1.1.0

**Comment by getdatakick** [comment]
There has been numerous fixes for supply orders in bleeding edge.
I can't reproduce this anymore.
