### ISSUE TITLE
Illegal string offset 

### ISSUE THREAD

**Issue by Vegaanders** [thirtybees/ThirtyBees#125]
New caught when opening module list page. See attachment
![screenshot 2017-02-26 14 05 17](https://cloud.githubusercontent.com/assets/25871096/23339883/414fa0ba-fc34-11e6-86b3-59759bd80141.png)

**Comment by firstred** [comment]
Thanks!

**Comment by firstred** [comment]
I pushed this change for PHP 7.1 a while ago. On line `1250` you have to change `$modules_preferences = '';` to `$modules_preferences = [];`

**Comment by Vegaanders** [comment]
Yep, it did the trick. THANKS
