### ISSUE TITLE
classes/Translate.php not updated with Core Updater

### ISSUE THREAD

**Issue by mbc3** [thirtybees/thirtybees#1258]
Using the Core Updater to update from 1.1.0 to 1.1.x broke my shop, giving a 500 error when I went to my storefront.

The error I got was: 

```
Call to undefined method Translate::getFrontTranslation()
in file config/smartyfront.config.inc.php at line 66

66:    return Translate::postProcessTranslation(Translate::getFrontTranslation($params['s'], $basename, $params['sprintf'], $params['js']), $params); 
```
I looked at my version of classes/Translate.php and it did not contain the getFrontTranslation method. I cleared my cache, made sure I had proper write permissions set on the file, and updated again with the Core Updater - it still didn't update the file to include the method.

I had to copy and paste classes/Translate.php from GitHub, and then the update works fine, and my store runs flawlessly. This makes me think there might be a bug in the Core Updater - especially since this was the only file that didn't get updated.

**Comment by getdatakick** [comment]
I have tested this functionality and it works correctly. Translate.php files was correctly updated 

I assume you must had some persmissions / restrictions issues on your server.
