### ISSUE TITLE
Error when try configure module

### ISSUE THREAD

**Issue by Vegaanders** [thirtybees/ThirtyBees#126]
Hi!
I this a TB bug or a module bug?

![screenshot 2017-02-27 11 03 52](https://cloud.githubusercontent.com/assets/25871096/23355076/c2441586-fcdc-11e6-9b92-723e7107ed8c.png)

**Comment by firstred** [comment]
Did you migrate or is this a clean install?

**Comment by firstred** [comment]
Ohh nvm, the module seems to have some payment module => carrier restriction in place, but it uses the same database table as thirty bees. Can you disable that functionality in the module? Function `assignShipAndPayInfo` probably.

**Comment by Vegaanders** [comment]
I will try. Its a clean install always

**Comment by firstred** [comment]
Hmmz it sucks that PrestaShop never had decent carrier - payment restrictions. It's not the first module that reimplements the system. Btw thirty bees uses tbe same structure as PS 1.7, so if you can find a 1.7 verdion of the module you might want to try that as well.

**Comment by Vegaanders** [comment]
I have another module from the same developer Best Kit, that also broke, this time when trying to install. The first one is their One Page Checkout that has worked perfectly in the ps shops we have and now want to migrate when the tool come. That is why I test the important ones on a clean install

**Comment by firstred** [comment]
Hmmz, this can't be fixed from thirty bees. The module is using the wrong primary and database table to process its data. The part of the module that adds the restriction will need to be removed, since it is handled natively by thirty bees now.
