### ISSUE TITLE
An error occurred while creating an object. supplier ()

### ISSUE THREAD

**Issue by Vegaanders** [thirtybees/ThirtyBees#127]
Probably same problem as with the Manufacturer. I can see that they are created in the database

**Comment by firstred** [comment]
Fixed by:
- https://github.com/thirtybees/ThirtyBees/commit/8d45d02ec923fa70acd326456473a0c969a47aed
- https://github.com/thirtybees/ThirtyBees/commit/b1ff21524a49a4df5ccae285c31ecceed7ac9e90

**Comment by Vegaanders** [comment]
Hi!

Can I download the changed files or need to download all files?



If the files are in the zip file then there is still a problem. Adding a supplier does not work. When you save it it just disappear

Anders

**Comment by firstred** [comment]
Hmmz, thanks for the info.

Reopening this issue to further investigate.

**Comment by firstred** [comment]
Fixed by further cleaning AdminControllers
