### ISSUE TITLE
Order Detail - space before first line of address

### ISSUE THREAD

**Issue by toplakd** [thirtybees/thirtybees#1315]
![Screenshot_2021-04-08 Orders Order KHWLILZLL from John DOE • My Store](https://user-images.githubusercontent.com/39807649/114052420-55f79900-988e-11eb-9204-a0040884f90f.png)
3x click and copy the very first line of the address (John DOE), than paste into some document and there will always be one space added to the pasted item.
This happens only with the very first line.
If the string is added within < p > string < /p > than this thing does not happen, and first line now also has no space added when copying it.

https://github.com/thirtybees/thirtybees/blob/fe5bf7c55449f8d454dffe830a73d66c4ab68e11/admin-dev/themes/default/template/controllers/orders/helpers/view/view.tpl#L716

**Comment by getdatakick** [comment]
I'm really not sure how to categorise this issue :) 
Let's mark it as a bug for now.

**Comment by toplakd** [comment]
It's only problematic when copying the data into Carriers forms, where the space is always added in the first line :)
It's nothing critical, I just edit the file manually after every upgrade.

**Comment by getdatakick** [comment]
This seems to be fixed by #1416.
