### ISSUE TITLE
Fresh Install - No way for customer to register, checkout crashes

### ISSUE THREAD

**Issue by sdalcorn** [thirtybees/thirtybees#1317]
I have just made a fresh install of Thirty Bees 1.2.0

There is a "SIGN IN" option, but no way to register. When clicking the SIGN IN, I get a "too many redirects" error.

So, I add a product to a cart, hit checkout and also get a "too many redirects" error.

My customers can not register either.

http://alcafe.com/

**Comment by getdatakick** [comment]
the site seems to be working correctly.
