### ISSUE TITLE
Thirty bees An error occurred during installation

### ISSUE THREAD

**Issue by Deekshithdp1997** [thirtybees/thirtybees#1319]
While installing thirty bees in byethost getting an error at 13%
Attached screenshot along with this, please check the same.
![Capture](https://user-images.githubusercontent.com/82814148/115229446-aee9eb80-a130-11eb-9121-f341dd16f339.JPG)

**Comment by getdatakick** [comment]
Your database server does not support `InnoDB` engine, which is required by thirty bees. Please ask your hosting provider to enable/install this engine
