### ISSUE TITLE
Order csv export - data are on single line

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/thirtybees#1326]
This is an injection caused by fix for issue #1138

**Comment by selwynorren** [comment]
Hi Guys, any progress on this. I have a customer that is heavily dependent on this feature to export the filtered list of orders, however the result CSV is semi-colon separated and everything is on a single line

**Comment by apppsitsolution** [comment]
hi. 
in /themes/default/template/layout-export.tpl
change code

{$export_precontent}{foreach from=$export_headers item=header}{$text_delimiter}{$header}{$text_delimiter};{/foreach}
{foreach from=$export_content item=line}
{foreach from=$line item=content}{$text_delimiter}{$content}{$text_delimiter};{/foreach}
{/foreach} 

with 

{$export_precontent}{foreach from=$export_headers item=header}{$text_delimiter}{$header}{$text_delimiter};{/foreach}

{foreach from=$export_content item=line}
{foreach from=$line item=content}{$text_delimiter}{$content}{$text_delimiter};{/foreach}

{/foreach}

(in essence it is enough to give line spacing-)
I hope it will be useful.

**Comment by getdatakick** [comment]
That would be basically just a revert of fix designed for issue #1138. That issue solved some problems with csv export -- extra lines caused a lot of problems elsewhere. 

We need to find solution that will work for all list exports, not only orders

**Comment by getdatakick** [comment]
I have submitted the fix into bleeding edge, and reopened original issue #1138
