### ISSUE TITLE
Thirty bees web page contact forms.

### ISSUE THREAD

**Issue by Marcin-J-PL** [thirtybees/thirtybees#1328]
Hello,
There is some problems on your page.

After send message on https://thirtybees.com/contact/ i have:
"
Error: Array ( [curl] => [Error] => Array ( [Type] => Sender [Code] => InvalidClientTokenId [Message] => Signature Version 3 requests are deprecated from March 1, 2021. From that date on, we are progressively rejecting such requests. To resolve the issue you must migrate to Signature Version 4. If you are self-signing your requests, refer to the documentation for Authenticating requests to the Amazon SES API [1] with Signature Version 4 [2]. If you are not self-signing your requests, simply update your SDK/CLI to the latest version. [1] https://docs.aws.amazon.com/ses/latest/DeveloperGuide/using-ses-api-authentication.html [2] https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html ) [RequestId] => 7d5b1907-a7c5-46f5-962f-d51d674acddc )

"

Here https://thirtybees.com/partners/become-a-partner/
Response status are spam.

{"into":"#wpcf7-f2666-p301-o1","status":"spam","message":"There was an error trying to send your message. Please try again later."}

**Comment by getdatakick** [comment]
Thank you for reporting the problem. We will investigate.

Closing this issue as it's not related to thirtybees core
