### ISSUE TITLE
Trying to create new carrier

### ISSUE THREAD

**Issue by Vegaanders** [thirtybees/ThirtyBees#133]
Trying to create new carrier

Notice on line 62 in file /var/www/vhosts/beautyandpleasure.co.uk/httpdocs/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(157) : eval()'d code
[8] Undefined index: currency_iso_code

Notice on line 62 in file /var/www/vhosts/beautyandpleasure.co.uk/httpdocs/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(157) : eval()'d code
[8] Trying to get property of non-object

**Comment by firstred** [comment]
Yup, thanks for notifying. This has been fixed some time ago. Can't find the exact commit, but if you're running the latest source it will no longer occur. It was in the carrier wizard btw.

**Comment by Vegaanders** [comment]
Then I need to find the change. I change when I see altered files but probably miss some

**Comment by firstred** [comment]
I think it's this one: https://github.com/thirtybees/ThirtyBees/commit/51c625e805a4c9b3ff00d0a3b911b657f044b6a0
