### ISSUE TITLE
mysql_error still present

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/thirtybees#1341]
In the files /controllers/admin/AdminImportController.php and /modules/tbupdater/classes/ConfigurationTest.php the function mysql_error is still present. Obviously it should be replaced with mysqli_error.

Note that the second case concerns the updater module. The file in the classes directory is ok. So it looks like the tbupdater files have an older version.

**Comment by getdatakick** [comment]
Thanks for noticing this. Fixed in core by commit 047bc1f3a6de4e96c23ebf4d701ce4249b58096b

**Comment by getdatakick** [comment]
Regarding tbupdater - I don't see usage of this function there, not in the current version, or in any of the historical one. @musicpanda  how did you find this?

**Comment by musicpanda** [comment]
Thank you for fixing the AdminImportController.php.

I can't find the tbupdater one at the moment and I don't remember in which installation I saw it. If I find it again I will mention it.
