### ISSUE TITLE
Date in back office and front office

### ISSUE THREAD

**Issue by sysadminix** [thirtybees/ThirtyBees#1352]
Thirtybees 1.2.0.
Theme Niara

In back and front office: date look like on screenshot

![изображение](https://user-images.githubusercontent.com/92815418/137959748-b176ef05-f0b9-42fd-9e86-8894aef4974d.png)

**Comment by getdatakick** [comment]
I can't reproduce this on vanilla installation of thirty bees, even with russian locale the date/time are displayed correctly.

What theme are you using? Do you have any overrides or core code modification?
