### ISSUE TITLE
Version differences

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/thirtybees#1360]
One of the parts of Prestashop that I often look at is the directory /install/upgrade/sql. It shows you the difference in database structure between the different versions. It makes it very easy to see at which version a certain field was added and that helps when people have problems with that field.

For a moment it appeared that Prestashop might neglect this directory in the Symfony madness but it still is maintained.

I miss such an overview in Thirty Bees. Do I overlook something?

**Comment by getdatakick** [comment]
Thirty bees no longer use upgrade scripts. Instead, database schema is derived directly from object models metadata.

There is file `/tests/golden_files/db_schema.sql` that holds current status of the database.

You can check differences by

```
git diff 1.2.0...1.3.0 tests/golden_files/db_schema.sql
```

Or using github compare: https://github.com/thirtybees/thirtybees/compare/1.2.0...1.3.0#diff-2a48baaddf0416cfb05978271a4ca9a83881e6f54ac663389063ba1d59c28135

**Comment by musicpanda** [comment]
Most likely nobody will ever take the trouble to search this deep. That will mean that when people in the future develop for TB they won't take the trouble to check for compatibility with older versions.

In my view software should be transparent. Not hiding its features in proprietary "meta data".
