### ISSUE TITLE
PHP Notice on file /pdf/invoice.tax-tab.tpl

### ISSUE THREAD

**Issue by toplakd** [thirtybees/thirtybees#1365]
This file generates PHP Notice for long time now and generates error_log when generating PDF invoices.
However this notice only happens for orders where tax is also included, but not on the orders which are without tax.
Tested on Freshly installed Stable 1.3 and Bleeding Edge.

PHP Notice:  Undefined index: order in /0.file.invoice.tax-tab.tpl.php on line 96
PHP Notice:  Trying to get property 'value' of non-object in /0.file.invoice.tax-tab.tpl.php on line 96
PHP Notice:  Trying to get property 'id_currency' of non-object in /0.file.invoice.tax-tab.tpl.php on line 96
PHP Notice:  Undefined index: order in /0.file.invoice.tax-tab.tpl.php on line 103
PHP Notice:  Trying to get property 'value' of non-object in /0.file.invoice.tax-tab.tpl.php on line 103
PHP Notice:  Trying to get property 'id_currency' of non-object in /0.file.invoice.tax-tab.tpl.php on line 103

**Comment by getdatakick** [comment]
Closed by 05212c942ce7c0dcf07191e478bc9e4071516e13
