### ISSUE TITLE
Canonical link generation throws exception for module controllers with parametrized urls

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/thirtybees#1368]
If module defines custom route using `moduleRoutes` hook, and this route is parameterized with keywords, then exception is throw when generating canonical link  https://github.com/thirtybees/thirtybees/blob/818571b59a40bfab23b734d816b4442367ddd4cd/classes/controller/FrontController.php#L463

Front controller should resolve parameters required by this route, and pass them as a third parameter to getModuleLink method

**Comment by getdatakick** [comment]
sample route: 
```php
            'module-samplemodule-controllername' => [
                'controller' => 'controllername',
                'rule' =>'custom-url/{id}/{rewrite}'
                'keywords' => [
                    'id' => ['regexp' => '[0-9]+', 'param' => 'id'],
                    'rewrite' => ['regexp' => '[_a-zA-Z0-9-\pL]*', 'param' => 'rewrite'],
                    'module' => ['regexp' => '[_a-zA-Z0-9_-]+', 'param' => 'module'],
                    'controller' => ['regexp' => '[_a-zA-Z0-9_-]+', 'param' => 'controller'],
                ],
                'params' => [
                    'fc' => 'module',
                    'module' => 'samplemodule',
                    'controller' => 'controllername',
                ],
            ],
```

**Comment by eschiendorfer** [comment]
I am not totally sure about this case. When using the hookModuleRoutes I always have some fights, to make it work. But I can say that this one is working for me:

```
'module-genzo_tags-feature' => array(
                'controller' => 'feature',
                'rule' => 'feature/{link_rewrite_feature}/{link_rewrite_feature_value}',
                'keywords' => array(
                    'link_rewrite_feature' => array(
                        'regexp' => '[_a-zA-Z0-9-\pL]*',
                        'param' => 'link_rewrite_feature',
                    ),
                    'link_rewrite_feature_value' => array(
                        'regexp' => '[_a-zA-Z0-9-\pL.+]*',
                        'param' => 'link_rewrite_feature_value',
                    )
                ),
                'params' => array(
                    'fc' => 'module',
                    'module' => 'genzo_tags',
                    'controller' => 'feature',
                ),
            ),```
            
So I am not totally sure, where the difference is!?

Btw: I am not yet on v.1.3, but I guess it has nothing to do with it...

**Comment by getdatakick** [comment]
the call `$link->getModuleLink('genzo_tags', 'feature', [])` would fail. It internally calls `$link->createUrl('module-genzo_tags-feature', 1, [])`. This method throws, because input $parameters are empty, but parameters with keys `link_rewrite_feature` and `link_rewrite_feature_value` are required

That's expected and valid behaviour. It should fail, because input are invalid.

But unfortuantely, this is what 'canonical url' functionality in FrontController was doing. It called the getModuleLink with empty parameters, and that resulted with exception.

The fix is to select parameters required by current route from $_GET array
