### ISSUE TITLE
Native Paypal module does not work in Live mode

### ISSUE THREAD

**Issue by Vegaanders** [thirtybees/ThirtyBees#138]
When setting the Paypal module in Live mode it stops working. Say that web profiles is missing and the checkout page gets incomplete. In sandbox mode all normal

**Comment by firstred** [comment]
You closed it, because it works, right?

**Comment by Vegaanders** [comment]
Yes. The problem is if you not look outbis that you get sandbox credentials and not live ones. It should be said on the config page that you must get live ones. Far from all are technicians. So I hope two things, A better documentation about it, and that they change the link to Paypal developer site to open in a new window so it does not close the BO where you should fill in the credentials
Then it is funny that there is a possibility to switch on Paypal Plus, which according to the developer site is not possible because it does not work with REST
