### ISSUE TITLE
"Standard Refund" not refunding shipping costs to credit slip

### ISSUE THREAD

**Issue by x97wehner** [thirtybees/thirtybees#1385]
When selecting the standard refund option on an order, after selecting "Generate a credit slip" tickbox, I select the "repay shipping costs" tickbox as well. Then when selecting the "Refund products" button, the credit slip only generates for the amount of the products. No shipping costs are added to the slip as it should.

**Comment by getdatakick** [comment]
This bug was injected by commit 35f1efeb058a96cc5939dd8af67beeb30dcdce6e
