### ISSUE TITLE
back office error when updating any product after update to bleeding edge

### ISSUE THREAD

**Issue by x97wehner** [thirtybees/thirtybees#1393]
When making any edit to any product in back office, getting the below error. Tested this with overrides and all non-native tb modules disabled as well.

![image](https://user-images.githubusercontent.com/44684415/155815641-109e308c-04a2-4838-972f-81b03e816565.png)

debug showing: 

SELECT SQL_NO_CACHE `reduction`
FROM `tbvy_product_group_reduction_cache`
WHERE (`id_product` = 1) AND (`id_group` = 0) LIMIT 1

**Comment by getdatakick** [comment]
Fixed by commit 00694930fb270b9212f44a8b5ad67add4a8a4f07
