### ISSUE TITLE
Categories: hard dependency on image types medium and category

### ISSUE THREAD

**Issue by DXXS** [thirtybees/thirtybees#1394]
I've seen this 'bug' reported by ~a handful of people before... this is what I was doing when I encountered it:

Categories ‘bug’ encountered while setting up MultiStore mode:
- 	Deleted a second MultistoreGroup ~’NameA’ which I had created
- 		[FWIW, I also had a category with the same ~’NameA’]
- 	Viewed two stores in leftover ‘Default’ group; were showing same product categories online
- 	Attempted to switch to showing different product categories : shops still showing same products
- 	Went back to products, changed product ‘combination’ on productX to only include child category
- 		previously had parent containing category checked also
- 		(changed & saved with multistore-‘all’ selected)
- 	Went back to multistore to verify category selection : subcategory ‘NameA’ now missing from choices
- 	Went back to product editor, subcategory ‘NameA’ missing from choices
- 	Went back to category preferences
- 		categories still listed, but only >>last category entered<< is editable
- 		attempting to ‘edit’ others just flashes / performs a page reload
- 	Turned on debug mode : when editing >>last category<<, produces error message
- 		produces same error when attempting to create a new category

#################### Debug messages: ####################
Notice on line 648 in file controllers/admin/AdminCategoriesController.php
[8] Undefined index: category

Notice on line 657 in file controllers/admin/AdminCategoriesController.php
[8] Undefined index: medium
########################################################

**Comment by DXXS** [comment]
Server information Linux #1 SMP Tue Aug 25 11:59:26 MSK 2020 x86_64
Server software version Apache/2.4.38 (Debian 10)
PHP version 7.3.31-1~deb10u1
MySQL version 8.0.26

**Comment by DXXS** [comment]
In looking at the code, these debug messages appear to have to do with the images associated with the category & the inability to edit most or create categories may be a separate issue...

Debug/Profiling output when attempting to edit one of the 'inevitable' categories:
https://holdings.x-in-g.com/Secure/categories_profile_debug_output.html

**Comment by getdatakick** [comment]
This issue occurs when there is no image type `category` or `medium` defined (Preferences > Images), of if these image types are not associated with 'Category'.

PHP code depending on hardcoded image types (data) is simply wrong. This needs to be completely rewritten

**Comment by DXXS** [comment]
FWIW, There are image types 'community-theme-default_medium_default' and 'community-theme-default_category_default' which apparently were both defined and associated with 'category' in preferences...

As I indicated above, I think there may be more than one 'bug' here, given the extreme inability to edit categories, but I felt I had to make progress, so I made a backup of the database, and restored my entire server to the snapshot that I had (IMO fortunately) taken the day before.  [Looks like someone's 'autocorrect' function changed my 'ineditable' into 'inevitable' above!? IMO, pretty sure that should be a word ;-/].  I did make a copy of the database before I restored my backup if anyone wants to see it [privately].

**Comment by getdatakick** [comment]
Fixed by recent image rewrite
