### ISSUE TITLE
Partial refunds calculating wrong

### ISSUE THREAD

**Issue by CasualRascal** [thirtybees/thirtybees#1399]
I think this may be related to #1077

Customer buys one product for the price of €38,50 plus €4,80 shipping for a total of €43,30

Partial refund, manually entering the values of €38,50 and €4,80 in the interface

Refund calculates to €42,00 instead of €43,30

I have 2 guesses:

1. decimals are just disregarded entirely.

2. rounding is broken

Set to the default *Round up away from zero, when it is half way there (recommended)*. The values in the calculation are negative therefore the "round up" rounds closer to 0 instead of further away from 0 in the negative side

**Invoice calculation**

38,50 => 35,00 + 10% VAT = 35,00 + 3,50 = 38,50 **no rounding**
4,80 => 3,93 + 22% VAT = 3,93 + 0,87 = 4,80 **no rounding**

**Refund calculation**

-38,50 **rounding gets applied** -> 38 (this shows up in the credit slip instead of 38,50)
Shipping is more confusing because in the credit slip it shows as -4,00 with an included -0,72 VAT, as if it rounded 4,80 to 4 and then calculated tax on 4.

**UPDATE**: I just read the old, long forum thread cited in #1077. Setting aside the unfriendliness of the original conversation, I can confirm that it is the same issue.

In my defines.inc.php
```
if ( ! defined('_TB_PRICE_DATABASE_PRECISION_')) {
    define('_TB_PRICE_DATABASE_PRECISION_', 6);
}
```

Installed without demo data

**UPDATE 2**: Because I have seen the forum conversation ended when reproduction steps were asked but not provided, I have gone through and installed thirty bees in a virtual machine to have a truly clean install and for the purpose of providing reproduction steps.

```
$ cat /etc/redhat-release
Virtuozzo Linux release 8.5.0 (Vz)
$ cat /etc/os-release
NAME="Virtuozzo Linux"
VERSION="8"
ID="virtuozzo"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Virtuozzo Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:virtuozzoproject:vzlinux:8"
HOME_URL="https://www.vzlinux.org"
BUG_REPORT_URL="https://bugs.openvz.org"
$ httpd -v
Server version: Apache/2.4.37 ()
Server built:   Dec  1 2021 17:53:29
$ mysql --version
mysql  Ver 8.0.21 for Linux on x86_64 (Source distribution)
$ php-fpm -v
PHP 7.4.19 (fpm-fcgi) (built: May  4 2021 11:06:37)
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.19, Copyright (c), by Zend Technologies
```
Install TB via graphical installer, Italy location, no demo data, no overrides, no third-party modules.

Create attribute: Pack size

Add value: 2Kg

Create product with combinations:

Name: Test

- Pre-tax wholesale price: 1.20
- Pre-tax retail price: 9.00
- Tax rule: IT Reduced Rate (10%)
- Unit price (tax excl.) 9.00 per Kg

Combination 1: 

- Attribute: Pack size
- Value: 2Kg
- Wholesale price: 2.20
- Impact on price: Increase of € (VAT excl.) 6.00
- Impact on weight: Increase of kg 1.00
- Impact on unit price: Reduction of € / Kg 1

Quantities:

2000 Test - Pack size - 2Kg

Edit default shipping carrier:
- Free shipping: no
- Handling costs: no
- Tax: IT Standard Rate (22%)

Zones: Europe €12.90

Now on the front office create an account and then an order for one test item the default combination (the only one inserted), pay by bank wire.

In the back office go to Orders > Orders, select the new order, change status to Payment accepted

Now click Partial refund
- Quantity 1/1
- Value 16,50
- Shipping 15,74
- Confirm Partial refund

There is a mismatch again:

- Invoice product price = 15+1.5 = 16.5
- Invoice shipping price = 12.90+2,84 = 15.74
- Invoice total = 32,24
- Credit slip product price = -16 (including -1.45 tax)
- Credit slip shipping price = -15 (including -2.70 tax)
- Refunded amount = -31,00

I really hope this information helps, I am available for more information if needed.

**Comment by getdatakick** [comment]
I believe this is duplicate of issue #1367

Could you please verify -- update your test store to bleeding edge, and try again.

**Comment by CasualRascal** [comment]
Ah. yes. I can confirm it is indeed the comma. 

Even without updating to bleeding edge, repeating the procedure above but providing values with a dot instead makes everything work correctly.

Everything in the backoffice uses commas, so I assumed values had to be provided using commas.

**Comment by getdatakick** [comment]
Thank you for confirming. This was very unfortunate bug, hopefully it is fully fixed
