### ISSUE TITLE
Smarty 4 is out

### ISSUE THREAD

**Issue by CasualRascal** [thirtybees/thirtybees#1402]
Hey Smarty 4 is out,

Main feature is PHP 8 compatibility, it drops compatibility for PHP <7.1

Because thirty bees aims to become PHP 8 compatible, I believe we should test Smarty 4.

**Comment by getdatakick** [comment]
Smarty 4 included in 1.4.0

**Comment by eschiendorfer** [comment]
> Smarty 4 included in 1.4.0

Sounds great! I guess it's 4.1 right? Is there anything I need to take into account as module/theme dev? The smarty website doesn't deliver too much information (or I have found it).

**Comment by getdatakick** [comment]
It's `4.1.1` for php >= 7.1, and `3.1.45` for php 7.0

https://github.com/thirtybees/thirtybees/blob/f284c4d3fc970456dbd269b4558225c45ea702b0/composer/php7.4/composer.json#L10-L12

I don't know about any backwards compatibility problems with this version, so hopefully it will work fine. I've been running bleeding edge with this on my demo and production server for a few weeks now without any problems. Of course, the problems can happen for different themes / modules / templates

**Comment by getdatakick** [comment]
I can see that new version 4.2.0 and 3.1.46 were released. There are minimum changes in these versions, definitely nothing that could break thirty bees. I will bump dependencies
