### ISSUE TITLE
AVIF images generation support

### ISSUE THREAD

**Issue by CasualRascal** [thirtybees/thirtybees#1405]
AVIF format is now supported by all major browsers and it offers superior compression benefits to webp. I would like to see AVIF image generation support perhaps with jpeg fallback for older browsers

**Comment by Dh42** [comment]
Not an official statement, but it seems like the support is severely lacking in most areas. IE / Edge do not support it and neither does Safari desktop or mobile. https://caniuse.com/avif

Also, using php the library only supports it for php 8.1. https://php.watch/versions/8.1/gd-avif

**Comment by CasualRascal** [comment]
> Not an official statement, but it seems like the support is severely lacking in most areas. IE / Edge do not support it and neither does Safari desktop or mobile. https://caniuse.com/avif
> 
> Also, using php the library only supports it for php 8.1. https://php.watch/versions/8.1/gd-avif

This is a very important thing to point out. However I must argue against this concern for a couple of reasons: 

- Internet Explorer is discontinued, I do not think we should concern ourselves with providing support to legacy browsers
- While Microsoft Edge indeed does not support AVIF, providing a jpeg fallback option via the `<picture>` tag is good practice anyway. Microsoft Edge will utilize the jpeg option within the picture tag if provided, this means that implementing AVIF only provides benefits in loading speed to browsers supporting the format and cause no ill effect to those that don't.

**Comment by Yabbertb** [comment]
Information from two years ago and all no longer current. Also, maybe the idea is worth revisiting?
Thirtybees already supports PHP 8.1 and 93.63% of browsers already support AVIF format.

**Comment by getdatakick** [comment]
Initial support implemented.

I'd appreciate some help with testing. @Yabbertb, (or anybody else), you can try to update your store to branch `issue-1405` (you can use coreupdater - custom target)

**Comment by Yabbertb** [comment]
@getdatakick I did a test of images in AVIF format and throughout the store all images display correctly. I found only one bug: on the product page, the zoom for the product image does not work. I tested with the original Niara template.

**Comment by getdatakick** [comment]
Thanks for reporting the zoom issue. Fixed by commit 572a7cb55a8ebb59e1f9eb061dd556615ef82eb9
