### ISSUE TITLE
Life hack in Orders and manual shipping label creation

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/thirtybees#1413]
![image](https://user-images.githubusercontent.com/11251370/161402033-3e26363f-f3ea-4b92-aac9-d161a9ad15a4.png)
It would be nice if we can have 'click to copy' text over the address fields in order view in admin.

Currently customer, address, phone is all rendered as one field and the approach I propose will be impossible to implement.

But it will be nice to have each field shown in different div so we can click to copy them: customer names, city, country, postal code, address (this will still need manual copying in many scenarios).

TB is used mostly by small merchandisers that don't use shipping label creation modules and make their labels by hand. It takes time and this will speed things up considerably.

Also one issue I encounter almost every day is that customers in FO are offered 2 phone fields and if they input their phone in one of them (I still don't know which one, probably home phone) it does not show under the list and you need to go up the page, enter customer's profile and copy it from the bottom of that page. If this is considered and phone is always shown in this Orders page it will be great too.

Regarding the click to copy function I believe this will do us just fine. The only thing it's lacking is indication if the click was successful (some small animation under or over the text) - https://stackoverflow.com/a/62728944 But as I said in order to implement this we will need to split the address information in different rows and make them one idea large so it's more user friendly.

**Comment by mwrouse** [comment]
About the phone number thing, I see both of them show up under the shipping address, both home and mobile phone numbers. 

I get this order:
```
Name
Company
Address 1
Address 2
City, State, Zip
Country
Home Phone
Mobile Phone
```

We are still on `1.2` but I hope that wouldn't have changed. Do you really not see both phones listed in that field?


Also, I'm interested in you creating your own labels? Do you actually make your own labels or do you just have to put the address into another services website?

Do you not make any labels at all, or do you just write down the address and take it to somewhere to ship? If you're doing that, anywhere but the post office you are overpaying.

**Comment by mwrouse** [comment]
Going back to the original request, I think a copy button is perfectly reasonable and would be a good feature to have, for copying the entire address.

Obviously a copy button on each line would be a little ridiculous. But moving each line to an `input` element that is disabled and stylized to not look like an input element would allow you to double click each line to select-all the text on that line. I think that might be the solution to the copying each line problem.

**Comment by therampagerado** [comment]
My idea is that you need to copy name, phone, postal code and probably country if you use this feature.

The address is almost all the time not useful for full copy-paste so no need imho to have full address copy function.

But all feedback is welcome for me. Just in Bulgaria all couriers have their own BO where you input first the city, then living quarters, then street name, then number and it becomes even funnier when the dude is shipping to home address as most of the people here live in living blocks - block number, entrance, floor, apartment number.

**Comment by mwrouse** [comment]
I opened a pull request for it. 

If you are familiar with the diff viewer it would be easy enough to make the changes yourself. https://github.com/thirtybees/thirtybees/pull/1416/files

**Comment by therampagerado** [comment]
@mwrouse , let me check it!

**Comment by therampagerado** [comment]
Implemented it in one of my shops and it's working fine but not very useful for me at least. Hopefully it will be for others! Thanks for your contribution.


In the meantime I digged little bit to see how this address is composed and it's a nightmare for me. I doubt I will be able to implement my idea miself.

**Comment by mwrouse** [comment]
Instead of single-click to copy, I did double-click to copy instead so you have to intentionally do that as an action, instead of just clicking around the screen leading to accidentally copying something. There is also no animation like you mentioned in the original request.

Change all the `ondblclick`s you added to `onclick` and you get it as a single-click action.

**Comment by therampagerado** [comment]
OMG! 

I didn't understand the code at that part and thought the copy function is only in the new button.

This is exactly what I needed, no matter one, two or three clicks!

Works like a charm! And as you said double click is just better because otherwise accidentally you may misclick.

Thank you very much! This will save me one minute each time I make a shipping label. :)

**Comment by mwrouse** [comment]
I just pushed more changes with a copied message that popsup to the left.
