### ISSUE TITLE
array_key_exits() is depreceated on objects

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/thirtybees#1417]
My log is full with warnings like:

`PHP message: PHP Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /path/SupplyOrderDetail.php on line 316`

**Comment by getdatakick** [comment]
Fixed by commit eeba3b4211adbaa9064af9ea8eb5842e1bcefd0b
