### ISSUE TITLE
Guest Checkout - cannot select state

### ISSUE THREAD

**Issue by firstred** [thirtybees/ThirtyBees#142]
See: https://forum.thirtybees.com/topic/82/guest-checkout

**Comment by sean-mullen** [comment]
I just came across this myself. It is caused by a typo in controllers/front/AuthController.php
where  $addresss  is misspelled with 3 x s
It has been fixed https://github.com/thirtybees/ThirtyBees/pull/119

**Comment by firstred** [comment]
Thanks for letting us know!
