### ISSUE TITLE
Undefined offset when using currency on lists

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/thirtybees#1420]
My log has quite some entries like:
`PHP Notice: Undefined offset: 1 in /path/cache/smarty/compile/7e/90/b5/7e90b51aa9ad63cd299f7c4a60d7bf3d585fcd77_0.file.list_content.tpl.php on line 328`

It happens on BO lists that are using type='price' and currency=true. An example is AdminStockMvtController.php. The issue was introduced by myself in:
https://github.com/thirtybees/thirtybees/pull/1200

**Comment by getdatakick** [comment]
Fixed by #1421
