### ISSUE TITLE
Open Github discussions

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/thirtybees#1428]
I would propose to open discussion (tab) on github. The intention would be, that we can discuss coding stuff here. It seems to me, that this doesn't work out too well in the forum. Earlier we had the slack channels for it.

As an example I would like to discuss some changes on the objectModel. I believe, that I found a real improvement, but maybe my understanding of object model is just wrong. That's why it doesn't make much sense, to invest a lot of time into a PR before the problem wasn't discussed. What do you think?

As a concrete example: I would like to know, what happens, if you use the following:

```
$object = new Object($id_primary, null, $id_shop);
$object->delete();
```

I would expect, that only the rows with id_shop=$id_shop are deleted. But it will delete the entire object. My argument: why would you specify a concrete $id_shop, if you want to delete the whole object? Similair stuff can happen, when you use add() or update().

Edit: the problem is probably mainly related to 'multilang_shop' use cases...

**Comment by getdatakick** [comment]
Discussions should be enabled now. Please test

**Comment by eschiendorfer** [comment]
Amazing! I appreciate that :) It's working!
