### ISSUE TITLE
Remove radio button for payment module currency restrictions

### ISSUE THREAD

**Issue by firstred** [thirtybees/thirtybees#143]
The radio button mode for payment modules need to be removed. Currency restrictions should always be in checkbox mode from now on.

**Comment by kpodemski** [comment]
Why is that?

**Comment by firstred** [comment]
What's the advantage of having those? They are also always broken btw.

**Comment by kpodemski** [comment]
if your payment module allows to select currency at the end of the order you can use checkbox, if not there's a radio option to choose the only available currency, simple as that

never had any issues with that

**Comment by firstred** [comment]
> if your payment module allows to select currency at the end of the order you can/you need use checkbox

Bankwire module doesn't use a checkbox?

**Comment by kpodemski** [comment]
Yes, bankwire uses `checkbox`, and it's working just fine

**Comment by firstred** [comment]
Oops I meant radio

**Comment by firstred** [comment]
So the customer currency options is more like just selecting all checkboxes?

I still don't see why we need a radio button

**Comment by firstred** [comment]
Looking back at this issue be like
![but why](https://media.giphy.com/media/1M9fmo1WAFVK0/giphy.gif)

**Comment by alwayspaws** [comment]
That's perfect!
