### ISSUE TITLE
Allow to install without installing demo data

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/ThirtyBees#145]
Let me open this to not forget it.

More advanced users typically want to install without installing all these nice demo products. Command line installation already allows this, but the GUI installer doesn't. Discussion see https://forum.thirtybees.com/topic/61/clear-demo-data

IMHO it'd be a good idea to add a checkbox in the installer to make demo data optional. Just products/categories/orders. Taxes, countries, currencies and such stuff should be always installed.

**Comment by firstred** [comment]
Awesome. Thanks for the reminder!

**Comment by kpodemski** [comment]
Why not just install `pscleaner` and clean catalog + customers? same story, less effort

**Comment by Traumflug** [comment]
> Why not just install pscleaner and clean catalog + customers? same story, less effort

Because it's actually more effort than just clicking a checkbox? And the module strategy is also more prone to errors, like bugs in the module or accidental clicking of the user when the shop is in production already. AFAIK, ```pscleaner``` will happily remove real data, too.

**Comment by firstred** [comment]
lol

For some reason the demo products option has been limited to dev mode only in the past.
![Genius](http://i1.kym-cdn.com/entries/icons/facebook/000/010/277/069.jpg)

**Comment by firstred** [comment]
Removing that check makes it available again: https://github.com/thirtybees/ThirtyBees/commit/5abcc50db92c71d6467cdf2c18047d610ed3f240

**Comment by Traumflug** [comment]
Oh, that's quick :-) And yes, removing code is always my favorite way of fixing issues :-)
