### ISSUE TITLE
issue with free order (when order total =0)

### ISSUE THREAD

**Issue by smarterweb** [thirtybees/thirtybees#1453]
Discovered this whilst using a gift certificate module that get's added after subtotal, tax and shipping, resulting in the total order to be $0.
When this is the case, TB would not proceed to the order confirmation page. The module developer made the following change to:

\controllers\front\ParentOrderController.php

line 199 FROM:
```php
    protected function _checkFreeOrder()
    {
        if ($this->context->cart->getOrderTotal() <= 0) {
            $order = new FreeOrder();
            $order->free_order_class = true;
            $order->validateOrder($this->context->cart->id, Configuration::get('PS_OS_PAYMENT'), 0, Tools::displayError('Free order', false), null, [], null, false, $this->context->cart->secure_key);

            return (int) Order::getOrderByCartId($this->context->cart->id);
        }

        return false;
    }
```
TO:
```php
    protected function _checkFreeOrder()
    {
        if ($this->context->cart->getOrderTotal() <= 0) {
			$cart_id = $this->context->cart->id; #  get cart_id before validating
            $order = new FreeOrder();
            $order->free_order_class = true;
            $order->validateOrder($this->context->cart->id, Configuration::get('PS_OS_PAYMENT'), 0, Tools::displayError('Free order', false), null, [], null, false, $this->context->cart->secure_key);

          //return (int) Order::getOrderByCartId($this->context->cart->id);
            return (int) Order::getOrderByCartId($cart_id); # $this->context->cart->id is now null
        }

        return false;
    }
```

Can someone confirm this and add as bug?
Thanks

**Comment by getdatakick** [comment]
I don't see any core code in `validateOrder` method that could reset `Context::$cart` variable, so the original code should work just fine. And it does -- I've just tested it.

I suspect that you have some module that uses hook to modify/reset this context variable during `validateOrder` call. That could be considered bug in that module.

Anyway, the proposed code change is very simple and there is no risk associated, so let's move this to core.
