### ISSUE TITLE
Disable “CUSTOMER SERVICE OPTIONS”

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#1456]
On tab, Customer => Customer Service, we have the emails “CUSTOMER SERVICE” and the configuration “CONTACT OPTIONS”, “CUSTOMER SERVICE OPTIONS” and “Sync”. 

![image](https://user-images.githubusercontent.com/38436949/175794801-735660b9-510b-4271-ab4a-0145979254f6.png)

When we give the permissions to the emails “CUSTOMER SERVICE”, they also have access to configuration “CONTACT OPTIONS”, “CUSTOMER SERVICE OPTIONS” and “Sync”. 

![image](https://user-images.githubusercontent.com/38436949/175794807-77119dba-320d-4dc4-b3eb-cb372c012eae.png)

The employees don’t need access to the “CUSTOMER SERVICE OPTIONS” to manage the emails and it's safer for us, but we can't disable this without disabling all Customer Service.

We should have the option to give or not access to each one (emails “CUSTOMER SERVICE”, the configuration “CONTACT OPTIONS”, “CUSTOMER SERVICE OPTIONS” and “Sync”).

**Comment by getdatakick** [comment]
Fixed by 34a609b7682c869e887a2e33038c7d397ae96aca
