### ISSUE TITLE
More Curl certificate trouble

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/thirtybees#1459]
During the installation I cannot download the languag pack as the Curl refuses an expired SSL certificate.
![curl](https://user-images.githubusercontent.com/13930107/176263449-6c2f5b19-409d-44c1-b0a1-feb188dca03e.jpg)

**Comment by getdatakick** [comment]
Fixed by commits a09146c3db421e1604dd45dc8d63925c4aee7c4f and e09774271a3f0a0b60a6001dd780eed1f8d461df.

Obviously, those commits are not part of thirty bees 1.2.0 distribution package.

**Comment by musicpanda** [comment]
Why is this not a problem for Prestashop? If the market thinks that their security is good enoughit should be good enough for Thirty Bees too.

**Comment by getdatakick** [comment]
Probably because their api server uses ssl certificate that was signed by different certificate authority

**Comment by musicpanda** [comment]
I have the luxury that I never needed to bother to investigate the details of certificates.

But I do know that when I download even a ten years old Prestashop version it is a fully functional piece of software. 

However, when I download a version of Thirty Bees that is just one year old it is a rather dysfunctional useless heap of bytes. This is not what opensource is supposed to be.

**Comment by getdatakick** [comment]
Try to download ps1.6.1.0 and try to install it on php7.4 server. Now, is it fully functional piece of software?

Of course not. 

Environment changes over the time. What worked perfectly well back in 2018 might not work now. Whatever the reason - be it php version, mysql version, or changes on transport layer (ssl cert). Nobody should seriously expect that few years old software package can be used without problems. 

Thats why we offer updates and new releases, after all.

**Comment by musicpanda** [comment]
I tried updating the cacert.pem file. It worked for the coreupdater in my migrated shop. It did not work in my new TB 1.2 shop. I get there still the same error messages. When I look in the PHP error log I see that there a notice: [:error]PHP Notice:  Undefined index: version in \classes\\LocalizationPack.php on line 503, referer: myadmin/index.php?controller=AdminLocalization

**Comment by musicpanda** [comment]
Not outdated. This is what I get with TB 1.3 for PHP 5.6
![update](https://user-images.githubusercontent.com/13930107/179183566-9e4406b6-0d5e-4570-9968-5fb30f4c510a.jpg)

Prestashop 1.6 could do without cacert.pem files without problems. When I see the endless problems it causes me in TB I wonder whether the alleged extra security it offers really justifies all this trouble.

**Comment by getdatakick** [comment]
> Prestashop 1.6 could do without cacert.pem files without problems. When I see the endless problems it causes me in TB I wonder whether the alleged extra security it offers really justifies all this trouble.

Update and migration is a mechanism that **overwrites** PHP code on your server with PHP code received from API server. It's as dangerous as it sounds. We have to make sure we are talking with the right API server before we use any code that it send us, otherwise it's just an open door for hack. The only way to ensure we are talking with the right peer is... yeah signed certificate.
