### ISSUE TITLE
Notice: tempnam() on PHP 7.1

### ISSUE THREAD

**Issue by firstred** [thirtybees/ThirtyBees#146]
`Notice: tempnam(): file created in the system's temporary directory in /var/www/default/classes/PrestaShopAutoload.php on line 125`

**Comment by DevNIX** [comment]
Shouldn't be fixed by configuring php.ini correctly?

**Comment by firstred** [comment]
Not everyone is capable of configuring `php.ini` correctly. There might be a better way.

**Comment by DevNIX** [comment]
Maybe, but if you are using a shared hosting account of a provider, it should be properly configured (even if you don't have enough capabilities to do it).

As I see it, the best approach would be to use an alternative function/system of `tempnam`. Using a `@` to mute the warning is considered a very bad practice.

**Comment by firstred** [comment]
Yeah it should be fixed via the configuration indeed. Thanks for the update!
