### ISSUE TITLE
hookDisplayAdminProductsExtra

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/thirtybees#1461]
The hook displayAdminProductsExtra gives extra tabs when you edit a product. Modules use it to add extra functionality.

Now I have in a migrated shop with three such tabs. The tabs are shown. But when I click the tab I get an empty page. I looked in the module's code: the code in its hookDisplayAdminProductsExtra() function is never called. So I wonder if this is some bug. 

/controllers/admin/AdminProductsController.php contains two references to the hook - just like the old Prestashop code that worked. 

I see the same behavior with three modules and there is no error in the log so it seems unlikely that the modules cause the problem.

I am working under TB 1.2 now but I couldn't find any reference to the issue in Github or the TB forum to suggest that it is a known problem.
![empty](https://user-images.githubusercontent.com/13930107/176732002-75a6463f-f866-4b68-a21c-e04175db8de5.jpg)

**Comment by musicpanda** [comment]
One extra note. When I look in the network tab of the browser console I see calls for those tabs but the response is empty. 

An example call is: http://localhost/testshop/myadmin/index.php?controller=AdminProducts&token=99a3c6d25e99b86a8731922f28bd03d9&id_product=0&action=ModuleBestkit_stickers&updateproduct&ajax=1&rand=1656600228331&_=1656600217626

This is for a new product (that is why id_product=0) but for existing products the same applies.

**Comment by musicpanda** [comment]
The empty response
![empty2](https://user-images.githubusercontent.com/13930107/176760510-5d2dfa05-2141-42c1-a712-3519b18ca30c.jpg)

**Comment by getdatakick** [comment]
This functionality works properly both in in 1.2.0 and in bleeding edge. This is actually one of the most used hook there, a lot of modules are using it. This have to be some bug specific to your installation. Most likely override.

**Comment by eschiendorfer** [comment]
I can confirm, that this works properly for me and my modules...

**Comment by musicpanda** [comment]
I had forgotten about overrides. Sorry. I guess it will be that.
