### ISSUE TITLE
AdminMeta - SEO & URLs

### ISSUE THREAD

**Issue by e-com-presta** [thirtybees/thirtybees#1465]
After updating thirty bees 1.3.0 to 1.4.0 bleeding edge, list of pages is empty.
![Zaznaczenie_216](https://user-images.githubusercontent.com/20421361/179440734-a359a2b9-97eb-4904-8cf8-a47105989c0c.png)

In edit mode, it is OK.
![Zaznaczenie_217](https://user-images.githubusercontent.com/20421361/179440779-ef7fe1da-3884-4b14-b80e-d633ff8bb748.png)

**Comment by getdatakick** [comment]
Thanks for reporting this, it was nasty regression. Fixed in bleeding edge
