### ISSUE TITLE
TB 1.4.0 - PHP 8.1 deprecated methods

### ISSUE THREAD

**Issue by e-com-presta** [thirtybees/thirtybees#1468]
After testing TB bleeding edge, I made a list of deprecated methods.

#### Core:

- [x] explode(): Passing null to parameter 2 ($string) of type string is deprecated in /controllers/admin/AdminModulesController.php on line 291. *Fixed by commit ab2f3a6*
- [x] explode(): Passing null to parameter 2 ($string) of type string is deprecated in /controllers/admin/AdminModulesController.php on line 661. *fixed by commit ab2f3a6*
- [x] stripslashes(): Passing null to parameter 1 ($string) of type string is deprecated in /classes/module/Module.php on line 984. *fixed by commit 8e9463f4b9afe192e8b2b02589180ff231049540*
- [x] mb_strtolower(): Passing null to parameter 1 ($string) of type string is deprecated in /classes/Search.php on line 379. *fixed by commit ea4da93b59d6b76486461bb7c1143ca4d04606f6*
- [x] Implicit conversion from float 55.96153846153846 to int loses precision in /classes/ImageManager.php on line 350. *Fixed by commit 01ab051717e7ebdf24f9208cfc321fb78f65fc4d*
- [x] Implicit conversion from float 55.96153846153846 to int loses precision in /classes/ImageManager.php on line 360. *Fixed by commit 01ab051717e7ebdf24f9208cfc321fb78f65fc4d*
- [x] Implicit conversion from float 55.96153846153846 to int loses precision in /classes/ImageManager.php on line 451. *Fixed by commit 01ab051717e7ebdf24f9208cfc321fb78f65fc4d*
- [x] mb_detect_encoding(): Passing null to parameter 1 ($string) of type string is deprecated in /classes/Tools.php on line 4857. *fixed by commit 9659d77905b21806cab1a5c285d510b1ca10a05d*
- [x] mb_strpos(): Passing null to parameter 1 ($haystack) of type string is deprecated in /classes/Tools.php on line 4857. *fixed by commit 9659d77905b21806cab1a5c285d510b1ca10a05d*
- [x] html_entity_decode(): Passing null to parameter 2 ($flags) of type int is deprecated in /classes/Mail.php on line 357. *fixed by commit fe924f9962106bb83ac5f57c00840934542edd37*
- [x] preg_match(): Passing null to parameter 2 ($subject) of type string is deprecated in /classes/Mail.php on line 577. *fixed by commit b5dc011e21af2559e5eed302fa628e2815e49ffe*

#### Third party libraries

**Note: We can't fix these, we have to wait for new library versions**
- strtolower(): Passing null to parameter 1 ($string) of type string is deprecated in /vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/AuthHandler.php on line 251
- Function strftime() is deprecated in /vendor/smarty/smarty/libs/plugins/modifier.date_format.php on line 81

#### Modules:
- [x] usort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /modules/tbupdater/tbupdater.php on line 1012
- [x] strtolower(): Passing null to parameter 1 ($string) of type string is deprecated in /modules/coreupdater/classes/schema/builder/InformationSchemaBuilder.php on line 282
- [x] Optional parameter $token declared before required parameter $id is implicitly treated as a required parameter in /modules/blocknewsletter/blocknewsletter.php on line 266
- [x] Optional parameter $token declared before required parameter $id is implicitly treated as a required parameter in /modules/blocknewsletter/blocknewsletter.php on line 288

**Comment by getdatakick** [comment]
Thank you. I'm sure there will be more. It will take some time to hunt all deprecation in the core.

**Comment by getdatakick** [comment]
All reported issues were fixed

**Comment by eschiendorfer** [comment]
"PHP message: PHP Deprecated: Function strftime() is deprecated in [/vendor/smarty/smarty/libs/plugins/modifier.date_format.php] on line 81" while reading response header from upstream. Is still there. 

Are we awaiting any fix from smarty?

**Comment by getdatakick** [comment]
Yes, nothing to do on our side. Smarty guys are aware about this

https://github.com/smarty-php/smarty/issues/824
https://github.com/smarty-php/smarty/issues/810

**Comment by e-com-presta** [comment]
Maybe, before smarty guys make a fix, make such a fix in thirty bees?
https://github.com/thirtybees/thirtybees/compare/main...e-com-presta:thirtybees:e-com-presta-patch-2

**Comment by getdatakick** [comment]
@e-com-presta That's a very nice change. I didn't know we can override build-in smarty modifies like this.

Let's pull this into the bleeding edge to get rid of warnings. If smarty guys fix the issue before we release 1.5 we will revert our fix, otherwise we will keep it for a little bit longer.

I created PR #1557 from your code
