### ISSUE TITLE
Some attachments can not be uploaded from product

### ISSUE THREAD

**Issue by WBNet-Wout** [thirtybees/thirtybees#1469]
When I try to upload for example [(GL-CP-I-001)控制器Pro说明书版本V1.4.pdf](https://github.com/thirtybees/thirtybees/files/9162008/GL-CP-I-001.Pro.V1.4.pdf) as attachment using Catalog -> Products -> some product -> Attachment -> Add file, I get an error saying`(GL-CP-I-001)控制器Pro说明书版本V1.4.pdf : Invalid file`. When I try to upload the same file through Catalog -> Attachments -> Add new attachment, it works fine and I am then able to link that attachment to a product. This issue happens with a significant portion of the PDF files I have tried to upload as attachment, but definitely not with all.

**Comment by getdatakick** [comment]
Reproduced. There are couple of issues here

1) error hiding -- any error in `$this->errors` is replaced with non-descriptive error message 'Invalid file'
2) mixing settings for Attachment and Downloadable products. Limit for downloadable product file is applied to attachments as well. 
3) invalid reporting on max upload size -- even when code correctly detect this situation the error message is dropped.


@WBNet-Wout until this is fixed, you can go to  Administration > Preferences, and set high enough values for both
- Maximum size for attachment
- Maximum size for a downloadable product

**Comment by getdatakick** [comment]
Fixed with commits above
