### ISSUE TITLE
TB 1.4.0 and PHP 8.1 - install and uninstall modules with overrides

### ISSUE THREAD

**Issue by e-com-presta** [thirtybees/thirtybees#1470]
When installing and uninstalling modules that have overrides, errors occur.
Module install:
PHP Fatal error:  Cannot use "parent" when current class scope has no parent in /classes/module/Module.php(1938) : eval()'d code on line 25
Module uninstall:
PHP Fatal error:  Cannot use "parent" when current class scope has no parent in /classes/module/Module.php(2049) : eval()'d code on line 26

Example module "mdimagemagick".

**Comment by getdatakick** [comment]
Wow. This is as bad as it can get.

Definitely a show stopper for `1.4.0` release, as it makes impossible to install any module with overrides
