### ISSUE TITLE
Fix AdminImportController

### ISSUE THREAD

**Issue by firstred** [thirtybees/ThirtyBees#148]
Lots of complaints about the importer. Time to check the whole file.

**Comment by quandaries** [comment]
Looking forward to the resolution. Thanks!

**Comment by firstred** [comment]
https://github.com/thirtybees/ThirtyBees/commit/6d733a31867c58525af4a50bf69b700a29fe107e

**Comment by firstred** [comment]
https://github.com/thirtybees/ThirtyBees/commit/c3ad12b7fb8593dab57f6eb4859f9cc9d4a040f5

**Comment by firstred** [comment]
These commits made me able to import the given CSV files again. Therefore closing this issue as it has the status `blocker`. 

If the changes mentioned above do not solve the issues you have with CSV import, feel free to open a new issue.
