### ISSUE TITLE
Image regeneration: The error message doesn't make sense

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/thirtybees#1481]
The error message doesn't make sense:
![errormsg](https://user-images.githubusercontent.com/13930107/182222866-7de79662-bbe8-4d37-b1bb-3a34601ac93e.jpg)

**Comment by getdatakick** [comment]
Related code:

https://github.com/thirtybees/thirtybees/blob/a6a187e5ed275de75ee8cb6503ff67143c5c68b4/admin-dev/themes/default/template/controllers/images/content.tpl#L255-L270

**Comment by eschiendorfer** [comment]
Funny, I am just about playing around with image regeneration. Is this feature well tested? I have multiple issues:

1. Delete generated thumbnails doesn't seem to work fine. I tried on my clone and clean store. For example when I delete them all and check folder img/p/1/0 the thumbnails are still there...
2. Regenerate products doesn't seem to work for all products. Especially products with attributes seem to make problems. Can that be?

**Comment by eschiendorfer** [comment]
I did now again regenerate again and I got more thumbnails. So probably the attribute thing is working, but maybe not 100% stable. 

But still thinking that deleting thumbnails has some issue.

**Comment by ehohetraw** [comment]
The regeneration is now running, every now and then an error appears, I think it was “Error 500 Server” or something like that.

The only problem is that now every time you click on a picture on the website, the standard thumbnail appears. This camera on a white background....
