### ISSUE TITLE
Installing from Softaculous when PHP is 8+

### ISSUE THREAD

**Issue by toplakd** [thirtybees/thirtybees#1498]
When installing thirtybees from softaculous where server has php version 8 or newer, install finishes to the end without problems.
Core updater needs to be upgraded to 1.6 but you can not access modules section to install it due to:

`*ERROR* 	2022/08/11 - 05:47:27: method_exists(): Argument #1 ($object_or_class) must be of type object|string, bool given at line 3460 in file classes/controller/AdminController.php
`

**Comment by getdatakick** [comment]
Version 1.3.0 is not compatible with php8

**Comment by toplakd** [comment]
I know it's not compatible, you know it's not compatible.
But random first time user who sees it on softacolous does not know that and he ends up with broken thirty bees which is not upgradable, not knowing that PHP version is the reason :) And proceeds with install of PS :)

**Comment by getdatakick** [comment]
Yeah, but what can we do?? It's the same think as if you download ps16 package from 5 years ago, and tried to install it. It just isn't compatible anymore.
