### ISSUE TITLE
Undefined array key in template features.tpl

### ISSUE THREAD

**Issue by e-com-presta** [thirtybees/thirtybees#1500]
Warning on line 0 in file admin/themes/default/template/controllers/products/features.tpl
[2] Undefined array key 1
Warning on line 0 in file admin/themes/default/template/controllers/products/features.tpl
[2] Trying to access array offset on value of type null
Warning on line 0 in file admin/themes/default/template/controllers/products/features.tpl
[2] Undefined array key 1
Warning on line 0 in file admin/themes/default/template/controllers/products/features.tpl
[2] Undefined array key 2
Warning on line 0 in file admin/themes/default/template/controllers/products/features.tpl
[2] Undefined array key 3

**Comment by getdatakick** [comment]
Already fixed
