### ISSUE TITLE
PHP 8 Deprecated

### ISSUE THREAD

**Issue by e-com-presta** [thirtybees/thirtybees#1504]
- [x] PHP Deprecated:  strip_tags(): Passing null to parameter 1 ($string) of type string is deprecated in classes/Configuration.php on line 650
- [x] PHP Deprecated:  strtolower(): Passing null to parameter 1 ($string) of type string is deprecated in controllers/admin/AdminTranslationsController.php on line 3287
- [x] PHP Deprecated:  mb_strtoupper(): Passing null to parameter 1 ($string) of type string is deprecated in classes/Tools.php on line 2834

**Comment by getdatakick** [comment]
The issue in `AdminTranslationController` was fixed by commit 3aa3f97f76b27f0bc61fd55b4bdbc9bb70bb2bc5
