### ISSUE TITLE
Undefined variable: body in Employee.php on line 365

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/thirtybees#1506]
I found this error message twice in my error log. I could not reproduce it.

However, when I checked the code I noticed that this variable "body" is the result from a Guzzle operation. So it looks like the error handling when this operation fails is not functioning well.
![guzzle](https://user-images.githubusercontent.com/13930107/186650527-08e8e62e-6324-44d2-b46a-3cda5784510a.jpg)

**Comment by getdatakick** [comment]
Yep, this looks like an obvious bug. The statement should definitely be inside `try` block, or the variable `$body` should be declared before the `try` statement
