### ISSUE TITLE
Another ImageType:getFormatedName bug

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/thirtybees#1512]
When I go the backoffice page to edit a category I get errors with debug mode on.
![admin](https://user-images.githubusercontent.com/13930107/188969216-15b4122a-9cfc-4772-a5fe-29ae08187623.jpg)

Analyzing this I see that $format["name"] and $format["category"] are not defined. When I look back a bit in the code to the place where those index values should be filled I see this:
![code1](https://user-images.githubusercontent.com/13930107/188967508-430db2b1-59b0-418c-9307-61b4724c68ac.jpg)

Things go wrong on the first line:
`$formattedCategory = ImageType::getFormatedName('category');`

$formattedCategory gets here the value "category" instead of the name of the relevant image format of the theme (in this case panda_category_default).

Looking in the function getFormatedName() it is not difficult to see that not everything is correct.
Take this line:
`strpos($name, $themeName) !== false`

The function strpos is defined as strpos(haystack, needle). The code here uses the opposite order.

**Comment by getdatakick** [comment]
That code does not exists anymore. Closing as outdated
