### ISSUE TITLE
Can´t use the translation even there is just one language installed

### ISSUE THREAD

**Issue by croquete1** [thirtybees/thirtybees#1513]
I only have Portuguese lang installed, and all the emails that are sending, is going in english...

**Comment by Jorgemgm** [comment]
I suppose you can contribute on https://crowdin.com/project/thirty-bees

**Comment by musicpanda** [comment]
If you look in the /Mails directory of your shop, what language subdirectories do you find there?

Did you accidentally create the language before you imported it? That can give problems.

**Comment by croquete1** [comment]
> I suppose you can contribute on https://crowdin.com/project/thirty-bees

its almost translated on modules about emails...



> If you look in the /Mails directory of your shop, what language subdirectories do you find there?
> 
> Did you accidentally create the language before you imported it? That can give problems.

i think i copy from prestashop files. I will delete the lang and import it from thirtybees.

**Comment by croquete1** [comment]
in /Mails i have En and PT.
on Crowdin, its almost everything translated to Portuguese and still, the emails on orders and accounts are still on english. I don´t why but the /Mails/PT the files are in english...

**Comment by getdatakick** [comment]
the email templates are saved inside

`/mails/<iso>/`
or in
`/themes/<theme>/mails/<iso>`

where `<iso>` is a two-digit iso code, in lowercase. 

So, you should look inside `/mails/pt` , not `/Mails/PT` -- those are two different locations, at least on most servers.

**Comment by croquete1** [comment]
i already looked for and its /mails/pt... still in english

![imagem](https://user-images.githubusercontent.com/16768315/190363247-f7ffa473-50d0-4cb4-a9d1-bca6b5d9cbe1.png)

**Comment by musicpanda** [comment]
The problem with creating a language is that it also may create some "translations" and by lack of content it copies the English values. That can become a problem when you load a language pack and that doesn't want to override existing values.

**Comment by musicpanda** [comment]
I am afraid there is no easy solution.

I checked it and you were right. When you install the localization pack it installs English mail templates. It is a heritage of Prestashop 1.6 that had the same problem. So the only solution to edit those 64 files yourself. It should be less than an hour work.

I hope that Thirty Bees will one day have a mail template generator like Prestashop has in 1.7.

**Comment by croquete1** [comment]
i already translated all relatives to emails (and some others things) on crowdin.
there is a way that can i download the lang on emails (not one by one)? cause i already translated and deleted to test it...

**Comment by croquete1** [comment]
YESSS, finally i could do it and it works.
its the way @musicpanda says...

**Comment by croquete1** [comment]
i installed a Crowdin module and now i cant do nothing :(( 
when i login in mydashboard, it keeps me open to login on Crowdin website, i login and nothing happens ://

**Comment by getdatakick** [comment]
Did you join 'thirty bees' crowdin project as a translator?

For me, crownin in context module works properly.

Please do not reuse the same github issue for multiple problems. If there is an issue with crowdin module, please file new issue inside [thirtybees/crowdin](https://github.com/thirtybees/crowdin/issues) project
