### ISSUE TITLE
"DATA SHEET" and the row order of features

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#1514]
In my case, the row order of features changes from device to device, from browser to browser and sometimes with the browser refresh.

![image](https://user-images.githubusercontent.com/38436949/189460086-2d9be1d8-af1f-4ab5-b50c-d2d7c6c24a36.png)

**Comment by getdatakick** [comment]
Fixed in commit c54ce1ffe08329afe7fa22fd1a993c046d25753c
