### ISSUE TITLE
Removing dynamic hook wrapping when output is empty

### ISSUE THREAD

**Issue by pjrp** [thirtybees/thirtybees#1516]
When full page cache is enabled, dynamic hook output is wrapped with a html comment even if a module returns no data. 

This triggers the theme to display empty left/right column

![sdasdad](https://user-images.githubusercontent.com/23322791/189492828-cfa82b1b-fb29-4f5d-872f-b88abc416232.png)

At ./classes/Hook  HookCore exec() line 307:

>                     // wrap dynamic hooks
>                     $key = $cacheEntry->setHook($idModule, $idHook, $hookName, $hookArgs);
>                     $delimiter = "";
>                     $return .= $delimiter.$data.$delimiter;

we could check if the module is outputting data, adding the delimiter only if needed: 

>                      // wrap dynamic hooks
>                     if($data) {
>                         $key = $cacheEntry->setHook($idModule, $idHook, $hookName, $hookArgs);
>                         $delimiter = "";
>                         $return .= $delimiter.$data.$delimiter;
>                     }

Can someone please check this out?

Thanks!

**Comment by getdatakick** [comment]
That is not possible. Just because the module did not emit any data during the first page render does not mean that it never returns anything. We would not be able to insert dynamic content into the page without the placeholders.

**Comment by pjrp** [comment]
So, full page cache is relying  on this html tags to output module content later on... that's  unfortunate. Not a quick fix after all. I'll just turn off FPC for this website.

@getdatakick  thanks for checking it out.
