### ISSUE TITLE
Geolocation Service- Cloudflare

### ISSUE THREAD

**Issue by marktnz1** [thirtybees/thirtybees#1539]
![Screenshot from 2022-10-31 10-48-10](https://user-images.githubusercontent.com/25965650/198903150-9e6a1520-e8e0-4abd-9d97-e86e291abef3.png)
If user has added and installed Datakick: Cloudflare Geo IP module then in the Cloudflare GEO IP module, set up a config section explaining about cloudflare and how to set up geo IP on cloudflare... and then run a test to see if Geo headers are being received. Only activate the actual service if geo headers are being received, otherwise leave de-activated until test results indicate headers received.

In the Geolocation Services section, if the Cloudflare Geo IP module is set by the system to "Active" , then add "Cloudflare" to Geolocation Services options (Preferences/ Geolocation Service/ Geolocation) and use the Cloudflare headers to operate the Geolocation Service and allow TB to run services that depend on country.

If the system has not set Cloudflare to active then remove it from the list options in the Geolocation Services section.

**Comment by getdatakick** [comment]
Thirtybees core don't have any information about modules implementation, environment requirements, etc. It just provides list of installed implementation, and does not really care if they work or not. 

If anything, this is an enhancement request for 'Cloudflare Geo IP' module, not for core.
