### ISSUE TITLE
Unable to upload .webp images as product images.

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/thirtybees#1548]
The recent commit was great.

Today I tried uploading webp images and TB does not allow me.

**Comment by eschiendorfer** [comment]
Yes, I have this problem as well. Was this working before or did you switch also recently to webp?

**Comment by therampagerado** [comment]
Prior to the recent addition of webp I did not try to upload such formats.

**Comment by getdatakick** [comment]
webp was never supported as source product image format.

Webp functionality only allows generating image variants in webp format, from source jpg file. Recently, we have also allowed uploading webp images in file manager, but that's not related to product images in any way.

**Comment by therampagerado** [comment]
Oh didn't know! Thanks @getdatakick !

**Comment by getdatakick** [comment]
We should definitely support webp as a source file. 

However, we should first remove hardcoded dependency on .jpg files, mostly from back office. And also implement fallback mechanism if somebody requested the source jpg file -- there are some modules out there that uses source product image files for zooming, for example. These modules should use dedicated image type for that, of course, but we should support it to some level.

**Comment by getdatakick** [comment]
Implemented as part of recent image rewrite
