### ISSUE TITLE
"IMPORT A LOCALIZATION PACK" feature is not enabled in TB 1.0

### ISSUE THREAD

**Issue by Hailong** [thirtybees/ThirtyBees#155]

**Comment by firstred** [comment]
Thanks, but that has been addressed already: 
https://github.com/thirtybees/ThirtyBees/commit/1f8454c6b33c9e14b3278f58f04a026be3ab0df3
https://github.com/thirtybees/ThirtyBees/commit/9015c21dada244f4c837be8db50e0c511891714e

**Comment by firstred** [comment]
Ahh maybe not the localization pack part

**Comment by Hailong** [comment]
Let me sync the latest code, and test it out.

**Comment by Hailong** [comment]
I think with the above two commits in place, this feature is almost ready. While it requires a file `localization/localization.xml` to be there so that the form shows up. Would you please take a look?

The code is in AdminLocalizationControllerCore::renderForm()

**Comment by firstred** [comment]
I believe the biggest problem was that we needed to host an updated version ourselves. I guess that's why we removed it at first. The files in `localization/localization.xml` are outdated, but could be used as a fallback for now.

**Comment by firstred** [comment]
Ohh and there were many bugs in the packages :/

Gonna fix those, too

**Comment by firstred** [comment]
Ahh yeah, biggest problem found. It also can happen during the install.

If you install the software or install a localization pack when offline, you can mess up the registered `Language`s. The whole back office can become no longer usable because everything errors out due to the `Language` items that are in a format that can't be recognized by thirty bees.

**Comment by firstred** [comment]
https://github.com/thirtybees/ThirtyBees/commit/a9bec66ae018083810e8d14ecfc5e8c8d125bb30

**Comment by firstred** [comment]
https://github.com/thirtybees/ThirtyBees/commit/dac1683ddd66a63973d79ec29135926c0c5e60f3
