### ISSUE TITLE
Combination link shows only product page default image in social links

### ISSUE THREAD

**Issue by marktnz1** [thirtybees/thirtybees#1552]
If I post the link of a combination in it shows up correctly on the product page, but not on social media. In places like Facebook, it shows the default image for the product not the combination image. This is a bit annoying when I post the combination to customers who want to see the blue product, so I post them that, but they only see the defult red variant in front of them on social media.

Datakick comment:
"That's because the combination link is constructed using hash parameters instead of query parameters. Hash parameters are ignored by servers, browser actually never sends them. If the url looks like this:

https://domain.com/en/category/product#attribute-color=blue

Browser will send only request for https://domain.com/en/category/product , and server does not know about attribute-color.

Currently, combination selection is done only in browser javascript code, on page load. And that is, of course, not performed by facebook crawler. Facebook sees only the default page, with default image and default combination.  

This also prevents proper GMC links for combinations, reviews associated with specific combinations, etc... "

https://forum.thirtybees.com/topic/5856-combination-link-shows-only-product-page-default-image-in-social-links/#comment-44848

**Comment by meswitch** [comment]
@getdatakick, could you point to the place in the core which in responsible for forming combination url with hash parameters?
I'm not a programmer, but understand the difference between hash and query parameters - https://dirask.com/posts/JavaScript-hash-parameters-vs-query-parameters-pa3EK1

We might hire a professional php programmer for this task. Yandex - big search engine needs product url in format without #.
Right now it's not possible to index combinations with Yandex Search and to show them in Yandex Product Search (these are 2 separate tasks, both will be solved with urls with query parameters).

**Comment by getdatakick** [comment]
In core, method `Link::getProductLink()` generates url with hash if parameter `$ipa` is provided.

https://github.com/thirtybees/thirtybees/blob/11105ee5fa83573c9077e778652971c2fad167ca/classes/Link.php#L230-L236

Then, every theme contains javascript code that process hash parameters. For example, niara theme: 

https://github.com/thirtybees/niara/blob/d469fcb47b589783deebe847b77bc8d1c0a1d242/js/product.js#L1104
