### ISSUE TITLE
Add more genders

### ISSUE THREAD

**Issue by croquete1** [thirtybees/thirtybees#1553]
We should add more genders on titles

**Comment by croquete1** [comment]
- Transgender
- Non-Binary
-  Agender

Here in Portugal, we are open to this genders

**Comment by therampagerado** [comment]
Good for Portugal!

Here in Bulgaria we hide this section and everybody is happy. :)

**Comment by croquete1** [comment]
but here in Portugal, they boycott companies and persons :))

**Comment by therampagerado** [comment]
If you don't offer them chance to choose their preffered sex?

If this makes them feel better, the first 2 sexes also lack the opportunity to choose so they should not feel discriminated.

**Comment by eschiendorfer** [comment]
> Note that every store can create their own 'titles' which acts de-facto as a genders.
> 
> So, if the goal is to provide customers an option to choose, the `Customers > Titles` is a way to go. There is no need for any change in code.
> 
> However, every title is internally associated with a gender (see those three options listed above). This is NOT visible to end customers. The only place we are using this in back office is in stats.
> 
> I suggest we remove this 'gender' from titles, and remove this unnecessary stats -- replace it with stats by titles, and we don't have to worry about anything :)

completly agree on this! A nice example of over complicating things!
