### ISSUE TITLE
This comes up on module list page

### ISSUE THREAD

**Issue by Vegaanders** [thirtybees/ThirtyBees#156]
Does not seem to affect anything

![screenshot 2017-03-24 14 38 15](https://cloud.githubusercontent.com/assets/25871096/24320073/2692df8c-1136-11e7-8ab0-380d12c139b1.png)

**Comment by Vegaanders** [comment]
Seems to come from TB updater module. I uninstalled it and it disappear

**Comment by firstred** [comment]
Hmmz, time to update the module. We'll soon have a look at it as we have to run `updater`/`1.0.1` tests soon.

**Comment by firstred** [comment]
Ahh I see what's going on. You can delete the module. We have totally redesigned the API and that module doesn't speak it anymore. There is no way to update the software without the newer module we will be releasing soon.
