### ISSUE TITLE
Combinations: Do Not allow a negative price or size decrease.

### ISSUE THREAD

**Issue by marktnz1** [thirtybees/thirtybees#1565]
In Catalog/Products/Combinations if I change a combination to a price or size decrease (using a postive number and selecting decrease) it saves ok at first but later it somehow changes the value from a positive value to a negative, rendering the combination invalid on the product page.

Ensure the number entered is always positive and cannot be negative (The negative aspect gets included if you choose "Decrease", but a negative negative invalids the combination).

![Screenshot from 2022-11-28 12-49-32](https://user-images.githubusercontent.com/25965650/204166594-6a02494e-e58b-416d-8129-5b951bdc4998.png)

**Comment by marktnz1** [comment]
The above image happens sometime after saving and causes a problem: this attached image is correct and fixes the problem by manually changing the negative to a positive
![Screenshot from 2022-11-28 12-58-55](https://user-images.githubusercontent.com/25965650/204166798-bd4ac410-5a70-440d-a6c6-6d4435bdf3a0.png)

**Comment by marktnz1** [comment]
Not allowing this to happen is great, but even better is fixing whatever causes the number to go from positive to negative and still preventing negatives, this is double safe.

**Comment by getdatakick** [comment]
This was injected by commit 09b2735e5b7ac30afda1065619c00133cafa46a5

**Comment by getdatakick** [comment]
The same issue is with all three impacts - price, weight, unit price. All three have been fixed by commit 3ff2bfc5ee202ff5eb61b0f3e080f183bc038d0d
