### ISSUE TITLE
Visitor reported a problem

### ISSUE THREAD

**Issue by Vegaanders** [thirtybees/ThirtyBees#157]
when I try to enter your site I get this message for a second and then the site loads.

I have now switched off the Geolocation
![bug_geo](https://cloud.githubusercontent.com/assets/25871096/24323632/283aa2c0-1181-11e7-9cdf-0b43b1cd2181.png)

**Comment by firstred** [comment]
You can remove this line in the file `/classes/controllers/FrontController.php` to solve it: `include_once _PS_GEOIP_DIR_.'geoipcity.inc';`

**Comment by Vegaanders** [comment]
OK done

**Comment by firstred** [comment]
It's a bug though. Let's keep that open until it's solved for everyone :)

**Comment by Vegaanders** [comment]
OK sorry!

A little too fast.

Anders

**Comment by firstred** [comment]
https://github.com/thirtybees/ThirtyBees/commit/7f0d6b9b4310252395b8110d7acffa715f1c720b

Now it's solved :)
