### ISSUE TITLE
OrderInvoice: Implicit conversion from float to int loses precision

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/thirtybees#1578]
Multiple PHP 8.1 deprecation warnings are showed in collectlogs:

```
Deprecation	Implicit conversion from float to int loses precision	classes/order/OrderInvoice.php:555
Deprecation	Implicit conversion from float to int loses precision	classes/order/OrderInvoice.php:556
Deprecation	Implicit conversion from float to int loses precision	classes/order/OrderInvoice.php:564
Deprecation	Implicit conversion from float to int loses precision	classes/order/OrderInvoice.php:565
```

**Comment by getdatakick** [comment]
Now this is beautiful bug. Nice example that these pesky PHP warnings can be useful.

I didn't even know that PHP does not support `float` as array keys. It instead casted them to `int` first:

```php
  $arr = [
     10 => 'oh',
     20 => 'no',
  ];
  echo $arr[10.4] . ' ' . $arr[20.9]; // prints "oh no"
```

We are using tax rates (float number) as key for tax breakdown 

https://github.com/thirtybees/thirtybees/blob/088c7fe025b23ff7eaa7f08e6fe78d81c175be75/classes/order/OrderInvoice.php#L554-L562

This can lead to some data loss, merging of similar tax rates together, or whanot.
