### ISSUE TITLE
Product PNG image

### ISSUE THREAD

**Issue by e-com-presta** [thirtybees/thirtybees#1579]
Error occurs if you have JPG images enabled in configuration and add a PNG image to the product.

#### Message: 

`exif_read_data(PS638e0f5435c9b3.05236110mgsapk): File not supported`

#### Location
`classes/ImageManager.php line 270`

#### Stacktrace
```
#0  builtin
#1  classes/ImageManager.php(270): exif_read_data("/home/ecom/public_html/tbtest/img/tmp/PS638e0f5435c9b3.05236110mgsapk")
#2  controllers/admin/AdminProductsController.php(5098): ImageManagerCore::resize("/home/ecom/public_html/tbtest/img/tmp/PS638e0f5435c9b3.05236110mgsapk", "/home/ecom/public_html/tbtest/img/p/2/6/26.jpg", null, null, "jpg", false, 0)
#3  classes/controller/AdminController.php(570): AdminProductsControllerCore->ajaxProcessAddProductImage()
#4  controllers/admin/AdminProductsController.php(1349): AdminControllerCore->postProcess()
#5  classes/controller/Controller.php(204): AdminProductsControllerCore->postProcess()
#6  classes/Dispatcher.php(863): ControllerCore->run()
```

**Comment by eschiendorfer** [comment]
What is the correct way/idea to fix this? We have the same problem with webp...

**Comment by getdatakick** [comment]
I think we can remove this from core completely. Thirty bees tries to determine the camera orientation, and rotate the appropriately. I believe it's not needed, and we should always use the source file as is.
