### ISSUE TITLE
Update of native modules: translation deleted

### ISSUE THREAD

**Issue by e-com-presta** [thirtybees/thirtybees#1585]
Module update process deletes all translation files.

**Comment by getdatakick** [comment]
This is related to issue #922, and thirtybees/homeslider#3

During update, `tbupdater` module wipes out entire module directory, and replaces it with fresh content.

This does not happen when module zip file is uploaded directly in back office -- in that case, files are merged into existing directory.

Both approaches have their drawbacks
- With merging, it's highly possible that deleted code from previous module versions will be be present on the system. If module uses some sort of smart autoloader, these files can be even loaded and executed -- fatal compilation issues, security issues, etc.
- With replacing, we are loosing any data that was stored inside module directory after update. In case of `homeslider` module it was upload files. In this case, it's translations.

For translations, we could probably implement smart merging. However, one could also argue that `translations` dir inside module directory should only contain translations provided by default developer, and should never be modified. Any modification should be stored on different translation level (theme)

**Comment by e-com-presta** [comment]
I also think that a better location for translations is theme directory.
However, the standard "Add / Update a language" option from AdminTranslations loads translations into the module root directories.
And again, no one does translations at theme level.

**Comment by getdatakick** [comment]
This is resolved in bleeding edge. `tbupdater` module is no longer used, and modules data are merged.
