### ISSUE TITLE
Languge: flag can be wrong

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/thirtybees#1587]
When installing language, system uses two letter [language iso code](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) to find flag image. Flag images are stored under two letter [country codes](https://en.wikipedia.org/wiki/ISO_3166-1), though.

In most cases this is not the issue, as language and country code is the same. Sometimes, this is not the case. For example, language code for estonia is `et`, but country code is `ee`. So the flag is stored as `ee.png`, but language uses `et.png` which is flag of Ethiopia. 

Simlarly, czech language code is `cs`, but country code is `cz`.

The fix could be based on extraction of country code from 5-letter language code (`et-EE` / `cs-cz`). Or we could implement mapping from language to country.

**Comment by Zengraph** [comment]
I believe mapping is the way to go.. as it can me customized if necessary or in future if standards change.
