### ISSUE TITLE
Combinations import errors - does not show combinations - double slash between domain name and category

### ISSUE THREAD

**Issue by alwayspaws** [thirtybees/ThirtyBees#159]
Combinations import errors - does not show combinations. There is a **double slash between the domain name and the category.**

Imported products and it was successful. Reindexed. Cleared Cache.
Imported combinations and it was successful. Reindexed. Cleared Cache.

On the home page single products show up and work fine, but clicking on the combo tee-shirt, goes here:

page not available: **PLEASE NOTICE the double forward slash in between .com and dog-t-shirt: I don’t know where it’s coming from or how to fix it.**

https://prestatest.alwayspaws.com//dog-t-shirt-tee-shirt-printed-with-love-is-a-four-legged-word

Only three products are on my site and only two can be purchased due to this error.

Thanks!

**Comment by firstred** [comment]
Superseded by: https://github.com/thirtybees/ThirtyBees/issues/161
