### ISSUE TITLE
Wishlist Module - PHPv8.1 - TypeError: count(): Argument #1 ($value)

### ISSUE THREAD

**Issue by jcolls** [thirtybees/thirtybees#1592]
Hi There,
Upgraded from PHP 7.4 to 8.1 and was receiving 500 errors when viewing product pages.

In the error log I found this.

`*ERROR* 	2022/12/23 - 12:47:21: TypeError: count(): Argument #1 ($value) must be of type Countable|array, bool given in template file themes/niara/modules/blockwishlist/blockwishlist-extra.tpl`

So I disabled the Wishlist Block and the product pages displays fine.

I don't know how to fix this but thought I should highlight it.

**Comment by getdatakick** [comment]
Thank you. This is actually already fixed in niara. You can either update niara to latest version, or apply the fix yourself.

https://github.com/thirtybees/niara/commit/ff11a59ccc98a1d3340d04f50655014c266b2416
