### ISSUE TITLE
Db::__destruct should unregister connection from pool

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/thirtybees#1600]
Following sequence leads to exception:
```php
Db::getInstance(_PS_USE_SQL_SLAVE_)->__destruct();
...
...
Db::getInstance(_PS_USE_SQL_SLAVE_)->execute('select * from table');
```

Calling `__destruct` will set internal `$link` property to `null`, which makes Db instance unusable. This instance is still referenced in `$instance` array, and can be returned by subsequent `Db::getInstance` call.

We should remove instance during `__destruct` call. Also, we should check all `$link` usage, and verify it's valid. That would prevent situations like this:

```php
$conn = Db::getInstance();
$conn->__destruct();
...
...
$conn->execute("select * from table");
```

**Comment by therampagerado** [comment]
Bit me hard in the arse.... restoring the shop after my 'fixes'.... :( 

There's a workaround for my issue but I believe this could pose much bigger issues.
