### ISSUE TITLE
Filemanager: remove dependency on session

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/thirtybees#1604]
File manager script in back office uses PHP sessions for authentication, instead of validating back office cookies. 

Sessions are disabled on some php servers, so it makes this whole functionality unusable

**Comment by musicpanda** [comment]
Maybe good to remember that Filemanager is a plugin for TinyMCE. Unfortunately this plugin hasn't been maintained for 9 years.
https://github.com/Tsubashi/TinyMCE-FileManager

**Comment by e-com-presta** [comment]
> Maybe good to remember that Filemanager is a plugin for TinyMCE. Unfortunately this plugin hasn't been maintained for 9 years. https://github.com/Tsubashi/TinyMCE-FileManager

This file manager is used in thirty bees:
https://github.com/trippo/ResponsiveFilemanager/
