### ISSUE TITLE
rename displayPrice in tools.js

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/thirtybees#1607]
I previously made a forum post about a conflict between the function displayPrice() in tools.js and AWP: 
https://forum.thirtybees.com/topic/6009-awp-and-thirty-bees/

I looked a little further and I saw that Prestashop 1.6.1 uses the function formatCurrency(() for the same purpose. When you look in Thirty Bees that function formatCurrency is still there but it calls the function displayPrice() with exactly the same arguments. Interesting is that this TB function formatCurrency also contains a comment:
`// Really? It's used quite a lot.
  //console.log('Deprecated with v1.1.0. Use displayPrice() directly.');`

displayPrice has a comment too:
` * This also uses global priceDisplayPrecision, so this should be right.
 * Formatting should match Tools::displayPrice().`

My conclusion is that the only reason for renaming this function was to make it have the same name as its Tools.php equivalent. A comment in Tools.php says that even explicitly. 

I think this was a bad reason for renaming a function and it should be turned back.

**Comment by getdatakick** [comment]
I'm not against it, as I don't like like polluting global space.

However, removing stuff from core is problematic, as there can be modules/themes that depends on it already.

Did you do analysis how much widespread is usage? If it's only core that is using this function, we might be lucky. However, if there are some modules or themes, we need deprecation path. Deprecation warnings, and removing only after at least one release.

**Comment by musicpanda** [comment]
As far as I can see only two files use it:
/js/admin/price.js
/js/admin/orders.js

A search for "displayPrice(" doesn't return more javascript files. I am now testing Panda with the function name removed. Until everything looks ok.

I assume you have a wider overview than me of software adapted for Thirty Bees.

**Comment by getdatakick** [comment]
I did a quick check, and it doesn't look like any tb native module and theme is using this function. 
Let's hope that no third-party module started using this function.

**Comment by getdatakick** [comment]
I've removed this function in commit 4908ec86b34a2fc3a78ea22508d0cdf42c5855bb.

Let's hope it will not cause any problems with third party modules/themes.

**Comment by musicpanda** [comment]
Thanks for removing it.

May I suggest removing the comment in Tools.php that discussed the connection between displayPrice() in Tools.php and its javascript equivalent in tools.js? It could become confusing in the future.
![dispprice](https://user-images.githubusercontent.com/13930107/214557759-2c9ed8a4-496f-44ed-bb04-7748e5ea522f.jpg)
