### ISSUE TITLE
Strange product_supplier behavior with incomplete database

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/thirtybees#1617]
Normally I wouldn't mention a problem that you see when the database is not consistent. But this case is so strange that it should at least be noted. 

When a product has attributes the product_supplier table has an entry for each of them plus an entry for attribute 0. So a product with 5 attributes and one supplier will have six entries in the tb_product_supplier table. Now in this case one of the attribute entries had disappeared (I don't know why) and the product had only 5 entries in total.

When I opened the product edit page in the backoffice and when to the supplier tab it still looked complete. The missing attribute had its own line where you could enter a reference and a price. So I entered a reference for that attribute and pressed save. The result: not only had the missing attribute value not been inserted, but also one of the other attribute records had been deleted. So now the database had only four entries for this product. For every save another attribute value was deleted. When the last attribute value had been deleted the 0 value was deleted too so that the product no longer had this supplier.

**Comment by getdatakick** [comment]
I can't reproduce this on bleeding edge.

Is this only issue on your store, or can you reproduce on other environments as well?

**Comment by musicpanda** [comment]
It indeed seems local. I withdraw this report.

**Comment by getdatakick** [comment]
Thanks for confirmation. It would be quite serious if this bug was in the core.
