### ISSUE TITLE
Shipping_number length (65) and removing the https://

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#1631]
**I - Shipping_number length (65)**

We fill in the tracking number field, with the tracking link.

![image](https://user-images.githubusercontent.com/38436949/218241527-51c3833c-ed6c-4289-aa97-39934ccedb0b.png)

That link crashes the site.

![image](https://user-images.githubusercontent.com/38436949/218241536-020b0fa0-976b-41df-bdda-d089b5e17c17.png)

Because the Shipping_number have a length of 65 must be between 0 and 64.

![image](https://user-images.githubusercontent.com/38436949/218241559-5d5ee1b7-41c9-443a-b0d5-e835bdedeb93.png)

**II - Removing the https://**

We removed the https:// and it works.

![image](https://user-images.githubusercontent.com/38436949/218241574-14a161b1-68a5-4f84-9855-b61ac2485231.png)

**Comment by ToplakD** [comment]
You have to enter only the tracking number, not complete tracking link.
This is not how tracking works in Thirtybees.

**Comment by getdatakick** [comment]
Entering complete url was not intended. You should enter just a tracking number, and then set **Tracking Url** template on Carrier with placeholder `@` -- this placeholder will be replaced with entered tracking number. 64 characters should be more than enough for any tracking numbers.
