### ISSUE TITLE
The email it’s done to send the Tracking number but it didn’t send

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#1632]
We fill in the tracking number field, with the tracking link.

![image](https://user-images.githubusercontent.com/38436949/218241745-0d48ac20-9695-4371-85ab-e004298b7d2c.png)

The TB do the update of the tracking number field, with the tracking link.

![image](https://user-images.githubusercontent.com/38436949/218241757-4e3ddb68-2d4f-4202-ae92-6663ff58a2e8.png)

The customer receives the email.

![image](https://user-images.githubusercontent.com/38436949/218241773-3c02bd65-f499-4759-9051-395cf29b541a.png)

.
.
.
**But the email didn’t bring the tracking link (Tracking number).**

![image](https://user-images.githubusercontent.com/38436949/218241793-36f8171a-e6d5-44f4-8700-914a0ae83bc0.png)

**Comment by ToplakD** [comment]
This is not how tracking works.

You add tracking link in Shipping/Carrier/General settings for that particular carrier, and enter just a tracking number on the order. That number than replaces the @ in tracking link and email is sent out. with the link.

![carriers](https://user-images.githubusercontent.com/39807649/218246887-7c94f3bf-19a1-404f-8a33-a234772d11c9.png)

**Comment by getdatakick** [comment]
If the **Tracking URL** template is not set for carrier, then the resulting tracking url after interpolation will be empty. That is expected behavior.

If you enter complete tracking url (not just number) on orders, then you have to at least enter '@' inside Tracking Url on carrier
