### ISSUE TITLE
@ on “Tracking URL”

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#1634]
At this moment on order, we only can add a tracking number, and then the email goes to pick up the carrier on the carrier's URL.

But we work with lots of suppliers and each supplier has several carriers we only know the carrier when the supplier sends us the carrier URL track to send to our own customers.

And we don’t have a place to send this information to the customer.

A new good feature is to allow us to add a carrier link to the email.

![image](https://user-images.githubusercontent.com/38436949/218941025-9b8d4ab7-f921-41ac-a331-49b5eb178c0b.png)

With @ on “Tracking URL” send direct the tracking URL.

![image](https://user-images.githubusercontent.com/38436949/218941992-39335917-d2d7-499a-8b30-faec4f348838.png)

**Comment by Dh42** [comment]
This does not directly answer your question, but one of the apps we developed provides tracking information based on that input, without knowing which carrier actually shipped the product. We use Ship24 to pull the tracking info. You might test that your carriers all work with it, it supports like 180 carriers. But all you would need to do is use their format, https://www.ship24.com/tracking?p=  for the tracking link and it should detect the carrier with your tracking number. I have done this with a few shops in the past as well.

**Comment by getdatakick** [comment]
I have removed validation for absolute URL for this field, so now it's possible to enter only `@` as Tracking URL template.
