### ISSUE TITLE
Enable/disable: Your message has been correctly sent

### ISSUE THREAD

**Issue by ToplakD** [thirtybees/thirtybees#1652]
Is it possible to add option to customer service contacts to enable disable the "correctly sent message" to the senders email?
This is mostly used to send out spam through contact forms, where one enters different email recipient to send various spam advertisements.

Currently I always comment out the 232 line in ContactController.php.
So button to enable/disable this function would be very welcome to many users.

![Customer-service](https://user-images.githubusercontent.com/39807649/221909739-c6faa1f5-237a-4cba-93db-7c2cebdadda9.png)

**Comment by getdatakick** [comment]
Easy one, let's make it happen
