### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/thirtybees#1656]
![image](https://user-images.githubusercontent.com/11251370/223096096-221b010a-281d-43a5-a744-3d3305805322.png)

**Comment by getdatakick** [comment]
This is a bug in override, not in the core. 

What module this override comes from? Is it some thirty bees native module?

**Comment by therampagerado** [comment]
No idea, I was unable to trace it back to any Warehouse or 3rd party module. Here's a list from my overrides:

![image](https://user-images.githubusercontent.com/11251370/223098528-4bf2b4bd-d589-4825-9795-cf9ede87d5a1.png)

**Comment by therampagerado** [comment]
Oh... I'm blind. Obiously Warehouse is adding this override by plugin adder.

![image](https://user-images.githubusercontent.com/11251370/223099192-af3d6f18-d633-4183-ad12-4ffbad795360.png)

Sorry, for bothering will try to sort out by myself!

**Comment by therampagerado** [comment]
Fixed:

			Hook::exec('actionSearch', array(
				'expr' => $tag,
				'total' => iscountable($result)
			));
