### ISSUE TITLE
Modules: invalid zip file can pollute modules directory

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/thirtybees#1669]
Uploading zip file that does not contain module can pollute `/modules/` directory. 

We should unzip file into some tmp location, validate that the content is valid, and only then move new module directory into `/modules/` dir

**Comment by Zengraph** [comment]
OK, do you have any clue about that task "validate that the content is valid" ? how to do that ? 
Already if the content of the zip is not seen as a module, it is deleted after being unzipped.

**Comment by therampagerado** [comment]
You can create 1.txt, zip it ad upload. Check result.
