### ISSUE TITLE
Warning Undefined array key: template suppliers.tpl

### ISSUE THREAD

**Issue by e-com-presta** [thirtybees/thirtybees#1682]
Error occurs if no supplier is created.

Message:
```
Undefined array key #number
Undefined array key 1
```

Location:
```
admin/themes/default/template/controllers/products/suppliers.tpl
```

**Comment by getdatakick** [comment]
The root cause of this problem was that thirty bees did not delete related records from `tb_product_supplier` table when parent record was deleted in `tb_supplier` table.
