### ISSUE TITLE
Unable to delete products from cart

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/thirtybees#1685]
![image](https://github.com/thirtybees/thirtybees/assets/11251370/72b92972-c5ad-4d30-9de9-75bd30098eec)

This error appears on most current edge (as of yesterday) when removing products from the cart.

Found by [SLiCK_303](https://forum.thirtybees.com/profile/323-slick_303/?wr=eyJhcHAiOiJmb3J1bXMiLCJtb2R1bGUiOiJmb3J1bXMtY29tbWVudCIsImlkXzEiOjYxNzMsImlkXzIiOjQ2Njg1fQ==), forum thread - https://forum.thirtybees.com/topic/6174-150-be-atm

**Comment by therampagerado** [comment]
It does it only for instock products w/o combinations.

Products with combinations work fine.

**Comment by therampagerado** [comment]
And here's the faulty line: 
![image](https://github.com/thirtybees/thirtybees/assets/11251370/37702cee-c6a5-4b1e-af62-bdafa0a52729)

**Comment by getdatakick** [comment]
This is not related to the issue reported by @SLiCK-303 in any way. This is issue in front office, not in back office

**Comment by therampagerado** [comment]
It appears when I click on the X in the cart.

**Comment by therampagerado** [comment]
Offf... wrong forum thread.... Sorry, will edit it now

**Comment by getdatakick** [comment]
Thanks for reporting this. 

The intent of this new method `getIntValue()` is to prevent SQL (and other) injections. But it was way too strict. I have downgraded the error to warning, so we can still make codebase better without causing unnecessary troubles.
