### ISSUE TITLE
Currency presentation in customer view

### ISSUE THREAD

**Issue by x97wehner** [thirtybees/thirtybees#1690]
In the attached image, the order is in CAD for the amount shown. Our store is USD based. There is no way to tell from this view if this total was in USD or CAD. I would expect this view to show a USD converted total as it's our primary currency. I think there is a store currency total on the order which should be totaled.

**Comment by x97wehner** [comment]
![image](https://github.com/thirtybees/thirtybees/assets/44684415/4884a211-11a8-40bf-915b-f51a1f112a40)

**Comment by getdatakick** [comment]
The SQL sub-select that calculates total spent amount looks like this:

https://github.com/thirtybees/thirtybees/blob/6a20b68807eb9f0a8d3da3722e8fb7d0e95fb9eb/controllers/admin/AdminCustomersController.php#L196-L203

It takes data from order payments (not order itself), and sums ((amount paid) / (conversion rate as of payment date)).

When payment module records payments, it stors current conversion rate between payment currency and store default currency into `tb_order_payment` table. 

In this case, it is likely that your conversion rate at the time of payment was 1.00

Look into `tb_order_payment` to see what currency rate was used.
