### ISSUE TITLE
Module 'thirty bees Updater' [tbupdater] is not compatible with target version of thirty bees

### ISSUE THREAD

**Issue by ToplakD** [thirtybees/thirtybees#1693]
After latest Core updater upgrade the following message appears:

Found 1 installed modules incompatible with thirty bees 1.5.0.
Module 'thirty bees Updater' [tbupdater] is not compatible with target version of thirty bees

It only happens if distribution channel is set to bleeding edge, on stable it works as ussual.

**Comment by getdatakick** [comment]
That is correct. Functionality to update modules has been moved to Core, so tbupdater is no longer needed/wanted on bleeding edge.
