### ISSUE TITLE
Bulk Delete Issue

### ISSUE THREAD

**Issue by pjrp** [thirtybees/thirtybees#1697]
Had this problem with a customer ranting for ages about missing cart rules.... 
After many hours investigating finally found the issue. 

Using ThirtyBees 1.4.0

class adminControllerCore > processBulkDelete does not check if object is loaded before deleting, causing unexpected behaviours. 

Example: Customer bulk delete, ends up inadvertently deleting cart_rules with id_customer = 0.

Steps to reproduce:
1. Create a Cart Rule, for example free shipping above 50€ for all,
2. Open two browser tabs in AdminCustomers listing.
3. In the first tab, delete a customer
4. In the second tab, select all checkboxes. Then, bulk actions > delete selected;
5. Check the cart rule created in step 1. It was deleted.

Seems like an easy fix, can you guys please throw in an if(Validate::isLoadedObject($to_delete)) to patch this?

Thanks!

**Comment by getdatakick** [comment]
This has already been fixed in bleeding edge, commit 7c5295cdefb5f0f422598953a96ae04f4712312b.

Thanks for reporting this anyway!

**Comment by getdatakick** [comment]
Also added extra fix fox non-bulk deletion mode: e5da8421728d73ef0e11a710ce1a55d24f955a5d
