### ISSUE TITLE
Customers contacts and disabled the “Subject Heading”

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#1707]
The old post #823 Enabled or Disabled the “Subject Heading” it’s closed and solved.

Now on TB 1.4.0, we can’t find the column of Enable or Disable.

![image](https://github.com/thirtybees/thirtybees/assets/38436949/ca332788-a7a1-4d4c-b55f-d35531059c2e)

**Comment by getdatakick** [comment]
Of course, it's not part of 1.4, but will be part of upcoming release 1.5 / bleeding edge
