### ISSUE TITLE
Text box in pages not showing

### ISSUE THREAD

**Issue by Kingsman40** [thirtybees/thirtybees#1709]
Hello,

As the title says, the text box to enter information on Pages is not showing. I don't have anyway to add text. 

(https://postimg.cc/c6QP0kL4)

**Comment by getdatakick** [comment]
I can't reproduce this problem, CMS pages are editable without issues.

![image](https://github.com/thirtybees/thirtybees/assets/34651851/1eac4add-6fb1-465f-bf6b-cc27533632e0)

I suspect the problem will be with some javascript error being thrown in your back office. Please open browser javascript console, and look for any javascript errors. 

Please let us know when you have more info.
Also, provide information about your thirty bees version.

**Comment by Kingsman40** [comment]
I figured out the issue. On Chrome it works fine, but on Firefox, the
textbook wouldn't show.

**Comment by getdatakick** [comment]
I've tested on latest firefox, and it works without issues

You might have some browser extension / plugin / adblocker that prevents site from working properly
