### ISSUE TITLE
Most modules install "uninstalled"

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#171]
Yesterday I made an installation package from current Git and installed that. It comes with some 85(wow!) modules. However, after the installation, only 15 of them show up as "installed" when looking in Back Office -> Modules and Services.

Also interesting: the statistics box above the module list notes 65 installed modules.

![module list](https://cloud.githubusercontent.com/assets/318581/24857019/0773b64a-1de7-11e7-9df6-76f3d06bacaf.png)

One of the "uninstalled" modules is e.g. ImageSlider. Back Office claims it's uninstalled, still it's visible and works perfectly fine in Front Office. If I click on "install", this error message shows up: "This module is already installed: homeslider." The menu in the modules' row still shows only "Install" and "Delete", configuration not possible.

![homeslider already installed](https://cloud.githubusercontent.com/assets/318581/24856995/e1bcd350-1de6-11e7-8be6-46a71cba6f60.png)

**Comment by Traumflug** [comment]
Some observations:

- Just loading the modules page calls ```TbUpdater::checkForUpdates```. Not sure if this is wanted behavior. There's also a 'Check for update' button near the top of the page.
- ```$lastCheck``` in ```TbUpdater::checkForUpdates``` is always zero, so the module always fetches for updates.
- The result of this fetch is just 5 modules.
- ```AdminModulesControllerCore::__construct()``` watches out for a module cache in ```config/xml/modules_list.xml```. However, I can't find any code writing this file and with a fresh installation, it doesn't exist.

**Comment by Traumflug** [comment]
5. All the modules not showing up get filtered in ```AdminModulesController::isModuleFiltered``` because they have no ID, ```$module->id``` is zero or entirely empty.

**Comment by Traumflug** [comment]
6. When attempting an installation, a check whether it's already installed (to avoid double-installation) is done twice. Once in ```Module::install()``` and once in ```AdminModulesController::postProcessCallback()```. One of them should be obsolete.

**Comment by firstred** [comment]
The ID of a module was set on a clone instead of the original object. This caused only some modules to show up as installed: https://github.com/thirtybees/thirtybees/commit/2f68b8cbd0c5c731bd0e29a8ffec427391cfa3b3

Thanks a lot, this was a really really good report!

**Comment by firstred** [comment]
> When attempting an installation, a check whether it's already installed (to avoid double-installation) is done twice. 
> Once in Module::install() and once in AdminModulesController::postProcessCallback(). One of them should be obsolete.

I'm going to keep this one for the moment. It is indeed redundant, but the context of the check determines what warning message should be shown.

**Comment by Traumflug** [comment]
Thanks for fixing it! Modules list now as expected :-)
