### ISSUE TITLE
Create a table to store a change of date

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#1711]
Create a table to store a change of date.

For example, if the customer changes the phone, we can store the Phone with information from 1/1/2020 to 1/1/2022.

![image](https://github.com/thirtybees/thirtybees/assets/38436949/f0a1ee7e-994b-4d97-99b4-67cc48bc7c77)

**Comment by getdatakick** [comment]
This is not responsibility of e-commerce core. It would require a lot of database space, an it would degrade performance.

We have implemented Audit Logs module that performs this task -- it records changes to individual entities (products, customers, ...) so you can see who and when made a change.

This module will be available for download soon.
