### ISSUE TITLE
Multishop - order list: order duplication

### ISSUE THREAD

**Issue by Yabbertb** [thirtybees/thirtybees#1719]
In multishop option, all orders are duplicated as many times as there are stores.
![Screenshot_20230907_181153](https://github.com/thirtybees/thirtybees/assets/144372521/4bf237f0-56a1-4b58-be77-7d4174ccd096)

**Comment by getdatakick** [comment]
It works fone in my multistore environment.

What tb version are you using?

**Comment by Yabbertb** [comment]
Sorry for the erroneous notification.
Duplicate orders were caused by a bug in override of the AdminOrders controller.
