### ISSUE TITLE
Tax Calculation Error When Applying Discounts for Multi-Category Price Rule Products

### ISSUE THREAD

**Issue by uguranium** [thirtybees/thirtybees#1720]
I'm experiencing an issue with discounts in Thirtybees. When I set up a new price rule and navigate to the conditions tab, I select "Product selection" and then choose "Add a rule concerning" for categories, and subsequently select the relevant categories.

However, my product is associated with multiple categories. When a customer uses this cart rule (voucher) to purchase the product at a discount, the tax calculation displayed on the tax-tab (located on the left side of the invoice) is incorrect. This seems to be because the base price is being calculated without considering the discount.

<img width="1044" alt="wrong_discount_tax" src="https://github.com/thirtybees/thirtybees/assets/18717007/be7004f2-7c59-48b8-bdcd-a352e1af512f">

When I don't apply any conditions, everything works correctly. However, when conditions are applied, the tax calculations are inaccurate. I've tested this on Thirtybees version 1.4.0, and there are no specific modules or themes installed.

**Comment by getdatakick** [comment]
It's likely this is fixed by commit 2b426ce1286c22c56b6dbbf9f56f023d02e94ac1.

Could you verify?
