### ISSUE TITLE
Column ps_employee.last_connection_date should NOT have default value '1970-01-01 00:00:00'

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/thirtybees#1722]
![image](https://github.com/thirtybees/thirtybees/assets/11251370/be3d1b32-e549-48db-9085-bd5cf9d4daa5)

After each update to edge after this fix was introduced it's reappearing in the DB section.

**Comment by getdatakick** [comment]
what db version are you using?

**Comment by therampagerado** [comment]
![image](https://github.com/thirtybees/thirtybees/assets/11251370/827b5c39-6e21-4fc5-a111-e2892baf1d4c)

**Comment by therampagerado** [comment]
![image](https://github.com/thirtybees/thirtybees/assets/11251370/eeb23c6f-a2e1-46f0-b6dc-57c7027794ad)

**Comment by getdatakick** [comment]
This was a bug in coreupdater module. Fixed
