### ISSUE TITLE
CMS category

### ISSUE THREAD

**Issue by Yabbertb** [thirtybees/thirtybees#1723]
Does the 'description' in CMSCategory class have to be TYPE_STRING?
Not being able to enter CMS category description in HTML format is a big drawback when it comes to SEO of CMS category pages.

**Comment by getdatakick** [comment]
Indeed, there's no reason for this. Let's do it. Such change in core will, however, need theme support. 

In template **cms.tpl**, every occurance of 
```smarty
{$cms_category->description|escape:'html':'UTF-8'}
```
will have to be replaced with
```smarty
{$cms_category->description}
```
