### ISSUE TITLE
"Save all" button for admin translations

### ISSUE THREAD

**Issue by 30knees** [thirtybees/thirtybees#1726]
Currently, each "section" or "block" within the admin translation page has its own "save" button. This means one cannot edit translations across sections or blocks in one go, for example if one wants to replace the same phrase or word across multiple sections.

Having a "Save all" button for the whole page would let a user work quicker.

**Comment by therampagerado** [comment]
We are tracking this regression here: https://github.com/thirtybees/thirtybees/issues/1434

The issue is that most hosting plans have very low max_input_vars settings and clicking save all used to lead to a timeout.

**Comment by 30knees** [comment]
Understood. Then I'll close this issue. Thank you!
