### ISSUE TITLE
Many code dependencies exist twice

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#173]
It just occurred to me that most of the imported code packages exist twice. For example, Smarty is in ```tools/smarty``` as well as in ```vendor/smarty/smarty/libs```. I take that the 1.0.1 release is going to be kind of a cleanup-release, so I consider it to be a good idea to remove these duplicates for that.

OK, probably you, @firstred, already know about this issue. If I can help resolving it, please let me know (by giving some hints on how to do it).

**Comment by firstred** [comment]
Yep. Those are backwards compatibility files. Many PS 1.6 modules seem to include the files directly, so they all point to the autoloader now.

**Comment by Traumflug** [comment]
On top of that, content of these duplicates aren't entirely equal, so modules might use a different smarty library than main code. Two distinct library versions for doing the same things aren't exactly the best idea for reliable operations.

Sounds like symbolic links (e.g. tools/smarty -> vendor/smarty/smarty/libs) are a good idea. Linux and Mac OS undoubtly support them, the [related PHP man page](http://php.net/manual/en/function.symlink.php) says, Windows is supported, too. The zip tool has the ```-y``` option. Accordingly these links can go directly into the archive or they can be created at installation time.

Good idea?

**Comment by Traumflug** [comment]
> Good idea?

Maybe a working idea, but no need for it.

Sometimes it helps to start implementing a change just to see that there's no need for it. This way I found out what you mean with "point to the autoloader". All the older files are still there, but each with just 5 lines of code inside: ```require_once _PS_ROOT_DIR_.'/vendor/autoload.php';```. Always the same code, that's why Git reports so many file copies.

Problem solved :-)
