### ISSUE TITLE
Some js files are not being included in windows based systems

### ISSUE THREAD

**Issue by pjrp** [thirtybees/thirtybees#1744]
I think there is issue in class Media.php with windows based systems.

Apache/2.4.54 (Win64) OpenSSL/1.1.1t PHP/8.0.30

Thirty bees version: 1.6.0
Thirty bees revision: [baa095b098aa369cc0b085b72fb36450bbb06174](https://github.com/thirtybees/thirtybees/tree/baa095b098aa369cc0b085b72fb36450bbb06174)
Build for PHP version: 8.0

My test shop is missing inclusion of some js files causing issue in the frontend and admin themes. 

For example:

- files in the js/autoload theme folder
- controller.js from the core updater v1.6.6.

Done some testing in function getLocalMediaFilePath($uri), i got a sample of the offending URIs:

"C:\laragon\www\shop/themes/niara/js/autoload/10-bootstrap.min.js"
"C:\laragon\www\shop/modules/coreupdater/views/js/controller.js"
...

I was unable to find how _PS_ROOT_DIR_ is added to some js files and not others.

Could we fix this by removing _PS_ROOT_DIR_  before calling getLocalMediaFilePath() ?

$mediaUri = str_replace(_PS_ROOT_DIR_, "",  $mediaUri);

**Comment by getdatakick** [comment]
While thirty bees is officially not supported on windows, I believe this should be fixed anyway.

Anyone with windows box, please try to fix and provide PR. I don't have access to windows machine myself :)

**Comment by deweblooper** [comment]
This can be a solution,
I´ve made it with comparing results of function on Windows and Linux server, it works without issues,
can be used as override, or if you decide to pull it to official TB, I will be happy.

```
class Media extends MediaCore
{

	/**
	 * for different server environments
	 */
    public static function getLocalMediaFilePath($uri)
    {
        if (! $uri) {
            return false;
        }

        $uri = (string)$uri;

        // if file exists locally, include its modification timestamp into uri as a version parameter
        $parsed = parse_url($uri);
        if (!array_key_exists('host', $parsed) && isset($parsed['path'])) {
            $path = $parsed['path'];
            $rootDir = rtrim(str_replace('\\', '/', _PS_ROOT_DIR_), '/');
            $filePath = $rootDir . '' . $path;	// deleted slash separator as unnecessary in both environments
            if (file_exists($filePath) && is_file($filePath)) {
                return $filePath;
            }
            $mediaUri = '/' . ltrim(str_replace($rootDir, __PS_BASE_URI__, $path), '/\\');
            if (isset($parsed['scheme'])) {
                // windows environment
                $mediaUri = $parsed['scheme'] . ":" . $mediaUri;
                $filePath = $mediaUri;
            } else {
                // linux environment
                $filePath = _PS_ROOT_DIR_ . Tools::str_replace_once(__PS_BASE_URI__, '/', $mediaUri);
            }
            if (file_exists($filePath) && is_file($filePath)) {
                return $filePath;
            }
        }

        return false;
    }
	
	
}
```
