### ISSUE TITLE
'ThirtyBeesDatabaseException: Duplicate entry '2-7-0-0-2023-12-24 00:00:00-2023-12-31 08:00:00-1-0-0-0-0-1-1' for key 'id_product_2' when entering more than 3 condition groups in Catalog Price Rules

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/thirtybees#1746]
Bug reported in forum - https://forum.thirtybees.com/topic/6427-catalog-price-rules/#comment-48139

Managed to replicate on new edge test installation.

EXCEPTION
Message:
ThirtyBeesDatabaseException: Duplicate key value
ThirtyBeesDatabaseException: Duplicate entry '2-7-0-0-2023-12-24 00:00:00-2023-12-31 08:00:00-1-0-0-0-0-1-1' for key 'id_product_2'

Location:
classes/ObjectModel.php line 608
SQL
INSERT INTO `DB_specific_price` (`id_specific_price_rule`, `id_cart`, `id_product`, `id_shop`, `id_shop_group`, `id_currency`, `id_country`, `id_group`, `id_customer`, `id_product_attribute`, `price`, `from_quantity`, `reduction`, `reduction_tax`, `reduction_type`, `from`, `to`) VALUES ('1', '0', '2', '1', '0', '0', '0', '0', '0', '7', '-1', '1', '3', '0', 'amount', '2023-12-24 00:00:00', '2023-12-31 08:00:00')

**Comment by getdatakick** [comment]
@therampagerado Can you please provide exact reprosteps? I don't really know how to test this

**Comment by pjrp** [comment]
> @therampagerado Can you please provide exact reprosteps? I don't really know how to test this

Had to patch it in my install. Its possible there are many ways of reproducing it as there is no verification if rule was already applied to the product.

Reprosteps:

1. Associate a product with more than one category. 
2. Add a catalogue rule that includes both categories as condition.

Saving this rule will, will cause this duplicate entry exception.

**Comment by therampagerado** [comment]
@getdatakick I did exactly what was given as info in the initial thread - created a new Catalog Price Rule with 3 or more sections and upon saving it I get the exception:
![image](https://github.com/thirtybees/thirtybees/assets/11251370/3a7f5e3e-e98f-4e9a-8a03-a267c3db3034)
