### ISSUE TITLE
The list of updateable modules is not correct

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/thirtybees#1759]
When I look at the modules page I see at the top a list of modules that can be updated. However, this list looks strange. It lacks modules that in the list below are shown as having and update and it includes something outdated as tbupdater.
![img1](https://github.com/thirtybees/thirtybees/assets/13930107/84d3df3a-611b-47b2-9ecc-757cb0922680)
![img2](https://github.com/thirtybees/thirtybees/assets/13930107/cb211362-e463-4c5c-8db2-8266de0b5963)

**Comment by getdatakick** [comment]
What's your thirty bees version?
