### ISSUE TITLE
Search checks wrong category table

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/thirtybees#1760]
Recently I had a problem that a product was visible everywhere and its category was visible too. And yet it didn't turn up in the search results. It turned out that the product was active in the `tb_category_shop` table but inactive in the `tb_category` table.

In the function find() in `/classes/search.php` search is done in two steps. The first step selects all eligible products (active, etc), the second searches for the keyword(s). The common products of those two searches are then returned. It is the first step that is problematic. It looks like:
```php
        $searchSql = (new DbQuery())
            ->select("DISTINCT `cp`.`id_product`")
            ->from('category_product', 'cp')
            ->innerJoin('category', 'c', '`cp`.`id_category` = `c`.`id_category`')
            ->innerJoinMultishop('product', 'p', 'ps', '`cp`.`id_product` = `p`.`id_product`')
            ->where('`c`.`active` = 1')
            ->where('`ps`.`active` = 1')
            ->where('`ps`.`visibility` IN ("both", "search")')
            ->where('`ps`.`indexed` = 1');
```

In my opinion this search should use the `category_shop` table here.

**Comment by getdatakick** [comment]
Indeed. Column `category_shop.active` was introduced recently by commit 4e0dd2f4b74c9f9daf03526726e2618a3af170e3. We should replace all usages in core/modules with the new column. This one is definitely one of them.

Thanks for reporting this
