### ISSUE TITLE
Multishop - additional shops don't populate shop name in db - tb_configuration - PS_SHOP_NAME

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/thirtybees#1762]
This results that all shops pick the default shop name and append it to the end of the page titles on some pages (index, contact, sitemap etc.)

Workaround - manually insert the row in the table associating it with the correct shop ID.

**Comment by getdatakick** [comment]
This is configurable in Preferences > Store Contacts > Shop Name. Field is multistore-aware, you can set it individually per store.

**Comment by therampagerado** [comment]
Thanks! I thought this was picked from Multishop -> Shop name.
