### ISSUE TITLE
layered navigation module not working with selecting filter on TB 1.5.0 - 1.5.1

### ISSUE THREAD

**Issue by deweblooper** [thirtybees/thirtybees#1763]
On fresh installation of ThirtyBees version 1.5.0 and 1.5.1 (and also after upgrade older version like fresh 1.4.0 with CoreUpdate module to new 1.5.x)
selecting any of filter values in any Layered Navigation in left column, has no effect to viewed products on products category page.
It occurs both system themes "Niara" and "Comunity Theme Default" too.
Tried with demo products installed.
On Apache with PHP 7.4.33 with:
thirtybees-v1.4.0-php7.4.zip
thirtybees-v1.5.0-php7.4.zip
thirtybees-v1.5.1-php7.4.zip

and Block Layered Navigation v 3.1.3

But it is not fault of module, I´ve tried also older ones, and PS 1.6.24 module also with same results.
In browser developer tools there are 4 errors and some notifications, but one of errors I suspect is about "**general.js**" for non existing function.
Same results on Firefox 119b09 and Chrome 103

**Comment by therampagerado** [comment]
For me at least this is working.

The only issue I have is that the manufacturer filter (and some other) are not working in regards to linking - if I want to make a preselected list everything after # is dropped and all products from selected category are visible.

**Comment by getdatakick** [comment]
Works for me as well. @deweblooper could you please describe detailed repro steps?

**Comment by deweblooper** [comment]
thank you, yes I'll try, but later, I am out of office until march 3rdOdoslané z môjho zariadenia Galaxy
-------- Pôvodná správa --------Od: DataKick ***@***.***> Dátum: 21. 2. 2024  8:20  (GMT+01:00) Komu: thirtybees/thirtybees ***@***.***> Kópia: deweblooper ***@***.***>, Mention ***@***.***> Predmet: Re: [thirtybees/thirtybees] layered navigation module not working
  with selecting filter on TB 1.5.0 - 1.5.1 (Issue #1763) 
Works for me as well. @deweblooper could you please describe detailed repro steps?

**Comment by getdatakick** [comment]
Any update?

**Comment by deweblooper** [comment]
I must confirm, that fresh install TB 1.5.1 on external servers works as expected.
I´ve tried now to install it on:
https://thirtybees.prestasphere.com/
and there are no issues.
I am sorry for loong delay and false alarm as well, guys.
I have to be more precise..

**Comment by deweblooper** [comment]
Now I see connection between this issue and:  https://github.com/thirtybees/thirtybees/issues/1744
Layered navigation is working correctly on real servers, based maybe od Linux, or Windows with different configuration than my local W10, Apache2459, PHP7.3.44, OpenSSL 1.1.1.
Newer Layered Navigation module can´t work without total-storage.js which should be called with autoload path to theme js
Based on issue #1744 I´ve tried to replace Media.php with old Media.php class file from thirtybees version 1.4.x,
and for FO started Layered Navigation module working properly even with thirtybees 1.5.1
But it is not way to resolve issue, new actual Media.php is needed to repair.
