### ISSUE TITLE
Multistore: Custom code per shop is deleted during store updatee process

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/thirtybees#1770]
thirtybees: edge

Multistore: yes

Repo steps: enter custom code in Add extra metas to the header per shop context (let's say custom tracking, GA4, etc.).

![image](https://github.com/thirtybees/thirtybees/assets/11251370/3134684c-6b38-4d39-9d3b-3cf80649bf6f)

Update shop using Core updater. For this test I made a second shop in my test scenario and updated between edge and 1.5.1 (files and table). Currently trying only with js custom code and i don't know if the other fields are affected also.

The custom code is missing in the respectful shop context when the update is done.

![image](https://github.com/thirtybees/thirtybees/assets/11251370/a804dda1-f690-477b-93f9-6bd30b35676a)

Same behavior I get on my official shop, I had argues with my hosting as I thought they rolled back some backup before I set this up but this appeared couple of times today also when I was rolling back to php7.4 (many bugs with Warehouse on 8) and again the GA4 code I put there was gone so I tried on my second shop and I managed to reproduce it.

**Comment by getdatakick** [comment]
This was fixed by commit https://github.com/thirtybees/coreupdater/commit/930438719ffcaefe07134754283a0fd1423dfec7
