### ISSUE TITLE
Modules shouldn't store their 'install' status in the DB

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#178]
This is kind of a follow-up on issue #177.

Having modules stored locally, but not "installed" is confusing. One can delete them, but they just re-appear, as they still exist on the remote module server.

This leads to the proposal: "A module is installed if its files exist locally". No need to duplicate this information in the DB. Uninstalling a module removes files from local storage. Menu entry "delete" shall go away. For turning modules on and off without downloading/removing its files one can still enable and disable them, of course.

Postponing this for after 1.0.1 because the current state is a bit confusing, but not buggy.

**Comment by Traumflug** [comment]
Another one which gets solved by this proposal is: deleted modules, like files removed locally, have "Mark as favorite" in their menu. Modules with local files, still uninstalled, don't have this entry.

**Comment by Dh42** [comment]
What if they were removed from the all list and there was a suggested module tab they were hidden under? It seems like most CMS's have a 4 module states. not installed, installed, installed and enabled, installed and disabled.

**Comment by Traumflug** [comment]
That's certainly possible, but I don't see how this makes things easier.

TB currently has 5 module states: deleted, not deleted and not installed, not deleted and installed and disabled, not deleted and installed and enabled.

**Comment by Dh42** [comment]
I am just trying to figure out a good compromise. If someone deletes say a main stat module they likely will not know how to get it back. We could always put a system in place to remove the delete option from the core modules and just allow them to be uninstalled only.

**Comment by Traumflug** [comment]
To get a module back one simply clicks on "install". The distinction is that this also downloads the module then.

So far I can't see a reason to have a module on disk, but having it not installed. This install flag in the DB can even lead to inconsistent states: if the module is marked as "installed" in the DB, but (e.g. after a backup replay) not present on disk.

**Comment by Traumflug** [comment]
For a related discussion see https://forum.thirtybees.com/topic/178/proposal-customization-of-modules-on-installation

**Comment by firstred** [comment]
Let's bring this to the forum.
