### ISSUE TITLE
 This description_short field (English (English)) is too long

### ISSUE THREAD

**Issue by marktnz1** [thirtybees/thirtybees#1781]
" This description_short field (English (English)) is too long: 400 chars max (current count 402)."

![Screenshot from 2024-04-11 12-55-47](https://github.com/thirtybees/thirtybees/assets/25965650/774db47a-4a34-4b66-aa20-17718c5e785f)

When I googled this bug it stated it was fixed in Prestashop here

https://www.prestashop.com/forums/topic/31438-solved-how-to-change-the-short-description-max-character-limit/

The bug seems not easily worked around, I cannot now update this product with this error.

Im on TB 1.5.1

**Comment by getdatakick** [comment]
This is not a bug, it's expected functionality.

You can set length of short description in Preferences > Products > Max size of short description. If not set, this defaults to 400.
