### ISSUE TITLE
Error page fails to load when an error occurs during installation

### ISSUE THREAD

**Issue by FranseFrikandel** [thirtybees/thirtybees#1785]
EDIT: 
Issue was originally for installation failing. It was eventually found this was an issue with a dependency.

However, it highlighted an issue where the thirtybees installer will fail to show the error page since it attempts to connect to the database, which has not yet been set up in the installer.

The logs seem to only show the database connection failing, and not the original error that caused the attempt to load the error page. This makes it a lot harder to debug any issues that occur during installation.

Original issue message below
---

Hello there,

Trying to install ThirtyBees version 1.5.1, with PHP 8.1, the installer fails and gives a blank page.

The PHP error log shows following error:
```
[30-Apr-2024 19:34:58 UTC] PHP Fatal error:  Uncaught Error: Undefined constant "_DB_SERVER_" in /var/www/shop/classes/db/Db.php:624
Stack trace:
#0 /var/www/shop/classes/db/Db.php(604): DbCore::getInstance(false)
#1 /var/www/shop/classes/Configuration.php(510): DbCore::readOnly()
#2 /var/www/shop/classes/Configuration.php(429): ConfigurationCore::loadConfiguration()
#3 /var/www/shop/classes/error/response/ProductionErrorPage.php(50): ConfigurationCore::get('PS_SHOP_EMAIL')
#4 /var/www/shop/classes/error/response/AbstractErrorPage.php(43): Thirtybees\Core\Error\Response\ProductionErrorPageCore->renderError(Object(Thirtybees\Core\Error\ErrorDescription))
#5 /var/www/shop/classes/error/ErrorHandler.php(134): Thirtybees\Core\Error\Response\AbstractErrorPageCore->sendResponse(Object(Thirtybees\Core\Error\ErrorDescription))
#6 /var/www/shop/classes/error/ErrorHandler.php(249): Thirtybees\Core\Error\ErrorHandlerCore->handleFatalError(Object(Thirtybees\Core\Error\ErrorDescription))
#7 [internal function]: Thirtybees\Core\Error\ErrorHandlerCore->shutdown()
#8 {main}
  thrown in /var/www/shop/classes/db/Db.php on line 624
```

After some searching around, it appears this same issue only triggered a warning in PHP 7, so this might have ended up never being fixed for PHP 8 compatibility?

I've tried fixing it by adding a check if the \_DB_SERVER\_ constant is set, and if not, setting all the variables as blanks using following code starting on line 622 in Db.php:

```
        if (!static::$_servers) {
            if (defined("_DB_SERVER_")) {
                static::$_servers = [
                    ['server' => _DB_SERVER_, 'user' => _DB_USER_, 'password' => _DB_PASSWD_, 'database' => _DB_NAME_], /* MySQL Master server */
                ];
            } else {
                static::$_servers = [
                    ['server' => '', 'user' => '', 'password' => '', 'database' => ''],
                ];
            }
        }
```

However I'm now running into the following error instead:

```
Link to database cannot be established: SQLSTATE[HY000] [2002] No such file or directory
```

It's not really making any sense to me, it appears it's already trying to connect to a database, however this is a completely fresh install and I've not yet had any chance to tell the installer where the database is, I'm simply being redirected to the install page that ends up blank.

**Comment by getdatakick** [comment]
Looks like some exception is thrown during very first steps of installation -- probably some required php plugin is not enabled, or something similar. 

Thirty bees tries to display error page, but this fails because the error page requires data from database (store email).

We should probably have different error page handler during installation process, I guess.

**Comment by FranseFrikandel** [comment]
Yup, turns out for whatever reason SimpleXML wasen't working - Even though it was installed. Purging it and then reinstalling using apt fixed it.
