### ISSUE TITLE
Cart rules: apply discount to cheapest not working

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/thirtybees#1789]
I am looking into cart rules atm. Since this code is very complex/messy. I just made some quick tests to get a better understanding. 

IMO to apply on "cheapest" does not work at all. I was already a bit sceptical, as I couldn't find much lines in the code about it and in my test (clean core installation) nothing happened. The cart rule seems to be saved to the cart, but no value is calculated or at least no reduction is applied.

Note: in cart_rule db there is no column "apply_discount_to" instead it's saved as "reduction_product=-1". Very strange imo, but it is, what it is.

**Comment by getdatakick** [comment]
Ok, after some hair pulling I figured out what is wrong.

This rule can be used ONLY for cart rules with **product restriction**  -- you have to select some products in Condition tab first, in the same way we do it for **Selected product(s)**

Stupid, isn't it?

We should, at least, disable this option if no products are selected.

Or we could change the semantics -- however such change can be dangerous

The safest solution would be to rename this option to **Cheapest product from selection**, and introduce new option **Cheapest product in cart**

**Comment by getdatakick** [comment]
Related code: https://github.com/thirtybees/thirtybees/blob/7d5c7e0db81f61ba61093148f1c34844ee22f7bb/classes/CartRule.php#L1557-L1561

**Comment by getdatakick** [comment]
Commit 97383063a014c0a2ff3de161b78e3fa1823615a3 make the things more clear

1) the option is renamed to **Cheapest product from selection**
2) this option is not selectable unless merchants first create product restriction in Conditions tab 

I've filed new issue #1833 to track enhancement request related to **Cheapest product in cart**
