### ISSUE TITLE
Store icon issue (white background)

### ISSUE THREAD

**Issue by NorwegianRat** [thirtybees/thirtybees#179]
There’s is something funky going on when uploading a new store icon. The default tb png icon from the install works fine. It also works fine if you just replace this file with a new one with FTP. The problems occur when uploading from BO. I used the exact same png file i uploaded through FTP. Now the icon gets a white background. (I made sure to change the image setting to "Use png only if the base image is in png format)

**Comment by firstred** [comment]
Thanks a lot for your description.

We are going to improve image processing with the next version, so I have tagged this issue with version `1.0.2`

**Comment by firstred** [comment]
Unable to fix this issue. A GIF file is required, but PHP cannot create transparent GIF files. If you need a transparent icon I recommend to keep using FTP.

**Comment by firstred** [comment]
Or use a transparent GIF as the source.
