### ISSUE TITLE
Wrong Bulgarian data on localization import

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/thirtybees#1805]
![image](https://github.com/thirtybees/thirtybees/assets/11251370/7fa5c562-7fc4-4cbe-b171-0d4e53bcc862)

Should be as follows: date_format_lite="d.m.Y" date_format_full="d.m.Y H:i:s"

![image](https://github.com/thirtybees/thirtybees/assets/11251370/e901748c-dc7e-43af-8212-6640e437cc0c)

https://en.wikipedia.org/wiki/List_of_date_formats_by_country

Also currently is_RTL is 0 in localization files but every time I import it on my test setup it pulls it as 1.

Are we're using the files from /localization, if so I can make a PR.

**Comment by getdatakick** [comment]
Fixed in translations pack
