### ISSUE TITLE
Inconsistent configuration tests

### ISSUE THREAD

**Issue by roband7** [thirtybees/thirtybees#181]
I'm assuming the intention is that he implementation and 'owner' of these tests is classes/ConfigurationTest.php

The problem is that a lot of the knowledge of test result array keys, and all the error texts, are duplicated in controllers/admin/AdminInformationController.php and install/controllers/http/system.php

Right now system.php seem to be in sync with ConfigurationTest.php, but AdminInformationController.php isn't.

The need for syncing and the duplication of error texts is silly and error-prone.

My suggestion is to move all the logic and and texts over to ConfigurationTest.php and slim down AdminInformationController.php and system.php

Also, if you do a command-line install using install/index_cli.php it doesn't call ConfigurationTest.php at all, bypassing all the tests! Yes, I learned this the hard way, and was why I started digging into this mess :)

**Comment by firstred** [comment]
Thanks. It is indeed something we want to take care of, but it currently requires too many changes for a patch version. Rescheduling for 1.1.0 instead.

**Comment by firstred** [comment]
Just a basic solution for now, not very verbose: https://github.com/thirtybees/thirtybees/commit/e08c47c383037f3560f8f975c0b15fb479ee000e

**Comment by Traumflug** [comment]
This area received a lot of smaller improvements over the last year. AFAIK the only issue left is the distribution of tests and their messages over several places. Installer, _AdminInformationController_, _ConfigurationTest_ and last not least the place where all this should go: module Core Updater with its _AdminCoreUpdaterController_.
