### ISSUE TITLE
Back office > Product image not when clicked

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/thirtybees#1816]
Steps:

1) Preferences > Images > set Image extension = webp
2) edit product in back office
3) click on any image

Expected result: image should be displayed in modal

Actual result: missing image placeholder is displayed -- system is trying to display image from url `https://domain/img/p/9/9.webp` but that does not exists.

![image](https://github.com/thirtybees/thirtybees/assets/34651851/5d26c76b-db87-48a4-9fa7-ea0c0ab28318)

**Comment by therampagerado** [comment]
This comment is also related to the recent image rewrite.

If I set jpg, in the same section I don't see the small images but I see the large ones. For webp both don't work.
![image](https://github.com/thirtybees/thirtybees/assets/11251370/39d25e80-9b35-4149-9c06-14affbad6c63)

Also in front office when using webp images everything is broken, they don't display in various scenarious.

Somehow I managed to upload webp image as a product one but there was an error displayed.

![image](https://github.com/thirtybees/thirtybees/assets/11251370/bb761569-7928-4065-b478-91fdf58d629b)

**Comment by yaniv14** [comment]
I've added 2 comments in the commit related to this issue.
https://github.com/thirtybees/thirtybees/commit/00d46427b13bd765579c6ad1997b72b08acedfd2#r143637369
https://github.com/thirtybees/thirtybees/commit/00d46427b13bd765579c6ad1997b72b08acedfd2#r143684868

**Comment by eschiendorfer** [comment]
I will join this issues, once I could make the upgrade on my store. I remember, that the popup was an issue for me too, but I could solve it somehow. 

That the whole FO is broken with webp is very strange/surprising. I have tested that a year ago with a clean installation. Also my live store is using webp. But ok the PR is so big a lot of things can happen. In a 1-2 weeks I can say more.

**Comment by therampagerado** [comment]
A screen shot of my issue in frontoffice - the system looks for the overlay image but does not find it:

![image](https://github.com/thirtybees/thirtybees/assets/11251370/bf205351-8425-4ee0-a524-b9c044800bdc)

What it looks for: http://www.domain.com/9-home_default/tin-cup-test.jpg

**Comment by getdatakick** [comment]
Guys, please keep things tidy. File separate issues for different problems.

**Comment by therampagerado** [comment]
Sorry, will create new issues.

**Comment by getdatakick** [comment]
This was fixed together with commit 5b119f725259f10a2448a6fc111317193a69ee86
