### ISSUE TITLE
Inventory Stock Bug 

### ISSUE THREAD

**Issue by Madhosh1993** [thirtybees/thirtybees#1819]
Hello, 

I have problems in my shop. For two products i do have stock of 10 pcs. But under the Product section the stock shows as -2 thus customers are not able to order the product. Do you know how to correct this ? Below is the screenshot.

<img width="516" alt="image" src="https://github.com/thirtybees/thirtybees/assets/174187459/049e5efd-8e2c-4bfd-8506-e9952003f45d">

<img width="589" alt="image" src="https://github.com/thirtybees/thirtybees/assets/174187459/89d440ed-75d3-454e-903e-d7bece22fd46">

Thanks
Madhosh

**Comment by therampagerado** [comment]
I'm unable to replicate this issue with 1.5.1.

Just activated my ASM on the test site and the values are the same.

What version are you using?

**Comment by getdatakick** [comment]
Hard to tell what is wrong. I can't reproduce this issue as well. 

Please try to come up with exact repro-steps

**Comment by eschiendorfer** [comment]
What is the third column saying? Cause the real_quantity is actually the one, that let customer order or not.
