### ISSUE TITLE
PS Module test gives this

### ISSUE THREAD

**Issue by Havouza** [thirtybees/thirtybees#182]
Hi!
Going through my PS modules to see if they will work when we migrate. 
The Advanced invoice one do not. See attachment. Can anyone tell me what the error is
TB 1.0.1 beta 2
![screenshot 2017-04-18 20 45 20](https://cloud.githubusercontent.com/assets/25871096/25145027/8dfbffe6-2478-11e7-923e-b3a71c8504cf.png)

**Comment by roband7** [comment]
thirty bees removed a couple of require_once calls from the top of PDFGenerator.php when all the external PHP classes were moved from tools to vendor. And your addon assumes they are there.

Attempts to get this backwards compatible were made in 1.0.1, but seems there are still ways addons make assumptions that break.

If you read this mdekker, I'm beginning to think the move from tools to vendor perhaps was a mistake, that the little cleanliness gained isn't worth it compared to the compatability mess it creates.

**Comment by Dh42** [comment]
I think we are going to have to put more backwards compatibility in, but in the long term it is a good idea to keep them separate so we don't have any of the legacy issues PS had, like swift coupled so tightly that they used a 6-7 old package that did not support TLS and other things like that

**Comment by firstred** [comment]
Hmmz, looks like we should downgrade TCPDF from 6.2 to 5.9

**Comment by roband7** [comment]
Hmm, are you sure that's the problem? From a quick look isn't the problem that the addon assumes the PDFGenerator class has a method named addTTFfont(), and Prestashop makes this happen because of the require_once(_PS_TOOL_DIR_.'tcpdf/tcpdf.php') they have at the top of PDFGenerator.php. This was removed in thirty bees.

I might be misunderstanding all this PHP autoloading crap...

**Comment by Vegaanders** [comment]
I have a load of 1.6.1.x compatible modules that I now test on TB beta 2 to see which I can throw in the dustbin. This one though I use and hoped I could use it also when we migrate.

I will report other problems with other modules. The machine is a testplatform so if it crash is no big deal

**Comment by Vegaanders** [comment]
FYI the module seems to be installed but the invoice templates are missing so I cant test if anything works

**Comment by Traumflug** [comment]
> I have a load of 1.6.1.x compatible modules that I now test on TB beta 2 to see which I can throw in the dustbin.

Instead of throwing them it's better to report how they fail, so compatibility can be improved. Such a list is also very interesting for non-developers, of course.

> From a quick look isn't the problem that the addon assumes the PDFGenerator class has a method named addTTFfont()

Grep-ing through ```vendor/``` finds no class 'PDFGenerator'. Moving these files back to ```tools/``` likely doesn't help. Method ```addTTFfont()``` is ```TCPDF_FONTS::addTTFfont()```. Maybe that's the reason why @firstred thinks about downgrading.

**Comment by roband7** [comment]
classes/pdf/PDFGenerator.php is part of the core.

This is also the root class in the error message reported by Vegaanders.

In Prestashop this class does require_once(PS_TOOL_DIR.'tcpdf/tcpdf.php')
In thirty bees it doesn't.

**Comment by firstred** [comment]
No idea what this is all about, but everything from the vendor folder is automatically loaded. PDFGenerator extends TCPDF, so it's using that TCPDF function that does not exist on 6.2. It does on 5.9, so downgrading solves it.

**Comment by roband7** [comment]
Like a wrote above "I might be misunderstanding all this PHP autoloading crap..."

Guess I did :)

**Comment by Vegaanders** [comment]
There is another route to go. I will contact the developer and ask if they can perhaps fix it to work with TB also

**Comment by firstred** [comment]
https://github.com/thirtybees/thirtybees/commit/779c15c65a25afdcc57a7bd6f916a919612520c6

**Comment by firstred** [comment]
Reopened. Couldn't find this super old version (2012) on the internet anymore. Let's build a compatibility layer instead.

**Comment by firstred** [comment]
Does this change solve it?
https://github.com/thirtybees/thirtybees/commit/1f0d14119e4c76ba8474a38122cd290e62ee87aa

**Comment by firstred** [comment]
Raw file: https://raw.githubusercontent.com/thirtybees/thirtybees/1f0d14119e4c76ba8474a38122cd290e62ee87aa/classes/pdf/PDFGenerator.php

**Comment by Vegaanders** [comment]
Hi Michael. 
The tests yesterday resulted in a php error log of 217 Gb overnight for some reason. I have now taken all away and wait for the developer

**Comment by firstred** [comment]
Closing this issue. The compatibility layer has been added quite a while ago now.

**Comment by firstred** [comment]
For 1.0.2 that is
