### ISSUE TITLE
Tax calculation error when using cart rules: selected and cheapest product selections

### ISSUE THREAD

**Issue by x97wehner** [thirtybees/thirtybees#1821]
When making a cart rule that utilizes cheapest product or selected products (Highlighted in yellow in image), the tax at checkout is incorrectly calculated against the full non-discounted product subtotal price. When making the same rule that applies to the entire order or uses the specific product setting (Highlighted in green in image), then the tax correctly calculates against the discounted product subtotal.

All settings should calculate tax the same, as the green options do.

![image](https://github.com/thirtybees/thirtybees/assets/44684415/c390374c-b7f9-4ad7-995e-3c5b20af7064)

**Comment by getdatakick** [comment]
I can't reproduce this issue on clean installation on bleeding edge. 

Order is generated with correct taxes.

During testing, I found and fixed issue #1823 - so maybe that one is related to this, but I doubt it.

Please provide more details and repro steps, ideally on clean installation (it's possible you have some overrides, or are using older version of the tb)

**Comment by x97wehner** [comment]
Here are screenshots from a clean install in bleeding edge. Same result. It's calculating wrong for those two options. 

Cart rule: Tax on order
![Cart rule tax on order](https://github.com/thirtybees/thirtybees/assets/44684415/6ac7c33e-0690-42a4-94cf-6caafd2e175d)

Result of tax on order (This works correctly)
![Result of tax on order - correct calculation](https://github.com/thirtybees/thirtybees/assets/44684415/baf2f7ad-d9c4-44f4-98a0-44589f2d138e)

Cart rule: tax on selected products
![Cart rule tax on selected products](https://github.com/thirtybees/thirtybees/assets/44684415/ef4aa6ad-02bb-4b63-ab62-b65ca892818d)

Result of tax on selected products (This is calculating wrong.)
![Result of tax on selected products - wrong calc](https://github.com/thirtybees/thirtybees/assets/44684415/d499716d-655e-44ef-9ad9-bfb96bc3b996)
