### ISSUE TITLE
Image rewrite context: Rollover image is not available

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/thirtybees#1825]
When I hover over my test products the alt image is not available (placeholder is displayed instead of What it looks for: `http://www.domain.com/9-home_default/tin-cup-test.jpg`

![image](https://github.com/thirtybees/thirtybees/assets/11251370/5c04a9e2-d023-4f47-b36e-d8932096fe23)

**Comment by getdatakick** [comment]
What module are you using for hover image? Looks like that module somehow constructs image url manually -- it method from `Link` class was used, the image url would look different:

`http://www.domain.com/products/9-home_default/tin-cup-test.jpg`

**Comment by getdatakick** [comment]
Anyway, for backwards compatibility reasons, we should have a fallback mechanism for those old image urls (maybe with warning)

**Comment by therampagerado** [comment]
This is Warehouse 3.8.7 theme and this functionality is part of 

Plugin adder module that comes with it, yes:

`public function getRolloverImageLink($name, $id_product, $type = null)
    {
        if (!isset($id_product)) {
            return;
        }

        $cache_id = 'Link_getRolloverImageLink_' . (int) $id_product . '_' . $type;
        if (!Cache::isStored($cache_id)) {

            // Check if module is installed, enabled, customer is logged in and watermark logged option is on
            if (Configuration::get('WATERMARK_LOGGED') && (Module::isInstalled('watermark') && Module::isEnabled('watermark')) && isset(Context::getContext()->customer->id)) {
                $type .= '-' . Configuration::get('WATERMARK_HASH');
            }

            $id_image = Db::getInstance()->getRow('SELECT id_image FROM ' . _DB_PREFIX_ . 'image WHERE id_product = ' . $id_product . ' AND (cover = 0 or cover IS NULL) ORDER BY `position`');

            if (isset($id_image['id_image']) && $id_image['id_image']) {
                $id_image = $id_image['id_image'];

                $theme = ((Shop::isFeatureActive() && file_exists(_PS_PROD_IMG_DIR_ . Image::getImgFolderStatic($id_image) . $id_image . ($type ? '-' . $type : '') . '-' . (int) Context::getContext()->shop->id_theme . '.jpg')) ? '-' . Context::getContext()->shop->id_theme : '');
                if ($this->allow == 1) {
                    $uri_path = __PS_BASE_URI__ . $id_image . ($type ? '-' . $type : '') . $theme . '/' . $name . '.jpg';
                } else {
                    $uri_path = _THEME_PROD_DIR_ . Image::getImgFolderStatic($id_image) . $id_image . ($type ? '-' . $type : '') . $theme . '.jpg';
                }
                $ret = $this->protocol_content . Tools::getMediaServer($uri_path) . $uri_path;
                Cache::store($cache_id, $ret);
                return $ret;

            } else {
                Cache::store($cache_id, null);
                return;
            }

        }
        return Cache::retrieve($cache_id);

    }`

**Comment by getdatakick** [comment]
Support for legacy product image urls were implemented in issue #1828 , as they are obviously needed.

However, this module is buggy as well. It should not construct the urls itself - by doing that, the module is not utilizing thirty bees webp support, there is no hidhdpi/retina support, incorrect watermark...

Module author should have simply call `Link::getImageLink`, and everything would work correctly.
