### ISSUE TITLE
 Warehouse theme does not install

### ISSUE THREAD

**Issue by aykou** [thirtybees/thirtybees#183]
I tried to install the theme warehouse and I could not, it is sent normally and back to page to choose theme, but has no option to choose the new theme.
I activated the debug mode but did not show any errors.
The theme worked well in PS 1.6.1.11.

![captura de tela_2017-04-18_21-25-01](https://cloud.githubusercontent.com/assets/11906530/25158863/de51e060-2481-11e7-87d5-f1315c440524.png)

**Comment by firstred** [comment]
https://github.com/thirtybees/thirtybees/commit/a0d9990088f6438313aab6175fc6fe2c1c22301d

**Comment by Traumflug** [comment]
Ahem. I've made good experience with keeping issues open until the issue opener can report the bug to be fixed. Closing issues quickly is often recognized as "go away, I don't want to hear this".

Thumbs up for taking care of it, of course.

**Comment by firstred** [comment]
I don't only contact people via GitHub ;)

**Comment by aykou** [comment]
@firstred 
 Another problem appeared in v1.0.1 regarding the theme, it installed and changed everything normally with the homepage (HOME).
In the beta I installed normally, the theme version is the same.

**Comment by Dh42** [comment]
Can you please explain more what the new issue is, I am not following.

**Comment by firstred** [comment]
Full page cache was still enabled. That caused the issue.
