### ISSUE TITLE
Default image generation in bleeding edge 1.6 incompatible with existing PS modules/webservice calls expecting .jpg image

### ISSUE THREAD

**Issue by x97wehner** [thirtybees/thirtybees#1850]
After updating to the latest bleeding edge 1.6, I noticed that images were no longer flowing within the standard PS web service call to Shipstation via web service call. After investigation, I found that the web service integration looks for the default image file for the product and expects it to be in jpg format as is standard with PS 1.6. The integration works fine in TB v1.5.1 and pulls the default product image in jpg format. After the update to BE 1.6, it's now being fed the .webp file for the product and no longer works. I attempted removing the .webp file to test for certainty, but after removing that file for the product, it automatically generates again while adding a new order for the product to test the integration and continues to fail pulling the jpg image. 

If the main file needs to be maintained in webp as was not the case in v1.5.1, in order to keep the new work that has been done with images, need a switch or way to designate whether that main product file should be stored as old way: jpg only, or new way: jpg and webp. 

The highlighted file in the attached image is the issue. It is new with bleeding edge 1.6 and regenerates itself if attempting to remove. The API call is being fed this file as the product image and it isn't backward compatible for modules following the PS 1.6 standard of jpg.

![image](https://github.com/user-attachments/assets/874365a7-8bae-4c79-97cc-9f44e86fd41c)

**Comment by therampagerado** [comment]
Did you test with this options here:

![image](https://github.com/user-attachments/assets/070c18cf-4ea7-465c-853a-0a8dbfc03a84)

**Comment by getdatakick** [comment]
Indeed, this is backwards compatibility problem.

I have implemented fix that gives you an option to select image format you want to use for returning images via webservice. You can set this individually for every webservice key (if you have multiple webservice integration)

![image](https://github.com/user-attachments/assets/a727a2f3-686d-4f48-a141-a134c3ea02d7)

**Comment by x97wehner** [comment]
This appears to work perfectly as designed. Thanks. It does open another question though that I think may be a new bug with the latest Bleeding edge release. I deleted and regenerated images to test. It no longer appears to generate the theme specific images as it did prior. You can see in the screenshot, it only keeps two files: the source and one converted. I've tried changing the field "Source file extension" from converted to uploaded + converted. It yields the same result each time (image 1.) Prior, it generated all theme specific sizes as shown in the second screenshot. Is this a new bug or am I doing something wrong?

![image](https://github.com/user-attachments/assets/b723c589-548e-4182-b39e-8c8e62d4fb8e)

![image](https://github.com/user-attachments/assets/4c53f8eb-92f3-44ba-acfd-1e1ee2c0236e)

**Comment by getdatakick** [comment]
I've just tested to regenerate images, and it generates properly. All image types were correctly generated:

![image](https://github.com/user-attachments/assets/73997a44-fd30-47cb-91a6-2282ae280c83)

Check your image type configuration. Ensure that your image types are associated with correct entities (products, categories, etc)

![image](https://github.com/user-attachments/assets/57811c4f-68a4-45fb-9c1c-a5092469f916)

**Comment by x97wehner** [comment]
I found the cause. Somehow a couple image files had been corrupted and were freezing the regeneration process. Works fine when I fixed those image files. Thank you.
