### ISSUE TITLE
Multistore: Manufacturer logo can't be deleted and the logo is not changed in the Manufacturer list when new one is uploaded.

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/thirtybees#1858]
thirty bees version: edge as of today

Issues:

**1. When deleting the manufacturer image nothing happens (other than that a note is displayed on top)**

![image](https://github.com/user-attachments/assets/c8a2005e-f3f4-49c2-8b1d-f8a2499c9590)

---------------------------------------------------------------------------------------------------------------------------------------
**2. Also when once uploaded the new logo is visible 'inside' the manufacturer page but in the list the old one is not replaced (this is pulled from tmp folder).**

![image](https://github.com/user-attachments/assets/b27fa094-1942-4a87-8a31-b3c90fa5bd1d)
![image](https://github.com/user-attachments/assets/13cc03ae-8383-44ab-bb07-7e7ed3e7c662)

**Comment by getdatakick** [comment]
I can't reproduce any of those two issues.

1) deletion of image works fine. Source file, and all image formats for given manufacturer was deleted from `/img/m` directory as expected
2) uploading new image regenerates miniature in tmp folder

Did you test on clean installation? Maybe this is some override/module?

**Comment by therampagerado** [comment]
I have couple of overrides but I'm failing to find anything image related. I have an override that swaps the product image onmouseover.

This happens both in my production site and my test site where I experiment.

Server has litespeed cache and I'm running a module on the production site - tested this too. On the test site I don't have it and it behaves the same way.

**Comment by getdatakick** [comment]
I've managed to reproduce -- it's a multistore issue. Functionality works fine for single store installations, but not for multistore

**Comment by therampagerado** [comment]
Sorry for not pointing it's in multistore setup, did not expect this to affect this part. :(
