### ISSUE TITLE
Customer Login Page isn't working

### ISSUE THREAD

**Issue by lukerb52** [thirtybees/thirtybees#1865]
I've been setting up a thirtybees site for some days now. Everything seems to be in working order, except when I try to make an account as a customer, I get an error in the browser. PHP, MySQL, and NGINX seem to be working fine. I couldn't find any errors in their respective logs (accessed by `systemctl status`, if that matters).

![image](https://github.com/user-attachments/assets/5344fa9a-b972-4cdb-9008-1065e31a3680)

**Comment by lukerb52** [comment]
Here's the relevant information:

Server information Linux #128-Ubuntu SMP Fri Jul 5 09:28:59 UTC 2024 x86_64

Server software version nginx/1.18.0

PHP version [8.2.22](https://shop.3ds3.xyz/admin582yjzwpy/index.php?controller=AdminInformation&display=phpinfo&token=3883faaf0aa5c15372ede361d226a2a0)

Memory limit 128M

Max execution time 30



MySQL version 10.6.18-MariaDB-0ubuntu0.22.04.1

MySQL server localhost

MySQL name thirtybees

MySQL user thirtybees

Tables prefix tb_

MySQL engine InnoDB

MySQL driver PDO 

 Thirty bees version: 1.5.1

Thirty bees revision: 1.5.1

Build for PHP version: 8.2 

Current theme in use Niara 

Your web browser Mozilla/5.0 (Windows NT 10.0; rv:128.0) Gecko/20100101 Firefox/128.0 

 Required parameters OK

Optional parameters OK

**Comment by lukerb52** [comment]
It seems to be a problem with loading pages that have an `&` in the URL. for example: `http://exampleshop.com/index.php?controller=authentication&back=my-account` doesn't work, but `https://exampleshop.com/index.php?controller=authentication` does work.

**Comment by therampagerado** [comment]
Did you edit something in your friendly url settings?

**Comment by getdatakick** [comment]
This is definitely server configuration issue
