### ISSUE TITLE
Courier logo gets erased if you leave it empty upon edit

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/thirtybees#1868]
thirt bees: edge

Repro steps:

1. Create new courier, upload a logo, save.
2. Logo is visible in the list of couriers.
3. Edit the courier but don't upload new logo, save
4. Logo is not visible in the list of couriers.

![image](https://github.com/user-attachments/assets/57275cd4-efc3-47f7-9231-94ee6cee9b79)

**Comment by getdatakick** [comment]
Oh, that's not nice. Thank you for reporting this

**Comment by getdatakick** [comment]
I can't reproduce this issue.

Could you please re-check?

**Comment by therampagerado** [comment]
Hello @getdatakick , I replicate this on two instances.

Please, remember I use multistore (if this has any affect on this part, I'm just mentioning it as it seems it affects many parts that are not logical from noob-like-me perspective :) ).

1. After I create new courier:
![image](https://github.com/user-attachments/assets/a26aaa2d-5f32-4764-9033-ea74fc432222)
2. I go and edit something (not uploading the logo again):
![image](https://github.com/user-attachments/assets/e7a86769-2ef4-468b-bb40-6a7c20f9277a)
3. Result:
![image](https://github.com/user-attachments/assets/69c2dd4c-43fc-4fc4-8ade-15271f673a8f)
![image](https://github.com/user-attachments/assets/53849abc-e9f4-45fc-aba1-f9d6f257f227)

**Comment by getdatakick** [comment]
Oh, I think I found it. Do you have, by chance, a dot in your root path? Something like

`/var/www/domain.com/`

There is a code that tries to extract image extension from the source path

```php
 $imageExtension = explode('.', $sourceImageOldLogo)[1];
```

and if the root dir path contains dot, this will fail

**Comment by therampagerado** [comment]
The local path is /home/USERID/public_html/main-domain.eu/

Current shops are in subfolders of this domain.

The test from above is in subdomain test2.main-domain.eu but I first saw this in the main shop I run now and it's on separate domain. (if this affects anything)

**Comment by getdatakick** [comment]
The fix should be in bleeding edge in few minutes. Please re-test and confirm that it is fixed now

**Comment by therampagerado** [comment]
Yes, it's fixed!

Thank you!
