### ISSUE TITLE
Product import: 'When out of stock' setting always import as 0

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/thirtybees#1885]
thirty bees: edge

Multistore: yes (with shared quantities between shops)

Bug is probably related to: https://github.com/thirtybees/thirtybees/issues/1878 but appears on brand new install with no mutlistore activated too.

1. Import a product.
2. When importing products the actual value should be 2(Default: Deny orders as set in the Products Preferences page), not 0 (Deny orders).

There is field in the import mechanism for 'Label when backorder allowed' but not for the actual 'When out of stock' setting (0, 1 or 2).
Support for this setting in the import process will be nice addition in future.

**Comment by getdatakick** [comment]
The default value settings is fixed.

Note that *Out of stock behaviour* can be already imported, it's named *Action when out of stock*
