### ISSUE TITLE
Sitemap missing in modules folder

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/thirtybees#1895]
I am cleaning up my github repositories. While doing it, I noticed, that the sitemap module is missing under https://github.com/thirtybees/thirtybees/tree/main/modules.

Is there any reason for it or was it just forgotten?

**Comment by getdatakick** [comment]
This module is not installed with the initial system installation, so it doesn't have to be packed inside the installation zip file.

**Comment by eschiendorfer** [comment]
Ah, these are only the standard modules. Thanks for clarification!
