### ISSUE TITLE
Exception when deleting carts with buttons

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/thirtybees#1896]
thirty bees: edge

1. When clicking on one of the two buttons that delete unneeded carts I get:

Exception

Message:
ThirtyBeesDatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '` cd INNER JOIN `ps_customization` c ON cd.`id_customization` = c.`id_customi...' at line 1

Location:
classes/Cart.php line 2836
SQL
SELECT cd.`value`, cd.`type
FROM `TB_customized_data` cd
INNER JOIN `TB_customization` c ON cd.`id_customization` = c.`id_customization`
WHERE (cd.`type` = 0) AND (c.`id_cart` = 5708)

**Comment by getdatakick** [comment]
Thank you
