### ISSUE TITLE
New Password email empty

### ISSUE THREAD

**Issue by Havouza** [thirtybees/thirtybees#190]
I changed my password on my shop by generation a new one. I am old so I wanted the new one sent by email. The email came but the password is empty

YOUR NEW BEAUTY & PLEASURE LOGIN DETAILS 
E-mail address: anders@mirawai.com
Password:

**Comment by firstred** [comment]
Which form/page did you use?

**Comment by alwayspaws** [comment]
If you used Chrome and let google save the password, I know how you can retrieve it.

**Comment by alwayspaws** [comment]
Here Is the link to retrieve a password saved in chrome. I hope that helps you.

http://www.thewindowsclub.com/manage-view-saved-passwords-chrome

**Comment by Traumflug** [comment]
Chromes password manager and 30bz' password mechanism are two entirely different things.

What's needed is the 30bz page used for requesting a new password. Is it a customer password (front office) or an employee password (back office). We can't see what you see, so a screenshot or list of steps for reproducing the problem would be great.

**Comment by alwayspaws** [comment]
Of course it's an issue that needs to be resolved, but I was just trying to give the poor guy a way of getting his password back. :)

**Comment by Vegaanders** [comment]
I opened my account in tband pressed change password. Pressed generate password and marked send it as email. Then save. Email came empty

**Comment by firstred** [comment]
Front office or back office?

**Comment by firstred** [comment]
Employee account or customer account?

**Comment by Vegaanders** [comment]
Back office/Employees

**Comment by firstred** [comment]
Issue still going on?
