### ISSUE TITLE
KPI configuration values might be broken

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/thirtybees#1903]
I am not 100% sure, if this is really a bug/broken, but I noticed that I have outdated "date_upd" values in the configuration_kpi table. 

As an example I recommend to test "AVG_ORDER_VALUE" and "AVG_ORDER_VALUE_EXPIRE".

Open AdminOrders and click the refresh button. Shouldn't then the values update in the table? For me it doesn't :S

**Comment by getdatakick** [comment]
Indeed, the logic to refresh the KPIs is flawed -- it only refreshed those KPI's that were already outdated at the time of page render

**Comment by getdatakick** [comment]
Should be fixed

**Comment by eschiendorfer** [comment]
Thanks! I looks fine now 👍

**Comment by eschiendorfer** [comment]
```
Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at Function.each (jquery-1.11.0.min.js?v=1650141258:2:2815)
    at HTMLDocument.<anonymous> (admin.js?v=1728398759:876:7)
    at j (jquery-1.11.0.min.js?v=1650141258:2:27136)
    at Object.fireWith [as resolveWith] (jquery-1.11.0.min.js?v=1650141258:2:27949)
    at Function.ready (jquery-1.11.0.min.js?v=1650141258:2:29783)
    at HTMLDocument.K (jquery-1.11.0.min.js?v=1650141258:2:30128)
```

I get now this error while looking at the detail page of an order (vieworder)

**Comment by getdatakick** [comment]
Thanks @eschiendorfer. 

The code to refresh KPI is triggered by existence of element with class 'kpi-container' in the page. Order detail page contains such element, but does not include any actual KPI, so it now fails.

I've fixed the code, should work now
