### ISSUE TITLE
Unnecessary Shop::addSqlRestriction in Order::getOrderByCartId() method

### ISSUE THREAD

**Issue by gregzawadzki** [thirtybees/thirtybees#1905]
In the `Order::getOrderByCartId()` method, the use of `Shop::addSqlRestriction()` is unnecessary and can cause incorrect results when not in the appropriate context. This function should return the correct order ID when the cart ID is provided, regardless of the shop context.

**Current code:**

```php
public static function getOrderByCartId($idCart)
{
    $result = Db::readOnly()->getRow(
        (new DbQuery())
            ->select('`id_order`')
            ->from('orders')
            ->where('`id_cart` = '.(int) $idCart.' '.Shop::addSqlRestriction())
    );

    return isset($result['id_order']) ? (int)$result['id_order'] : 0;
}
```

The `Shop::addSqlRestriction()` is restricting the result based on the shop context, which might lead to false results when the query is executed outside the appropriate context.

**Proposed solution:**
Remove `Shop::addSqlRestriction()` to ensure the method always returns the correct order ID for a given cart ID, regardless of the current shop context.

It's not consistent with `Cart::orderExists` method, which does not have this restriction.

I also traced back this change and it's since beginning of repository it seems. Correct me if I'm wrong and it should actually be there.

**Comment by gregzawadzki** [comment]
PS: Also, it affects `AdminCartsController`. If order is from different shop (ShopID = 1), then I can view it in ShopID = 2. But it will falsely display that order has not been placed. Removing this line shows properly, that order has been placed.

**Comment by getdatakick** [comment]
Agree, this method should not be restricted by current context.

**Comment by gregzawadzki** [comment]
@getdatakick just wondering. What did you put ` ->orderBy('`id_order`')` there for?

**Comment by getdatakick** [comment]
@gregzawadzki `order by` is there to ensure deterministic ouput. Sometimes, multiple orders is created from one cart (for example in case of multi-shipping). Without `order by`, the method can return any random id_order (depending on db, cache,...). With `order by`, we will always get first order id for given cart

**Comment by gregzawadzki** [comment]
Thought so. I don't think its proper to have one cart for multiple orders unless there was long time ago option for split orders that had same reference. Or some script. But that are edge cases i think should not exist. 
Thank you for info! :)
