### ISSUE TITLE
Calling Product::update on unsaved product executes and messes database

### ISSUE THREAD

**Issue by gregzawadzki** [thirtybees/thirtybees#1909]
Hello,
I admit I found this bug on PS 1.6.1.14 but after looking at the code, I think it also affects tb

https://github.com/thirtybees/thirtybees/blob/main/classes/Product.php#L5220

Calling this method on unsaved product calls for update, update calls for inserts. Inserts add data to `product_shop` table, but `$this->id` is `NULL`. Making it add entry with id_product = 0.

So basically, either this one should be fixed ( i know you catch error, but there is no throw inside update, or I don't see one).

Or, even better. Throw exception when trying to call ObjectModel::update if there is no `$this->id`

Why?

Calling update on not saved product should never happen. So instead of adding garbage to database and catch errors, we should either throw exception, or return false if there is no ID.

Also, this line
https://github.com/thirtybees/thirtybees/blob/main/classes/ObjectModel.php#L785
Will return false only if data is wrong, but will return true, if nothing is updated as well.

So other approach could be to check if something was acually "updated".

Or maybe do both checks.

**Comment by getdatakick** [comment]
Good catch, it indeed creates a bogus multistore entry with id = 0.

I've added the check, and return `false` when `update` is called on unsaved object. I think exception would be too strict here, as there are undoubtedly many places where this can happen.  Instead, we log this as a warning, so it should be picked up by collectlogs module, and we will have a chance to fix it.
