### ISSUE TITLE
[PrestaShop Exception] After creating a discount

### ISSUE THREAD

**Issue by TobyMudito** [thirtybees/thirtybees#191]
Hello, to reproduce the issue, just create a discount for a customer from the backoffice, and go to the Shopping Cart Summary. The following exception appears:

[PrestaShopException]

**Class 'Discount' not found
at line 390 in file classes/CartRule.php**

```
385.             $cartRule['cumulable'] = !$cartRule['cart_rule_restriction'];
386.             $cartRule['id_discount_type'] = false;
387.             if ($cartRule['free_shipping']) {
388.                 $cartRule['id_discount_type'] = Discount::FREE_SHIPPING;
389.             } elseif ($cartRule['reduction_percent'] > 0) {
390.                 $cartRule['id_discount_type'] = Discount::PERCENT;
391.                 $cartRule['value'] = $cartRule['reduction_percent'];
392.             } elseif ($cartRule['reduction_amount'] > 0) {
393.                 $cartRule['id_discount_type'] = Discount::AMOUNT;
394.                 $cartRule['value'] = $cartRule['reduction_amount'];
395.             }
```

- CartRuleCore::getCustomerCartRules - [line 392 - controllers/front/ParentOrderController.php] - [8 Arguments]

- ParentOrderControllerCore->_assignSummaryInformations - [line 317 - controllers/front/OrderController.php]

- OrderControllerCore->initContent - [line 390 - classes/controller/Controller.php]

- ControllerCore->run - [line 742 - classes/Dispatcher.php]

- DispatcherCore->dispatch - [line 33 - index.php]

**Comment by Traumflug** [comment]
Class Discount was indeed removed: https://github.com/thirtybees/thirtybees/commit/0335d82603d48d0edd7ad149dbe729f6b69d005c

Likely not without a replacement, but which one?

**Comment by firstred** [comment]
What if we remove the 1.4 stuff?
https://github.com/thirtybees/thirtybees/commit/d4174745c7fb8db964fcc3a10e9cb463e42854b4

**Comment by TobyMudito** [comment]
The error has disappeared with the commit, but, if you create a discount and you try to add the discount to the cart, an error message appears: The discount doesn't exist.
