### ISSUE TITLE
Chrome update breaks BO order product search

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/thirtybees#1922]
Today my chrome got updated to the version 131.0.6778.70. Now the product search in controller=AdminOrders&addorder doesn't work any more. The options aren't filled inside the select. I was investigating a bit and found this. 

https://github.com/thirtybees/thirtybees/blob/7bc479f406fb8068575fc93029b9a5d90c437c60/admin-dev/themes/default/template/controllers/orders/form.tpl#L657

There is a closing </div> at the end. I believe this is not necessary or at least not in all cases. It's basically just wrong to close the mother div, while the select tag is still open. If I remove this closing div, it seems to work again. I can imagine, that the old chrome version was handling this wrong html code "correctly" and the new version does handle it different.

**Comment by getdatakick** [comment]
Absolutely, the closing div is added on line  694

https://github.com/thirtybees/thirtybees/blob/7bc479f406fb8068575fc93029b9a5d90c437c60/admin-dev/themes/default/template/controllers/orders/form.tpl#L694

So it should be removed from the line 657.
