### ISSUE TITLE
Can't build a pack based on product when it has combinations

### ISSUE THREAD

**Issue by x97wehner** [thirtybees/thirtybees#1925]
I sell products that have many different specifications, i.e. combinations.  I'd like to package this product with another product in a pack and have the exact auto calculating inventory decrementing work. To build a pack for each possible combination would be far too many packs to build plus would be a horrible user experience for a shopper on the website.

The best functionality would be to be able to use the entire product in a single pack so that only one pack shows on the front office. Then let the user select the combination they'd like exactly the same as how they do when selecting just the product combination alone.  The experience should be similar to this. https://www.golfworks.com/maltby-tc-max-driver-pak/p/pma0343/

**Comment by therampagerado** [comment]
Already tracked here: https://github.com/thirtybees/thirtybees/issues/1742

datakick said they have progress in this aspect so we're waiting for this enhancement.
