### ISSUE TITLE
AdminRequestSqlController: CSV separator

### ISSUE THREAD

**Issue by Yabbertb** [thirtybees/thirtybees#1930]
In generateExport() method, the CSV data is semicolon-separated, which is a mistake, because the CSV standard is **Comma**-separated values.

**Comment by getdatakick** [comment]
Indeed, this controller uses hardcoded `;` as a delimiter.

We will not change it to `,` (standard or not), we should honor user settings set in Preferences > General > Export field delimiter (`TB_EXPORT_FIELD_DELIMITER` configuration key)
