### ISSUE TITLE
Product List availability status "Out of stock" label not working correctly

### ISSUE THREAD

**Issue by x97wehner** [thirtybees/thirtybees#1933]
I'm not 100% sure, but I investigated and believe this to be a core issue and not theme related.

When I have a product with multiple combinations and out of stock ordering is allowed, if the sum of all combinations goes to zero or negative, then the product displays the out of stock message in the product list.  This doesn't work in scenarios where one combination is still actually in stock and others not. Example: Combo A has qty = -10, Combo 2 has qty = -1, and combo 3 has qty = 11. Because the net sum is zero, the product list shows the product as out of stock. Instead, it should just evaluate if any of the combinations have qty = 1 or more and, if not, then show out of stock. 

Edit: I'm also now noticing that in this scenario, it's taking away the Add to Cart button for combo 3 as well. It shouldn't do this either. Just validated on a clean TB install.

**Comment by x97wehner** [comment]
@getdatakick, I'm testing this update on a clean install of TB this morning on bleeding edge. Appears to still have same issue on product page. See screenshots below. In this scenario, Candle Honey has quantity of 1 and candle Puffin has quantity of -3. All other combinations are 0. 

Honey combination, add to cart button is hidden and should not be:
![image](https://github.com/user-attachments/assets/5ead9e9a-fb65-4060-82b6-96af4390a3dc)
I also notice in this situation that the "In Stock" label is colored with the alert red color and should not be.

Puffin combination, add to cart button is hidden correctly.
![image](https://github.com/user-attachments/assets/5231b11f-e426-4424-b088-2ea4e3bd837f)

**Comment by getdatakick** [comment]
This issue was about product list display. There, theme received incorrect information, so it was corr issue

Template for product page receives information about all combinations, including their quantities. If it don't display info correctly, it's a theme issue.

**Comment by x97wehner** [comment]
Understand. It sounds like this is issue with TB Niara theme... and, thus, all supported themes then. I will open a new issue for it there.
