### ISSUE TITLE
AdminDuplicateUrls: checking duplicates from Meta class

### ISSUE THREAD

**Issue by Yabbertb** [thirtybees/thirtybees#1936]
If the store administrator makes a mistake and adds duplicate URLs in the Meta class, we have a malfunctioning store. If we have several languages in the store, then visually determining the error of duplicate URLs is not even possible.
Also, it would be very useful to check duplicate URLs from the Meta class in AdminDuplicateUrls.

**Comment by therampagerado** [comment]
Will something like this suffice? 
![image](https://github.com/user-attachments/assets/05370569-9651-4779-ad3f-6f9ea184ecd9)

It detects the pages that don't need additional parameters (like Shops, Contact us, Best sellers) and matches them against all other cases.
