### ISSUE TITLE
An error occurred while generating image types

### ISSUE THREAD

**Issue by judemont** [thirtybees/thirtybees#1939]
When I upload an image for a product, I get this error:
```
An error occurred while generating image types
```

![image](https://github.com/user-attachments/assets/c8eb9c5e-c532-4956-b4dd-ea55f234e1af)

**Comment by getdatakick** [comment]
What tb version are you using?

What error message. do you see in **collectlogs** module?

**Comment by judemont** [comment]
I updated the system and now it works, thank you.
