### ISSUE TITLE
Missing language flags images

### ISSUE THREAD

**Issue by yaniv14** [thirtybees/thirtybees#197]
I did a new installation with default EN language, after that I imported Israel localization pack (which adds Hebrew & Arabic) and both flag images are missing.

![languages thirty bees](https://cloud.githubusercontent.com/assets/3071129/25395653/70eaa318-29ea-11e7-88d4-2d0be630f7fc.png)

**Comment by Traumflug** [comment]
Did this work with an earlier version?

**Comment by yaniv14** [comment]
Didn't check it with earlier version but its working fine with PS 1.6+

**Comment by firstred** [comment]
Added local flags for that

**Comment by firstred** [comment]
https://github.com/thirtybees/thirtybees/commit/7b71bc2cd6c57b41eb08fd81bddaf455a1e4b962
