### ISSUE TITLE
Missing fork info (branch)

### ISSUE THREAD

**Issue by SebSept** [thirtybees/ThirtyBees#20]
Hi,

Is it a fork of the 1.6 or 1.7 prestashop branch ?
I think you should mention it in the Readme file. (at least I'd like to know).

**Comment by Dh42** [comment]
Sorry we were not clear, it is the 1.6 branch. We do not agree with the 1.7 branch's direction.

**Comment by SebSept** [comment]
Good
Thanks for the reply ... and for the initiative.

I hope it will bear fruit .

**Comment by firstred** [comment]
I think it's fixed now? Let me know if there might be something that's still not clear. Thank you!

**Comment by SebSept** [comment]
yes, [fixed](https://github.com/thirtybees/ThirtyBees/commit/3bc782aadc6b7a184c9c82109bdaca49d49ccee2) .

**Comment by firstred** [comment]
Cool, thanks for the feedback!
