### ISSUE TITLE
Webservice API issue: Manufacturer Add returns "Unable to save resource"

### ISSUE THREAD

**Issue by techjp** [thirtybees/thirtybees#201]
I have been trying to use the TB webservice to add Manufacturers (brands). I have written some code that has been tested & works on a Prestashop site but is having a strange problem on a TB site.

The code generates some XML that is then sent to the webservice. Here is a simple example used for testing, as captured by Fiddler going to the TB webservice:

```<thirtybees>
<manufacturer>
  <name>Canon</name>
  <active>1</active>
  <description>
    <language id="1">Canon</language>
  </description>
  <short_description>
    <language id="1">Canon</language>
  </short_description>
  <meta_title>
    <language id="1">Canon</language>
  </meta_title>
  <meta_description>
    <language id="1">Canon</language>
  </meta_description>
  <meta_keywords>
    <language id="1">Canon</language>
  </meta_keywords>
  <associations>
    <addresses />
  </associations>
</manufacturer>
</thirtybees>
```

Please excuse how everything just says "Canon", it's simply for testing.

In any case, I can send this XML to PS 1.6 and it works flawlessly. When I send the same XML to TB it does successfully add the manufacturer to the database and everything seems to be complete. However the webservice returns an error which causes the library I use (Prestasharp) to throw an exception. This is what is returned:

```<?xml version="1.0" encoding="UTF-8"?>
<thirtybees xmlns:xlink="http://www.w3.org/1999/xlink">
  <errors>
    <error>
      <code><![CDATA[46]]></code>
      <message><![CDATA[Unable to save resource]]></message>
    </error>
  </errors>
</thirtybees>
```

The PS 1.6 webservice does not support uploading a thumbnail for the manufacturer (another issue, but not a concern right now), but I wonder if the reworked TB manufacturer code is trying to save a "thumbnail" that doesn't exist and that is what is causing the error?

My other idea is that I know some directories were removed in the transition to TB so I am wondering if one of those removed directories is causing this.

I've been poking around but I can't figure it out. Any thoughts or assistance would be greatly appreciated.

--techjp (dynambee on the forums)

**Comment by techjp** [comment]
I backed up the /classes/Manufacturer.php file and copied a PS 1.6 version of the same file into my TB site. After copying the PS file into the TB site I was able to run my code and add all 80 brands to the dev site without any errors.

I tried comparing the code in the two files but my lack of PHP knowledge is only exceeded by my lack of understanding of the internals of PS & TB. I know something isn't right with the TB file but for the life of me I have no idea what it is.

**Comment by roband7** [comment]
I tried with the "Canon" XML you pasted above against the webservice in my TB 1.0.1beta2, worked just fine. I don't know why it doesn't work for you.

**Comment by techjp** [comment]
This is quite interesting. I'm using 1.0.0 currently so I will try a fresh install with 1.0.1beta2 and see if that fixes the issue. Thank you for taking the time to test!

**Comment by Traumflug** [comment]
A non-beta 1.0.1 exists already: https://github.com/thirtybees/thirtybees/releases

**Comment by techjp** [comment]
Updating to 1.0.1 resolved this issue.
