### ISSUE TITLE
Mailchimp module not working

### ISSUE THREAD

**Issue by sennevb** [thirtybees/thirtybees#202]
![image](https://cloud.githubusercontent.com/assets/6636264/25441392/67f2e8ac-2aa2-11e7-8b6f-15738bee24ee.png)

**Comment by firstred** [comment]
Alright then, let's just go ahead with 1.1.0 and skip 1.0.0

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/eUFY8Zw0Bag/0.jpg)](https://www.youtube.com/watch?v=eUFY8Zw0Bag)
