### ISSUE TITLE
Updater not working

### ISSUE THREAD

**Issue by Havouza** [thirtybees/thirtybees#203]
See attached screenshot. Comes up every step and when press update nothing happens, only the warning
![screenshot 2017-04-26 19 25 49](https://cloud.githubusercontent.com/assets/25871096/25445443/1ce1a7d0-2ab7-11e7-9e89-3c31524642ee.png)

**Comment by firstred** [comment]
Please use the correct repository.

**Comment by Havouza** [comment]
I used the link you published in Gitter

**Comment by firstred** [comment]
No I meant for the issue, but have you tried [1.1.1](https://github.com/thirtybees/tbupdater/releases/tag/1.1.1)? We are patching everything as fast as we can.
