### ISSUE TITLE
CLI Install fails on autload.php

### ISSUE THREAD

**Issue by inetbiz** [thirtybees/thirtybees#216]
thirtybees@thirtybees:/var/www/html$
```php install-dev/index_cli.php --timezone America/New_York --base_uri / --domain localhost --db_server localhost --db_user thirtybees --db_password 123 -db_name thirtybees --prefix tb_ --engine InnoDB --name test install --activity 0 --country us --firstname test --lastname test --password 123 --email user@localhost```

```PHP Warning:  require_once(/var/www/html/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/config/autoload.php on line 35
PHP Fatal error:  require_once(): Failed opening required '/var/www/html/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/config/autoload.php on line 35
`thirtybees@thirtybees:/var/www/html$ ll /var/www/html/config/autoload.php
-rw-r--r-- 1 thirtybees thirtybees 1489 May  2 11:40 /var/www/html/config/autoload.php

**Comment by Traumflug** [comment]
Smells like you're missing a `composer install` to update your vendor stuff. This should also create vendor/autoload.php.

**Comment by Traumflug** [comment]
I mean, `vendor/autoload.php` is missing, while you listed `config/autoload.php`. Two distinct files with the same name.

**Comment by inetbiz** [comment]
@Traumflug the install instructions say that `composer install` is yet but one way to install. The php-cli way just takes params. Or, there is a flaw in the install directions. `vendor` folder does not exist in the release tag, obviously. =)

**Comment by inetbiz** [comment]
I went ahead and ran `composer install`

```thirtybees@thirtybees:/var/www/html$ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpoffice/phpexcel 1.8.1 requires ext-xml * -> the requested PHP extension xml is missing from your system.
    - phpoffice/phpexcel 1.8.0 requires ext-xml * -> the requested PHP extension xml is missing from your system.
    - Installation request for phpoffice/phpexcel ^1.8 -> satisfiable by phpoffice/phpexcel[1.8.0, 1.8.1].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.1/cli/php.ini
    - /etc/php/7.1/cli/conf.d/10-mysqlnd.ini
    - /etc/php/7.1/cli/conf.d/10-opcache.ini
    - /etc/php/7.1/cli/conf.d/10-pdo.ini
    - /etc/php/7.1/cli/conf.d/20-bz2.ini
    - /etc/php/7.1/cli/conf.d/20-calendar.ini
    - /etc/php/7.1/cli/conf.d/20-ctype.ini
    - /etc/php/7.1/cli/conf.d/20-exif.ini
    - /etc/php/7.1/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.1/cli/conf.d/20-ftp.ini
    - /etc/php/7.1/cli/conf.d/20-gd.ini
    - /etc/php/7.1/cli/conf.d/20-gettext.ini
    - /etc/php/7.1/cli/conf.d/20-iconv.ini
    - /etc/php/7.1/cli/conf.d/20-igbinary.ini
    - /etc/php/7.1/cli/conf.d/20-json.ini
    - /etc/php/7.1/cli/conf.d/20-mysqli.ini
    - /etc/php/7.1/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/7.1/cli/conf.d/20-phar.ini
    - /etc/php/7.1/cli/conf.d/20-posix.ini
    - /etc/php/7.1/cli/conf.d/20-readline.ini
    - /etc/php/7.1/cli/conf.d/20-redis.ini
    - /etc/php/7.1/cli/conf.d/20-shmop.ini
    - /etc/php/7.1/cli/conf.d/20-sockets.ini
    - /etc/php/7.1/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.1/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.1/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.1/cli/conf.d/20-tokenizer.ini
    - /etc/php/7.1/cli/conf.d/20-zip.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
```

**Comment by inetbiz** [comment]
I have more php modules to add and enable. Still testing.

**Comment by inetbiz** [comment]
`Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.` composer finished. @firstred

**Comment by inetbiz** [comment]
ok I can now confirm that `composer install` is a required step and the instructions do not reflect this.

**Comment by inetbiz** [comment]
```thirtybees@thirtybees:/var/www/html$ php install-dev/index_cli.php --timezone America/New_York --base_uri / --domain localhost --db_server localhost --db_user thirtybees --db_password 123 -db_name thirtybees --prefix tb_ --engine InnoDB --name test install --activity 0 --country us --firstname test --lastname test --password 123 --email user@localhost
Link to database cannot be established: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)``` Shouldn't be trying root! =(

**Comment by inetbiz** [comment]
```[Tue May 02 22:32:24.415421 2017] [php7:error] [pid 2604] [client 127.0.0.1:45838] script '/var/www/html/install-dev/sandbox/anything.php' not found or unable to stat, referer: http://localhost/install-dev/index.php```

**Comment by Traumflug** [comment]
> I can now confirm that composer install is a required step and the instructions do not reflect this.

Yes, for installations straight from the Git repo. Distribution packages have all the vendor files included.

> It shouldn't be trying to use root!

It's database root, not operating system root. And it has to match your actual database. AFAIK, using 'root' as the only database user is pretty common, anything else requires setting up additional users with phpMyAdmin (or a similar tool).

Do you try to run the regression test suite, perhaps? This likely needs additional configuration in codeception.yml, e.g. `modules->config->Db->password`

**Comment by inetbiz** [comment]
@Traumflug everything matched that I had setup with phpmyadmin. The mysql access denied for root@ tells me that the flag for database user wasn't being parsed?

**Comment by firstred** [comment]
Has it been solved? If so, could you please close this issue?

**Comment by inetbiz** [comment]
@firstred I think it should stay open until docs and readme are corrected with correct syntax. The snippet listed on both properties failed to install.
