### ISSUE TITLE
Bogus master branch

### ISSUE THREAD

**Issue by roband7** [thirtybees/thirtybees#221]
Looks like the source code of beesblog by mistake was checked into the main thirtybees repository, as a master branch.

**Comment by firstred** [comment]
Is this better? https://github.com/thirtybees/thirtybees/blob/43ecb1c/.gitmodules

**Comment by roband** [comment]
That might have been another bug. I was talking about:
https://github.com/thirtybees/thirtybees/branches
The master branch there looks bogus

**Comment by firstred** [comment]
lol
thx!

**Comment by firstred** [comment]
Closing, because we fixed this quite a while ago. Dunno why it was still open.
