### ISSUE TITLE
RTL: Product price format in product page

### ISSUE THREAD

**Issue by yaniv14** [thirtybees/thirtybees#222]
In product page the formatted price with symbol comes from product.js which returns different than the way Smarty does.
This cause a bug with Israeli shekel because when using it in RTL language the direction is RTL and the symbol need to have a space between the price and the currency symbol (because the symbol needs to be on the left side of the price).

the content is from smarty “{convertPrice price=$productPrice|floatval}” and the price is from product.js
`<span id=“our_price_display” class=“price” itemprop=“price” content=“‏59.66 ₪‎”>₪‎59.66</span>`

**Comment by yaniv14** [comment]
This is issue was solved.
It was only cause because of wrong Hebrew language code ("he" instead of "he-il")

**Comment by Traumflug** [comment]
> It was only cause because of wrong Hebrew language code ("he" instead of "he-il")

'he' (or 'en', 'fr', 'de', ...) is a valid language code. 30bz should be able to deal with this.

**Comment by firstred** [comment]
No, the `language_code` must be an IETF locale code.

the `iso_code` should be ISO

**Comment by firstred** [comment]
So if you're seeing this, too, check your language.

This is what Hebrew should be:
![hebrewlocale](https://cloud.githubusercontent.com/assets/6775736/26152179/25f10ce4-3b06-11e7-8df4-05743385152c.png)
