### ISSUE TITLE
tbupdater error when no english language installed

### ISSUE THREAD

**Issue by yaniv14** [thirtybees/thirtybees#223]
Tried to install new beesblog module and got an error.
Installed it from the module section (without downloading the module directly to the folder).
The error I am getting is:
Warning in line 386 in file C:\wamp\www\myshop\modules\tbupdater\tbupdater.php
[2] Illegal string offset ‘en-us’

I added English translation because “in line” and “in file” were in Hebrew.
My guess is that it is related to the fact that I have only one language installed and thats Hebrew, so no [‘en-us’] can be retrieved.

$locale fall back should be default language locale

**Comment by firstred** [comment]
Wierd. `en-us` should always be available as that is the global default.

I'll check the feed then.

**Comment by yaniv14** [comment]
This issue is related to windows only.
When doing the same on linux, everything works fine.

**Comment by firstred** [comment]
Moved to https://github.com/thirtybees/tbupdater
