### ISSUE TITLE
Debug shows error on tbupdater

### ISSUE THREAD

**Issue by yaniv14** [thirtybees/thirtybees#224]
When entering configuration of tbupdater module I am get this when debug open.
Notice line 67 file C:\wamp\www\myshop\modules\tbupdater\views\templates\admin\blockupgradebutton.phtml
[8] Undefined property: TbUpdater::$manualMode

Notice line 39 file C:\wamp\www\myshop\modules\tbupdater\views\templates\admin\mainjs.phtml
[8] Undefined property: TbUpdater::$manualMode

I am using TB v1.0.1 with only Hebrew language (no english at all)

**Comment by firstred** [comment]
Does it still do that?

**Comment by yaniv14** [comment]
No, version 1.1.3 works fine.

**Comment by firstred** [comment]
Thank for the update!
