### ISSUE TITLE
Logo not saving correctly with unicode

### ISSUE THREAD

**Issue by yaniv14** [thirtybees/thirtybees#225]
When having a store name in Hebrew, after trying to upload a new logo.
The logo is being renamed to the store name - logo - timestamp (i think).
The actual filename is being created with gibrish text instead the unicode one, which makes the logo file unreachable.
You will have to manually rename the logo name to match the store name.

**Comment by firstred** [comment]
Strange. That shouldn't happen as unicode is used everywhere. Let's have a look.

**Comment by yaniv14** [comment]
My store name is in Hebrew.
[this is what happen after i upload logo](http://prntscr.com/f5ehdi)
This is with inspect element:
`<img src="/levis/img/לויס-logo-1494235820.jpg" alt="לוגו כותרת" title="לוגו כותרת">`
and this is the name of the file saved in img dir:
`׳׳•׳™׳¡-logo-1494235820.jpg`

Now this is on windows with wamp server.

**Comment by firstred** [comment]
Does this change solve it?

https://github.com/thirtybees/thirtybees/commit/04d36863994fc776affc2333d96ffaea13d2c217

**Comment by yaniv14** [comment]
No.
It does encode the file name (%D7%9C%D7%95%D7%99%D7%A1-logo-1498628220.jpg)
And the filename matches the {$logo_url} output.
But it still doesn't show the logo.

```
Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/levys/img/%D7%9C%D7%95%D7%99%D7%A1-logo-1498628220.jpg
```

**Comment by firstred** [comment]
Then I am going to remove the % sign as well as I don't see any other way to make it work on Windows.

https://github.com/thirtybees/thirtybees/commit/c727ff556543dffc387fb6b1905bdc21b452a7b2

**Comment by yaniv14** [comment]
Well.... it's working fine now without the % sign.
But isn't it also effecting linux now?
And also, why do we need to save the logo name like that? why can't we just name it logo.{ext}?
Who care about the filename? anyway we have alt tag with shop name.

**Comment by firstred** [comment]
No, it's keeping track of the filename via the database, so this can be safely applied.

Thanks for confirming that it works! Much appreciated.
