### ISSUE TITLE
RTL: Community theme lack of RTL support in css and tpl.

### ISSUE THREAD

**Issue by yaniv14** [thirtybees/thirtybees#228]
Back arrows need to be addressed in tpl files to be reversed on RTL.
Also css needed.

Also blocksearch autocomplete result box is not aligned correctly on RTL.

PR: https://github.com/thirtybees/community-theme-default/pull/2/commits/f8e0927316672b5fb76297b1c4583aa451989350

**Comment by firstred** [comment]
Closing, as this issue is part of the community-theme-default repo. Thanks for the PR nonetheless!
