### ISSUE TITLE
RTL: layered navigation module range filter

### ISSUE THREAD

**Issue by yaniv14** [thirtybees/thirtybees#230]
The range filter need support for RTL.
This is more than just css, because part of it comes from JS.
[example](http://prntscr.com/f5e51p)

RTL reads from right to left but digit consider LTR which place the currency symbol wrong.

**Comment by firstred** [comment]
Moved to https://github.com/thirtybees/blocklayered

**Comment by Traumflug** [comment]
@yaniv14, the other issue doesn't want to notify you, but your help is needed, you probably know best how price sliders should look like in Israel:

https://github.com/thirtybees/blocklayered/issues/1#issuecomment-399533547

**Comment by yaniv14** [comment]
Just commented on the other issue
