### ISSUE TITLE
AdminDuplicateUrlsController bug

### ISSUE THREAD

**Issue by yaniv14** [thirtybees/thirtybees#236]
getManufacturerUrls & getSupplierUrls should return empty array instead of false when there is no manufacturer or supplier.

**Comment by firstred** [comment]
https://github.com/thirtybees/thirtybees/commit/06edefed6f8f2bcce510dd1cb393a5c971a0acce

**Comment by Traumflug** [comment]
Does this commit work for you as well, @yaniv14 ? I simply applied it to an already installed shop and the issue is gone.

**Comment by yaniv14** [comment]
Yes, its working fine.

**Comment by Traumflug** [comment]
Excellent.
