### ISSUE TITLE
Duplicate URLs test throwing errors

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#237]
This is a shop installed from the 1.0.1 package *without* demo data. Accordingly there are no products.

Whenever I choose Back Office -> Preferences -> Duplicate URLs I get this:

![duplicate urls](https://cloud.githubusercontent.com/assets/318581/25858522/3a9be2b6-34dc-11e7-8900-ea98f72e7f3b.png)

**Comment by firstred** [comment]
Duplicate of: https://github.com/thirtybees/thirtybees/issues/236

We're working on it. Both @Traumflug @yaniv14 thanks!

**Comment by firstred** [comment]
https://github.com/thirtybees/thirtybees/commit/06edefed6f8f2bcce510dd1cb393a5c971a0acce

**Comment by Traumflug** [comment]
Applying this fix to an installed shop works just fine. Thank you for taking care, @firstred.
