### ISSUE TITLE
Many modules show &#039; in texts

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#242]
See https://forum.thirtybees.com/topic/314/does-anyone-else-see-website-039-s-in-admin-modules-and-services

Putting this here, because it happens in many modules. It's the `<description>` text in each module's `config.xml`. Similar codes can be found in some JavaScript strings, e.g. in `blocktopmenu/js/superfish-modified.js` line 18. Depending on what the point of inserting code there is, it might be preferred to change the module manager to respect such codes instead of fixing each module.

**Comment by Traumflug** [comment]
Command line to find occurences:

```sh
find modules -type f ! -name \*.gif ! -name \*.svg ! -name \*.ttf ! -name \*.eot ! -name \*.jpg -exec grep '&#' {} \; -print
```

**Comment by firstred** [comment]
https://github.com/thirtybees/thirtybees/commit/dffdeba2b1cd8a70896d833d37a9deae853d7fb4
