### ISSUE TITLE
Customized orders mess up the checkout page

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#244]
This might be a theme problem, can't tell what exactly is going wrong so far.

Steps to reproduce:

- Standard installation with demo products.
- Go to Backoffice -> Catalog -> Products -> Product 'demo_5' -> Customization and enter '1' in 'text fields'.
- Click 'Save & Stay'. (to make additional fields visible)
- Enter something at 'Define the label of the text fields'.

So far the required setup. I also have a multishop, which shouldn't matter. Next steps:
- Go to the shop front page.
- Click on that 'demo_5' product.
- Go to the text field near the bottom and enter some custom text.
- Click 'Save'.
- Click 'Add to cart', then 'Proceed to checkout'.

Now the checkout page looks like this:

![bildschirmfoto vom 2017-05-25 16-09-51](https://cloud.githubusercontent.com/assets/318581/26453691/e6faf170-4164-11e7-8265-a673bc494808.png)

Several things go wrong here:
- This custom text is separated from the product.
- Quantity is displayed twice.
- Clicking on the '+' button to raise quantity doesn't change quantity in the table. Quantity shown in the drop-down in the header does change.
- After clicking '+', clicking '-' empties the table. Cart drop-down in the header still reports quantity 1.

To some extents it looks like this custom text field is handled like a separate product by some, but not all parts of the logic.

**Comment by kpodemski** [comment]
This is all good here, you can add as many customized products as you wish, these are not attributes, this is why it is looking like this

**Comment by Traumflug** [comment]
Still clicking on '+', then '-' makes the product going away. And quantity is shown twice. Even if this kind of display were intended, it's not usable.

**Comment by kpodemski** [comment]
I suggest you to add more customized version of the product to see how qty displaying works, for the problem with +, it seems that there is some issue with it

**Comment by firstred** [comment]
It was definitely a nasty bug by some old broken code. Here's the fix: https://github.com/thirtybees/thirtybees/commit/6433ad88ed4cd2492e0ca99fbf1f9a7b8b710b8c

**Comment by firstred** [comment]
Pleas close this issue if you can confirm it works.

**Comment by firstred** [comment]
More info in this topic: https://forum.thirtybees.com/topic/424/quantity-in-cart-not-updated-when-using-custom-text-field-s

**Comment by Traumflug** [comment]
I can confirm this patch works just fine. Thanks for fixing the issue!
