### ISSUE TITLE
Manufacturers block image missing from feed

### ISSUE THREAD

**Issue by yaniv14** [thirtybees/thirtybees#246]
[screenshot](http://prntscr.com/fdfkef)

**Comment by Traumflug** [comment]
One can upload images here, see this small text at the bottom of the edit field :-)

This is the same screenshot:

![](https://image.prntscr.com/image/ca717f6fa200491687831db2ed62ae3e.png)

**Comment by yaniv14** [comment]
what?

**Comment by firstred** [comment]
Thanks!

It was https//cdn.rawgit.com/thirtybees/blockmanufacturer/master/logo.png
but should be https://cdn.rawgit.com/thirtybees/blockmanufacturer/master/logo.png
