### ISSUE TITLE
Exception throw when missing php zip extension on server

### ISSUE THREAD

**Issue by yaniv14** [thirtybees/thirtybees#247]
Its not an issue, but maybe it is something that can be checked prior.
[screenshot](http://prntscr.com/fdflyo)

**Comment by Traumflug** [comment]
![](https://image.prntscr.com/image/e90c5123151740aab2e0be8f04050122.png)

**Comment by firstred** [comment]
Did you migrate or fresh install?

**Comment by yaniv14** [comment]
Migrate

**Comment by firstred** [comment]
Moved to https://github.com/thirtybees/psonesixmigrator/issues/5
