### ISSUE TITLE
[Pending of a deep study] Error with credit slips and refund process

### ISSUE THREAD

**Issue by TobyMudito** [thirtybees/thirtybees#248]
Steps to reproduce the issue.

1. Install a clean 1.0.1 Thirty bees version.
2. Make a test order with 3 products.
3. Go to the order in the back office.
4. Create a standar refund with two of the products.
![image](https://cloud.githubusercontent.com/assets/25913840/26556295/040f5872-449a-11e7-8532-f4d604d5544d.png)

In the documents tab, the quantity showed is incorrect. It doesn't show the total order slip amount, just the quantity of the first product of the order slip.

![image](https://cloud.githubusercontent.com/assets/25913840/26556367/6c2220de-449a-11e7-9737-2a0d94fd786d.png)

Regards.

**Comment by firstred** [comment]
That is a really good and detailed report. Thank you!

**Comment by firstred** [comment]
Does this commit fix it?

https://github.com/thirtybees/thirtybees/commit/998dfd34ea9df313fd8b3fed34b6d63b811896d3

**Comment by firstred** [comment]
Have you been able to verify if the fix works?

**Comment by TobyMudito** [comment]
No, I have it pending. I hope to do it soon :)

**Comment by firstred** [comment]
Unable to verify the issue. Removed the milestone for now.

**Comment by firstred** [comment]
Closing this issue. You can reply to get it reopened.
