### ISSUE TITLE
No combinations when products are virtual

### ISSUE THREAD

**Issue by Havouza** [thirtybees/thirtybees#253]
Perhaps this is not a bug, but for me it is. I cant see one reason why the combinations/attributes are disabled for virtual products. This is ofc a rest from PS. @NemoPS has done a tutorial for PS to fix it but unfortunately, the AdminProductsController is much rewritten in TB so you cant follow it. 
Please enable the attributes in Virtual/Service products once and for all

**Comment by Dh42** [comment]
This is the current way it works. I will see if Nemo can update it or give you information on how to change it for thirty bees. We should try to merge this into the core very soon.

**Comment by mke-tb** [comment]
@NemoPS Did you ever do this on Thirty Bees or do we need to do it from scratch?

**Comment by getdatakick** [comment]
Closes by c6e3694becb6f9b8aa8256d3d662e275ce19d179
