### ISSUE TITLE
My account -> Discount

### ISSUE THREAD

**Issue by asymetria** [thirtybees/thirtybees#255]
Some issues in discount.tpl :
- **undefined index: minimal** ($discountDetail.minimal),
- **undefined index: cumulable** ($discountDetail.cumulable),
- **Array to string conversion** ({$discountDetail.gift_product_name})
----
Issue in controllers/front/DiscountController.php on line 70:
- **undefined index: value** ($discount['value'])

**Comment by firstred** [comment]
Does this change help?

https://github.com/thirtybees/thirtybees/commit/9fa79eb17b78472f935704fd5daddf5a3535a04b

**Comment by asymetria** [comment]
Unfortunately still:
- undefined index: value in controllers/front/DiscountController.php  on line  72
+ no changes in discount.tpl

**Comment by firstred** [comment]
Another fix: https://github.com/thirtybees/thirtybees/commit/1613917b05446a9d488f1fc01cb0dd47d939aabf

**Comment by firstred** [comment]
https://github.com/thirtybees/thirtybees/commit/dcd755da352370ee0db8992a09eafcf9d6ed54d0

**Comment by firstred** [comment]
Please close this issue if these fixes have solved it. Thank you!
