### ISSUE TITLE
My account -> Order history -> Order detail -> Comment about your order

### ISSUE THREAD

**Issue by asymetria** [thirtybees/thirtybees#256]
Add a message (Comment about your order) does not send any message. No info about sending, no message in order details in BO too.

**Comment by firstred** [comment]
Fix: https://github.com/thirtybees/thirtybees/commit/b7a11cb7789b7ea13222a89ea70f85b1a0efe5c8

**Comment by firstred** [comment]
Please close this issue if confirmed to be fixed.
