### ISSUE TITLE
Allowing module frontController overrides

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/thirtybees#258]
Some time ago a user posted in PS forum a solution, to use overrides on FrontController in a module. Could we add this to core? 

Details: https://www.prestashop.com/forums/topic/480523-override-front-controller-of-modules/
@NemoPS: http://nemops.com/overriding-modules-controllers-in-prestashop-1-6/#.WUo5rGjyiUk

**Comment by Traumflug** [comment]
I still consider the usage of overrides to be asking for trouble. AFAIK, PS 1.7 got rid of them, so developers should get accustomed to add functionality in a less troublesome way.

Which raises the question: why feel developers a need for such overrides? Is there a hook missing? Some functionality missing which could go into core code, too?

**Comment by alwayspaws** [comment]
I agree with Traumflug. Let's not use overrides. Too much individual coding for those who want it and then something else breaks or the module or other details becomes less functional in other ways. 

It's best to create a fresh module or fix for whatever is needed.

**Comment by eschiendorfer** [comment]
@Traumflug yesterday I have changed my blog module a bit. I have added a "shortcode" functionality. I have overwritten one method and added another one. How should I do this, by using hooks?

Another example: In backoffice product list we display different fields than standard. Override is just perfect, to change it. How else would you do it?

I agree that multiple override causes some troubles, but single ones are working nicely for me. If thirty bees can reduce the needs for overrides I am the first who will like it!

**Comment by Traumflug** [comment]
> Another example: In backoffice product list we display different fields than standard. Override is just perfect, to change it. How else would you do it?

By registering a hook '...FormModifier', removing unwanted fields, adding wanted ones. Invoking code see https://github.com/thirtybees/thirtybees/blob/1.0.x/classes/controller/AdminController.php#L2849

If these hooks don't cover such adjustments I'm entirely fine with adding more of them.

**Comment by roband** [comment]
We are stuck with the existing hooks and with the existing override system for a long long time, for compatability with PS 1.6.

Should we add new hooks or should we extend the override system? Probably not.

See this for another approach suggested by @mdekker some time ago:
https://trello.com/c/d3Yfci7f/47-replace-override-system-with-go-aop-framework

**Comment by alwayspaws** [comment]
Traumflug:  "If these hooks don't cover such adjustments I'm entirely fine with adding more of them."  - yes, great idea.

Roband: "See this for another approach suggested by @mdekker some time ago" -   can we add more tasks to Michael Dekker's burden? Much better than overrides. I don't think he will mind. :)

**Comment by eschiendorfer** [comment]
@roband I have no problems if tb choses a different approach, but not sure if it's realistic for the near future!?

**Comment by guestisp** [comment]
IMHO, overrides are evil and should be totally removed from thirtybees as they make almost impossible to update a thirtybees shop safely. If you have tons of overrides (like many modules needs), updating thirtybees to a newer version is a pain, as the overridden function (that newer thirtybees version needs) will work differenty as it should.

thirtybees should remove overrides by forcing modules/theme developers to not use overrides when publishing modules/themes on thirtybees marketplace or by moving the `overrides_on` `overrides_off` out of the admin interface. If you really really need to use overrides, you should enable them manually in config file.

**Comment by mke-tb** [comment]
I think the majority thinks that overrides are evil and either should not be extended or removed altogether.

Do we need this issue dangling in the history or define a clear approach to overrides and act upon it? @Dh42 Would be nice to hear your opinion as well.

**Comment by Traumflug** [comment]
I'd vote for closing this without change. The can of worms opened is bigger than the possible gain.

**Comment by mke-tb** [comment]
Looks like not touching anything ATM seems like the best option. Closing.
