### ISSUE TITLE
Can't install Deutsch

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#259]
While trying to verify the solution for issue #244 I ran into this:

![grafik](https://user-images.githubusercontent.com/318581/27381816-8e8c9fe0-5684-11e7-98e2-abb2293edb3e.png)

Steps I did:

- Checkout `1.0.x` in my repository fork.
- Run `build.sh` to make a package.
- Unpack that package into a new directory.
- Direct the browser to this new directory, install using English as installation language and Germany as shop location.
- Proceed as usual.

I have no such issue with the official 1.0.1 package. Repeating the procedure using this red link ('clicking here') doesn't change behavior. Error log isn't of much help:
```sh
$ cat log/20170621_installation.log 
*ERROR* 	2017/06/21 - 13:16:25: Cannot install language "Deutsch (German)"
*ERROR* 	2017/06/21 - 13:17:04: Cannot install language "Deutsch (German)"
```
Will try to verify #244 by some other means now and then come back to this issue.

**Comment by Traumflug** [comment]
P.S.: I always wondered why the installer would install German when the choosen installation language is English.

**Comment by Traumflug** [comment]
Problem found: 30bz version on *1.0.x* is currently `1.0.2-beta.1` and there is no such language pack on translations.thirtybees.com.

First idea was to not download languages, like it's done when installing in "safe_mode". This works. However, it also misses translations.

Looking for an even better solution now. Like trying to download, then fallback to the safe_mode procedure, together with a user notification.

**Comment by firstred** [comment]
Yeah `1.0.2-beta.1` means it looks for `1.0.2` language packs.
Gotta find something for that. Gradually try to lower the patch version?

**Comment by Nobodaddy** [comment]
Well, I didn't try the German language pack I uploaded [here in my TB repository](https://github.com/Nobodaddy/ThirtyBees/tree/patch-1/translations) - four month ago! - on 1.02 yet, but it works pretty well for 1.01. :)

**Comment by Traumflug** [comment]
@Nobodaddy, I wasn't aware of this before (either), but language and translation packages are distinguished not only by language, but also by version. German for 1.0.1 and German for 1.0.2 are two distinct packages.

About improving the situation. Outcome of this story is something close to overengineering.
- I introduced non-fatal installer error messages, which are equal to fatal ones, except that they don't stop the installation procedure. They appear as soon as they're found. If one appears, progress screen doesn't slide away as installation completes.
- If installing the current version fails, it tries with one version earlier (test with `_TB_INSTALL_VERSION_ = 1.0.2-beta.1`):

![grafik](https://user-images.githubusercontent.com/318581/27454746-4913c368-579b-11e7-9aab-cd886d2e7607.png)

- If this also fails, it creates a language pack from those XMLs coming with the installer (test with `_TB_INSTALL_VERSION_ = 1.9.99`):

![grafik](https://user-images.githubusercontent.com/318581/27456514-a3581378-57a1-11e7-854e-51e5780ae880.png)

If the language pack is available, everything is as before.

Code is the most recent 9 commit here: https://github.com/Traumflug/thirtybees/commits/missing-language If there are no objections, I'll nitpick and move them tomorrow.

**Comment by firstred** [comment]
Nice! That's a great way to handle it. Merge it if you like :)

I have copied the 1.0.1 language package to 1.0.2 for now. We can't keep the packages updated properly at the moment because CrowdIn has asked us to use branching instead of directories and until that time we can only host 2 versions in our CrowdIn project.

**Comment by Nobodaddy** [comment]
@Traumflug Thanks for your kind lesson :D, but I'm familiar with these basics since years. Anyway, I had no problems with language packs when installing TB 1.0 and 1.0.1. So I just wasn't aware of this bug due to a different install routine in _install.php_, compared with the same file of PS 1.6.

**Comment by Traumflug** [comment]
This solution isn't fine, yet. Running the 1.9.99 test I end up with English installed three times. More work ahead :-)

**Comment by Traumflug** [comment]
File `translations/en.gzip` being part of the code repository is the cause of this unwanted behaviour. Code tries to download it and if the download fails, it generates an error message, nevertheless it installs it anyways, because it's already there. That's a bit inconsistent for my taste. Either error or success, but not both.

While it's certainly possible to get this straight, I wonder whether it's a good idea to have `en.gzip` and `fr.gzip` in the code repository. English needs no translation, that's hardcoded already. And french? *shrugs*

Is it OK to remove these two files? Removes the burden to keep them in sync with online versions :-)

**Comment by firstred** [comment]
is french part of the main repo? :O

**Comment by firstred** [comment]
Interesting. I think we should remove both. And having just the French translation available offline isn't fair. We should treat all languages equally!

**Comment by Nobodaddy** [comment]
French was always attached, a given for a French software. Whereas the English translation for 1.6 has never been  complete. Even the current PS English translations for 1.6 are wrong to some extent and not fully approved. There is every reason to remove both.

**Comment by Traumflug** [comment]
Just pushed this stuff. Together with crossing fingers this didn't break language/translations stuff elsewhere. I tested installing languages and translations, it still works.

Notes for the next visit of this area:
- Separate language and translations handling code. Currently they're kind of mixed, with some duplicate code. Some code allows version selection, other code works for the installed version, only.
- Move backoffice menu items of these two next to each other.
- Move language installation into the languages panel. That also means, allow installation of a language without installing translations.
- Allow adding translations for existing languages, only. Certainly in code, maybe also user-visible.
