### ISSUE TITLE
1.0.2 release - Code review

### ISSUE THREAD

**Issue by firstred** [thirtybees/thirtybees#274]
A thorough code review of every single file is needed, due to the large rewrites. 

Everyone with write access to this repository is invited to tick the boxes of checked files. Good luck!

- [x] classes/County.php
- [x] classes/range/RangePrice.php
- [x] classes/range/RangeWeight.php
- [x] classes/Tag.php
- [x] classes/RequestSql.php
- [x] classes/Gender.php
- [x] classes/Cookie.php
- [x] classes/Currency.php
- [x] classes/ConfigurationKPI.php
- [x] classes/pdf/HTMLTemplate.php
- [x] classes/pdf/PDFGenerator.php
- [x] classes/pdf/HTMLTemplateSupplyOrderForm.php
- [x] classes/pdf/PDF.php
- [x] classes/pdf/HTMLTemplateOrderReturn.php
- [x] classes/pdf/HTMLTemplateDeliverySlip.php
- [x] classes/pdf/HTMLTemplateInvoice.php
- [x] classes/pdf/HTMLTemplateOrderSlip.php
- [x] classes/Referrer.php
- [x] classes/module/Module.php
- [x] classes/module/ModuleGrid.php
- [x] classes/module/FreeOrder.php
- [x] classes/module/CurrencyRateModule.php
- [x] classes/module/ModuleGraphEngine.php
- [x] classes/module/ModuleGridEngine.php
- [x] classes/module/BoOrder.php
- [x] classes/module/CarrierModule.php
- [x] classes/module/LibraryModule.php
- [x] classes/module/ImportModule.php
- [x] classes/module/ErrorModule.php
- [x] classes/module/PaymentModule.php
- [x] classes/module/ModuleGraph.php
- [x] classes/Chart.php
- [x] classes/Carrier.php
- [x] classes/controller/ModuleAdminController.php
- [x] classes/controller/Controller.php
- [x] classes/controller/AdminController.php
- [x] classes/controller/FrontController.php
- [x] classes/controller/ModuleFrontController.php
- [x] classes/db/DbPDO.php
- [x] classes/db/DbQuery.php
- [x] classes/db/Db.php
- [x] classes/CMS.php
- [x] classes/Guest.php
- [x] classes/Validate.php
- [x] classes/Country.php
- [x] classes/LocalizationPack.php
- [x] classes/Rijndael.php
- [x] classes/Image.php
- [x] classes/ImageManager.php
- [x] classes/Customer.php
- [x] classes/Context.php
- [x] classes/Encryptor.php
- [x] classes/tree/TreeToolbarButton.php
- [x] classes/tree/TreeToolbarSearchCategories.php
- [x] classes/tree/TreeToolbar.php
- [x] classes/tree/TreeToolbarLink.php
- [x] classes/tree/TreeToolbarSearch.php
- [x] classes/tree/ITreeToolbarButton.php
- [x] classes/tree/Tree.php
- [x] classes/tree/ITreeToolbar.php
- [x] classes/SmartyCustom.php
- [x] classes/Page.php
- [x] classes/CartRule.php
- [x] classes/Attribute.php
- [x] classes/Search.php
- [x] classes/Zone.php
- [x] classes/Cart.php
- [x] classes/DateRange.php
- [x] classes/SpecificPrice.php
- [x] classes/State.php
- [x] classes/SmartyCacheResourceMysql.php
- [x] classes/CustomerMessage.php
- [x] classes/PrestaShopAutoload.php
- [x] classes/cache/Cache.php
- [x] classes/cache/CacheMemcached.php
- [x] classes/cache/CacheMemcache.php
- [x] classes/cache/CacheFs.php
- [x] classes/cache/CacheRedis.php
- [x] classes/cache/CacheApcu.php
- [x] classes/Profile.php
- [x] classes/Dispatcher.php
- [x] classes/AttributeGroup.php
- [x] classes/Theme.php
- [x] classes/PrestaShopLogger.php
- [x] classes/ImageType.php
- [x] classes/webservice/WebserviceSpecificManagementSearch.php
- [x] classes/webservice/WebserviceSpecificManagementImages.php
- [x] classes/webservice/WebserviceOutputXML.php
- [x] classes/webservice/WebserviceSpecificManagementInterface.php
- [x] classes/webservice/WebserviceOutputInterface.php
- [x] classes/webservice/WebserviceOutputBuilder.php
- [x] classes/webservice/WebserviceRequest.php
- [x] classes/webservice/WebserviceOutputJSON.php
- [x] classes/webservice/WebserviceException.php
- [x] classes/webservice/WebserviceKey.php
- [x] classes/PaymentCC.php
- [x] classes/Message.php
- [x] classes/CustomerThread.php
- [x] classes/Pack.php
- [x] classes/ProductSale.php
- [x] classes/Media.php
- [x] classes/ConnectionsSource.php
- [x] classes/Meta.php
- [x] classes/SearchEngine.php
- [x] classes/Connection.php
- [x] classes/CustomizationField.php
- [x] classes/log/AbstractLogger.php
- [x] classes/log/FileLogger.php
- [x] classes/CMSCategory.php
- [x] classes/Translate.php
- [x] classes/CryptBlowfish.php
- [x] classes/SpecificPriceRule.php
- [x] classes/Tools.php
- [x] classes/Uploader.php
- [x] classes/PageCache.php
- [x] classes/Risk.php
- [x] classes/tax/TaxManagerFactory.php
- [x] classes/tax/TaxManagerInterface.php
- [x] classes/tax/TaxCalculator.php
- [x] classes/tax/Tax.php
- [x] classes/tax/AverageTaxOfProductsTaxCalculator.php
- [x] classes/tax/TaxRulesTaxManager.php
- [x] classes/tax/TaxRulesGroup.php
- [x] classes/tax/TaxManagerModule.php
- [x] classes/tax/TaxRule.php
- [x] classes/Employee.php
- [x] classes/ObjectModel.php
- [x] classes/Upgrader.php
- [x] classes/Delivery.php
- [x] classes/Link.php
- [x] classes/FeatureValue.php
- [x] classes/Address.php
- [x] classes/Blowfish.php
- [x] classes/AdminTab.php
- [x] classes/helper/HelperCalendar.php
- [x] classes/helper/HelperOptions.php
- [x] classes/helper/Helper.php
- [x] classes/helper/HelperShop.php
- [x] classes/helper/HelperKpiRow.php
- [x] classes/helper/HelperView.php
- [x] classes/helper/HelperImageUploader.php
- [x] classes/helper/HelperForm.php
- [x] classes/helper/HelperTreeShops.php
- [x] classes/helper/HelperKpi.php
- [x] classes/helper/HelperUploader.php
- [x] classes/helper/HelperList.php
- [x] classes/helper/HelperTreeCategories.php
- [x] classes/Scene.php
- [x] classes/PhpEncryption.php
- [x] classes/UrlRewrite.php
- [x] classes/Hook.php
- [x] classes/Tab.php
- [x] classes/PrestaShopBackup.php
- [x] classes/Alias.php
- [x] classes/Group.php
- [x] classes/exception/PrestaShopModuleException.php
- [x] classes/exception/PrestaShopPaymentException.php
- [x] classes/exception/PrestaShopDatabaseException.php
- [x] classes/exception/PrestaShopException.php
- [x] classes/TranslatedConfiguration.php
- [x] classes/PrestaShopCollection.php
- [x] classes/FileUploader.php
- [x] classes/stock/StockManager.php
- [x] classes/stock/StockMvtReason.php
- [x] classes/stock/Warehouse.php
- [x] classes/stock/SupplyOrderState.php
- [x] classes/stock/WarehouseProductLocation.php
- [x] classes/stock/SupplyOrder.php
- [x] classes/stock/SupplyOrderDetail.php
- [x] classes/stock/StockManagerFactory.php
- [x] classes/stock/SupplyOrderHistory.php
- [x] classes/stock/StockMvt.php
- [x] classes/stock/Stock.php
- [x] classes/stock/StockMvtWS.php
- [x] classes/stock/StockManagerModule.php
- [x] classes/stock/StockAvailable.php
- [x] classes/stock/SupplyOrderReceiptHistory.php
- [x] classes/stock/StockManagerInterface.php
- [x] classes/.htaccess
- [x] classes/QuickAccess.php
- [x] classes/ProductSupplier.php
- [x] classes/Manufacturer.php
- [x] classes/ConfigurationTest.php
- [x] classes/Combination.php
- [x] classes/CMSRole.php
- [x] classes/CSV.php
- [x] classes/Supplier.php
- [x] classes/Mail.php
- [x] classes/Customization.php
- [x] classes/Contact.php
- [x] classes/Attachment.php
- [x] classes/CompareProduct.php
- [x] classes/Language.php
- [x] classes/Notification.php
- [x] classes/ProductDownload.php
- [x] classes/Feature.php
- [x] classes/order/OrderHistory.php
- [x] classes/order/OrderMessage.php
- [x] classes/order/OrderState.php
- [x] classes/order/Order.php
- [x] classes/order/OrderCartRule.php
- [x] classes/order/OrderReturn.php
- [x] classes/order/OrderSlip.php
- [x] classes/order/OrderPayment.php
- [x] classes/order/OrderDetail.php
- [x] classes/order/OrderReturnState.php
- [x] classes/order/OrderCarrier.php
- [x] classes/order/OrderInvoice.php
- [x] classes/Product.php
- [x] classes/Category.php
- [x] classes/shop/ShopGroup.php
- [x] classes/shop/Shop.php
- [x] classes/shop/ShopUrl.php
- [x] classes/Store.php
- [x] classes/ControllerFactory.php
- [x] classes/Configuration.php
- [x] classes/GroupReduction.php
- [x] classes/AddressFormat.php
- [x] controllers/admin/AdminCartsController.php
- [x] controllers/admin/AdminTagsController.php
- [x] controllers/admin/AdminStockManagementController.php
- [x] controllers/admin/AdminSlipController.php
- [x] controllers/admin/AdminAttributesGroupsController.php
- [x] controllers/admin/AdminProductsController.php
- [x] controllers/admin/AdminEmailsController.php
- [x] controllers/admin/AdminAttributeGeneratorController.php
- [x] controllers/admin/AdminRangeWeightController.php
- [x] controllers/admin/AdminQuickAccessesController.php
- [x] controllers/admin/AdminDuplicateUrlsController.php
- [x] controllers/admin/AdminSearchEnginesController.php
- [x] controllers/admin/AdminGroupsController.php
- [x] controllers/admin/AdminContactsController.php
- [x] controllers/admin/AdminOutstandingController.php
- [x] controllers/admin/AdminCurrenciesController.php
- [x] controllers/admin/AdminStockCoverController.php
- [x] controllers/admin/AdminModulesPositionsController.php
- [x] controllers/admin/AdminNotFoundController.php
- [x] controllers/admin/AdminBackupController.php
- [x] controllers/admin/AdminTaxesController.php
- [x] controllers/admin/AdminAdminPreferencesController.php
- [x] controllers/admin/AdminStatsTabController.php
- [x] controllers/admin/AdminCustomersController.php
- [x] controllers/admin/AdminOrderMessageController.php
- [x] controllers/admin/AdminStockMvtController.php
- [x] controllers/admin/AdminCmsController.php
- [x] controllers/admin/AdminEmployeesController.php
- [x] controllers/admin/AdminShopController.php
- [x] controllers/admin/AdminSearchConfController.php
- [x] controllers/admin/AdminRangePriceController.php
- [x] controllers/admin/AdminMetaController.php
- [x] controllers/admin/AdminCustomCodeController.php
- [x] controllers/admin/AdminManufacturersController.php
- [x] controllers/admin/AdminLanguagesController.php
- [x] controllers/admin/AdminStatesController.php
- [x] controllers/admin/AdminFeaturesController.php
- [x] controllers/admin/AdminPPreferencesController.php
- [x] controllers/admin/AdminStockConfigurationController.php
- [x] controllers/admin/AdminCmsContentController.php
- [x] controllers/admin/AdminCartRulesController.php
- [x] controllers/admin/AdminReferrersController.php
- [x] controllers/admin/AdminSuppliersController.php
- [x] controllers/admin/AdminMaintenanceController.php
- [x] controllers/admin/AdminPreferencesController.php
- [x] controllers/admin/AdminZonesController.php
- [x] controllers/admin/AdminStatsController.php
- [x] controllers/admin/AdminStockInstantStateController.php
- [x] controllers/admin/AdminModulesController.php
- [x] controllers/admin/AdminCarrierWizardController.php
- [x] controllers/admin/AdminCustomerThreadsController.php
- [x] controllers/admin/AdminCountriesController.php
- [x] controllers/admin/AdminReturnController.php
- [x] controllers/admin/AdminAccessController.php
- [x] controllers/admin/AdminShippingController.php
- [x] controllers/admin/AdminRequestSqlController.php
- [x] controllers/admin/AdminCarriersController.php
- [x] controllers/admin/AdminPaymentController.php
- [x] controllers/admin/AdminScenesController.php
- [x] controllers/admin/AdminDeliverySlipController.php
- [x] controllers/admin/AdminTranslationsController.php
- [x] controllers/admin/AdminPerformanceController.php
- [x] controllers/admin/AdminStatusesController.php
- [x] controllers/admin/AdminLogsController.php
- [x] controllers/admin/AdminAddressesController.php
- [x] controllers/admin/AdminLocalizationController.php
- [x] controllers/admin/AdminGendersController.php
- [x] controllers/admin/AdminDashboardController.php
- [x] controllers/admin/AdminTaxRulesGroupController.php
- [x] controllers/admin/AdminTabsController.php
- [x] controllers/admin/AdminProfilesController.php
- [x] controllers/admin/AdminSpecificPriceRuleController.php
- [x] controllers/admin/AdminSearchController.php
- [x] controllers/admin/AdminShopGroupController.php
- [x] controllers/admin/AdminPatternsController.php
- [x] controllers/admin/AdminShopUrlController.php
- [x] controllers/admin/AdminCustomerPreferencesController.php
- [x] controllers/admin/AdminInvoicesController.php
- [x] controllers/admin/AdminAttachmentsController.php
- [x] controllers/admin/AdminGeolocationController.php
- [x] controllers/admin/AdminPdfController.php
- [x] controllers/admin/AdminCmsCategoriesController.php
- [x] controllers/admin/AdminMarketingController.php
- [x] controllers/admin/AdminThemesController.php
- [x] controllers/admin/AdminInformationController.php
- [x] controllers/admin/AdminCategoriesController.php
- [x] controllers/admin/AdminTrackingController.php
- [x] controllers/admin/AdminImagesController.php
- [x] controllers/admin/AdminStoresController.php
- [x] controllers/admin/AdminWebserviceController.php
- [x] controllers/admin/AdminOrdersController.php
- [x] controllers/admin/AdminLoginController.php
- [x] controllers/admin/AdminSupplyOrdersController.php
- [x] controllers/admin/AdminOrderPreferencesController.php
- [x] controllers/admin/AdminImportController.php
- [x] controllers/admin/AdminWarehousesController.php
- [x] controllers/front/HistoryController.php
- [x] controllers/front/OrderReturnController.php
- [x] controllers/front/CategoryController.php
- [x] controllers/front/ChangeCurrencyController.php
- [x] controllers/front/ManufacturerController.php
- [x] controllers/front/NewProductsController.php
- [x] controllers/front/ParentOrderController.php
- [x] controllers/front/StoresController.php
- [x] controllers/front/AttachmentController.php
- [x] controllers/front/PricesDropController.php
- [x] controllers/front/PdfOrderSlipController.php
- [x] controllers/front/SearchController.php
- [x] controllers/front/OrderOpcController.php
- [x] controllers/front/PasswordController.php
- [x] controllers/front/AddressController.php
- [x] controllers/front/OrderController.php
- [x] controllers/front/PdfOrderReturnController.php
- [x] controllers/front/BestSalesController.php
- [x] controllers/front/PageNotFoundController.php
- [x] controllers/front/IndexController.php
- [x] controllers/front/AddressesController.php
- [x] controllers/front/DiscountController.php
- [x] controllers/front/GuestTrackingController.php
- [x] controllers/front/AuthController.php
- [x] controllers/front/OrderFollowController.php
- [x] controllers/front/SitemapController.php
- [x] controllers/front/GetFileController.php
- [x] controllers/front/OrderConfirmationController.php
- [x] controllers/front/IdentityController.php
- [x] controllers/front/OrderDetailController.php
- [x] controllers/front/CartController.php
- [x] controllers/front/OrderSlipController.php
- [x] controllers/front/StatisticsController.php
- [x] controllers/front/CompareController.php
- [x] controllers/front/CmsController.php
- [x] controllers/front/SupplierController.php
- [x] controllers/front/PdfInvoiceController.php
- [x] controllers/front/ContactController.php
- [x] controllers/front/MyAccountController.php
- [x] controllers/front/ProductController.php

**Comment by Traumflug** [comment]
Uhm, review for what? Proper formatting?

**Comment by firstred** [comment]
Database queries

**Comment by firstred** [comment]
I just pushed beta 1 this morning to my own production environment and quite a few were broken. I want them to be right this time.

**Comment by firstred** [comment]
These are the mistakes I see happen most:
- Backquote ` forgotten
- ``$sql->where(' AND `id_blabla` = ...');``, should be ``$sql->where('`id_blabla` = ...');``
- ``Db::getInstance()->delete('table', 'WHERE \`id_blabla\` = ...');`` => ``Db::getInstance()->delete('table', '`id_blabla` = ...);``

**Comment by Traumflug** [comment]
Thanks, that's helpful.

**Comment by yaniv14** [comment]
In classes/customer -> getLastConnections()
I don't see any from(table_name)
I believe we are missing: ->from('guest', 'g')

**Comment by firstred** [comment]
Gracias

**Comment by firstred** [comment]
Could you make pull requests, please? Might be better and more credits go to you! :)

**Comment by yaniv14** [comment]
ok.
I wasn't sure about PR for those issues because it looks like a private code review between the 4 of you.
