### ISSUE TITLE
Better e-mail validation

### ISSUE THREAD

**Issue by benzon** [thirtybees/thirtybees#287]
Hi,

Noticed the change to using swift mail lib to validate e-mails.

Would integration checkdnsrr(); make sence? check if there is a dns record for the domain entered in the e-mail.

This would help the user from entering there e-mail wrong, like hotmail.con etc.

**Comment by firstred** [comment]
Hi,

Thanks for your suggestion, but I am not so sure about the change.

I think that (potential) buyers are not going to like the extra delay. You want them to reach the checkout as quickly as possible, not wait for extra validation.

@Dh42 What do you think?

**Comment by alwayspaws** [comment]
Michael, I totally agree with you.

**Comment by Traumflug** [comment]
The trick would be to do this check without imposing delays for the user, right? Like with an Ajax request as soon as the user leaves this field (and currently types in the next field).

**Comment by benzon** [comment]
I think what Traumflug says would make the most sence, to avoid hitting the user with a delay.

In most cases checkdnsrr should be fast on a properly configured server, not using very slow nameservers.

**Comment by benzon** [comment]
Just did a test with 6 domains im looking up for a MX record i think it was about 60-100 ms in total.

We actually had to trustpilot cases, where costumers blamed us for them having entered a wrong e-mail, so not having any check can backfire to.

**Comment by alwayspaws** [comment]
Yes, Traumflug. 

Benzon, there must be a way to overcome this but as quickly as possible, so as not to dilute the UX.

**Comment by Dh42** [comment]
My thought would be to do it like @Traumflug  mentioned by using ajax on the field. At the same time we could have a setting for it on the email page to for people that do not care to use it. I know @inetbiz has been trying to get validation like this in the core for a minute.

**Comment by benzon** [comment]
Maybe offer the option to be able to select if it should be via ajax, or using the php function.

I think in most cases, with a propper server setup, the checkdnsrr uses less then 100ms to get it's result, in the end it depend on what nameserver the server is using ofc.

**Comment by firstred** [comment]
@benzon Thank you very much for sharing your case and benchmarking it as well. This really helps a lot.

Seen the fact that it takes 60-100ms we might not even need to use ajax validation.

With @dh42 I have tested Algolia in PHP code (wait for Algolia to return results then render the page). The 2-4ms it has isn't even noticable. 100ms is also hard to notice. I'm sure of that. This has def. convinced me to integrate it.

Now the question remains, (@dh42 @Traumflug) could this be done on a patch version? We have added support for Google Maps API keys in `1.0.2`...

**Comment by benzon** [comment]
Did a small test with the bulkemailchecker, thats a more aggressive way of checking not free tho, but that takes about 1 sec, calling there api and getting a reply from that.

But again the fact is if the nameservers the server uses are slow and bad, then the function will reply slower, but again most serious hosts and shop hosts more or less uses google's dns servers today since they are blazing fast.

**Comment by Dh42** [comment]
I personally would say wait to 1.0.3 for it. It would give us more time to test for bugs in it.

**Comment by firstred** [comment]
Will do

**Comment by firstred** [comment]
Tried this, but impossible to implement this without breaking backwards compatibility. Therefore closing this one, sorry.
