### ISSUE TITLE
Image optimization

### ISSUE THREAD

**Issue by benzon** [thirtybees/thirtybees#290]
Most of us knows how important image optimization is when it comes to the end.

Today there is not a good way of optimizing images, i know that the integration of ImgMagic dos abit vs GD.

But i am thinking why not build in something like https://wordpress.org/plugins/ewww-image-optimizer/ that can be enabled on servers that are able to optimize images via thos small programs.

And then have an alternative integration to something like kraken.io for thos hu cant use the small programs, like EWWW dos for wordpress.

That way it would be possible to optimize the images, and that would in the end give even better loading speeds, and better work flow, that you dont have to do the optimization manual before uploading, and even making sure generated thumbs are optimized to.

**Comment by Dh42** [comment]
I think most of that might be in the land of paid / 3rd party modules. One thing I would like to see in the 1.1.x version is gd webp support. But it would have to be an option.

**Comment by benzon** [comment]
Hmm I think something like EWWW could be integrated feature for servers supporting it.

The only reason for this is to help shop owners optimize, but I agree that a module might be the way to go, the only option i have found is something like kraken.io, not something like EWWW, even though most servers today allows executing binary’s, because a lot of them run in cloudlinux environments.

The only reason I am suggesting it, is I see on a daily basis that image optimization is something most don’t do anything about, and in the end, if they optimized their images, the performance of the site would be increased, even google rankings would increase.

@Dh42 When it comes to webp, I agree this would be a nice feature, but then there should without doubt be some check that validates if the user, do use a browser supporting webp.

**Comment by Dh42** [comment]
We would need a polyfill for detecting browsers, there are a few pretty good ones that work well out there. I think that is going to be the best way.

**Comment by benzon** [comment]
Last time i just played with something that would deliver webp if the browser would handle it.

Think I just used something like

`if ((isset($_SERVER['HTTP_ACCEPT']) === true) && (strstr($_SERVER['HTTP_ACCEPT'], 'image/webp') !== false))`

Not optimal but it works.

**Comment by Dh42** [comment]
I was thinking about using something like this, http://webpjs.appspot.com/  we need it to be browser based, or it will destroy the page cache.

**Comment by benzon** [comment]
Agree, thats why my way is not an option for something like Thirty Bees,

**Comment by benzon** [comment]
@Dh42 one thing i got to say i think Thirty Bees is going to be a smashing succes, the reason is simple, you listen to the users, insted of just doing it all after your own head, and ye i might keep comming with ideas, since there is a lot of areas where i think minor changes would make a huge impact.

Oh one thing more i thought of with the image optimization, maybe a feature that asks if the user want to convert png's to jpg's this yet another common issue i found alot of places, forgetting to convert from png to jpeg, on product images, that got a white background, only a very few images should use transparent like logo, and stuff like that, the rest should be jpeg, that alone would save a ton, and optimize the speed alot.

**Comment by Dh42** [comment]
I hope we are. We are a band of developers, but we have a lot of merchant contact. In the contact with my clients over the years I have realized I don't know half their struggles. That is why we have an active feature request section, and we have been spending more time talking to merchants. We firmly believe if we give merchants the best tools, the tools they ask for, they will be successful. While at the same time delivering stable software as well. 

For the png to jpeg, that is already the default behavior on most images in the shop. I do however think we need to revamp the image uploading area to create more of a media center type area like wordpress has. Where you can easily use product images in blog posts or descriptions. Some of these changes could very well be in that new area.

**Comment by benzon** [comment]
That would make sence with a media manager with out doubt.

Ill keep adding some ideas added a couple to how internals work like reference id's and better combination handling, since it's a mess to figure out sometimes what products got a combination.

Do you guys prefere me adding it here on the forum or where?

Im comming from wordpress development, and raw php programming, right now im trying to learn some more about prestashop and how to develope against it, so right now im not able to do a hole lot of coding for the project, but ideas i can do.

**Comment by Dh42** [comment]
Have you see the feature request section on our site? We monitor it and when we start specing out 1.1.x we are going to organize the requests into version that the features will be in. https://thirtybees.com/feature-request/

**Comment by benzon** [comment]
Ahh okay perfect ill try to use that insted of filling up Github with idea's even tho im not a big fan of that forum gets to messy for me.

**Comment by benzon** [comment]
https://thirtybees.com/suggestions/image-optimization/
