### ISSUE TITLE
Track & Trace Variable for e-mail tremplate

### ISSUE THREAD

**Issue by benzon** [thirtybees/thirtybees#297]
Think an important change that needs to happen quite fast, is actually adding Track and Trace variable for the e-mail templates where it could be used and would make sence, so we can actually send out the track and trace link, and shipping number when the costumer gets the mail when you changes the status to Shipped.

Important feature in my view.

**Comment by firstred** [comment]
Don't forget country iso, postcode, numerical part of mixed postcodes etc.
We will likely need to patch in a lot of stuff. I think it's okay starting with 1.0.2 despite it being a patch version, PS' implementation just sucked.

**Comment by benzon** [comment]
If i knew how to do the class overwrights i would fix it that way currently, but ye im not that in to doing modules yet, since prestashop coding is fairly new.

But i agree, there is some things that needs to be changed, the reason i just thaught of it is our carrier again again got issues sending out track and trace to costumers, and we just want to make sure they get it.

**Comment by benzon** [comment]
You just gotta "love" gls HAHA :D

**Comment by firstred** [comment]
Doesn't gls just use one tracking number?

Are you using the `in_transit` mail?

**Comment by benzon** [comment]
Quick question i know this is dumb, the translations for the Status of the order, Like Payment error, Backorder and so on where are they located? i cant find then currently in the translation part.

**Comment by firstred** [comment]
Orders > Statuses

**Comment by benzon** [comment]
Perfect, but still would make sence to use the shipped template to for adding the track and trace?

Since in_transit and shipped more or less do the same thing in the end in my point of view.

**Comment by firstred** [comment]
Not if you have multiple shipments per order.

**Comment by firstred** [comment]
Postponed till 1.0.3 though. 1.0.2 is almost ready to be shipped.

**Comment by benzon** [comment]
How and when is the in_transit mail send out? We use a module for handling shipping GLS module for Prestashop, and im not sure when the in_transit is triggered and how.

**Comment by benzon** [comment]
Tryed digging around cant find any good documentation on when in_transit email is triggered.

**Comment by firstred** [comment]
When a tracking number is entered or when a module adds the shipping number and triggers an email. If the email doesn't get triggerd then the module needs to be changed.

**Comment by getdatakick** [comment]
This was resolved by commit d69889e5bc4f2b9ff821bd555b7ebee0798e95af
