### ISSUE TITLE
Installer does not detect beta versions

### ISSUE THREAD

**Issue by firstred** [thirtybees/thirtybees#298]
![installerdoesnotdetetbeta](https://user-images.githubusercontent.com/6775736/27966548-e9797cd0-633f-11e7-8157-c4d8e296a735.png)

**Comment by firstred** [comment]
Closing, because
![https://i.ytimg.com/vi/BLUkgRAy_Vo/maxresdefault.jpg](https://i.ytimg.com/vi/BLUkgRAy_Vo/maxresdefault.jpg)

**Comment by alwayspaws** [comment]
LOL 😂
