### ISSUE TITLE
Issues with address validation

### ISSUE THREAD

**Issue by benzon** [thirtybees/thirtybees#300]
Just noticed the address validation could actually be improved.

Personally i would make a check if the address field includes adleest one numeric value, since the house number should be included in the address field, either that or separate address and house number field, to make sure you get a better validation.

**Comment by Dh42** [comment]
There actually are still addresses in some countries that do not use numbers in the first address field. Namely a lot of them are in Africa and Asia.

**Comment by benzon** [comment]
Just wondering if it could be made an option if the address field should include a number or not.

That way the shop decide them self how they want that pice of validation to be handled.

**Comment by Dh42** [comment]
You can put it in as a feature request. The one thing we struggle with is adding so many options that the interface becomes cumbersome to users. We could have a ton of cool validation options, but then it would add a ton of new fields in the back office and options. People might think the software is too complicated then. I am not sure of any other platform doing this or having this option either, so it might not be as widely used as you think.
