### ISSUE TITLE
docs/readme_xx.txt all points to prestashop

### ISSUE THREAD

**Issue by inetbiz** [thirtybees/thirtybees#303]
All the readme_xx.txt files are referencing prestashop

**Comment by Dh42** [comment]
Can you link me to what you are talking about?

**Comment by inetbiz** [comment]
@Dh42 https://github.com/thirtybees/thirtybees/blob/1.0.x/docs/readme_en.txt as an example

**Comment by Dh42** [comment]
Do you have time to rewrite it and make a pull request?

**Comment by inetbiz** [comment]
I'll whittle them down. There are several.

**Comment by firstred** [comment]
Merged. Thank you.
