### ISSUE TITLE
Remove P3P Support

### ISSUE THREAD

**Issue by inetbiz** [thirtybees/thirtybees#304]
Read:
- http://marketingland.com/google-impractical-to-comply-with-ie-privacy-6543
- https://www.w3.org/TR/P3P11/ **Work Suspended in 2006**

**Comment by inetbiz** [comment]
This is an interesting document https://www.w3.org/2011/tracking-protection/drafts/tracking-dnt.html

**Comment by Dh42** [comment]
This was removed here, https://github.com/thirtybees/thirtybees/commit/dfe6ab642956712e47e66dc5eb578415ee47922d
