### ISSUE TITLE
Feature: DNT Header Request / Response

### ISSUE THREAD

**Issue by inetbiz** [thirtybees/thirtybees#305]
https://www.w3.org/2011/tracking-protection/drafts/tracking-dnt.html

**Comment by inetbiz** [comment]
This issue is related to issue #304 in controlling user privacy and sending back response json in how a site is using data about the person/browser and how this may affect other modules such as google analytics tracking and anonymizing.

**Comment by Traumflug** [comment]
Disrespecting user privacy wishes is always an issue which easily fires back on reputation. Even if many others do it already or these wishes are pointless.

- What are the benefits in less code to maintain, faster/better shop customer experience?
- Is core shop software affected, or is it a matter of the various tracking modules?

**Comment by Dh42** [comment]
Wouldn't this obliterate the whole cart function?

**Comment by inetbiz** [comment]
@Traumflug all I saw was P3P was abandoned back in 2006 when everyone else rejected IE's privacy framework policy. Then, I saw this. The DNT header does signal on but there is no header response as to how they are tracked or not tracked.

**Comment by Dh42** [comment]
This is something I think needs to be left alone. We have either two options I can see

- Act like we respect the request, but in reality ignore it
- Rewrite the whole cart in a way that does not use cookies. 

I can imagine a blog might respond to these type of headers, but it will be virtually impossible for an ecommerce site to.

**Comment by inetbiz** [comment]
@Dh42 How about remove p3p header injection and move the issue to a future milestone?

**Comment by Dh42** [comment]
We can remove the header, as for a future milestone, that is highly unlikely.

**Comment by inetbiz** [comment]
@Dh42 Never know. Someone in the future might tackle the issue and commit a PR or two.

**Comment by Dh42** [comment]
I think you are out of your depth. There is no way to track cart contents and order information using DNT. If you do not save information on a user how do you ship an order?

**Comment by Dh42** [comment]
I removed the p3p header, https://github.com/thirtybees/thirtybees/commit/dfe6ab642956712e47e66dc5eb578415ee47922d
