### ISSUE TITLE
Admin help icon points to PS

### ISSUE THREAD

**Issue by yaniv14** [thirtybees/thirtybees#308]
Not really a bug.
But the help icon link still points to PS.
The link is not linking to PS on click because of help.js function.

[screenshot](http://prntscr.com/fvny42)

the link is located in classes/controllers/AdminController.php -> initPageHeaderToolbar()

**Comment by firstred** [comment]
Thanks!

**Comment by firstred** [comment]
https://github.com/thirtybees/thirtybees/commit/b32da25b745ed02155be9ba2a88e6fba652790ff
