### ISSUE TITLE
Mail Alerts Module says "Powered by PrestaShop"

### ISSUE THREAD

**Issue by NorwegianRat** [thirtybees/thirtybees#317]

**Comment by inetbiz** [comment]
I don't see that module added in thirty bees 1.0.x @firstred https://github.com/PrestaShop/mailalerts

**Comment by firstred** [comment]
k

**Comment by NorwegianRat** [comment]
It was on the update list, though. Now I got version 4.0.4 by TB and on my 1.0.1 mirror site I got version 3.6.0 by PS

**Comment by inetbiz** [comment]
@NorwegianRat it is not linked as a submodule for thirty bees I mean. Check the repo in modules. Not there.

**Comment by alwayspaws** [comment]
Excuse me but I just got an email alert yesterday and the bottom says:

Always Paws powered by PrestaShop™  and it's hotlinked.

**Comment by alwayspaws** [comment]
@firstred  I have the latest thirty bees installed as you know.

**Comment by inetbiz** [comment]
https://github.com/thirtybees/thirtybees/tree/1.0.x/modules/ is not linked. It's not linked in either release. No code to work on.

**Comment by alwayspaws** [comment]
What is this then?

Date: July 20, 2017 at 7:01:08 PM EDT
To: Customer service <info@alwayspaws.com>
Subject: **[Always Paws] Message from contact form [no_sync]** - and what is this?

MESSAGE FROM A ALWAYS PAWS CUSTOMER 
Customer e-mail address: ......
body of message here...

Below message:
Always Paws powered by PrestaShop™ - the second half goes here:  https://www.prestashop.com/en

**Comment by Traumflug** [comment]
> It's not linked in either release.

True.

> No code to work on.

Uhm. Maybe it isn't the ideal bug tracker to discuss this issue, still there is code and people do have an issue.

The solution isn't that complicated: go trough all the files in `mails/` inside the module folder using a plain text editor and, well, replace "PrestaShop" with "thirty bees". That should be enough. Nice simple task for beginners :-)

**Comment by NorwegianRat** [comment]
It's an easy fix for sure, @Traumflug . Just a little annoying doing it over and over again if the "Mail alert" module shows up in the "Modules to update" list every now and then (even though it's not in the repo=)

**Comment by alwayspaws** [comment]
@everybody :) 

@Traumflug yes it's easy but please (pretty please) see what I copied below.

@NorwegianRat Totally agree.

I'm going to repeat what I got directly from our forum located here:

https://forum.thirtybees.com/topic/477/email-template-translations-core-or-theme/9

@lesley said above: "Make the changes to the theme, the core ones might be updated soon in the future. I am planning at some point in the next month or two to try to start adding rich data actions that will work with Google. So in a core update in the next couple months they might get overwritten."

So I want to know where it’s done in the Transformer theme so it won’t be overwritten again and again.

**Comment by alwayspaws** [comment]
@inetbiz I'm using TB 1.0.2

This module is listed:
AdministrationMail alerts v4.0.4 - by thirty beesSends e-mail notifications to customers and merchants.

So how can you not find it?

![thirty bees 1-0-2 mail alerts module](https://user-images.githubusercontent.com/26662422/28491226-3b944e92-6ebb-11e7-9776-7ca0268cecbf.png)

**Comment by inetbiz** [comment]
I found the repo at https://github.com/thirtybees/mailalerts It just wasn't linked to the main repository's git sub modules that sigh link to /modules! hehe This pull request changes that.

**Comment by alwayspaws** [comment]
Really glad you found it but it must have been hard to dig through all the changes and updates you and the team have been working on. Kudos to you! :)

**Comment by inetbiz** [comment]
@alwayspaws Here's how I done it. Navigate to https://github.com/thirtybees the github project main URL. There's a mini search bar. Searched for mailalerts. Found it. Go back to https://github.com/thirtybees/thirtybees and modify https://github.com/thirtybees/thirtybees/blob/1.0.x/.gitmodules and include the mailalerts module.

Then, switched over to https://github.com/thirtybees/mailalerts and made changes. Made pull request in that project. When all pull requests are merged, it'll be back in the main https://github.com/thirtybees/thirtybees /modules folder. It was missing before.

**Comment by alwayspaws** [comment]
Wow! @inetbiz  - I will definitely leave this up to you and the other masters of our thirty bees universe! :)

**Comment by Traumflug** [comment]
> Go back to https://github.com/thirtybees/thirtybees and modify https://github.com/thirtybees/thirtybees/blob/1.0.x/.gitmodules and include the mailalerts module.

The right way is to do a `git submodule add ...`, which gives a similar, but actually working change.

Now with the module repository found, the obvious solution to this issue is to make a pull request, with the text edits mentioned above, against this module repository.

**Comment by alwayspaws** [comment]
@Traumflug It was closed. I don't know if @inetbiz will open it again, but thanks.

**Comment by inetbiz** [comment]
@alwayspaws I don't have the power to close it. It was closed by @firstred . I made code changes to https://github.com/thirtybees/mailalerts/pulls and the request remains open.

**Comment by alwayspaws** [comment]
Thanks, Denver. I saw it.
