### ISSUE TITLE
Dashboard order state is missing

### ISSUE THREAD

**Issue by roband7** [thirtybees/thirtybees#319]
Using TB 1.0.2, bugreport started based on the discussion in
https://forum.thirtybees.com/topic/574/order-status-disappeared-when-upgraded-to-1-0-2

It's a regression in 1.0.2 due to the SQL rewrites. Bug is in classes/order/Order.php in function getOrdersWithInformations()

It forgets an AS `state_name` fieldname remapping of the subselect. Just compare with older code and it's clear what happened.

**Comment by firstred** [comment]
Thanks for watching so closely! I sometimes lose track of all the current issues.
