### ISSUE TITLE
Per customer group listing is not correct

### ISSUE THREAD

**Issue by Zengraph** [thirtybees/thirtybees#323]
Edit or change group for customer is working, but listing is corrupted and don't show proper group assignment for each customer.

**Comment by yaniv14** [comment]
Are you sure about it?
Because customer can be assigned to multiple groups

**Comment by Zengraph** [comment]
On the database you can see all the groups assigned to each customers (it can be multiple yes !) but on front office it only shows group id 3, I imported my customers and groups from csv file without error message.

**Comment by Zengraph** [comment]
OK.. problem solved : on back-office  advanced parameters -> performance  : GROUP USERS should be ON.
mine was off and I worked with groups since begining.. never had any warning message, that should be added in function getGroups(). I had to activate it in Sql, the button was not activable in BO.
