### ISSUE TITLE
Localization->Translations->Copy stopped working in 1.0.2

### ISSUE THREAD

**Issue by roband7** [thirtybees/thirtybees#328]
This is a regression in 1.0.2, see discussion on forum:
https://forum.thirtybees.com/topic/630/bug-in-copying-translations-in-the-backend-between-themes

Bug is in classes/Language.php function copyLanguageData

It gets table names of the form tb_attachment_lang from "SHOW TABLES FROM ...", then goes on passing these table names into DbQuery() which adds in another DB_PREFIX.

So we end up with queries like:
select * from tb_tb_attachment_lang

**Comment by firstred** [comment]
I think it's time for auto prefixing. How about https://github.com/thirtybees/thirtybees/commit/f5951147f19b8cb64a1ad7c7f3a9cc8119a90dec?
