### ISSUE TITLE
Belarus currency sign BYR -> BYN

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#331]
Found here: https://www.prestashop.com/forums/topic/504343-new-default-theme-for-prestashop-17/page-3#entry2592789

_On Jule 01, 2016 in Belarus was redenomination and currency changed from BYR to BYN, but you have still BYR._

**Comment by Dh42** [comment]
Pretty funny, I just got that reply and was looking at it, then I saw the commit before I could do anything.

**Comment by Traumflug** [comment]
Apparently we're subscribed to the same thread :-)

Regarding 30bz I fear we have no language file for Belarus and without language file one can't add a currency. At least I'm not aware of other ways to install a currency.

**Comment by Dh42** [comment]
They can be added manually from the localization currencies tab. That is where they can be configured. The localization packs just do it automatically.

**Comment by Traumflug** [comment]
So, no package or file which could have a bug. Sorry for the noise :-}
