### ISSUE TITLE
unable to install featured products on the homepage

### ISSUE THREAD

**Issue by yaniv14** [thirtybees/thirtybees#332]
Unable to install from feed.

[image](http://prntscr.com/g4nfoy)

**Comment by firstred** [comment]
Feed changed. Thanks!

**Comment by yaniv14** [comment]
I still can't get it to install from feed.
Try to delete the module from the modules list and reinstall it from the feed

**Comment by NemoPS** [comment]
the exact error 
Client error: `GET https://github.com/thirtybees/homefeatured/releases/download/1.0.0/homefeatured-v1.0.0.zip` resulted in a `404 Not Found` response:

**Comment by NemoPS** [comment]
Feed updated. If it's still broken for you, try to erase modules\tbupdater\cache\modules.json, it should fetch the new one (2.0.0)

**Comment by firstred** [comment]
Thanks @NemoPS 
Closing this one.
