### ISSUE TITLE
Issue with 404 when using nbgItemPage, after switching template.

### ISSUE THREAD

**Issue by benzon** [thirtybees/thirtybees#333]
Hi,

Just switched template, that whent fine but something broke, 

```
<form action="https://stage.qubeit.dk/sexlegetoej-til-maend" method="get" class="nbrItemPage">
   <div class="clearfix selector1">
      <label>Show :</label>
      <input type="hidden" name="q" value="/sexlegetoej-til-maend">
      <div class="selector" id="uniform-nb_item" style="width: 94px;">
         <span style="width: 94px; user-select: none;">110</span>
         <select name="n" id="nb_item" class="form-control">
            <option value="55" selected="selected">55</option>
            <option value="110">110</option>
            <option value="275">275</option>
         </select>
      </div>
   </div>
</form>
```

This is from the staging site where im testing out the changes.

**Comment by benzon** [comment]
```
<form action="https://stage.qubeit.dk/sexlegetoej-til-maend" method="get" class="nbrItemPage">
			<div class="clearfix selector1">
				<label>Show :</label>
												
				
				
																						<input type="hidden" name="q" value="/sexlegetoej-til-maend">
																														<div class="selector" id="uniform-nb_item" style="width: 94px;"><span style="width: 94px; user-select: none;">110</span><select name="n" id="nb_item" class="form-control">
																							<option value="55" selected="selected">55</option>
																														<option value="110">110</option>
																														<option value="275">275</option>
																					</select></div>
				
			</div>
		</form>
```

**Comment by benzon** [comment]
This is from the clean install using demo products.

```
<form action="https://tb.qubeit.dk/coffee-and-tea" method="get" class="nbrItemPage">
   <div class="clearfix selector1">
      <label>Show :</label>
      <input type="hidden" name="q" value="/coffee-and-tea">
      <input type="hidden" name="id_category" value="3">
      <div class="selector" id="uniform-nb_item" style="width: 87px;">
         <span style="width: 87px; user-select: none;">12</span>
         <select name="n" id="nb_item" class="form-control">
            <option value="12" selected="selected">12</option>
            <option value="24">24</option>
         </select>
      </div>
   </div>
</form>
```

**Comment by benzon** [comment]
Not sure why it's trowing a 404 error since it worked with the other theme with out issues, but with the new theme it's broken, but works with a clean install, this is an issue in Thirtybees and Prestashop testet both things out.

**Comment by Dh42** [comment]
Is this working with a clean install of thirty bees, but not working when you switch themes?

**Comment by benzon** [comment]
Yes it's working with a 100% clean install of Thirty Bees, but on an version that is convertet from Presta to Thirty Bees it got this behaviour.

**Comment by Dh42** [comment]
Check the URL rewrites to make sure they are the same.

**Comment by benzon** [comment]
![screenshot-tb qubeit dk-2017-08-07-21-28-48](https://user-images.githubusercontent.com/3528000/29042536-8dfc8dda-7bb7-11e7-97aa-88665e706848.png)
![screenshot-stage qubeit dk-2017-08-07-21-28-24](https://user-images.githubusercontent.com/3528000/29042538-8ecc8b16-7bb7-11e7-9a0a-bed97bb72732.png)


They are the same.

**Comment by benzon** [comment]
Almost, since there are some minor stuff on the staging thats different to the Clean install

**Comment by benzon** [comment]
Just replicated the rewrights 100% from the clean install did nothing.

**Comment by benzon** [comment]
So not sure what the heck is causing the issue ad all.

**Comment by Dh42** [comment]
Can you try to disable overrides on the performance page and see if the issue still happens.

**Comment by benzon** [comment]
Okay that works, so what we are talking about is one of the modules then is causing this odd behaviour ?

**Comment by Dh42** [comment]
It is, likely it is an SEO module or a url rewriting module.

**Comment by benzon** [comment]
Found the issue prettyurls, funny this is an issue in normal prestashop to, might be the them dev that has to do a fix for his theme.

But think we more or less decided to migrate our live site to Thirtybees when we do the theme and design update of the site, since the support here is top notch compared to presta and we love the idea around crowdfunding.

**Comment by Dh42** [comment]
This is a main reason we decided to put pretty urls in the core. Its something that cannot be done correctly with a module. Glad we got it worked out.
