### ISSUE TITLE
Multiple back-end language issue with url

### ISSUE THREAD

**Issue by benzon** [thirtybees/thirtybees#334]
Found a minor issue, in normal prestashop i can have english installed but disabled and it wont ad the prefix to the url with /da or /en

But if i do this in thirtybees it will ad the prefix no matter what, is there a work around, or is this a flaw/bug?

**Comment by Traumflug** [comment]
Sounds much like this, there's a solution, too:

https://forum.thirtybees.com/topic/608/iso-code-added-to-url-after-migration/15
