### ISSUE TITLE
Product Attributes delete - bug

### ISSUE THREAD

**Issue by sergbbb** [thirtybees/thirtybees#335]
To fix it :

classes/stock/StockAvailable.php:647

            'id_product = '.(int) $idProduct.($idProductAttribute ? ' AND `id_product_attribute` = '.(int) $idProductAttribute : '').static::addSqlShopRestriction(null, $shop)

classes/AttributeGroup.php:263

                    || !Db::getInstance()->delete('attribute', '`id_attribute_group` = '.(int) $this->id)

**Comment by Traumflug** [comment]
Ah, here's the hero! Nice. Well, then here a thank you to @sergbbb for these two catches. Fixes are now on branch *1.0.x*, commit crafted by @yaniv14 (see #336).
