### ISSUE TITLE
I've updated thirty bees from 1.0.1 to 1.0.2

### ISSUE THREAD

**Issue by laurentiusar** [thirtybees/thirtybees#338]
Hi all,

First I’ve made the migration from Prestashop 1.6 to thirty bees 1.0.1. And every thing was ok, but when I’ve made the update I didn’t have errors. When I try to generate pdf invoice from Order -> Invoices it doesn’t work. I have the following error:
Argument 1 passed to HTMLTemplateInvoiceCore::__construct() must be an instance of OrderInvoice, instance of OrderInvoiceCore given, called in /var/www/html/public_html/classes/pdf/PDF.php on line 151
at line 54 in file classes/pdf/HTMLTemplateInvoice.php

**Comment by Traumflug** [comment]
There were 724 (counted) improvements between 1.0.1 and 1.0.2, so you should at least upgrade to 1.0.2 before investigating bugs.

**Comment by laurentiusar** [comment]
I have upgraded to 1.0.2, and I've encountered that error.

**Comment by firstred** [comment]
Able to reproduce this one. Noted for 1.0.3

**Comment by firstred** [comment]
This should fix it: https://github.com/thirtybees/thirtybees/commit/381b3f3ad84eddc284ffe15746b30fb6de8b5829
