### ISSUE TITLE
 Tax Issues when generating a Credit Slip should already be fixed

### ISSUE THREAD

**Issue by laurentiusar** [thirtybees/thirtybees#349]
Complete an order with shipping costs -> Cancel/Refund the order choosing refund/refund of shipping costs -> generated credit/order slip won’t show add the Tax to the Total Amount -> Order Overview in Backend won’t show the Total amount - shows only the shipping costs.
![image](https://user-images.githubusercontent.com/30897501/29824927-76d81310-8cdb-11e7-965b-e9442c8aa363.png)
The TOTAL must be 17.57 € = 14.64 + 2.93

**Comment by laurentiusar** [comment]
If you need more detailes just let me know. 
Thank you!

**Comment by firstred** [comment]
Hi @laurentiusar 
Thanks for opening an issue.

I bet it sucks to find out that the credit slips are still wrong. I will try to fix this for you as soon as possible.
I will probably need a few details first:
- Which version of thirty bees processed the refund and thus generated the credit slip?
- Did you use the default credit slip template that comes with 1.0.3 or is this template migrated from PrestaShop?

**Comment by laurentiusar** [comment]
Neither one isn't working, I've tried two methods:
 - First is in Orders select button Article. Check refund set to numbers of articles, check Return remuneration and Shipping costs include (orders with shipping tax )
- Second, it's in Orders in find Refunds and click the button Full refund.

I've made the migration from PrestaShop 1.6.1.11 to Thiry bees 1.0.3, so I think that is a migrated template.

If you need more information just let me know.

Thank you!

**Comment by firstred** [comment]
And which version generated the credit slip at the time?

**Comment by laurentiusar** [comment]
The theme is Theme973 version 1.0

**Comment by laurentiusar** [comment]
And which version generated the credit slip at the time? 

Where I can find that?

**Comment by firstred** [comment]
Can you remember which version of thirty bees did the refund?

**Comment by laurentiusar** [comment]
In the last version 1.0.3

**Comment by firstred** [comment]
Okay. Thanks!

**Comment by firstred** [comment]
Could you share with me the product list (incl. prices) on the original invoice?

**Comment by laurentiusar** [comment]
[2017-004200.pdf](https://github.com/thirtybees/thirtybees/files/1266669/2017-004200.pdf)
[order-slip-000150 (2).pdf](https://github.com/thirtybees/thirtybees/files/1266671/order-slip-000150.2.pdf)
[product_2017-08-31_120311.zip](https://github.com/thirtybees/thirtybees/files/1266675/product_2017-08-31_120311.zip)

Tell me if these are ok

**Comment by laurentiusar** [comment]
Hi,
Any news regarding this threat?
Thank you!

**Comment by laurentiusar** [comment]
I solved the issue of the credit slip, I've copied the default template of the credit slip in the folder theme pdf because there were commented some lines.

Best regards.
Laurentiu

**Comment by firstred** [comment]
Yeah same here, sorry for the late response. I double-checked and checked, but couldn't reproduce the issue.

I should have advised the original templates earlier, sorry about that. I'm glad it's okay now.
