### ISSUE TITLE
Minify HTML

### ISSUE THREAD

**Issue by benzon** [thirtybees/thirtybees#352]
Hi,

Noticed the Minify HTML option is removed in Thirtybees whats the reason behind that?

**Comment by firstred** [comment]
You can find it on the forum: https://forum.thirtybees.com/topic/518/minify-html-option

**Comment by Dh42** [comment]
It slows down a site more than it helps a site.

**Comment by benzon** [comment]
ahh okay super :) good to know.

Just a side question is it possible to contact one of you to thrue mail, since i would love to get more info on the full pagecaching, might even hire one of you to set it up correct, since im not to sure what i can enable in full page caching and what not.

**Comment by Traumflug** [comment]
> is it possible to contact one of you to thrue mail, since ...

In addition to Dh42 and firstred, one can find many other people with experience in the forum, so asking there might be an even more fruitful option.
