### ISSUE TITLE
IMAP import Base64 issue

### ISSUE THREAD

**Issue by benzon** [thirtybees/thirtybees#353]
@firstred i am not 100% sure if your big email import fix is covering this part.

This is taken from a Prestashop running shop, but we have had some issues with the IMAP import adding Base64 encoded messages to the support area, and failing to decode them.

Just want to hear if the big email import is covering this.

**Comment by firstred** [comment]
No, it is not.

We are likely going in a different direction in the future. Currently we are (internally) testing a Mandrill inbound address for processing new mails. Seems to work much better than IMAP. Once that works we will release it here: https://github.com/thirtybees/mandrill
and try to provide the same package for the other transactional email services.

**Comment by inetbiz** [comment]
Isn't mandrill a paid service? http://www.mandrill.com/pricing/

**Comment by benzon** [comment]
That's my thought to, and it's going to be messy if you run your own mail server to, having to use something like mandrill for reading incomming mails.

There must be some sort of lib out there that can actually read IMAP the right way.

**Comment by benzon** [comment]
I think one thing that would up the imap import abit is adding encoding check, and have function that out from that decodes it the right way.

```
imap_7bit();
imap_8bit();
imap_binary();
imap_base64();
quoted_printable();
```

**Comment by firstred** [comment]
I'm still not sure if we should make any changes. An email should not be base64 encoded unless it's for attachments AFAIK. Can you give us an example?

**Comment by Traumflug** [comment]
@benzon, looking at the comments here it's a bit unclear what the actual issue is or how to reproduce it. Can you provide a set of steps to reproduce, or some demo data to recreate the issue? I'm keen on finding out whether the issue still exists.

**Comment by Traumflug** [comment]
Hmm. Apparently no interest in fixing this and as there's nothing to reproduce here, closing this.
