### ISSUE TITLE
Wrong query for getOrderDetailTaxes() in Order.php

### ISSUE THREAD

**Issue by bart-lunika** [thirtybees/thirtybees#354]
Since version 1.0.3 my orders are not being sent to my accounting software. I first reported the issue there but it seems there is an error in the getOrderDetailTaxes() query in Order.php

The FROM statement is missing, which is causing the query to fail.

**Comment by bart-lunika** [comment]
I added:
`->from('orders', 'o') to fix the issue:`

So the class now looks like:
`    public function getOrderDetailTaxes()
    {
        return Db::getInstance(_PS_USE_SQL_SLAVE_)->executeS(
            (new DbQuery())
                ->select('od.`id_tax_rules_group`, od.`product_quantity`, odt.*, t.*')
                ->from('orders', 'o')
                ->innerJoin('order_detail', 'od', 'od.`id_order` = o.`id_order`')
                ->innerJoin('order_detail_tax', 'odt', 'odt.`id_order_detail` = od.`id_order_detail`')
                ->innerJoin('tax', 't', 't.`id_tax` = odt.`id_tax`')
                ->where('o.`id_order` = '.(int) $this->id)
        );
    }`

I don't have git installed, so maybe you can fix and merge it into future updates of TB

**Comment by Traumflug** [comment]
Nice catch, thank you! Looking at the last change to this section of code https://github.com/thirtybees/thirtybees/commit/1b68e3efec6c46e7087f2372c300f18db3b32886#diff-ae7d4e8c2d926ede8b1a0ac509510fdaR2885, this FROM got actually lost there.

Will make a commit in a minute.

**Comment by Traumflug** [comment]
I hope this solves it. If not, please don't hesitate to re-open this issue.

**Comment by bart-lunika** [comment]
It does, my invoices are being sent again to my accounting software. So this fixed my issue. Thanks!
