### ISSUE TITLE
Hard coded inactivity timeout

### ISSUE THREAD

**Issue by benzon** [thirtybees/thirtybees#355]
Some of my coworkers got issues with having to re-login after 10-15 min, and i did some searches to figure out what was wrong.

There where quite abit there that had issues.

Some one then mentioned this part of the code, and changing the +900 would be a fix, so the inactivity part is hardcoded and dos not respect the settings.

classes/controller/AdminController.php

if ($this->context->cookie->last_activity + 900 < time()) {

**Comment by NemoPS** [comment]
Fixed
https://github.com/thirtybees/thirtybees/commit/0c5ea7cfbbf125076231c313d3c39d93bd9d4f33

**Comment by Traumflug** [comment]
Not a fan of this "fix". It adds noise to Backoffice for no reason and duplicates Backoffice -> Administration -> Preferences -> Lifetime of back office cookies. thirty bees shall to be easy to use, duplicate functionality is counterproductive to this goal.

**Comment by Traumflug** [comment]
The issue brought up here was already solved with f73c59ac14aa5997e0a811e0b44c609a5372f3c4, it was also reported here: https://github.com/thirtybees/thirtybees/pull/399

**Comment by Traumflug** [comment]
Actually, this change removes the purpose of the "Stay logged in" checkbox on the login dialog, because behavior is now the same with or without the box checked, just the mechanisms used are different.

**Comment by NemoPS** [comment]
So why was it set as milestone for 1.0.4, and the commit was not in the latest build?
