### ISSUE TITLE
Translations Update only for Backoffice

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/thirtybees#358]
Updating translations is quite a pain. Imagine you have made some changes in Mails, FrontOffice and so on. Many merchants do it. When you upgrade your translations, you will lose all your changes. 

It would be great, to have an option like "Update only Backoffice translations". That way merchants will be up to date in Backoffice, but customers won't see any "wrong" texts.

**Comment by firstred** [comment]
I'd definitely love to see this.

**Comment by mke-tb** [comment]
It sounds tempting, but how would you assure that it won’t break the features? IMO it’s usually not easy and also not optimal to separately alter a shared functionality between the front and the back office.

I am more in favor of creating a step that allows to you review translations during updates but either way, it seems like a costly improvement.
