### ISSUE TITLE
Product suppliers tab -> currency multistore bug

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/thirtybees#359]
I am using advanced stock management, three multistores and three currencies. As you can see in the screenshot, it shows all my currencies multiple times:
![currency_bug](https://user-images.githubusercontent.com/15154932/30514675-2d94f180-9b1a-11e7-8093-42b06bc57903.jpg)
It does load all currencies for every shop. That should be fixed.

**Comment by doclucas** [comment]
@eschiendorfer
I have tried to reproduce this with 2 currencies and 2 multistores on TB 1.0.6 without success.
Is it still an issue?

**Comment by eschiendorfer** [comment]
@doclucas thx for looking at it. I don't know about 1.0.6. I am still on 1.0.3...

**Comment by doclucas** [comment]
No problem.
If you can somehow test it on 1.0.6 and reproduce the issue, please post simple step by step instructions on how to reproduce this on a vanilla installaiton. 
Should be easy to fix, but only if we can see it. ;)
Thanks

**Comment by Traumflug** [comment]
This should be fixed with https://github.com/thirtybees/thirtybees/commit/0407a2720deb41ef9ce82bc60a3cb972fdc7c8b0.

If there's something left, please don't hesitate to reopen this issue or open another one.
