### ISSUE TITLE
Coverage bug in AdminStockCover

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/thirtybees#361]
The Coverage in advanced stock management doesn't work correctly. If I set for example a period of one year, I don't get any coverage value:
![stockcoveragebug](https://user-images.githubusercontent.com/15154932/30618901-d65b0dde-9d9c-11e7-85a3-ed0fe25cd8e0.PNG)

In Additon there really should be the possibility to show all variants in the table. As you can see in the screenshot above, the table is quite useless without variants of the product.

**Comment by firstred** [comment]
I agree. We'll have a look with `1.0.5`

**Comment by getdatakick** [comment]
Fix ready for testing in branch issue-361. @eschiendorfer can you verify the fix?

**Comment by eschiendorfer** [comment]
I don't use this controller anymore. But I just tried it out and it doesn't seem to be fixed... Looks more or less the same to me.

**Comment by eschiendorfer** [comment]
I am sorrry! It is working correct! I forget to switch to a bigger time span than the defaul "one week". Obviously that was kind of stupid in a test shop ;)

**Comment by getdatakick** [comment]
Thanks for the testing!
