### ISSUE TITLE
500 error gives full path when logfile cannot be written

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/thirtybees#367]
500 error gives path when logfile cannot be written. See the picture. It had the full path from the root on.
![thirty12](https://user-images.githubusercontent.com/13930107/30932903-3bbc6970-a3c9-11e7-8358-359bce510e27.jpg)

**Comment by Traumflug** [comment]
This is pretty much expected. Didn't the installer prohibit an installation with this folder unwritable? It should have.

If write privileges were removed later, this removal is the bug (if caused by thirty bees).

**Comment by Traumflug** [comment]
*clonk* Sorry, sometimes it takes a while until I get it.

Now I see what the report means. It's about "**gives path**". That's right, customer visible messages shouldn't show server internals.

**Comment by firstred** [comment]
That's not okay, but I see that PHP is already set to not to display errors, so I wonder why it still shows that one. Could there be a module or AdminController that overrides the `display_errors` setting (I know the import controller does for example)?

**Comment by Traumflug** [comment]
The reason why this error was visible was that it was written straight to output, no translation, no other handling, as  an argument to `die()`.

Bold as I am, I simply removed these messages. Logging failures shouldn't be fatal. To compensate the removed diagnosis I also restored test results display in AdminInformationsController (Backoffice -> Advanced Parameters -> Configuration Information), which reported 'OK' despite of flaws found. Now it looks like this:

![bildschirmfoto vom 2017-10-04 20-03-48](https://user-images.githubusercontent.com/318581/31191860-cf7093dc-a93f-11e7-9146-3ef5653c29c8.png)

Code is on branch *1.0.x*. I hope this works for everybody. If not, please don't hesitate to re-open this issue. Thanks for reporting!
