### ISSUE TITLE
modulename/ is not a valid module name

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/thirtybees#368]
When I install a module in TB 1.03 under Windows with Developmode enabled I get a white screen with the line 
mollie/ is not a valid module name. 

This is for mollie, but I tried it with three different modules with the same result: the name plus a slash and the message that it is not a valid module name. In the end the module is installed but you see it only after you refresh the page. 

 Locating the issue I found that it happens in the file AdminModulesController.php in the function extractArchive() when it calls Module::getInstanceByName($folder) on line 1265.

**Comment by firstred** [comment]
Windows?

It looks like it tries to filter a directory separator, which ofc. is different on Windows.

**Comment by musicpanda** [comment]
My impression is that inside the zipfile forward slashes are used and that as a consequence the line

$filePath = explode(DIRECTORY_SEPARATOR, $zip->getNameIndex($i));

has no effect as it explodes on backward slashes.

**Comment by firstred** [comment]
Indeed, despite running it on Windows, zips are treated like *NIX filesystems.

**Comment by firstred** [comment]
https://github.com/thirtybees/thirtybees/commit/66994c55088b7d743b036f8ab843361dd4b205da should do the trick
