### ISSUE TITLE
Warehouse Bug when adding product to an order

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/thirtybees#373]
When you add a product to an order in backoffice, there is a nasty warehouse bug. In the form is a hidden select field with name="add_product_warehouse". The options are loaded by ajax, I believe. If you add a product with attributes. It won't find any warehouse! 

To be more precise: I think, the problem only arises for the standard attribute. 

I have no clue, why it happens. But the bug is very critical since in order_detail you will see id_warehouse=0. This is a serious issue, if you use advanced stock management.

**Comment by getdatakick** [comment]
Fixed in branch issue-373. @eschiendorfer could you test if the functionality is really fixed?

**Comment by eschiendorfer** [comment]
Thanks for your help! But this branch is not available in core updater...

**Comment by getdatakick** [comment]
Yeah, not anymore. It was already integrated into bleeding edge

**Comment by eschiendorfer** [comment]
Ok. I believe, that we tester should at least have 7 days to do it. Only if the issue is so critical, that it affects many merchants.

But I will try with bleeding edge now...

**Comment by eschiendorfer** [comment]
Ok as you can see this bug report is more than two years old. So I don't remember the problem exactly. When I recreated now, I had the feeling, that the issue arises for **non-standard attributes**. 

But after using bleeding edge it worked as it should. So I guess you fixed it right anyway! 

Good job and thanks a lot!
