### ISSUE TITLE
Cart total is independent of content

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/thirtybees#375]
In my Prestools webshop I sell single tools and a "super package" that contains all tools. To lower the threshold of buying I have the rule that if they buy first a single tool and then the package the price of the single tool will be subtracted from their price for the package. 

This has been implemented by making a modification on the function getProducts() in the file classes/Cart.php that changes the content of the cart. In Prestashop this works. With Thirty Bees it doesn't work. I can change the price for the product but the total remains the same and the new price is presented as a discount. See the image for the inconsistent result:
![thirty](https://user-images.githubusercontent.com/13930107/31465944-c92211cc-aed5-11e7-9835-4f305d31709b.jpg)

Investigating what happens I found that the final retrieval of cart content is the function getSummaryDetails() in classes/Cart.php. For order related pages this functions is called by the function _assignSummaryInformations() in controllers/front/ParentOrderController.php.

I find this is rather dirty solution. In Prestashop the cart is set and then left alone. In TB changes are made during what should just be information retrieval. This is a mixup of functionality. 

The consequence is that the kind of functionality that I added - and there are a lot of shops that like to have special pricing deals - becomes harder to implement and less straight forward. Not to mention the risk that things don't add up - as is visible in my picture where despite a discounted price the total is not discounted.

**Comment by firstred** [comment]
This is just some functionality introduced since PrestaShop 1.6.1.0 to support the Advanced EU Checkout and additional EU VAT calculations. Nothing has been changed here.

If you want to have the same functionality on thirty bees you will have to make your code PS 1.6.1.x+ compliant.

**Comment by musicpanda** [comment]
Strange. It worked under 1.6.1.
