### ISSUE TITLE
Geoip is broken

### ISSUE THREAD

**Issue by firstred** [thirtybees/thirtybees#376]
It detects `en-us` via the browser, but applies `nl-nl` as soon as it detects the country via the IP address. This happens **after** most important functionality has been intialized (spoiler: that's way too late!)

**Comment by NemoPS** [comment]
What part should it come before?

**Comment by doclucas** [comment]
Has this been fixed yet?

**Comment by bdacus01** [comment]
I didnt want to open a new issue.  adding this here.
https://support.maxmind.com/geolite-legacy-discontinuation-notice/
Just to be sure if you are working on this part.

**Comment by Captain-FLAM** [comment]
I found this : https://github.com/sherpya/geolite2legacy

In waiting that adaptation, you can download the latest archive (2018-12-11) there :

https://web.archive.org/web/20181211081730/http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz

**Comment by Captain-FLAM** [comment]
After testing the conversion, it doesn't work !
I made my own address form that fill automatically from the visitor ip ...
And the town where I live is wrong !!
So I switch back to the original .dat from MaxMind, even if it's outdated 2018-03-27 but at least it works !
BTW, to be sure that the conversion doesn't work, I also tested with many ip from different countries (catched with my torrent software) ...
