### ISSUE TITLE
Uncaught ReferenceError: baseDir is not defined

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/thirtybees#377]
I have noticed this now in multiple modules. Backoffice modules, wich use Ajax often use baseDir. Somehow baseDir is not globally defined. I believe it's only reachable in FrontOffice. Is my assumption correct? 

If yes, this has to be added.

**Edit:** I just noticed the error comes always from ganalytics module...

**Comment by firstred** [comment]
When visiting the module page of the ganalytics module?

**Comment by eschiendorfer** [comment]
There I didn't even check. It came, when I visited AdvancedSearchModulePage. It also appeared when visiting Dashboard.

**Comment by firstred** [comment]
Yes, it's indeed not defined in the back office. I just pushed an update of the module to solve it.

**Comment by eschiendorfer** [comment]
Just did the upgrade... Could it be, that you forget about SSL? I get now: jquery-1.11.0.min.js:4 Mixed Content: The page at 'https://www.domain.com/admin/index.php?controller=AdminDashboard&token=a860aa8152293d9474a5d912b550a16d#' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.domain.com/modules/ganalytics/ajax.php'. This request has been blocked; the content must be served over HTTPS.

**Comment by firstred** [comment]
Can you confirm this has been solved with the latest `ganalytics` module?

**Comment by eschiendorfer** [comment]
Yes it is solved!
