### ISSUE TITLE
500 Server Error on several parts o the Back Office

### ISSUE THREAD

**Issue by RaptorX** [thirtybees/thirtybees#378]
I installed 30Bs on a 1and1 server.

When I click on the Advanced Parameters > Performance tab I am taken to a 500 Error page indicating a Server error.

please provide steps for me to get log info or other relevant information for you to confirm if this is a bug or just a configuration problem.

EDIT: I have the same issue in other parts of the Back Office
* Modules and Services
* Payments

# Store info
thirty bees version 1.0.3
Shop URL http://avaliontech.com/
Current theme in use community-theme-default

# Server info
Server information Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux
Server software version Apache
PHP version 7.0.24
Memory limit 256M
Max execution time 50000

# Database info
MySQL version 5.5.57-0+deb7u1-log
MySQL server db703036393.db.1and1.com
MySQL name db703036393
MySQL user dbo703036393
Tables prefix tb_
MySQL engine InnoDB
MySQL driver DbPDO

# Configuration
Required parameters OK
Optional parameters OK

**Comment by Traumflug** [comment]
Logs are in `log/`.

Usually I'd recommend to go to Advanced Settings -> Performance to turn on Debugging. As this is apparently not possible, please find file `config/defines.inc.php` and apply this patch (change the red line to read like the green line):
```diff
---------------------------- config/defines.inc.php ----------------------------
index 04e20c70bd2..70436040ffe 100755
@@ -31,7 +31,7 @@
 
 /* Debug only */
 if (!defined('_PS_MODE_DEV_')) {
-define('_PS_MODE_DEV_', false);
+define('_PS_MODE_DEV_', true);
 }
 /* Compatibility warning */
 define('_PS_DISPLAY_COMPATIBILITY_WARNING_', false);
```

**Comment by RaptorX** [comment]
weird, now that i tried again there was no error... I assume it was a 1and1 thing then... I will wait a few hours and try again.

If I cant reproduce I will close the issue
