### ISSUE TITLE
Carrier creation shows disabled zones

### ISSUE THREAD

**Issue by RaptorX** [thirtybees/thirtybees#379]
i have disabled some zones in my store but when creating a carrier they show up in the list of available zones for that carrier.

![screct_7qhuuo4ajo](https://user-images.githubusercontent.com/328761/31552800-d3ab3f1c-b00e-11e7-932c-8b28b4a93022.png)
![screct_xbpzngoqoghqj](https://user-images.githubusercontent.com/328761/31552801-d3bffd08-b00e-11e7-952e-62fe88200b67.png)

**Comment by firstred** [comment]
Yes, the idea is that you can still configure disabled zones, e.g. to prepare them before putting them live.

**Comment by RaptorX** [comment]
Makes no sense from my point of view.

The store is in Dominican Republic, no-one of the local carries I am setting up would go to Europe/Asia/Oceania ever, period.

The fact that I manually disabled them is because I don't need them and won't need them for this store. They are cluttering this section.

This 'feature' might be better called "put on hold" instead of "disable"...

**Comment by Dh42** [comment]
If you never plan to use them, you can always delete the zones.

**Comment by RaptorX** [comment]
@Dh42 yes is true.

But I we not expecting this behavior, in fact I am migrating from PS and I don't recall having this issue so I was thinking this might be a bug.

I want expecting it to be a feature :)

**Comment by Dh42** [comment]
The same behavior is in PrestaShop as well. If they are removed, there is no way to set up shipping for zones before you set them live. That would be a problem for people that are testing setting up new shipping methods in new zones.

**Comment by RaptorX** [comment]
> If they are removed, there is no way to set up shipping for zones before you set them live

Having the store in maintenance mode is designed for me to set up everything I need to before going live.

Disabling stuff is meant for not using that on my site, and I would expect that behavior to be in general... Not just some parts of my site.

If I can't use Authorize.Net in my page I don't want it cluttering any part of my store... Not sure if my logic is clear or correct but that's how I see it.

**Comment by Dh42** [comment]
Maintenance mode is not an option for a busy site trying to expand their shipping to the EU or another zone. The carrier system is not a module system, so disabling zones does not work like disabling modules. You are welcome to write an override to make this possible on your shop, but I cannot see it becoming a part of the core currently.

**Comment by RaptorX** [comment]
@dh42 I see your point and stand corrected.

Thanks for your input. Issue closed as it is not a bug.
