### ISSUE TITLE
Handling mcrypt_{en|de}crypt() deprecation

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#386]
After upgrading from Ubuntu 17.04 to 17.10 today, which also upgraded PHP from 7.0 to 7.1, virtually all shop pages, FO and BO, show one or both of these messages:

`mcrypt_decrypt() is deprecated in /var/www/html/ThirtyBees/classes/Rijndael.php on line 102`
`mcrypt_encrypt() is deprecated in /var/www/html/ThirtyBees/classes/Rijndael.php on line 75`

This appears to be cookie handling code:

```none
# | Function                           | Location
1 | {main}()                           | .../index.php:0
2 | require('config/config.inc.php')   | .../index.php:32
3 | Cookie->__construct()              | .../config.inc.php:180
4 | Cookie->update()                   | .../Cookie.php:107
5 | Rijndael->decrypt()                | .../Cookie.php:166
```
Deprecation is discussed here, these encryption methods are considered to be outdated: https://wiki.php.net/rfc/mcrypt-viking-funeral
Further reading, suggesting to use hashes (`password_hash()`, `password_verify()`) instead: https://stackoverflow.com/questions/41272257/php-7-mcrypt-deprecated-need-alternative

Any reason to keep encryption? Cookies should be rather short-lived, so I see no compatibility issue with changing them.

**Comment by firstred** [comment]
Make everyone migrate to the PHPEncryption library?

**Comment by Dh42** [comment]
What about detection? The thing that worries me is shared hosts do not update php often, or users not knowing how to update it.

**Comment by doekia** [comment]
I don't understand the purpose of this request. The vanilla code uses proper mechanism should this be available by the host. The only reason why @Traumflug's host is reporting such message is that the host does not have openssl encrypt|decrypt. 
The mcrypt functions are used as fallback

**Comment by doekia** [comment]
Adressed in the vanilla classes/Rijndael.php of 1.6.1.17
A drop in replacement fixes the issue.
No side effect

**Comment by firstred** [comment]
Thanks @doekia
It has been addressed with a likewise solution now.
