### ISSUE TITLE
[feature request] xenforo bridge

### ISSUE THREAD

**Issue by kintaro1981** [thirtybees/thirtybees#387]
Xenforo community is in search of an e-commerce platform to bridge with.
I think that many xenforo forum admins will adopt Thirty Bees if you are going to make a xenforo <=> 30bees bridge.

**Comment by Dh42** [comment]
It would be nice if they built the bridge, they are a paid solution with more resources.

**Comment by firstred** [comment]
Closing this issue since this is not the place for feature requests. Feel free to post them here instead: https://thirtybees.com/feature-request/
