### ISSUE TITLE
Rounding problems

### ISSUE THREAD

**Issue by SLiCK-303** [thirtybees/thirtybees#388]
Make a cart rule that is say 15% off all products, now go add a product to your cart and goto the cart summary page, add the 15% off voucher, the system is not rounding correctly, the total will be wrong.  I have my settings set at Round Mode:  Round down towards zero when it is halfway there, and Round Type: Round on each item.

![cart-sum](https://user-images.githubusercontent.com/763426/32086124-b7b6c490-ba98-11e7-98b7-25cd76bd1af5.PNG)

Note the total, $3.82, it should be $3.83

![rule](https://user-images.githubusercontent.com/763426/32086128-bbc061fe-ba98-11e7-8490-7b058d07dec6.PNG)

**Comment by SLiCK-303** [comment]
Seems like it's wholy depended on the price.  Make a product for $4.50 like mine is, and you'll see

**Comment by Dh42** [comment]
Have you tried changing the rounding methods?

**Comment by Dh42** [comment]
Actually, it is correct for that rounding method. The prices have a 6 decimal precision, so what you are actually dealing with is
.150000 * 4.5000000  = .675000
4.500000 - .675000 = 3.825000  
since you are rounding down at .5, this is expected behavior.

**Comment by SLiCK-303** [comment]
look at the pict, or setup a product with a price of $4.50 and a voucher of 15%.  You will see the math is wrong.  The total should be $3.82.  ($4.50 - $0.67 = $3.83), NOT $3.82.  If you choose the round up method, you get the same math error

**Comment by firstred** [comment]
Looks good to me as well. Note that the new rounding method is not applied until you start with a completely new cart (have to remove in admin panel).

**Comment by firstred** [comment]
Your last example is item/line rounding.

**Comment by SLiCK-303** [comment]
If you use the round up method you get...  $4.50 - $0.68 = $3.83.....should be $3.82

**Comment by firstred** [comment]
Yes, if you use item/line rounding.

**Comment by SLiCK-303** [comment]
even with round on total it shows up wrong

**Comment by SLiCK-303** [comment]
On your test site it seems to be working, are you using different code there than 1.0.3?

**Comment by SLiCK-303** [comment]
I see, if i set it to round on each line it works....hmm

**Comment by SLiCK-303** [comment]
needs to work the other way too though

**Comment by SLiCK-303** [comment]
Ill just set it to round on each line and call it even i guess....
