### ISSUE TITLE
Fix for friendly URL

### ISSUE THREAD

**Issue by selwynorren** [thirtybees/thirtybees#389]
Hey Guys,
I am re-creating my prestashop website using ThirtyBees on a new domain. However I have run into a small mystery for the Friendly URL. Prestashop always used the category id as part of the url, which used to irritate me. However I find now its the only solution available to me. I have a category called home, which has a bunch of sub categories. This category is for household items I will be selling. So naturally the is also a home category under which all of this falls under as well as a root (I am unsure why there is a need for both) which means the url rewriting breaks and gives me a 404 error page (Which also then breaks styling for that page as well).

 I have to change the SEO rewriting. So I thought I would just pre-pend the word category before all teh categories, however this has no effect for me. So I have to then pre-pend the category id by writing {id}-{rewrite}, seems this is the only way possible.

Is there perhaps a better way for doing this?

**Comment by RaptorX** [comment]
So you have something like this:

Root
  Home
     Category1
     Category2
     Category3
     Home
         Subcategory1
         Subcategory2
         Subcategory3

Then you have issues with www.page.com/home since the category name is duplicated.

Why not use a different category name like: Home Items, Household, Household Items or some other version of that?

**Comment by selwynorren** [comment]
Thanks, yeah I can definitely do that. Is there a reason why you have a root and a home category? Could we not do without the home category? Or does that category have some significance somewhere else? Just wondering

**Comment by selwynorren** [comment]
BTW I fixed it by changing the category friendly url to something else. So the main category still says home, however the rewrite now says shelter.

**Comment by Traumflug** [comment]
> Why not use a different category name

Such workarounds don't solve the problem.

----
> I fixed it by changing the category friendly url to something else

AFAIK that's the recommended procedure. There's also Backoffice -> Preferences -> Duplicate URLs to list all duplicates.

**Comment by selwynorren** [comment]
> AFAIK that's the recommended procedure. There's also Backoffice -> Preferences -> Duplicate URLs to list all duplicates.

Oh wow, I never saw that. That did indeed help. So much so that I changed the category routes to {categories:/}{rewrite}. This meant that it would show category/subcategory

Thanks for the help

**Comment by Traumflug** [comment]
Looks like this one is solved. Please don't hesitate to file a new issue or re-open this one if the problem appears again.
