### ISSUE TITLE
Unable to remove product from Pack of products

### ISSUE THREAD

**Issue by selwynorren** [thirtybees/thirtybees#391]
Using TB 1.0.3 I created a new pack of products. After duplicating the product to create a new version, I added the new product to the pack and tried to delete a product from the pack list.

Nothing happens. I opened the console and it shows the following error:
TypeError: window.delPackItem is not a function[Learn More] Showing in products.js:1315:7 If I expand the error console It shows the following
window.product_tabs.Pack</this.bindPackEvents/< https://www.orren-life.com/js/admin/products.js:1315:7
	dispatch https://www.orren-life.com/js/jquery/jquery-1.11.0.min.js:3:8014
	add/r.handle https://www.orren-life.com/js/jquery/jquery-1.11.0.min.js:3:4750

**Comment by selwynorren** [comment]
Just for reference, I made a backup of products.js in the js/admin folder and uploaded the prestashop version of the same file and now it deletes the product as expected. I am not sure what implication this has and if it will break other functionality

**Comment by Traumflug** [comment]
Thanks a lot for the informative report!

It's quite possible this was fixed already ... https://github.com/thirtybees/thirtybees/commit/ba2ff1133234fb6c107bba5ac08b56bf313956fe ... just not part of the latest release.

@firstred, perhaps it's time to package thirty bees 1.0.4?

**Comment by selwynorren** [comment]
lol Thanks. I am pretty passionate about the Thirty Bees project. So by so I now use it for my own website project (https://www.orren-life.com) instead of PS.

Can I go ahead and integrate that file your reference into my shop and test? or has it already been tested?

**Comment by Traumflug** [comment]
This commit was certainly tested by the person writing it, but likely not much more. Even if it was tested more, it solves your problem, doesn't it? No point in not using it.

**Comment by Traumflug** [comment]
Appears to be solved.
