### ISSUE TITLE
Category pages don't load with SSL turned on

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#394]
See https://forum.thirtybees.com/topic/1064-1064/category-page-non-accessible

> I have enabled ssl on my site. Everything works except the category page https://www.abc.com/?controller=category&id_category=3
>
> When the friendly url is on it says 404 not found. When it is switched off it redirects to non ssl link http://www.abc.com/?controller=category&id_category=3 and says too many redirects

**Comment by kintaro1981** [comment]
I don't know if can be any help but I got the "too many redirects" error too (on all pages, not only category pages) and I solved enabling:

Configure -> Shop Parameters -> General:
enable "SSL"
enable "SSL on all pages" options

**Comment by Traumflug** [comment]
The solution probably should be to get rid of this _Enable SSL on all pages_ switch and making it always turned on. Mixing SSL and not SSL pages was a good idea when SSL was a performance bottleneck, but these days it no longer is. In fact the opposite is true, one risks browser complaints when mixing secure and non-secure stuff.

**Comment by mke-tb** [comment]
@traumflug what’s the difference between those two options?

**Comment by Traumflug** [comment]
With _Enable SSL on all pages_ set to No, but SSL generally enabled, some links direct to the not secured version of pages.

**Comment by mke-tb** [comment]
I agree with you, we should remove the option to and disallow mixing those. There shouldn't be any gray zone with SSL.

**Comment by mke-tb** [comment]
Fixed in https://github.com/thirtybees/thirtybees/commit/3318789af2cdcd833724c32643880aa0b84c96fb

**Comment by Traumflug** [comment]
Thanks for the work, @mke-tb, picked right to _1.1.x_.

@kintaro1981 should it turn out to not work for you, please don't hesitate to re-open this issue.
