### ISSUE TITLE
Default combo not reassigned if you delete it

### ISSUE THREAD

**Issue by NemoPS** [thirtybees/thirtybees#395]
Referring to this post in the prestashop forum

https://www.prestashop.com/forums/topic/634176-16117-multishop-default-combinations-missing-price-000/?do=findComment&comment=2632504

It seems the issue is in TB as well. If you erase the default combination, and don't manually reassign it, the product price will be broken in the front office

**Comment by alwayspaws** [comment]
I recently experienced this issue with TB 1.0.3

**Comment by NemoPS** [comment]
Seems to work in the latest build closing this
