### ISSUE TITLE
Allow Bcc to merchant on all email messages sent

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#397]
This issue has come up here: https://forum.thirtybees.com/topic/1096/how-to-get-copy-sent-to-me-of-all-customer-order-related-emails and part of a solution is shown in this post by @dynambee https://forum.thirtybees.com/topic/1096/how-to-get-copy-sent-to-me-of-all-customer-order-related-emails/34

The point is that merchants get a copy of all sent email. For verification, debugging, archiving demanded by law, whatever.

Not put into a commit, yet, because there should be a Backoffice switch to turn this on and off.

**Comment by Dh42** [comment]
I think we need to merge with this issue since they are pretty much the same, https://github.com/thirtybees/thirtybees/issues/337

**Comment by Traumflug** [comment]
Great work, @mke-tb ! Moved issue branch to _1.1.x_ after simplifying that code a bit (see commit message).

As always: if there's something left, please don't hesitate to re-open this issue or open another one.
