### ISSUE TITLE
Re-sent emails contain placeholders instead of account details

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#402]
Found by @tinho.chan: https://forum.thirtybees.com/topic/862/bank-wire-resend-email-does-not-display-bank-information

I can confirm this. Go to Backoffice -> Orders -> Orders, then click on an order awaiting bank wire payment, then on the *Resend email* button. Delivered emails indeed show just the placeholders, not what should be there. In both, text and HTML version:

![bildschirmfoto von 2017-11-25 22-21-58](https://user-images.githubusercontent.com/318581/33234939-231ee034-d22f-11e7-925b-659b351250e7.png)

**Comment by Traumflug** [comment]
Another, related finding by @30knees: https://forum.thirtybees.com/post/11958

> It’s not just when you resend the email, but when you create the order in the backend and send out the initial email from the backend.

**Comment by NemoPS** [comment]
Possible fix, moved the code retrieving those vars from validation.php to the module's validateOrder

https://github.com/thirtybees/bankwire/commit/6c42c12fe4b636d68f99c4db2aee959034b5042e

**Comment by Traumflug** [comment]
Like [this report in the forum](https://forum.thirtybees.com/post/12152), no visible change in behavior here, too.

**Comment by firstred** [comment]
Fixed, via both the core and the new bankwire module! :D
