### ISSUE TITLE
Errors when ordering product Packs

### ISSUE THREAD

**Issue by selwynorren** [thirtybees/thirtybees#406]
Hey all,

I think I may have found a bug. I have a product that is made up of three existing products in my catalogue. One of these products makes use of combinations. I load the specific product combination into my pack and that all works fine enough.
When I customer tries to order the pack I am getting this error when they have to pay via Bank wire:
Argument 1 passed to Adapter_PackItemsManager::getPackItems() must be an instance of Pack, instance of Product given, called in /xxxxxxxxxxxx/public_html/Core/Business/Stock/Core_Business_Stock_StockManager.php on line 58
at line 53 in file Adapter/Adapter_PackItemsManager.php

If I use another gateway, the order does complete, however it does not affect stock, in the order summary, no products are listed. So even though there was a valid order that has taken place, it does not show which product nor the pack contents of that order.

Not sure if its relevant in this scenario, but I do not make use of the advanced stock management feature at all

**Comment by RaptorX** [comment]
Regarding the stock verify that in the settings you have selected the correct "decrement option"

As far as I remember you have the options of:
Decrement pack only
Decrement products only
Decrement both.

The other error I'm not sure about.

**Comment by selwynorren** [comment]
Thanks Raptor, I had selected to decrememt both. But I have tried the other decremenmt options as well.

This is all one bug not two. I was just highlight the case that this error is not originating from a payment gateway module, but has to do with how ThirtyBees is handling product packs.

The minute I changed the exact same product into a standard product instead of a pack, it all worked out just fine and the customer could order. However as good as this is an alternative, its not a solution to the problem. Even though I am not using advanced stock management, I do still need to know how the stock is currently managed and what stock I have on hand.

But thanks for your advice

**Comment by Traumflug** [comment]
Similar bug report here: https://forum.thirtybees.com/topic/762/error-when-try-to-make-a-payment-with-test-card

**Comment by Traumflug** [comment]
I can reproduce it :-)

**Comment by firstred** [comment]
Alright, got it. This function should be relaxed to accept products as well, but only when the product itself is a pack. It seems like a Product can become a pack by adding just a few properties. It doesn't necessarily have to extend Pack. Not a good design, but I expect that relaxing `Pack::getPackItems` will be sufficient.

**Comment by Traumflug** [comment]
Yes, works beautiful now. Thank you very much!
