### ISSUE TITLE
generated robots.txt files section can block products

### ISSUE THREAD

**Issue by sean-mullen** [thirtybees/thirtybees#408]
eg robots.txt:
```
..
# Files
..
Disallow: /*cart

```
will block a printer-cartridge product url from Google's index 

I believe the wildcard is to match multi-language installations

**Comment by Dh42** [comment]
I was looking at this earlier tonight. Have you tried generating a robots.txt with different languages? It looks like the problem might extend to them as well in blocking the iso's.

**Comment by Dh42** [comment]
I have changed it to not use the wildcards, this feels safer. https://github.com/thirtybees/thirtybees/commit/d5c5e8d32ea9b59f617b60d04e2b3387deca3648
