### ISSUE TITLE
Error when going to Customers>Shopping Cart

### ISSUE THREAD

**Issue by SLiCK-303** [thirtybees/thirtybees#409]
I get the following error/white screen when using PHP 5.6.32, when going to Customers>Shopping Cart in the BO. With 1.0.4 RC1
Running on 7.1.12 it works fine.
 Fatal error: Using $this when not in object context in /var/www/vhosts/paganliving.net/thirtybees.paganliving.net/controllers/admin/AdminCartsController.php on line 146

**Comment by firstred** [comment]
Thanks for the detailed bug report!

**Comment by firstred** [comment]
Fix :D
