### ISSUE TITLE
Allow general backoffice search to be able to search phone numbers [enhancement]

### ISSUE THREAD

**Issue by EvilOni** [thirtybees/thirtybees#411]
What it says on the tin.

We can search based on customer name in the backoffice, sometimes we want to lookup based on phone number (when there's a missed call for example)

**Comment by RaptorX** [comment]
Actually this is good one.

In my current store we lookup customers mainly by phone because they talk to us via whatsapp for example and many times I have their phone before their name. So phone lookup would be greatly helpful.

**Comment by SLiCK-303** [comment]
I don't know if this is the correct way or not to do an override, but it works for me.  After copying this to your system, delete your /cache/class_index.php file.  Unzip this file into your override/controllers/admin folder.  It will give you the phone number search plus it will give you a state field, which is nice if you live in a country like the USA that has states.
[AdminAddressesController.zip](https://github.com/thirtybees/thirtybees/files/1585020/AdminAddressesController.zip)

![capture](https://user-images.githubusercontent.com/763426/34328540-bc2e054c-e8a6-11e7-8717-83fece680a95.PNG)

**Comment by SLiCK-303** [comment]
Ok, so here is one just for the phone numbers, both normal and mobile, no other changes.  Again unzip this file into your sites override/controllers/admin folder, and delete your sites /cache/class_index.php file.

![capture](https://user-images.githubusercontent.com/763426/34330948-e5679e3c-e8e7-11e7-9ec9-1d362d5ac1ae.PNG)

[AdminAddressesController.zip](https://github.com/thirtybees/thirtybees/files/1585211/AdminAddressesController.zip)

**Comment by RaptorX** [comment]
great one!
will use!
