### ISSUE TITLE
An error is showing "PrestaShop" instead of "thirty bees"

### ISSUE THREAD

**Issue by riffcko** [thirtybees/thirtybees#414]
The following error code is showing 

> Technical error: PrestaShop could not install this module.

I don't know if it's deliberate or not, so I won't change it myself (not that I really know how either)

But here is it in the source https://github.com/thirtybees/thirtybees/blob/8b9c03fa1e26b23f8a6e8c04d35ba6cf84dadad6/classes/module/Module.php#L1515

**Comment by Dh42** [comment]
Thanks for that I just changed it and closed it. If you find anything else like feel free to make a pull.
