### ISSUE TITLE
Bug on Class Stock.php

### ISSUE THREAD

**Issue by TobyMudito** [thirtybees/thirtybees#420]
Hello. 

There is a bug, in the class Stock.php.

Method:

`    public static function productIsPresentInStock($idProduct = 0, $idProductAttribute = 0, $idWarehouse = 0)
    {
        if (!(int) $idProduct && !is_int($idProductAttribute) && !(int) $idWarehouse) {
            return false;
        }

        $result = Db::getInstance(_PS_USE_SQL_SLAVE_)->executeS(
            (new DbQuery())
                ->select('`id_stock`')
                ->from('stock')
                ->where('`id_warehouse` = '.(int) $idWarehouse)
                ->where('`id_product` = '.(int) $idProduct)
                ->where((int) $idProductAttribute ? ' AND `id_product_attribute` = '.$idProductAttribute : '')
        );

        return (is_array($result) && !empty($result) ? true : false);
    }`

The last "where" clause doesn't need AND, since where is putting it automatically. Now it produces the following SQL sentence:

[ThirtyBeesDatabaseException]

You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND `id_product_attribute` = 76)' at line 3

`SELECT `id_stock`
FROM `tb_stock`
WHERE (`id_warehouse` = 1) AND (`id_product` = 110) AND ( AND `id_product_attribute` = 76)`

The solution is very simple. Just remove the AND and everything will be ok.

**Comment by firstred** [comment]
Hey, great to see you here!

Can you make a pull request for that, please?

**Comment by firstred** [comment]
Merged! :D
