### ISSUE TITLE
guzzle is deprecated warning during composer install

### ISSUE THREAD

**Issue by ChangePlaces** [thirtybees/thirtybees#422]
During `composer install`

"Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead."

This occurs just before writing the lock file. I see the composer.json uses guzzlehttp/guzzle, but after a bit of grepping, it seems two dependencies are using it:

- satooshi/php-coveralls
- facebook/webdriver/

Maybe there are updates to these depencies?

**Comment by firstred** [comment]
It's okay for dev dependencies.

**Comment by ChangePlaces** [comment]
So, you're a lead developer who's stating it's ok to use deprecated software, even though it's for "dev dependencies"?

Good luck!
