### ISSUE TITLE
Recursive write permissions for Apache user on 

### ISSUE THREAD

**Issue by ChangePlaces** [thirtybees/thirtybees#423]
"Apache user" should become "web user" or the actual name of the user. Very strange to see when I'm using  nginx and haven't used apache for over ten years!

**Comment by firstred** [comment]
Strange, indeed

**Comment by ChangePlaces** [comment]
So, have you fixed this? Or are you're ignoring this or just behaving like a moron? 

If either of the latter two, then go back to playing your games, your 'project' will become a laughing stock if this is how you treat potential developers who could contribute to your project.
