### ISSUE TITLE
data collection

### ISSUE THREAD

**Issue by ChangePlaces** [thirtybees/thirtybees#424]
What is this nonsense:

> All information you give us is collected by us and is subject to data processing and statistics, it is necessary for the members of the thirty bees company in order to respond to your requests. Your personal data may be communicated to service providers and partners as part of partner relationships. Under the current "Act on Data Processing, Data Files and Individual Liberties" you have the right to access, rectify and oppose to the processing of your personal data through this link.

By self-hosting I haven't given you any data. This is worded amateurishly  and makes ~~little~~ no sense. Do you mean any data I enter ever in my shop is collected by you?

I believe (infact, quite sure) this is illegal in some countries without an opt-out box. I have no idea what you're referring to under "Act on Data Processing, Data Files and Individual Liberties" but it certainly doesn't apply to someone not in the USA.

> it is necessary for the members of the thirty bees company in order to respond to your requests. 

what requests? and of course, no it isn't "necessary".

> Your personal data may be communicated to service providers and partners as part of partner relationships. 

Where I'm sitting, this is illegal without my explicit consent which I can't give because I can't opt out of it. Using the opensource software (which you believe in, remember) does not equal, consent.

>  you have the right to access, rectify and oppose to the processing of your personal data through this link

An email address isn't a link. It's... a joke. So, do I have to make a fork of this now without this data collection nonsense? Until this is removed, I'll remove it manually...

**Comment by Dh42** [comment]
One thing you have to realize is that thirty bees is a US project that complies with US law. Just because a data collection policy is illegal for an EU company, does not mean it is for a US company.

**Comment by ChangePlaces** [comment]
You're not following. I'm not in the USA. Therefore American laws are about as important to me as... well... as this nonsense. A product available in country X must comply with the laws of country X. I don't recall mentioning anything about an EU company.

As an individual (a person, a non-legal entity with certain privacy rights) does not have to give this information - though they can, if they want to. Again, **if they want to**.

This is not welcome. This is scummy.

**Comment by Dh42** [comment]
Actually, that is not the case. Just because something can be downloaded anywhere in the world does not mean we have to follow those laws. A good example would be that most countries have sanctions on Iran and DPRK, but our software can still be downloaded there because the internet. 

We collect less information than Wordpress, Joomla, PrestaShop or Magento, but we still do collect some for statistical purposes. This is not something we are going to change. We need to know how many installations we have in the wild. We need to know what country they are located in. These things help us target what integrations to make and also allow us to share raw number data with partners in creating better partnerships. We don't share any user data with third parties other than numbers. No names, no emails, just numbers of installs and active shops. That is all.

**Comment by ChangePlaces** [comment]
Allow me to break down your lies:

> Actually, that is not the case. Just because something can be downloaded anywhere in the world does not mean we have to follow those laws

Ironically, actually, that is not the case.

>  we still do collect some for statistical purposes
You collect more data than you need to for 'statistical' purposes, so this is a lie.

> We need to know how many installations we have in the wild.
No, you **want** to know.

> We need to know what country they are located in
No, you **want** to know.

> These things help us target what integrations to make
It's an opensource piece of software, remember?

> also allow us to share raw number data with partners in creating better partnerships
So, your business model is to get funding from companies, with the 'community' working for you?

> We don't share any user data with third parties other than numbers
In that case, all you need is a counter: $numberOfInstallations++;

Why do you collect names. That... makes it illegal where I'm sitting without an opt-out box.

> This is not something we are going to change.
Hahaha! You realise, this has marked thirtybees as scum and has signed its own death warrant?

Thirtybees talks about being "opensource", for the community yada yada yada, when it's all lies. You just want to get behind an ecommerce platform you can drum up funding for, when the heavy lifting has realistically been done already.

**Comment by ChangePlaces** [comment]
Does the fact you closed this issue mean you've seen the light and have stopped needlessly collecting data including personally identifiable data such as names and emails? 

https://github.com/thirtybees/thirtybees/blob/3ab3c9486e4d88e6201824deb35d6a9b843ba1b3/install-dev/controllers/http/configure.php#L80

**Comment by inetbiz** [comment]
@ChangePlaces if you don't like the software as-is then fork it and change it! I think you need to re-read the license disclosure.

**Comment by ChangePlaces** [comment]
> I think you need to re-read the license disclosure.

To which license are you referring to?

Infact, I prefer to know my rights and complain when software is invading my personal rights.

**Comment by inetbiz** [comment]
You have no rights using said software. It is AS-IS. 

```THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
```

**Comment by inetbiz** [comment]
The minute you downloaded the software " Creative Work ", you are bound to the license. https://github.com/thirtybees/thirtybees/blob/1.0.x/LICENSES There isn't any promise to the merchantability of the shopping cart. You are harassing and do not understand commercial open source.

**Comment by ChangePlaces** [comment]
> You are harassing and do not understand commercial open source

I am harassing? Thank you, that was quite funny. "I do not understand commercial open source"? That too is also funny. You should consider stand-up.

You quote a portion of what appears to be the MIT license, however, the very first line of the license file - unarguably the most important states:

> This work is licensed under the Creative Commons Attribution-NonCommercial 3.0 Unported License. To view a copy of this license, visit http://creativecommons.org/licenses/by-nc/3.0/ or send a letter to Creative Commons, 444 Castro Street, Suite 900, Mountain View, California, 94041, USA.

Oh dang.

**Comment by inetbiz** [comment]
The cart is free so your argument is moot! You have 69 commits. https://github.com/ChangePlaces What does the first line have to do with "rights" you are creating out of thin-air? The creative work is as-is. If you don't like it, fork it or delete the source code?

IF you must comply with regulation, extend the source code. Simple.
