### ISSUE TITLE
Error on function getOrdersReturnDetail($idOrderReturn)

### ISSUE THREAD

**Issue by Derbai** [thirtybees/thirtybees#433]
->where('`id_order_detail` = '.(int) $idOrderReturn)

should be

->where('`id_order_return` = '.(int) $idOrderReturn)

**Comment by firstred** [comment]
Has been changed. Thanks!

https://github.com/thirtybees/thirtybees/commit/05e74d7da8b2950ee65d1bc1859949304cf045b3
