### ISSUE TITLE
Redis Cache - does not work with single Redis cache

### ISSUE THREAD

**Issue by sean-mullen** [thirtybees/thirtybees#441]
Hi,

A successful Redis connection test response is +PONG. 

The Redis Protocol specification https://redis.io/topics/protocol states string responses are prefaced with a  "+"

ThirtyBees however, expects an array response from Redis and erroneously disables the cache completely when it receives a "+PONG" string response from Redis:

https://github.com/thirtybees/thirtybees/blob/78945f8a7ef41cc1e25afdd65b6022a78c0d71a8/classes/cache/CacheRedis.php#L135-L142

I guess Redis must return an array under some circumstances (otherwise this code would not have been written) so I have gone with a fix incorporating both cases. e.g.:

`  $ping = $this->redis->ping();
                            if ($ping === '+PONG') {
                                $this->is_connected = true;
                            }
                            elseif (is_array($ping)) {
                                $ping = array_values($ping);
                                if (!empty($ping) && $ping[0] === '+PONG') {
                                    // We're connected if a connection without +AUTH receives a +PONG
                                    $this->is_connected = true;
                                }
                            }`

**Comment by firstred** [comment]
Looks good to me. Thanks!

**Comment by firstred** [comment]
https://github.com/thirtybees/thirtybees/commit/866c25ae93a3ba0a1ed87dcee0471571992f3c1f
