### ISSUE TITLE
Voucher based on customer group condition is not working

### ISSUE THREAD

**Issue by romaric33** [thirtybees/thirtybees#461]
How to replicate the issue:

1/ Create a customer group, for example HIGHVALUE.
2/ Create or select existing user, add him to the HIGHVALUE group. Default group can still be Customers or HIGHVALUE, whatever you prefer the issue is the same.
3/ Create a new voucher with valid dates and this condition: user being in the HIGHVALUE group.
My action is a 5% reduction on order.
4/ Go to the frontoffice and login as a user in the HIGHVALUE group. Try to order something and apply the voucher.

I get the error: “1. You cannot use this voucher”

This voucher was working in PS 1.6.1.17 and after migrating to Thirtybees it doesn’t work anymore.

Other vouchers with other conditions seem OK. It seems related to the condition: customer group.

TB forum post: https://forum.thirtybees.com/topic/1399/voucher-based-on-customer-group-condition-is-not-working/

**Comment by SLiCK-303** [comment]
works fine for me...

**Comment by SLiCK-303** [comment]
for a stock version of 1.0.3 this is true.  In 1.0.4 it's been fixed.

**Comment by Dh42** [comment]
Fixed in 1.0.4
