### ISSUE TITLE
Bug - can't register admin tabs when only one permission profile exists [v1.0.4]

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/thirtybees#463]
This problem reproduces when you have only SuperAdmin profile in your system, and no others. At that point it's not possible to successfully add new Tab, so many modules fails during installation.

This was injected by [Tabs::initAccess(): initialize with no profiles besides SA, too](https://github.com/thirtybees/thirtybees/commit/310de03d9681d4adac3dc231de4f3b1a8d01b5c5#diff-6aaaeb3ff78d8ffe86daa2918452de3a)

I guess the code should return true, when there is only SuperAdmin profile

**Comment by firstred** [comment]
Ahh, great one.

The 
```php
if (!$profiles) {	
    return false;	
}	

```
seems to make no sense, indeed.

**Comment by firstred** [comment]
I think it was meant to allow access when there are only SuperAdmin profiles.

**Comment by firstred** [comment]
So maybe back to
```php
if (!$profiles) {	
    return true;	
}
```
instead would be the solution.

**Comment by Traumflug** [comment]
Agree on the apparent intention, @firstred.

However, returning there at all means no permission profile for the new tab gets created, not even one for the super admin (SA). Which can result in SA having no access if access code doesn't exclude SAs from permission testing.

Not sure which strategy is the preferred one:

One strategy is to create a permission profile even for SAs. SAs get all permissions set, of course. That's what happens with @getdatakick's patch.

The other strategy would be to get every chunk of code asking for permissions into excluding SAs. Fewer rows in the database, more code required. Switching to this strategy means re-adding the return, but also removing line [639..646](https://github.com/thirtybees/thirtybees/blob/1.0.x/classes/Tab.php#L639-L646).

... and yes, I think current core code does both, putting SA profiles into the database as well as excluding SAs from permission checks (see e.g. [here](https://github.com/thirtybees/thirtybees/blob/1.0.x/classes/Tab.php#L366-L368) ), so deciding for either one would give an opportunity to remove redundant code.

Anyways, reviewed @getdatakick's patch, it's currently in branch *tabpermissions* for running the testsuite.

**Comment by Traumflug** [comment]
Alright, the commit passed, so moved it to 1.0.x.

Will write a code review issue for getting rid of the redundant code in a minute.
