### ISSUE TITLE
Calls towards api.thirtybees.com during full page cache module config

### ISSUE THREAD

**Issue by lucasRolff** [thirtybees/thirtybees#465]
Hi,

## Problem:

API calls towards api.thirtybees.com when doing ajax kall to `/admin123/index.php?controller=AdminPerformance` with form data:
```
action: updateDynamicHooks
ajax: true
hookName: displayFooter
idModule: 12
status: true
```

## Thirty bees version:

1.0.3

## Description

When using the full page cache and wanna enable caching for a specific module - an ajax call will be made to enable the caching for the specific module.

This call is rather slow (1.5 seconds) even on a fast server - so it made me wonder what actually happens.

It turns out after looking in New Relic, that a call towards api.thirtybees.com is being made when performing this ajax call.

Doing a quick grep for api.thirtybees.com in the source code, reveals the URL is only being used for checking possible Thirty Bees upgrades - so I wonder if the ajax call somehow also manage to trigger a version check?

The main issue is the fact that each call takes about 540 ms to make towards the API, so that's rather slow - and if I wanna enable the module caching for 10+ modules, I have to wait plenty of time for the thing to even get enabled.

## Expected result 

api.thirtybees.com shouldn't get called at all for this action.

**Comment by firstred** [comment]
Thanks for the issue. Here's a quick message to notify you that we've been looking at it, but haven't found the answer, yet. If you can figure it out or have found something new that helps, please let us know!

**Comment by Dh42** [comment]
There is actually a trigger to update the API feed on that page.

**Comment by lucasRolff** [comment]
@Dh42 so what you're saying is that it's absolutely required to run for every single module being enabled or disabled? That sounds silly.

**Comment by firstred** [comment]
Sounds silly to me as well. Module update checks should piggy-back on ajax calls, but this sounds like it is happening too often. Needs to be checked...

**Comment by Traumflug** [comment]
Checking for updates automatically would be a task nicely fitting into ShopMaintenance.

That said, it's a bit questionable to check for updates without notifying the merchant. Listing modules in back office does check for updates already.
