### ISSUE TITLE
Function mcrypt_get_iv_size() is deprecated

### ISSUE THREAD

**Issue by SLiCK-303** [thirtybees/thirtybees#466]
I get the following error on the site, with php 7.1.x...
mod_fcgid: stderr: PHP Deprecated: Function mcrypt_get_iv_size() is deprecated in /classes/Rijndael.php on line 75

**Comment by firstred** [comment]
Thanks for the issue. It should be addressed with 1.0.4. Have you tested it on 1.0.4?

**Comment by Traumflug** [comment]
Maybe related: https://forum.thirtybees.com/topic/1937/rindjael-with-php-7-ssl-encrypt

**Comment by Prince-David** [comment]
So I decided to push it there :

https://github.com/thirtybees/thirtybees/commit/4e76040e6282a660ecb7ec7a82fe3d9f5b095c71

**Comment by Traumflug** [comment]
This method is still used in some code, in _classes/Rijndael.php_ and _install-dev/models/install.php_. Plan is to remove all encryption variants but the one provided by PHP's OpenSSL, for less code and removal of a switch a merchant has to decide about.

**Comment by getdatakick** [comment]
Outdated - Rijndael was removed from core
