### ISSUE TITLE
Vanilla installation of 1.0.4-rc.1 shows fatal error in frontoffice

### ISSUE THREAD

**Issue by johanlantz** [thirtybees/thirtybees#468]
**Scenario:**

Clean install of Thirtybees 1.0.4-rc.1 from github using xampp VM with php version 7.1.7 (latest default for xampp VM).

**What happens:**

Installation completes ok and backoffice works fine. Frontoffice however shows the following warning and error:

```
Warning: count(): Parameter must be an array or an object that implements Countable in /opt/lampp/htdocs/thirtybees/modules/blockcart/blockcart.php on line 370

Fatal error: Declaration of StatsRegistrations::getData($layers) must be compatible with StatsModule::getData($layers = NULL) in /opt/lampp/htdocs/thirtybees/modules/statsmodule/stats/statsregistrations.php on line 208
```

**Expected behaviour:**
Working frontoffice.

**Comment by slvrspiral** [comment]
Had the same issue. Went to php 7.1.0 and it worked fine using MAMP Pro.

**Comment by johanlantz** [comment]
Thanks for confirming. It’s probably not that hard to fix then unless it was an isolated issue with the php version rather than tb.

**Comment by slvrspiral** [comment]
just installed via composer and it is working fine on 7.2.1

**Comment by johanlantz** [comment]
I am closing this, no need to waste time on it if it was an issue with a specific PHP version.
