### ISSUE TITLE
Syntax error in supplier query

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/thirtybees#469]
In my 1.03 I regularly get the following error

`*ERROR* 	2018/03/04 - 20:03:33: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND product_shop.`active` = 1) AND ( AND product_shop.`visibility` IN ("both", "' at line 6<br /><br /><pre>SELECT COUNT(DISTINCT ps.`id_product`)
FROM `ps_product_supplier` ps
INNER JOIN `ps_product` p ON ps.`id_product` = p.`id_product`
 INNER JOIN ps_product_shop product_shop
		ON (product_shop.id_product = p.id_product AND product_shop.id_shop = 1)
WHERE (ps.`id_supplier` = 0) AND (ps.`id_product_attribute` = 0) AND ( AND product_shop.`active` = 1) AND ( AND product_shop.`visibility` IN ("both", "catalog")) AND (p.`id_product` IN (SELECT cp.`id_product`
FROM `ps_category_product` cp
LEFT JOIN `ps_category_group` cg ON (cp.`id_category` = cg.`id_category`)
 INNER JOIN `ps_category` ca ON cp.`id_category` = ca.`id_category` AND ca.`active` = 1
WHERE (cg.`id_group` = 1)
)) LIMIT 1</pre> at line 808 in file classes/db/Db.php
`
It looks like this causes the problem: `AND ( AND product_shop.`active` = 1) `

I did some research and found at line 362 in classes/Supplier.php the most likely faulty query (in the latest version a few lines lower). It is the query that starts with `return (int) Db::getInstance(_PS_USE_SQL_SLAVE_)->getValue(`
The lines that look problematic are:
`->where($active ? ' AND product_shop.`active` = 1' : '')
 ->where($front ? ' AND product_shop.`visibility` IN ("both", "catalog")' : '')`

Note that I don't use suppliers in my shop.

**Comment by Dh42** [comment]
Fixed with Yaniv's commit
