### ISSUE TITLE
Trouble with bzopen()

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/thirtybees#470]
I have been busy implementing a function in Prestools that recovers the database backup of an upgrade. Thereby I found one weird thing: on my Windows computer I cannot open the files with bzopen(). It must be some rights issue: I cannot run a hello world php program in a backup directory either. And the bz functions are supported.

As a solution I now read the bz2 files with fread(). And then I convert them with bzdecompress(). This works good.

I don't know whether this is just a Windows problem. But given how often people have problems with their database when restoring an old version it might be an idea to add this option when bzopen fails.

**Comment by Dh42** [comment]
This looks to be more of a BZ bug or a windows bug. We do not officially support windows currently.

**Comment by musicpanda** [comment]
I have a theory of what is happening here. I suspect that php creates an uncompressed version of the file in some temp directory when you open a file with bzopen. The error would then happen when there is something wrong with the settings for that temp directory: either a non-existing directory or one where you don't have the rights.

If that is the case then it would happen just as well in *nix installations.
