### ISSUE TITLE
Multistore Category Bug fix

### ISSUE THREAD

**Issue by sean-mullen** [thirtybees/thirtybees#471]
**Case:**
A TB multi-store installation with different category structures is a good wholesale/resale solution for a small business. 

**Issue:**
In multi-store, working in Store A: Widget is saved in appliance category.
Switch to Store B: Widget is not in its category. Save Widget to correct category. 
Switch back to Store A, Widget is no longer in its category. 

**Cause:**
There is a missing *Product-Category-Shop* multi-store join 

**Fix:**
Add Shop association to classes/Product.php. A one line fix that took me all day to find....

**classes/Product.php**
```php
@@ -4583,7 +4583,6 @@
         $sql->select('c.`id_category`');
         $sql->from('category_product', 'cp');
         $sql->leftJoin('category', 'c', 'c.`id_category` = cp.`id_category`');
+	$sql->Join(Shop::addSqlAssociation('category', 'c', true));
         $sql->where('cp.`id_category` NOT IN ('.implode(',', array_map('intval', $categories)).')');
         $sql->where('cp.`id_product` = '.(int) $this->id);
         $result = Db::getInstance()->executeS($sql);
```

**Comment by Traumflug** [comment]
Sounds like you know what you're doing. Made a commit with the provided diff and put it onto *1.0.x*, to make sure it gets into the *1.0.6* release.

Thank you very much! If there's something left, please don't hesitate to open another issue.
