### ISSUE TITLE
nginx: failure to generate thumbnails upon access

### ISSUE THREAD

**Issue by dvershinin** [thirtybees/thirtybees#474]
## Issue

With nginx, when you access a thumbnail URL, e.g. ```/11031-big_default/lined-beanie.jpg``` it always returns missing (placeholder for not found) product image.

## Reason

ThirtyBees relies on ```$_SERVER['REDIRECT_URL']``` variable value to generate missing thumbnails of product images.

With nginx that variable is not present (it is Apache only).

I see there's sort of workaround for the lack of ```$_SERVER['REDIRECT_URL']``` [here](https://github.com/thirtybees/thirtybees/blob/3edf14cca95fada6d9ce0d168300bffc64456a07/controllers/front/PageNotFoundController.php#L67).

However, it does not work correctly. For the given URL the variable is set to ```"/p///11031-big_default/lined-beanie.jpg-11031.jpg"```.

For users affected, nginx configuration changes which workaround the issue can be found [here](https://www.getpagespeed.com/server-setup/nginx/add-server-redirect_url-to-nginx).

**Comment by Traumflug** [comment]
Alright, thanks for reporting. I think I managed to remove the dependency on `$_SERVER['REDIRECT_URL']' in this place.

**Comment by Traumflug** [comment]
(updated commit with just the commit description extended)

**Comment by dvershinin** [comment]
@Traumflug yep: copied `PageNotFoundController.php` from *redirect-url* branch and things work fine without server side workarounds.

**Comment by Traumflug** [comment]
Excellent. Moved these three commits to *1.0.x*.
