### ISSUE TITLE
[Suggestion] Hooks for accountUpdate and delete

### ISSUE THREAD

**Issue by johanlantz** [thirtybees/thirtybees#480]
In Prestashop 1.7 they added the actionCustomerAccountUpdate hook which is very helpful and proabably quite easy to add to TB as well.

I would also like to propose a hook for actionCustomerAccountDelete to let third party modules know if a user has been removed. I think this is beneficial and probably even mandatory for gdpr. If a customer account is deleted, we need to ensure that any data in the database from 3:rd party modules that can identify the user is also deleted.

**Comment by firstred** [comment]
Have you already tried dynamic hooks like `actionObjectCustomerUpdateBefore` / `actionObjectCustomerUpdateAfter`?
