### ISSUE TITLE
Writing error in the word “Preferrably”

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#482]
Back office => Preferences => Themes => YOUR CURRENT THEME => ICONS => Source favicon (PNG) => Make sure you upload a big enough favicon. Preferrably one that covers all sizes and a square size.

The word “Preferrably”, Preferably.

[Preferably.pdf](https://github.com/thirtybees/thirtybees/files/1916498/Preferably.pdf)

**Comment by Traumflug** [comment]
Travis tests passed. Thanks for reporting!

**Comment by Jorgemgm** [comment]
Hi @Traumflug thanks for correct the word.
