### ISSUE TITLE
Professional Copywriter Willing To Contribute...

### ISSUE THREAD

**Issue by order4adwriter** [thirtybees/thirtybees#483]
Hello @firstred and the rest of the guys out there,

I am a professional copywriter and I 'd like to contribute to the Thirtybees repository by writing compelling and informative content /webpage copy, especially for the [Thirtybees website...](https://thirtybees.com/download/) 

- About Us page, 
- Privacy Policy,
-  Help/FAQ, 
- Terms Of Use, 
- Case Studies, 
- Blog posts ... and other necessary marketing content needed on the website

.
My question is .... would you merge them into your repository when it's all done?

Please let me know so I can get started as soon as possible.

Thanks.

**Comment by Dh42** [comment]
We cannot merge things from our website to the repo, since the website does not have a repo. You are welcome to contact me at lesley@thirtybees.com if you want though.
