### ISSUE TITLE
Cart error when creating backoffice order

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/thirtybees#485]
In 1.0.3 there is an issue when creating a backoffice order. When trying to add an order it returns: "An order has already been placed with this cart."

I don't know why this appears, maybe it doesn't create a new Cart in some circumstances. Another merchants has the same issue: https://forum.thirtybees.com/topic/1672/manual-order-from-back-office-gives-error-for-certain-customers

It could be related to multistore, since we both have this feature activated.

**Comment by Dh42** [comment]
Can you confirm for 1.0.4 too? Do you have a test installation?

**Comment by eschiendorfer** [comment]
No I don't have any such set up. It take a huge amount of time to set up multistore, shipping, products and customer. If there is an updater, I can of course clone my data and test it with that.

It's hard to recreate the issue. For me it's months ago, when I had it. I just removed the condition from the code. But obviously something is wrong.

**Comment by getdatakick** [comment]
@eschiendorfer did you encounter this problem recently? Is this still active? 

It's possible this was fixed since, for example by #612

**Comment by eschiendorfer** [comment]
It's very hard to tell, as I never understood, when this happens and when not. My brother told me, that this error didn't come up recently. So I will close this issue for now.
