### ISSUE TITLE
Suggested size of Favicon and Source favicon

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#486]
Preferences => Themes => YOUR CURRENT THEME => ICONS

In 1.0.4 I think it’s good idea, when mouse hover of Favicon and Source favicon (PNG) have the size, for instance, suggested size 96x96 px PNG.

**Comment by Dh42** [comment]
Are you using the 1.0,4 source already? We have changed the whole favicon device icon setup in there.

**Comment by Jorgemgm** [comment]
I use a fork from https://github.com/thirtybees/thirtybees and everyday I check the Compare.

Please check the attach pdf.

Thank you for your excellent work.

[Thitybees_favicon.pdf](https://github.com/thirtybees/thirtybees/files/1924762/Thitybees_favicon.pdf)

**Comment by Dh42** [comment]
Are you talking about just adding the suggested favicon size in text below the favicon? Or are you wanting to show the source icons size as well?

**Comment by Jorgemgm** [comment]
Only adding the suggested favicon and Source favicon (PNG) size as you have in the Store icon: "Suggested size: 30x30, transparent GIF."

**Comment by firstred** [comment]
Makes sense. We could add that to the page.
Suggested size likely would be the max size found in the template or when unavailable, some generic default.

**Comment by Dh42** [comment]
Fixed with this commit, https://github.com/thirtybees/thirtybees/commit/6db9aa80a3ddbf87738d3c393945bbb8ac14d909
