### ISSUE TITLE
My Account block for your website's footer

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#487]
The module list has the name “My Account block for your website& #039;s footer”, can be corrected to “My Account block for your website's footer”?
[thirtybees_my-account-module.pdf](https://github.com/thirtybees/thirtybees/files/1925000/thirtybees_my-account-module.pdf)
Please check the attach pdf.

**Comment by Dh42** [comment]
Fixed in this release, https://github.com/thirtybees/blockmyaccountfooter/releases/tag/2.0.1  it has been pushed to the api, so just update the module.
