### ISSUE TITLE
Display “Powered by PrestaShop” in the footer

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/ThirtyBees#488]
Modules and Services => Modules and Service => MODULES LIST => CMS block => Configure
In the “CONFIGURATION OF THE VARIOUS LINKS IN THE FOOTER” we can check “Display “Powered by PrestaShop” in the footer”.
What is the function of “Powered by PrestaShop”?
It is a bug or can you change Prestashop to thirtybees?
Please check the attach pdf.

[Thirtybees-PrestaShop.pdf](https://github.com/thirtybees/thirtybees/files/1925086/Thirtybees-PrestaShop.pdf)

**Comment by Traumflug** [comment]
True. This exhibits a few more of them:

```bash
cd modules
grep -rni 'powered by'
```

Which means, it's fixed in core, but not yet in a couple of modules.
