### ISSUE TITLE
Display the theme

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#489]
When enter/refresh the homepage are display at the same time (fraction of second) all three images of Image slider, please check the attach pdf.
[thirtybees_image-slide.pdf](https://github.com/thirtybees/thirtybees/files/1925117/thirtybees_image-slide.pdf)

**Comment by firstred** [comment]
Hey, thanks for the issue. It is called FOUC (flash of unstyled content) and happens when using JavaScript to style parts of the page. Since it's pretty trivial we are not going to change it, but feel free to make a pull request if you want to change it.

**Comment by Jorgemgm** [comment]
Ok, I will make a pull request, because I think this make the page more professional.
Thank you for your excellent work.

**Comment by Jorgemgm** [comment]
I checked to open a pull request, but I didn't open because I am not a programmer and I don't know how fix that.
