### ISSUE TITLE
BO: Admin Stat Badges Needs Font Color Change

### ISSUE THREAD

**Issue by inetbiz** [thirtybees/ThirtyBees#49]
See https://github.com/thirtybees/ThirtyBees/pull/48. The default color of bootstrap badge is white font and the background is orange. It was difficult to see the stats until I changed the color to black. I could not find the sass file to modify. Here is what I propose:

![2017-01-31_3-38-02](https://cloud.githubusercontent.com/assets/3696477/22471897/e0ad4f24-e7a1-11e6-9340-998ae98715fa.jpg)

**Comment by inetbiz** [comment]
@firstred it was fixed when you closed it?

**Comment by firstred** [comment]
Ohh closed because of duplicate, I think. No worries, it's still on the roadmap.

**Comment by firstred** [comment]
Ahh here it is: https://github.com/thirtybees/ThirtyBees/issues/76
