### ISSUE TITLE
Misplaced fixtures

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#493]
There are two misplaced images: `img/c/3-0_thumb.jpg` and `img/c/3-1_thumb.jpg`. These should go into `install-dev/fixtures/img/c/`; the installer should install them together with demo products, and only then.

One can see these images in a demo installation when hovering over the *coffee and tea* main menu and the submenu drops down.

Not sure whether there's a larger underlying issue or why these files are there.

**Comment by Dh42** [comment]
Its for the menu images. I think we should just leave it for the time being. They are not generated automatically by the installer, but its unsure if we will use them in 1.1.x branch. So it might be best to wait until then to address it.
