### ISSUE TITLE
The “VAT number” field must be always displayed

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#494]
The “VAT number” field in “Your address” only is displayed if the customer fill “Company” field, but for European countries must be always displayed the “Vat number” field, not only to companies, but also to private costumers.

There are a lot of private customers in Europe that want the VAT Number in their invoices due to the personal tax deductions.

Please check the attach pdf.

[VAT_number.pdf](https://github.com/thirtybees/thirtybees/files/1940316/VAT_number.pdf)

**Comment by dosbiner** [comment]
I think we can close this issue. Solved by @Traumflug with new module https://github.com/thirtybees/vatnumber

**Comment by Traumflug** [comment]
True. Discussed this a bit with others and the conclusion is, another field visible makes this dialog less attractive, doing more harm than good. Customers having a VAT number usually know that they have to claim to be a "company". If that's still not enough, there's now a simple checkbox which can get turned on.

I hope this is sufficient.
