### ISSUE TITLE
Request for comment: move from serialize() to json_encode()

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#508]
Today we became aware of this security issue: https://blog.ripstech.com/2018/prestashop-remote-code-execution/

Lo and behold, this issue applies to thirty bees as well. To fix it I not only found PS' fix, but also reworked a couple of additional usages of PHP serialize(). In two places it's used to store arrays in the database. These additional steps aren't strictly necessary, but I consider generally frowning on serialize() is a good idea for avoiding accidental issues.

Result is branch *serialize* with 6 commits on it. How many of them should we keep?

https://github.com/thirtybees/thirtybees/commits/serialize

**Comment by firstred** [comment]
It is going to break some backwards compatibility (settings lost), but definitely worth it. Unserialize is not secure, not necessary, inefficient and in general should be avoided at all costs if you ask me!

**Comment by Traumflug** [comment]
Allright, made this series complete and moved it to *1.0.x*. Thanks for the comment!
