### ISSUE TITLE
Count orders without invoice as well

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#511]
Discussed here: https://forum.thirtybees.com/topic/1720-1720/stats-do-not-show-orders-and-carts-correctly-tb-1-0-4

I fetched the patch provided there and aligned it to the newer syntax, see the one commit on branch *stats*: https://github.com/thirtybees/thirtybees/commit/26aa0dab78b2d4f01f9f3180930dcda93bfbe6ac

I think it's a matter of taste on what one wants to count. All orders recorded or only orders with an invoice ( = completed orders). As far as I can see, the methods changed are used by some backoffice statistics modules, only.

**Comment by Dh42** [comment]
I am ok with adding it in.

**Comment by Traumflug** [comment]
As usual when asking for votes, votes for and against it are 50:50 :-) Which leads to the idea that we need both, requiring a few additional code changes.

**Comment by Dh42** [comment]
Maybe we can put this off and then add a few more features in the 1.1.x branch. I saw a couple stats posts on the forum that we might could merge into the core as well. 

https://forum.thirtybees.com/topic/1163/module-free-stats-unpaid-orders

https://forum.thirtybees.com/topic/1163/module-free-stats-unpaid-orders

**Comment by Traumflug** [comment]
Probably related to this: https://forum.thirtybees.com/topic/2600-stats-module-bug-multistore/?tab=comments#comment-25801

> The issue is when you untick the option "Allow a customer to download and view PDF versions of his/her invoices." in the order status, then the stats module does not consider the order as being paid and valid.
>
> In my opinion this is a little bug as there is a specific setting "Set the order as paid." - shouldn't this be the main factor of how the stats module displays best selling products and other order related modules like the dashboard?

**Comment by Traumflug** [comment]
There is a patch on branch _issue-511_, which is broken. See https://travis-ci.org/thirtybees/thirtybees/jobs/571262791

> Column 'date_add' in field list is ambiguous at line 956 in file controllers/admin/AdminStatsController.php

**Comment by ksimunovic** [comment]
@Traumflug This should fix the failing Travis CI run
