### ISSUE TITLE
Shipped email doesn't take email logo

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/thirtybees#513]
There seems to be an issue with the logo attachement in the emails. When the "shipped" email is sent, the header logo is used instead of the email logo.

I tested just with version 1.0.3 but couldn't find any commit, which seem to have solved this...

**Comment by Traumflug** [comment]
TBH, I'd be happy if changes to email templates in the core repository would actually change the template used in a shop installation. Last time I looked into this corner I found that these templates get overwritten pretty immediately after an installation. Source of these other templates is currently unknown to me, just as the mechanism for changing them.

And then there are email templates coming with the theme. So, first step would be to find out which template is actually used. The one coming with the repository, the one overwriting that or the one coming with the theme.

**Comment by eschiendorfer** [comment]
Thx for your fast answer. Its not a problem about the html templates I guess. For example in my case I use custom templates in the theme folder. The order_confirmation.html works fine. It uses also {shop_logo} and it displays the correct logo. I guess it's some bug in the send function of mail class. But I am really not sure.

**Comment by yaniv14** [comment]
I can't see any way this can happen unless there is some override for the templatevars by "actionGetExtraMailTemplateVars" which is the only hook executed after the {shop_logo} var was set.

looking at this code, it looks like the shop logo is set as an attachment to the mail.
but regardless its still the same for all mail templates.
````
            if (Configuration::get('PS_LOGO_MAIL') !== false && file_exists(_PS_IMG_DIR_.Configuration::get('PS_LOGO_MAIL', null, null, $idShop))) {
                $logo = _PS_IMG_DIR_.Configuration::get('PS_LOGO_MAIL', null, null, $idShop);
            } else {
                if (file_exists(_PS_IMG_DIR_.Configuration::get('PS_LOGO', null, null, $idShop))) {
                    $logo = _PS_IMG_DIR_.Configuration::get('PS_LOGO', null, null, $idShop);
                } else {
                    $templateVars['{shop_logo}'] = '';
                }
            }
            ShopUrl::cacheMainDomainForShop((int) $idShop);
            /* don't attach the logo as */
            if (isset($logo)) {
                $templateVars['{shop_logo}'] = $message->embed(Swift_Image::fromPath($logo));
            }
````

**Comment by Dh42** [comment]
@yaniv14  Were you able to reproduce this on 1.0.4? I was testing a minute ago and I cannot.

**Comment by Dh42** [comment]
@eschiendorfer  Are you using stock templates or edited one? Single store or multi-store? Also, are you sure this is not a mail service caching issue.

**Comment by eschiendorfer** [comment]
Thx for the answers. It's multistore and the templates are edited. I will look now deeper into it, since as @yaniv14 says, its probably something on my end. I will update this entry here later this week.

**Comment by Dh42** [comment]
Were you able to figure out what is going wrong?

**Comment by eschiendorfer** [comment]
I don't remember, what caused this problem. But it's gone. Either from update 1.0.3 to 1.0.7 or something on my end.
