### ISSUE TITLE
Registered clients in disable countries

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#519]
1. In Localization => Countries we can Enable (e.g. France).

2. The client that country (e.g. France) can register.

3. The e-commerce decide Disable that country (e.g. France).

4. The new clients for that country, can’t register (e.g. France). 

5. The registered clients, that countries (e.g. France), can “Add to cart”. 

6. After “Add to cart” => “Proceed to checkout” => “Proceed to checkout” and then go to “Your address” where didn’t exist that country (e.g. France) and they can’t finish the buy without change the country.

7. This issue in Europe is very important because the VAT, (in middle of the year the e-commerce could need stop sell for that country and the next year start sell again).

8. I think is great value, if before open “Your address”, open one box with some text who previous the e-commerce could fill: 
“Sorry for inconvenience, but we didn’t sell for your country until the end of the year. Please feel free for change your Delivery address or come in the next year.”
or
“For the logistic issues we stop sell for your country. Please feel free for change your Delivery address.”
or
“Sorry for the inconvenience but temporary we stop sell for your country. Please feel free for change your Delivery address or check for update.”
or
“Sorry for the inconvenience but we stop sell for your country. Please feel free for change your Delivery address.”
or 
…

9. In that box the client has the option to “Change the delivery address” or “Sign out”.

10. For that it’s good idea in Localization => Countries => (e.g. France) => Active => YES/NO => below create the option “Registered client” and open a field who e-commerce could fill.

**Comment by Dh42** [comment]
This is an edge use case and should be handled buy a module, not the core.
