### ISSUE TITLE
Delivery address

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#521]
In TB “Localization” => “Taxes” => “TAX OPTIONS” => “Based on”

I tested, but for me, the “Based on” don’t work (only works “Invoice address”).

I think the best and easy solution it’s move “Based on” from “Localization” => “Taxes” => “TAX OPTIONS” to “Localization” => “Countries” and in all countries display “Based on”.

**Comment by getdatakick** [comment]
I've tested this functionality:

1) Created new Tax rule
     - country A -- tax 10%
     - country B -- tax 20%
2) Associated this tax rule with some product
3) added this product to cart
4) created 2 addresses for country A and B

Result:
Based on works according to expectation. When 

- based on Delivery -- tax rate depends on Delivery address
- based on Invoice -- tax rate depends on Invoice address

If you still experience the issue, please provide exact reprosteps for vanilla thirtybees installation.
