### ISSUE TITLE
Product image not showing in Chrome

### ISSUE THREAD

**Issue by johanlantz** [thirtybees/thirtybees#523]
I have just cloned TB from develop and I see two weird things on the product page:

1. The big image is not showing at all in Chrome. In Safari it works.
<img width="736" alt="screen shot 2018-05-29 at 15 11 24" src="https://user-images.githubusercontent.com/7461655/40660920-ae6c7692-6352-11e8-972c-5a5f41ac412b.png">

2. When clicking on the thumbnails (in safari) the image is zoomed. I would expect the big image to change when clicking the thumbnail, not zooming. Video on this link:
[https://drive.google.com/file/d/1MV6FwCxCjXODmli_SIeRm1dnpfqvMgyi/view?usp=sharing](https://drive.google.com/file/d/1MV6FwCxCjXODmli_SIeRm1dnpfqvMgyi/view?usp=sharing])

**firstred edit: fix URL**

**Comment by firstred** [comment]
If I recall correctly @Dh42 has the solution to this already?

**Comment by Dh42** [comment]
Yeah, this is related to the deeper issue of keeping the submodules in sync. The community theme submodule does not have the fix, but the community theme repo does have the fix. 

So copying the community repo files over them will fix it.

**Comment by johanlantz** [comment]
yeah, submodules can be a bit nasty but I like that you have separated the theme into its own repo. Would it be possible for you to update develop to reflect the submodule change when you complete tasks on the theme? Something like:
https://www.activestate.com/blog/2014/05/getting-git-submodule-track-branch

**Comment by Traumflug** [comment]
> Would it be possible for you to update develop to reflect the submodule change when you complete tasks on the theme?

A module validator is currently work in progress, see https://github.com/thirtybees/thirtybees/commits/validatemodule

**Comment by johanlantz** [comment]
@Dh42 Indeed if I copy paste the theme code from develop, the product image is show.

However the second comment is still valid. If I click a product image thumbnail, you should not zoom (show the thickbox image), only change the large-default image.

**Comment by Dh42** [comment]
This was fixed with some of @Traumflug 's fixes for building.
