### ISSUE TITLE
Currency formatting not working

### ISSUE THREAD

**Issue by RaptorX** [thirtybees/thirtybees#524]
I imported my localization settings and the store currency is DOP.

DOP formatting is as with Dollars and I set it up on BO as such:

![2018 05 29-14-25-41_avaliontech com](https://user-images.githubusercontent.com/328761/40677632-946005c8-6354-11e8-9c95-0f6f14d33d38.png)

but still have the euro formatting on store, after clearing cache and refreshing:

![2018 05 29-14-26-13_avaliontech com](https://user-images.githubusercontent.com/328761/40677662-a71a77d4-6354-11e8-9672-aa62c85c2347.png)

I had the same issue with PS before and turning off "AutoFormatting" usually fixed the issue but in this case if I turn the option off, and then re-enter in to the currency settings it is still on.

Seems to be currency formatting is being ignored by TB.

**Comment by Traumflug** [comment]
True. This switch doesn't stick.

**Comment by RaptorX** [comment]
any workarounds for the moment?

I also noticed that this is a problem that affects 1.0.4 only as I have other stores with 1.0.3-below and they are working just fine...
this is from 1.0.3 store:

**autoformat switch was off as i went and checked the currency**
![2018 05 29-15-36-39_pointshoprd com](https://user-images.githubusercontent.com/328761/40681072-7d9b3a24-635e-11e8-8da2-d9db2a10448c.png)

**store front is showing the prices correctly**

![2018 05 29-15-36-04_pointshoprd com](https://user-images.githubusercontent.com/328761/40681036-65f14314-635e-11e8-9d9e-299039fbd493.png)

**Comment by Traumflug** [comment]
This *Auto format* switch appeared between thirty bees 1.0.1 and 1.0.2-beta.1. And between v1.0.4-rc.1 and 1.0.4, there's commit d4ba353285f16d5ffbeda4ae426c6585536e6b7f which partially reverts this code. Probably by accident.

Try branch *currency*, there's a commit 8541769483f4ba2a4063549fc6b1a5dec9a74967, which undoes this partial reversal. With this commit applied, the *Auto format* switch should work again.

Does it work for you as well? Does it fix the problem?

**Comment by RaptorX** [comment]
Confirmed. That fixes the issue.

As soon as "auto format" is off and I set the proper formatting front office displayed the format as intended.

![2018 05 29-16-26-08_avaliontech com](https://user-images.githubusercontent.com/328761/40683592-64e75902-6365-11e8-8b10-baf7c2a92f5d.png)

semi-offtopic: what is the purpose of the autoformat option?
If i edit the currency settings I am expecting my changes to work as i set them and It is perplexing when they dont, until suddenly you realize that the autoformat option comes on **by default**. 

Also is there a way to specify what the autoformat option for a specific currency is? because obviously for DOP Thirty Bees has it wrong. :)

**Comment by Traumflug** [comment]
> That fixes the issue.

Excellent, and thanks for testing! Will move that to branch *1.0.x* in a minute to get it into the next release.

> what is the purpose of the autoformat option?

It came with PrestaShop and given that, we have to support it for the time being. They probably had a reason to implement this.

I'd pledge for turning it off by default as well and keep this issue open for getting this done.

**Comment by RaptorX** [comment]
Always available for quick tests!
:D

**Comment by RaptorX** [comment]
UPDATE:

something weird is happening. The currency format is working but when i refresh the page it reverts to EURO format, If i refresh several times in a row the formatting changes from DOLLAR formatting (which is the desired format) and EURO formatting.

I cleared cache, and used incognito mode from chrome and the formatting alternates between those two mentioned,

**Comment by doclucas** [comment]
@Traumflug based on the comments above, it seems resolved. Isn't it?

**Comment by Traumflug** [comment]
True. Opened #782 to handle removal of this switch.

Thanks to all participating!
