### ISSUE TITLE
Tools::dieOrLog terminates script execution in development mode

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/thirtybees#528]
Tools::dieOrLog method has very annoying and dangerous behaviour. Here's the current code:

```php
    public static function dieOrLog($msg, $die = true)
    {
        if ($die || (defined('_PS_MODE_DEV_') && _PS_MODE_DEV_)) {
            die($msg);
        }

        return Logger::addLog($msg);
    }
```

Script execution always terminates when debug mode is enabled, even when $die parameter is false.

As an example why is this dangerous, see this code snippet:

```php
public function processOrder() {
  ...
  Mail::Send($id_lang, 'notify-customer', Mail::l('Your order has been shipped', $id_lang), $data, $email, null, null, null, null, null, _PS_MAIL_DIR_, false);
  $this->setOrderStatus($order);
  ...
}
```
Mail::Send internally uses Tools::dieOrLog - for example it's called when email template is missing

So, in this example, if ```notify-customer``` template is not translated to ```$id_lang```, then 
- with debug mode enabled, the script will die, and ```$this->setOrderStatus($order)``` will be never called. This can lead to data inconsistency
- with debug mode disable, ```Mail::Send``` will return false, and script continues to work.

I believe that debug mode should not change the execution path.

**Comment by Traumflug** [comment]
> I believe that debug mode should not change the execution path.

True.

`dieOrLog()` is used in class Mail only, with only two exceptions, so this somewhat asks for deprecation of that method in favor of using `Logger::addLog()` directly.

**Comment by getdatakick** [comment]
Great, deprecation is probably the best way to tackle this. I'll prepare a pull request

**Comment by getdatakick** [comment]
Ok, I finally got to this. Here's my commit: 39f806bccc8a56f4ab3ac2babc28e31bc59dd0bd . @Traumflug please review

**Comment by Traumflug** [comment]
Thanks for the commit. Looks good.

Only one thing: thirty bees prefers the overrideable `static::` over `self::`. I fixed this by adding another commit. Let's see what Travis means: https://travis-ci.org/thirtybees/thirtybees/builds/418170632?utm_source=github_status&utm_medium=notification

**Comment by Traumflug** [comment]
D'oh:

> PHP Parse error:  syntax error, unexpected ';', expecting ',' or ')' in /home/travis/build/thirtybees/thirtybees/controllers/admin/AdminTranslationsController.php on line 2789

Added the missing ')', let's try again: https://github.com/thirtybees/thirtybees/commits/travis

**Comment by Traumflug** [comment]
Better now:

> Build: #2160
> Status: Passed

Moved it to *1.0.x*.

Thanks again!
