### ISSUE TITLE
New customers email

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#531]
When the customer creates an account receive one email, that email have the expression "IMPORTANTA 'SECURITY TIPS:" I think it is better "IMPORTANT SECURITY TIPS:"
Please check the attached pdf.
[New customers email.pdf](https://github.com/thirtybees/thirtybees/files/2088125/New.customers.email.pdf)

**Comment by Dh42** [comment]
/this could be a theme level error for a theme that shipped with bad templates, this is not in the core, https://github.com/thirtybees/thirtybees/blob/1.0.x/mails/en/account.html#L112
