### ISSUE TITLE
Custom Payment Methods ignore Carrier restrictions after update

### ISSUE THREAD

**Issue by RaptorX** [thirtybees/thirtybees#533]
Hi, 

I just noticed that even though i select not to show a specific payment method for a carrier the module still shows it on the payment page.

This is after 1.0.4 update

![screenshot-avaliontech com-2018 06 13-22-11-33](https://user-images.githubusercontent.com/328761/41386214-bf70138a-6f56-11e8-876b-b1942e536d31.png)

This settings should only show the Cash On Delivery for customers that receive with my store carrier, but right now the store is showing it no matter which carrier I pick.

**Comment by RaptorX** [comment]
bump

**Comment by Traumflug** [comment]
Recently I've developed a tendency to put everything into either the core or default theme issue tracker. Issues in module trackers get forgotten easily. So: thanks for looking this up, but let's keep this one open until the other one is done.

**Comment by getdatakick** [comment]
I've retested this functionality and I can confirm it was fixed by thirtybees/custompayments#3
