### ISSUE TITLE
Find the addresses of one customer by email

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#537]
When the customer “Create an account” fill one page with “Your personal information” and other with “Your address”. 

In Back Office we can find “Your personal information” in “Customers” => “Customers” => “MANAGE YOUR CUSTOMERS” and we can find “Your address” in “Customers” => “Addresses” => “ADDRESSES”.

But the ID of “ADDRESSES” is different of the ID of “MANAGE YOUR CUSTOMERS” and because that we can’t know what it is the address of the customer without many tries.

We only have the confirmation of “address” of one “customer” after edit “ADDRESSES” and in the top came the same name and email of the “Customer” the “Your personal information”.

I think it is good idea in “ADDRESSES” we could find the customer making the search by email.

**Comment by doclucas** [comment]
I think it is a good idea, but this is a feature request and not an issue, so should be closed and posted in the right place: https://thirtybees.com/feature/?meta=_avfr_status&val=all

**Comment by doclucas** [comment]
@Traumflug if it stays open, I think it's best to add the "enhancement" flag to this one.
