### ISSUE TITLE
Field “Date of Birth” In “Your personal information” 

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#547]
It’s good if the e-commerce, in Back office, could manage the field “Date of Birth” appears or not in “Your personal information”, when the customer creates an account.

The “Date of Birth” is displayed in “Your personal information” with or without “*Required field”.

The e-commerce could set the minimum age, after the customer fill “Date of Birth” and the software check if the customer has minimum age set by the e-commerce.

**Comment by Dh42** [comment]
This is a good idea, but not something we can implement in this branch. If we added the logic, it would only work with the default theme.
