### ISSUE TITLE
Full page cache 'index' errors

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#551]
Steps to reproduce:

- Default installation with demo products.
- Back office -> Advanced Parameters -> Performance -> panel *Server Side Caching*: click on *Yes* for *Use cache*.
- Back office -> Advanced Parameters -> Performance -> panel *Server Side Caching*: click on *Save*.
- Back office -> Advanced Parameters -> Performance -> panel *Full Page Cache*: click on *yes* for *Use full page cache*
- Back office -> Advanced Parameters -> Performance -> panel *Full Page Cache*: click on *Save*
- Visit the shop front page.
- Reload this page.

Expected result: front page loading.

Actual result: Error 500 without debugging enabled, this error with debugging enabled:

```
[ThirtyBeesException]

Cannot use object of type stdClass as array
at line 246 in file classes/cache/Cache.php

241.      * @since 1.0.0
242.      * @version 1.0.0 Initial version
243.      */
244.     public function get($key)
245.     {
246.         if (!isset($this->keys[$key])) {
247.             return false;
248.         }
249. 
250.         return $this->_get($key);
251.     }

    CacheCore->get - [line 293 - classes/controller/Controller.php] - [1 Arguments]
    ControllerCore->run - [line 837 - classes/Dispatcher.php]
    DispatcherCore->dispatch - [line 33 - index.php]
```

Known workaround:
- Back office -> Advanced Parameters -> Performance -> panel *Full Page Cache*: hold down the Ctrl key and click on *index* in the list.
- Back office -> Advanced Parameters -> Performance -> panel *Full Page Cache*: click on *Save*

This turns off full page caching for the front page, which is obviously an performance drawback, but the front page works again.

**Comment by therampagerado** [comment]
It's working for me without your workaround. 

Do you experience this every time or this can be server side issue?

**Comment by dosbiner** [comment]
@therampagerado can you share your server configuration in BO > advance parameters > configiration information

**Comment by therampagerado** [comment]
CONFIGURATION INFORMATION
This information must be provided when you report an issue on our bug tracker or forum.

 SERVER INFORMATION
Server information: Linux #1 SMP Tue May 22 10:39:25 EDT 2018 x86_64

Server software version: LiteSpeed

PHP version: 7.0.30

Memory limit: 512M

Max execution time: 3600

 DATABASE INFORMATION
MySQL version: 10.2.15-MariaDB-cll-lve

MySQL server: localhost

MySQL name: name

MySQL user: user

Tables prefix: ps_

MySQL engine: InnoDB

MySQL driver: DbPDO

 STORE INFORMATION
thirty bees version: 1.0.5

Shop URL: http://www.domain.com/

Current theme in use: warehouse

 MAIL CONFIGURATION
Mail method: You are using the PHP mail() function.

 YOUR INFORMATION
Your web browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

 CHECK YOUR CONFIGURATION
Required parameters: OK

Optional parameters: OK

**Comment by dosbiner** [comment]
I've same server configuration like that except litespeed. I can confirm native nginx and apache working fine, maybe not full compatible with litespeed?

**Comment by therampagerado** [comment]
I'm saying that I don't see this issue at all. Not that it doesn't work.

Probably it's some sort of local issue with db/files.

**Comment by Traumflug** [comment]
Well, I use Apache, have no custom modules enabled and see the issue, so it's certainly a bug.

**Comment by doclucas** [comment]
Easily reproducible. Just tested with a fresh installation of 1.0.5 on WAMP with Apache+PHP 7.0.29+MariaDB and immediately followed the steps in the OP.
Some pages loaded fine, but http://localhost/tea gave me 500 error with the same debug information.

**Comment by doclucas** [comment]
I modified the code to get rid of the error (convert the object to an array), although I have no idea if this affects the caching and why this issue has suddenly come up in your project's code, maybe something prior to this triggers it. Probably requires more investigation.

This is what I have changed.

```
public function get($key)
    {
	if (is_object($this->keys)) {
        $this->keys = get_object_vars($this->keys);
        }
	    if (!isset($this->keys[$key])) {
            return false;
        }

        return $this->_get($key);
    }
```

Basically added:
```
       if (is_object($this->keys)) {
        $this->keys = get_object_vars($this->keys);
        }
```

**Comment by pdurko** [comment]
It's occasionally happening on other pages too, not just index page.
But it's hard to reproduce. Sometimes after clearing the cache everything is working and then suddenly this error came up.

[ThirtyBeesException]
Cannot use object of type stdClass as array
at line 246 in file classes/cache/Cache.php

241.      * @since 1.0.0
242.      * @version 1.0.0 Initial version
243.      */
244.     public function get($key)
245.     {
246.         if (!isset($this->keys[$key])) {
247.             return false;
248.         }
249. 
250.         return $this->_get($key);
251.     }
CacheCore->get - [line 293 - classes/controller/Controller.php] - [1 Arguments]
ControllerCore->run - [line 837 - classes/Dispatcher.php]
DispatcherCore->dispatch - [line 33 - index.php]

**Comment by getdatakick** [comment]
I believe that the this is another victim of serialize -> json_encode conversion. Specifically commit 7bc4831c4c9e2feca15b29ec67131ad56ad57104. 

line 57: ```$this->keys = json_decode(file_get_contents($keysFilename));```

json_decode by default returns stdClass, but keys are expected to be associated array.

Fix should be fairy simple -- replace this linke with ```$this->keys = json_decode(file_get_contents($keysFilename), true);```

And of course, we need to investigate what is expected output of the second json_decode call on line 97. Maybe we need to fix this one as well

**Comment by doclucas** [comment]
This seems to work. Thanks.
 I noticed another, possibly related bug, where the shopping cart quantity remains an old value when going to a cached product page.
For example, go to "Mug", add 1 piece, go to product listing page, add 1 piece of another page, return to the "Mug", you will see the old value in cart.

**Comment by Traumflug** [comment]
Commit looks good! Thank you very much. Picked it into the thirty bees repository, where it should land on *1.0.x* in a couple of minutes.
