### ISSUE TITLE
Meta generator is still Prestashop

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/thirtybees#552]
Meta generator is still Prestashop

**Comment by Dh42** [comment]
Where are you seeing it at? This is what I see, https://github.com/thirtybees/community-theme-default/blob/0aa28a7214db4f4c897e6efb4d2c830d9a199c9f/header.tpl#L24

**Comment by Traumflug** [comment]
Maybe it's because it's a theme thing and a *1.0.3* or *1.0.4* -> *1.0.5* upgrade doesn't upgrade the theme as well. Much less themes other than the default theme.

**Comment by Traumflug** [comment]
It was fixed here, a bit over a year ago: https://github.com/thirtybees/community-theme-default/commit/24892434c7cb725565d575c621f0785d449a0316

**Comment by therampagerado** [comment]
You are correct. I forgot that this tag is added by the theme and was quick to check on 2 tb sites of mine, one migrated and one none. Both of them used the same theme for PS. Sorry, my bad! :)
