### ISSUE TITLE
Error during new 1.0.5 installation

### ISSUE THREAD

**Issue by doclucas** [thirtybees/thirtybees#559]
An error occurred during installation...
This is a non-fatal error. It can be fixed in Backoffice later. Just jot it down or make a screenshot to not forget it now, or look it up in logs/ later.

Translations for English (English) and thirty bees version 1.0.5 not found.
Installed translations for thirty bees version 1.0.4 instead.

**Comment by Traumflug** [comment]
You've seen the fallback mechanism working fine. No bug.

**Comment by doclucas** [comment]
It's not a bug, but not suppose to need to fallback if you set it up right (ie. add the 1.0.5 translation where it should be). When a new user installs a new software without seeing any such errors, it makes that user much more confident in the software...

**Comment by doclucas** [comment]
Seems to be fixed in 1.0.6, so can be closed. Thanks.
