### ISSUE TITLE
Deal with default max_input_vars

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#561]
Trying to translate something when running on a standard server, one might well see this:

![grafik](https://user-images.githubusercontent.com/318581/43281376-cbb61bc4-9113-11e8-87a2-221c9c6af2a0.png)

That's likely a major showstopper for merchants.

What's going on? The translations page gets served just fine with or without this limit. However, when saving, this pages POSTs not just translations related to the clicked Save button, but translations of the *entire* page. That's a) unexpected (think of fields changed without intention to get saved) and b) a bit silly (big traffic, running into the limit).

All the code dealing with figuring and displaying this `max_input_vars` limit can get removed when JavaScript of translation pages gets changed to POST just the translations related to the Save button. Such an area is typically well below 100 strings, far away from any trouble.

**Comment by Traumflug** [comment]
Limits figuring happens in `controllers/admin/AdminTranslationsController.php` and in `modules/blocklayered/blocklayered.php`, `'limit_warning'` gets applied in several places. `displayLimitPostWarning()` can probably get deprecated.

Limits display (variable `$limit_warning`) happens in various templates in `admin-dev/themes/default/template/controllers/translations/helpers/view/` and `modules/blocklayered/views/templates/admin/`

**Comment by therampagerado** [comment]
Nice find. It's really annoying for newcomers, yes! It can get fixed once and for all but if somebody is willing to spend time fixing this for good will be nice.

**Comment by Traumflug** [comment]
Alright, we're close to a solution, thanks to @ziyaindia.

Review brought up the following questions:
1. https://github.com/thirtybees/thirtybees/commit/2d9b45b59072ee2bfba1761abdbc96bca42ca1cb#diff-f83d12ca4c36efb6fc6fce4102958187L109 and https://github.com/thirtybees/thirtybees/commit/2d9b45b59072ee2bfba1761abdbc96bca42ca1cb#diff-f83d12ca4c36efb6fc6fce4102958187L113: why was the value shaping removed?
2. https://github.com/thirtybees/thirtybees/blob/412d8f634ffa1f4ed28744b3149e73a2df41060b/controllers/admin/AdminTranslationsController.php#L1351 This code is inefficient. Saving 100 translations means reading and writing the file 100 times. Loading it once, then applying changes, then writing it would be much more efficient.
3. Same place: failure to write the file gets no longer detected. Such a test with appropriate error message was there before.
4. https://github.com/thirtybees/thirtybees/commit/2d9b45b59072ee2bfba1761abdbc96bca42ca1cb#diff-f83d12ca4c36efb6fc6fce4102958187R118 why is there a new input field? This used to work without such a field before. Translations get recognized by their MD5.
5. https://github.com/thirtybees/thirtybees/blob/412d8f634ffa1f4ed28744b3149e73a2df41060b/controllers/admin/AdminTranslationsController.php#L1346-L1347 these two lines most likely no longer work. Before, `$_POST` contained all translations, so just counting the array would give the number of all translations. Now, the same variable contains translations of one panel, which is an entirely different number. It looks like translations should get counted another way.
6. Identical translations get changed both, even if only one gets edited:
    Before:
    ![grafik](https://user-images.githubusercontent.com/318581/55578814-10d88380-5717-11e9-8776-a569640c22ab.png)
    Edit one translation:
    ![grafik](https://user-images.githubusercontent.com/318581/55578853-31a0d900-5717-11e9-8691-198498cb2840.png)
    After clicking _Save and stay_, both translations got changed:
    ![grafik](https://user-images.githubusercontent.com/318581/55578973-70cf2a00-5717-11e9-923f-9c19cf9e4ec0.png)
    This misbehavior might be a result of the change questioned in 4).
7. What's the point of _Save_ and _Save and stay_ buttons in the topmost panel now? It looks much like they have no longer a purpose and can get removed, together with the code handling them.

Other than that: good work! Changing translations actually works.

**Comment by Traumflug** [comment]
It looks much like there's not one translations template file, but four of them: https://github.com/thirtybees/thirtybees/tree/1.0.x/admin-dev/themes/default/template/controllers/translations/helpers/view

Which obviously means, all four need the same or a similar set of changes.

**Comment by ziyaindia** [comment]
Committed latest code related to issue-561.
Please re review.

**Comment by Traumflug** [comment]
Appears to work now. If there's something left or a regression was introduced, please don't hesitate to open another issue.
