### ISSUE TITLE
\translations\en\admin.php seems to break php opcache extension on PHP 7.2

### ISSUE THREAD

**Issue by doclucas** [thirtybees/thirtybees#562]
Just FYI for future reference.
As the title says, when having opcache enabled, using php 7.2, the BO is inaccessible and only 3 things I tried worked around that:
1) decrease the size of admin.php file
2) exclude (blacklist) admin.php from opcache
3) disable opcache completely (and losing its performance benefits).

**Comment by getdatakick** [comment]
I can't reproduce this problem. I also have many clients running on php 7.2 with opcache enabled without any issues. I think this can be closed
