### ISSUE TITLE
Quantity discount leads to wrong prices

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#574]
Reported here: https://forum.thirtybees.com/topic/1901/problem-with-price-on-product-page-after-upgrade-to-1-0-4

![](https://forum.thirtybees.com/assets/uploads/files/72/1531076258074e9be7d49-fec2-4887-a253-c453b00407bf-image.png)

Apparently introduced with *1.0.4* and still present in *1.0.6*.

**Comment by yaniv14** [comment]
Can't reproduce it with new installation (v1.0.6)

**Comment by getdatakick** [comment]
I've reproduced it on 1.0.6 - this is issue with theme, not with core, though. I've created new [issue](https://github.com/thirtybees/community-theme-default/issues/61) in community-theme and will submit pull request with fix soon
