### ISSUE TITLE
Link to BO directory is incorrect at the end of initial installation

### ISSUE THREAD

**Issue by doclucas** [thirtybees/thirtybees#577]
When completing the installation, the link to the BO takes the user to `/admin/`, which doesn't exist, instead of the correct BO directory.

[Screenshot](https://lh3.googleusercontent.com/-ymnkWtDietw/W3xVcQLe6BI/AAAAAAAAKrY/f799bbC-I0UsL3gC3rHq2hgcHqMDzwU6wCHMYCw/s0/chrome_2018-08-22_01-09-52.png)

**Comment by Traumflug** [comment]
How did you manage to get this? Intended behavior is that clicking this link gives the hint to remove the `install` folder and also adds this random text to `admin`, along with providing the new link.

**Comment by doclucas** [comment]
I believe you that that's the intended behavior. That's why I posted the issue.
Downloaded the latest package from here: https://thirtybees.com/download/ and extracted it.
Installed it as usual. When it was done, I clicked the link shown in the screenshot, which took me to `/admin/`.
Tested on WAMP in Windows and on Linux.
Did you try a new standard installation to see if you can reproduce this?

**Comment by Traumflug** [comment]
Doing an installation with the to be released package is part of the release making procedure, so yes, I tried. Apparently I have to try again.

Please note that Windows isn't supported. If it happens to work, fine. If it doesn't, patches get accepted, but not written by staff.

**Comment by doclucas** [comment]
About windows - as we already discussed on the other thread - understood.
That said, it was also tested on Linux, as I wrote.
Would love to hear if you can reproduce it. Thanks.

**Comment by Traumflug** [comment]
Just tried an installation with a package downloaded from https://thirtybees.com/download/.

During installation, when seeing the page in the opening post and even after clicking on the front office link I get this:
```sh
drwxr-xr-x   9 www-data www-data   4096 Aug 15 21:00 admin/
```
After clicking on the back office button on the same page I get this:
```sh
drwxr-xr-x   9 www-data www-data   4096 Aug 15 21:00 admin6325v3bpi/
```

And a page with a dialog like this:
 ![grafik](https://user-images.githubusercontent.com/318581/44462194-16fc7280-a614-11e8-825e-d85c3071b6ad.png)
URL shown in the browser's address bar is http://localhost/releasetest/admin6325v3bpi/index.php?controller=AdminLogin&token=25118f032c9ac0431c575e18df84c97a, so it's already loading from the renamed directory.

Obviously I've exercised this many many times, so I can't imagine what one could do differently to get this procedure into not working.

**Comment by doclucas** [comment]
Could be cookies issue. Closing.
