### ISSUE TITLE
Adding columns for product, category and cms pages

### ISSUE THREAD

**Issue by paintspec** [thirtybees/thirtybees#582]
Left nd right column possibility for product, category pages is still not standard in TB install. Some themes need this to customize these pages.
![columns](https://user-images.githubusercontent.com/30367310/44633669-97153600-a98e-11e8-8e61-7f5330bc7bef.png)

**Comment by paintspec** [comment]
I dont get this. I asked this already some time ago, and i got the answer it will be in the next release. In Prestashop these columns are added so i(and others) can easily set columns for these pages.

I add an image of the columns in Prestashop
![columns](https://user-images.githubusercontent.com/30367310/46914025-222aa980-cf98-11e8-9526-4492098cdb15.jpg)

**Comment by getdatakick** [comment]
It is, I can edit appearance of all these pages in tb 1.0.7:

<img width="600" alt="community-theme-default" src="https://user-images.githubusercontent.com/34651851/46914356-586a2800-cf9c-11e8-8cb9-fc714376c195.png">

**Comment by paintspec** [comment]
thanks! for some reason it didnt appear in my installation, after a fresh installation it works.
