### ISSUE TITLE
ganalytics: javascript using es6 features  

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/thirtybees#584]
Reported [here](https://forum.thirtybees.com/topic/1981/bug-version-3-3-5-throws-a-js-syntax-error-in-ie-11).

In modules\ganalytics\views\templates\hook\analyticsjs.tpl
```js
  function uuidv4() {
    return ([1e7]+-1e3+-4e3+-8e3+-1e11).replace(/[018]/g, c =>
      (c ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> c / 4).toString(16)
    )
  }
```
This function throws a syntax error in IE 11 which in my case blocked customers from checking out on IE 11

**Comment by doclucas** [comment]
@getdatakick 

Isn't your alternative implementation a good enough alternative to be merged instead?
```
function uuidv4() {
  var uuid = "", i, random;
  for (i = 0; i < 32; i++) {
    random = Math.random() * 16 | 0;

    if (i == 8 || i == 12 || i == 16 || i == 20) {
      uuid += "-"
    }
    uuid += (i == 12 ? 4 : (i == 16 ? (random & 3 | 8) : random)).toString(16);
  }
  return uuid;
}
```

**Comment by Traumflug** [comment]
Thanks, @getdatakick ! Picked this commit onto *master* in this module.
