### ISSUE TITLE
tbupdater: support auto-upgrade to newest version

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/thirtybees#585]
I know there is a work in progress on new updater, but that will take months until it's production ready. Meanwhile, merchants are required to upgrade manually. That's bad situation.

After discussion with @Dh42, I'm right now working on updating [psonesixmigrator](https://github.com/thirtybees/psonesixmigrator/) module so it can migrate prestashop 16 shops directly to the latest version of thirtybees. Under the hood, migrator module uses the very same mechanism as current [tbupdater](https://github.com/thirtybees/tbupdater) module. Since I'm already fixing this mechanism for migrator, it makes sense to port it to updater as well.

To make updater work again, this is what needs to be done:

1) add new entries to https://api.thirtybees.com/updates/channels/stable.json 
2) prepare ```fileActions``` file to describe changes. Here's example for [1.0.3](https://api.thirtybees.com/updates/packs/thirtybees-file-actions-v1.0.3.json) version
3) prepare database migration [scripts](https://github.com/thirtybees/patchscripts)

Version ```1.0.4``` introduced new statsmodule, so updater needs to delete old stats modules as well. That's something that can be done using ```fileActions``` file. Well, it should be possible, but there is a bug in ```tbupdater``` module itself that ignores all delete operations. So, we need to fix tbupdator module first. I've prepared the fix [here](https://github.com/getdatakick/tbupdater/commit/959fb03e6647e8402b3ffe627db7e29b3de4e1a1)

Fortunately, stable.json has a ```compatibility``` field that we can use to hide entries from older version of updater -- merchants will be able to update to 1.0.6 only after they update tbupdater module itself. 

## What next?

- I have already prepared new version of [stable.json](https://github.com/getdatakick/tb-api/blob/master/updates/channels/stable.json) file, as well as all the ```fileActions``` [files](https://github.com/getdatakick/tb-api/tree/master/updates/packs) to perform update to 1.0.6. 

- New json + zip files needs to be uploaded to ```api.thirtybees.com``` server -- it's safe to do even now, as the new entries will be ignored by current version of tb updater.

- we need to merge my changes to tb updater, build new package, and push it to users. @Traumflug, please review the [changes](https://github.com/getdatakick/tbupdater/commit/959fb03e6647e8402b3ffe627db7e29b3de4e1a1) 

- once merchants update tbupdater to new version, they'll be able to use it to upgrade thirtybees to 1.0.6 version.

## How to test locally

1) clone repository [getdatakick/tb-api](https://github.com/getdatakick/tb-api)
2) deploy the cloned repository to apache/nginx, under server name ```api.thirtybees.com```
3) add this entry to ```/etc/hosts``` file: ```127.0.0.1 api.thirtybees.com```
4) download new version of [tbupdater](https://github.com/getdatakick/tbupdater) and install it to your local tb installation
5) perform upgrade

**Comment by Traumflug** [comment]
Upgrading from *1.0.3* to *1.0.4* requires to run a certain SQL query. Module *tbupdater* supports this somehow, but the required files and their formats are unknown. This SQL query is the actual reason why no updater package was built for the *1.0.4* release.

These file action JSONs you built appear to be close to what's needed, well done. Still I see files like *README.md* or *buildmodule.sh* in there, which don't go into the distribution package. Inside `build.sh` one can find a mechanism to filter files. This should be used directly, not duplicated into another script. Adding a parameter to `build.sh` to exit after setting filters is possible, of course.

**Comment by getdatakick** [comment]
> Upgrading from 1.0.3 to 1.0.4 requires to run a certain SQL query. Module tbupdater supports this somehow, but the required files and their formats are unknown. This SQL query is the actual reason why no updater package was built for the 1.0.4 release.

It is known. This is done via file [thirtybees-extra-v1.0.4.zip](https://github.com/getdatakick/tb-api/blob/master/updates/packs/thirtybees-extra-v1.0.4.zip). That one is already prepared

>These file action JSONs you built appear to be close to what's needed, well done. Still I see files like README.md or buildmodule.sh in there, which don't go into the distribution package. 

README.md is part of the thirtybees-v1.0.4.zip. Actually, this list is compiled by diffing 2 distribution packages. If you take thirtybees-v1.0.3.zip and upgrade it to 1.0.4, you'll get the same content as if you unpacked 1.0.4 directly. 

If these files are not part of 1.0.5 / 1.0.6, they are marked for delete in the filesAction file for later version. So, if one upgrades from 1.0.3 directly to 1.0.6, these files will not be there in the end. 

This is correct behaviour.

> This should be used directly, not duplicated into another script. Adding a parameter to build.sh to exit after setting filters is possible, of course.

this initiative is to support auto-updater until *new updater* is implemented. It does not need to be perfect.

**Comment by Traumflug** [comment]
> Actually, this list is compiled by diffing 2 distribution packages.

Sounds good!

**Comment by therampagerado** [comment]
As I see it the future manual updates are files only and this is not difficult to do.

If this updater is not 1 click only like PS the users will find it as hard to use it as manually updating.

**Comment by getdatakick** [comment]
??? But it is 1-click only

**Comment by getdatakick** [comment]
Done. New version of tbupdater has been released, and api updated to include updates up to 1.0.6
