### ISSUE TITLE
Disable non thirty bees modules does not work

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/thirtybees#586]
**Disable non thirty bees modules** functionality does not work according to spec. The root cause  is in ```Module.php``` file,  method ```getNativeModuleList```. This method returns array of all modules in the system. That's obviously incorrect:

```php
    public static function getNativeModuleList()
    {
        return static::getNonNativeModuleList();
    }

    public static function getNonNativeModuleList()
    {
        return Db::getInstance(_PS_USE_SQL_SLAVE_)->executeS((new DbQuery())->select('*')->from('module'));
    }
```
Note that the return type is array of arrays, which is **not compatible** with ps16. The original return type was array of strings (module names). 

Because of incorrect return type, the code in ```Hook.php``` filters out **all modules** (kind of ironic considering that the ```getNativeModuleList()``` claims that every module in the system is native)

The end result is that every module in the system is blocked - this functionality totally useless.

This wouldn't be a big issue, because nobody has this option enabled in the store. It's used primarily to troubleshoot the issues with modules.

However, migrator module enables this option by default, so every migrated prestashop shop is useless. And that's really not a good first impression. 

The question is, how to fix this issue. Probably the best approach is to download (and cache) native module list from tb api - https://api.thirtybees.com/updates/modules/all.json

Any other idea?

**Comment by getdatakick** [comment]
possible fix in commit 11379d6c4f241178d0c4eb0facc4c7f784e4177c

**Comment by Traumflug** [comment]
`all.json` is more a list of all available modules, not necessarily only proven reliable ones.

There's also [default_modules.php](https://github.com/thirtybees/thirtybees/blob/1.0.x/install-dev/default_modules.php). This file was spun off of another file only a few weeks ago to make its list available for `build.sh`. This is a list of all modules going into the release package, so it's also a list of modules guaranteed to be up to date after installing a release.

This file is currently for the installer, only. It can get moved into `config/default_modules.inc.php`, of course. Sounds good?

**Comment by getdatakick** [comment]
sounds good

**Comment by doclucas** [comment]
> This wouldn't be a big issue, because nobody has this option enabled in the store. It's used primarily to troubleshoot the issues with modules.

True. And that's when shop owners may need to enable it, so the functionality is important.
Does your proposed commit (https://github.com/thirtybees/thirtybees/commit/11379d6c4f241178d0c4eb0facc4c7f784e4177c) fixes this in the core? Or only in the updater?

**Comment by getdatakick** [comment]
changes in 49a45ad297c5091e0642a245081d7ff379ab60b5
