### ISSUE TITLE
B2B siret/ape validation error

### ISSUE THREAD

**Issue by palo** [thirtybees/thirtybees#587]
Siret and ape validation is incorrect for portuguese and probably many other locations.
Portuguese format example bellow. 

Steps to reproduce:

1. Enable b2b mode;
2. Add a customer from backoffice;
3. APE "PT999999999"
4. SIRET "70220"
5. Save

Plase fix Class/Validate or make validation optional.

Thank you.

**Comment by Traumflug** [comment]
Thanks for the report.

Uhm. What is "Siret"? Or "ape"?

**Comment by doclucas** [comment]
![](https://lh3.googleusercontent.com/-0iZ5SdbQbQM/W4qON8K_HwI/AAAAAAAAKvs/Zb5fnmWiWBMBKfdAIAFJJ5HwsH1Zc_C_QCHMYCw/s0/chrome_2018-09-01_20-03-50.png)
The SIRET code (French: Système d’identification du répertoire des établissements), or SIRET number, is an INSEE code which allows the geographic identification of any French establishment or business.
APE - http://www.startbusinessinfrance.com/blog/post/tip-what-is-your-ape-code

**Comment by doclucas** [comment]
Related discussion:
https://www.prestashop.com/forums/topic/573067-vat-siret-ape-not-valid/
It seems adding a button that makes validation of these fields optional is indeed a good solution, or add modify the validation options to be compatible with other countries using these codes with different string formats.

**Comment by doclucas** [comment]
Not the most elegant solution, but suggested fix:
https://github.com/thirtybees/thirtybees/pull/588

**Comment by palo** [comment]
Still a bug in Thirtybees 1.1.0.
We really need a permanent fix for this.
Having a VAT field usable in any country is base requirement for an e-commerce platform.

**Comment by getdatakick** [comment]
siret/ape are not for VAT numbers

**Comment by palo** [comment]
Sure, but... Having an universal "vat number" tied to the address... 
While "siret/ape" (with validation for few countries) tied to the customer?

Also "siret/ape" shows right next to the company field that's ideal for b2b...
Maybe you'r overthinking this.
Its way better to make siret/ape validation optional. Just let the translation handle siret and ape to local equivalent name.

**Comment by palo** [comment]
Closing this as a bug because:
- This is more a feature request than a bug;
- Siret/ape fields can be removed from theme template;
- Validation can be overwritten if required for a b2b project; 

Still think it should be optional, because siret doesn't apply to many countries (only France?).

Please note that there are many theme and backoffice translation issues.
siret and even dni fields are getting translated as tax/vat numbers.

For clarification:
> SIRET code (French: **Système d’identification du répertoire des établissements**),
is an INSEE code ( "National Institute of Statistics and Economic Studies" French: **Institut national de la statistique et des études économiques**) which allows the geographic identification of any French establishment or business.
