### ISSUE TITLE
Thirtybees 1.0.6 won't run on php5 when Rijndael is used

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/thirtybees#593]
This is critical issue. 

PHP fatal error is thrown when Rijndael is used as a ciphering algorithm on server with php5:

```
PHP Fatal error: Call to undefined function random_bytes() in /home/sandbox/domains/sandbox.com/public_html/classes/Rijndael.php on line 77
```

This is caused because [random_bytes](http://php.net/manual/en/function.random-bytes.php) function exists on php7 only. 

How come it worked on php5 before? By sheer luck. That's because thirtybees includes package `defuse/php-encryption`, and one of its dependency is package `paragonie/random_compat`. This package provides polyfill for for `random_bytes` function. There is a special version [9.99.99](https://github.com/paragonie/random_compat#version-99999) of this package that does absolutely nothing, but is only installable on PHP 7. It seems that this version was installed for thirtybees, probably because php-cli used to run composer was on php7

**Comment by getdatakick** [comment]
On related note - I believe we should deprecate Rijndael altogether. Its implementation depends on `mcrypt` which is already deprecated in php7 and will be dropped in 7.2, there are warnings in debug mode.

**Comment by Dh42** [comment]
We likely should detect and set the best working one during upgrade and new installation. That would take a lot of the headache out.
