### ISSUE TITLE
Compatibility: _PS_CACHE_ENABLED_ is no longer used

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/thirtybees#596]
Prestashop 16 used `_PS_CACHE_ENABLED_` and `_PS_CACHING_SYSTEM_` constants to manage server-side caching. Thirtybees retrieves this info from configuration table instead, keys `TB_CACHE_ENABLED` and `TB_CACHING_SYSTEM`. 

Those constants are still defined, but with incorrect values - `_PS_CACHE_ENABLED_` is always false, and `_PS_CACHING_SYSTEM_` is set to `CacheMemcache`.

This may cause some  issues with modules. For example, thirtybees native tbupdater module uses `_PS_CACHE_ENABLED_` constant to check that caching is disabled ([see this code](https://github.com/thirtybees/tbupdater/blob/7809ec4e4e5619eae4bfe821a258e85197b73116/tbupdater.php#L606)). In this case, it allows tbupater to perform updates even with server-side caching enabled.

Another examples are [mercadopago](https://github.com/mercadopago/cart-prestashop/blob/91d0eb57ac6a10e7780cc58fdb0276a33b6784e0/v1.7.x/mercadopago/mercadopago.php#L1828) or [correios](https://github.com/dlanileonardo/correios/blob/d789d19b2dbfa5b51f31084eb1720f155deb34a9/correios.php#L374) modules. Impact here is not big - these modules simply won't cache their data. 

Shall we do anything about this, or do we consider this change safe?

**Comment by getdatakick** [comment]
google search within github does not reveal any other usage, so I guess this change is probably safe

**Comment by Traumflug** [comment]
Uhm, which change?

**Comment by getdatakick** [comment]
> Prestashop 16 used _PS_CACHE_ENABLED_ and _PS_CACHING_SYSTEM_ constants to manage server-side caching. Thirtybees retrieves this info from configuration table instead, keys TB_CACHE_ENABLED and TB_CACHING_SYSTEM.

This one

**Comment by Traumflug** [comment]
I think that's safe. Even if I personally prefer to save configuration stuff in files, like PS does/did (better performance, accessibility by FTP).

**Comment by getdatakick** [comment]
It does cause some [problems](https://forum.thirtybees.com/topic/2086/updater-v-1-3-3-thirty-bees-caching-features-are-disabled/5)

**Comment by getdatakick** [comment]
I've prepared a fix in
- 49aa7e656da76577d576f68178ab7948b72d6d67  
- 530711c8e79d71cbf602e8a2201ac74fe9ebcd00

**Comment by Traumflug** [comment]
Looks good after addressing the comment.

**Comment by getdatakick** [comment]
closed by 89610b2c667d6b648d224b9c2e035b91ac6b2fe2
