### ISSUE TITLE
Class 'NumberFormatter' not found in classes\Tools.php

### ISSUE THREAD

**Issue by Forforce** [thirtybees/ThirtyBees#6]
Exception in AdminProducts

**Comment by firstred** [comment]
`NumberFormatter` is part of the PHP `intl` extension: http://php.net/manual/en/book.intl.php

Most likely this isn't installed on your system. I recommend to have a look at the [requirements](https://github.com/thirtybees/ThirtyBees#requirements) and double-check if your system meet them.

**Comment by Forforce** [comment]
my fail. Sorry.

**Comment by firstred** [comment]
No problem and thanks for opening the issue. We've just updated the installation checks because of it: https://github.com/thirtybees/ThirtyBees/commit/43133955bdd2ee5acd4bd928b8e705d3e1dacb42
:smile:
