### ISSUE TITLE
Upgrading from PrestaShop makes Shop URL settings empty

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#604]
That's back office -> Preferences -> SEO & URLs, panel *Schema of URLs*

Two users reported these fields to be empty after migrating from PrestaShop:
- https://forum.thirtybees.com/topic/2035/wrong-url-resolution-after-customizing-seo-url-at-tb-1-0-6
- https://forum.thirtybees.com/topic/2024/making-prestashop-urls-compatible-with-tb-1-0-6/11

Known workaround: insert the default strings manually. They are:

- *Route to products*: `{categories:/}{rewrite}`
- *Route to category*: `{rewrite}`
- *Route to category which has the "selected_filter"...*: `{categories:/}{rewrite}{/:selected_filters}`
- *Route to supplier*: `{rewrite}`
- *Route to manufacturer*: `{rewrite}`
- *Route to CMS page*: `info/{categories:/}{rewrite}`
- *Route to CMS category*: `info/{categories:/}{rewrite}`

Also note that these routes are per-language, so they have to get set for each installed language (see language selector next to each field).

For those migrating from PrestaShop, original PS settings are probably better, to keep search engine rankings. These are:

- *Route to products*: `{category:/}{id}-{rewrite}{-:ean13}.html`
- *Route to category*: `{id}-{rewrite}`
- *Route to category which has the "selected_filter" ...*: `{id}-{rewrite}{/:selected_filters}`
- *Route to supplier*: `{id}__{rewrite}` (note the double underscore)
- *Route to manufacturer*: `{id}_{rewrite}`
- *Route to CMS page*: `content/{id}-{rewrite}`
- *Route to CMS category*: `content/category/{id}-{rewrite}`
- *Route to modules*: `module/{module}{/:controller}` (not applicable in thirty bees)

NOTE: while this is a single setting on PS, it's a per-language setting in thirty bees. Accordingly, set these values to all languages.

**Comment by mauroagr** [comment]
I upgrade it from 1.6.0.14 using the migration module  1.0.0 and test again with 1.0.1, and they clean the schemas.
But i add the original in both languages, and working fine.

**Comment by Traumflug** [comment]
Note: looking into realworld installations, these routes are often NULL. In this case a migration should insert PS' default settings. Else the shop switches from PS default to thirty bees default settings, which are different (see above).

These default settings can be found hardcoded in `classes/Dispatcher.php`.

**Comment by Traumflug** [comment]
It turns out this was a two-fold problem.

First issue was that PS doesn't store routes in the database at all, unless a merchant edits these rules. Without edits, it falls back to the hardcoded defaults in class Dispatcher. This should be fixed in the migrator module with this commit: thirtybees/psonesixmigrator@8c4185089ad9228139f59f5333b491d212c54575

Second issue was that PS has common schemes for all languages, while thirty bees has individual ones for each language. Accordingly I added a single->multi script to the v1.0.8 upgrade: https://github.com/thirtybees/thirtybees/commit/45be233f35a0995bcbf42d84535d0ef151a27244. This should fix shops which had manually edited rules before, which were not yet restored manually in thirty bees. This will also execute in the migrator after the v1.0.8 release, of course.

This is about the best way to heal this problem I can think of. Left in the dust are those which used default routes in PS and migrated to thirty bees before, and see now their URL schema field empty. They used PS defaults before the migration and thirty bees defaults after the migration, probably loosing some SEO ranking for a while.
