### ISSUE TITLE
Error when adding orders from the backend - An order has already been placed with this cart

### ISSUE THREAD

**Issue by dosbiner** [thirtybees/thirtybees#612]
forum post: https://forum.thirtybees.com/topic/2055/error-messages-when-adding-orders-from-the-backend

Adding orders from the backend works for some customers but for others not. I can’t figure out why it works only for some.

Error messages:

“An order has already been placed with this cart. This product cannot be added to the cart.” This is regardless of the product.

Each error message is specific to certain customers.

**Comment by getdatakick** [comment]
I'll split this to two separate issues, as those errors are probably not related

**Comment by getdatakick** [comment]
This particular error is fixed by 54c54a81e4f109e0efedecfe8e6c5d10bf03cbe1

**Comment by dosbiner** [comment]
you right, in my case I just got this error:
“An order has already been placed with this cart. This product cannot be added to the cart.”

===
oh my god, thats so fast as I typed this message this issue has been fixed :dancer:
