### ISSUE TITLE
Smarty upgrade - OPC checkout does not work

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/thirtybees#617]
The root cause behind this issue is the fix in the smarty engine. 

After the iteration over the list ends smarty will keep reference to the last item.

```php
{foreach $list as $carrier}
  ... 
{/foreach}
// at this point $carrier still references the last carrier in the $list
```

The problem is when $carrier variable already exists before {foreach} statement. 

In smarty 3.1.19, original value was overwritten. That was deemed as a bug, and was fixed in newer version. Now the original value is restored. That means:

```php
{assign var='carrier' value=1}

{foreach $list as $carrier}
  ... 
{/foreach}

// at this point $carrier contains value 1
```

There isn’t much we can do about this in general, if the template depended on the original behavior. 

We can only fix this particular issue with OPC --  `$carrier` variable is assigned in `ParentOrderController::_assignSummaryInformation` as a side effect. This variable is not used anywhere in the standard template. If we drop it, it will work again.

Note that this is a compatibility change itself -- there may be some template that actually uses this variable

**Comment by therampagerado** [comment]
Hello @getdatakick as you probably saw in 1.1.0 forum thread I have this issue and the proposed fix does not work for me. Which is very strange on its own but...

How I can apply the other fix you proposed - to rename $carrier to something else?

I can send you carrier-OPC.tpl from warehouse if you don't have it.

Thank you!

**Comment by getdatakick** [comment]
This issue was fixed already in both `niara` and `community-default-theme`
