### ISSUE TITLE
Adding producty to orders in back office removes them from stock twice

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#622]
See https://forum.thirtybees.com/topic/2110/bug-in-stock-to-add-product-in-backoffice

> I try to add product in backoffice, in a order but when i add the item…they reduct the stock two times.
> example:
> stock before add: 10
> add in order: 2
> expected stock result: 8
> result in TB: 6

There's also a solution (or workaround):

> I solved here in controller/admin/AdminOrderController.php
> Line 2429 (comment the line):

        // StockAvailable::updateQuantity($orderDetail->product_id, $orderDetail->product_attribute_id, ($orderDetail->product_quantity * -1), $order->id_shop);

> Line 2775:
> Before:

        // Update product available quantity
        StockAvailable::updateQuantity($orderDetail->product_id, $orderDetail->product_attribute_id, ($oldQuantity - $orderDetail->product_quantity), $order->id_shop);

> After:

        StockAvailable::updateQuantity($orderDetail->product_id, $orderDetail->product_attribute_id, ($oldQuantity - $productQuantity), $order->id_shop);

**Comment by 30knees** [comment]
@Traumflug This hasn't made it into the latest tb 1.0.8 yet, has it?

**Comment by getdatakick** [comment]
this was fixed in commit 45fe39bf0b82aedf0e570263447c8fb7cc306a58
