### ISSUE TITLE
Cache rights issues installing 1.07 on Windows

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/thirtybees#623]
When I installed 1.07 on Windows I got the error that I was not allowed to write a certain file in the cache. There was a button that allowed me to retry. I had to press this button about three times (each time seeing another file name) before I got the message that everything was ok and I could continue.

With previous versions I seldom had these problems (I saw them once on a 1.06). It is also a bit amazing to see any rights issues at all on a Windows installation - what suggests that it may be something different. Note that this is an ordinary up-to-date Windows 10 - the most common operating system in the world.
![tb107](https://user-images.githubusercontent.com/13930107/46755320-0dfb5980-ccc5-11e8-8b60-dfce7f45ea3a.jpg)

**Comment by musicpanda** [comment]
I hadn't seen this error with previous versions.

**Comment by Dh42** [comment]
We do not officially support windows because of these type of issues.

**Comment by musicpanda** [comment]
I noted that my re-installation of XAMPP had switched mod_auth_basic back on. I assume that that was the cause. So I will mark this as solved.
