### ISSUE TITLE
image issue on duplicate product in multistore

### ISSUE THREAD

**Issue by smarterweb** [thirtybees/thirtybees#624]
steps to reproduce (only in multishop) as reported in forge: http://forge.prestashop.com/browse/BOOM-4727
apparently related to: http://forge.prestashop.com/browse/BOOM-4001 (I have not tested this yet)

applies to latest TB 1.0.7

1. Create new product.
2. Copy it.
3. Change index.
4. Change name.
5. Save.
6. Publish.
7. Remove image (Dont remove row in database).
8. Save.
9. Refresh page.
10. Still have old image.
11. Upload new image.
12. Displays error message.
13. In table image_shop don't add new product.

**Comment by ksimunovic** [comment]
Tested on latest 1.1.x commit and seems that this is already fixed

**Comment by Traumflug** [comment]
Works just fine on v1.1.x here as well.

@smarterweb, if this issue comes up again, please don't hesitate to re-open this bug or open another one.
