### ISSUE TITLE
Problem choosing different theme in Dutch language

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/thirtybees#626]
I noted that when I select another theme the page refreshes but nothing happens. When I checked the javascript console I found the following error:
`Uncaught SyntaxError: missing ) after argument list`

When I looked in the sourcecode of the page in the browser I discovered the following:
`if(method == 'add')
   var name = prompt('Geef een naam aan deze shortcut', 'Thema's');`

"Thema's" is the Dutch translation of "Themes" and it looks like this is not escaped.

Searching for the original code I found the following at line 257 of Header.tpl of the default admin theme (admin\themes\default\template\header.tpl):
`if(method == 'add')
	var name = prompt('{l s='Please name this shortcut:' js=1}', '{$quick_access_current_link_name.0|truncate:32}');`

![themabug](https://user-images.githubusercontent.com/13930107/46904698-cc4af880-cee8-11e8-954f-36db359a3a29.jpg)

**Comment by Traumflug** [comment]
That's obviously a translation bug.

I can't find it in the official translations, though. Did you perhaps add this as a local translation?

It you want a single quote there, use ` or ´, but not '.

**Comment by getdatakick** [comment]
I beg to differ. This is bug in theme itself, smarty expression `$quick_access_current_link_name.0|truncate:32` should be escaped 

```
if(method == 'add') var name = prompt('{l s='Please name this shortcut:' js=1}', '{$quick_access_current_link_name.0|truncate:32}');
```

**Comment by musicpanda** [comment]
> I can't find it in the official translations, though. Did you perhaps add this as a local translation?

I didn't add any translations.

I have no idea where this translation comes from. I can't find it among the backoffice translations. I found in the backoffice translations four times the word "Thema's" but always in complex sentences - never stand-alone. The name comes somehow from the tabs. In AdminController.php you find at line 4186 
`        $this->context->smarty->assign(
            [
                'breadcrumbs2'                   => $breadcrumbs2,
                'quick_access_current_link_name' => $breadcrumbs2['tab']['name'].(isset($breadcrumbs2['action']) ? ' - '.$breadcrumbs2['action']['name'] : ''),
                'quick_access_current_link_icon' => $breadcrumbs2['container']['icon'],
            ]
        );`

**Comment by getdatakick** [comment]
Steps to reproduce:

1. go to `Administration > Menus`
2. change name of `Dashboard` to `Dash'board`
3. save & go to Dashboard page

Result:
Javascript error is thrown
