### ISSUE TITLE
DuplicateUrls not working with multistore

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/thirtybees#637]
The AdminController "AdminDuplicateUrls" has problems, to give correct results with multistore. 
![duplicate-url-bug](https://user-images.githubusercontent.com/15154932/47566000-92d3ad80-d92a-11e8-9140-d9e73a19430d.JPG)

In these screenshot I get multiple errors for categories. But these categories aren't even active for the shop. 

In addition there is a smilair issue for cms pages. For 3 different shop is use three different cms pages. The urls are like this:

- domain1.com/portal/zahlung (id_cms=1)
- domain2.com/portal/zahlung (id_cms=2)
- domain3.com/portal/zahlung (id_cms=3)

Since the ending uf the url is always /portal/zahlung they show up in the duplicate table. But they shouldn't! These cms pages are all only active for one shop. So there is no issue at all.

Edit: I am on version 1.0.3

**Comment by dosbiner** [comment]
what about force admin to select shop when access AdminDuplicateUrls Menu, something like this:
![2018-12-11_16-22](https://user-images.githubusercontent.com/6780215/49790526-060d7380-fd61-11e8-9795-4a2a4393789e.png)

but I don't know how to code
