### ISSUE TITLE
admin rtl css not being applied on installation with rtl country/language

### ISSUE THREAD

**Issue by yaniv14** [thirtybees/thirtybees#646]
https://github.com/thirtybees/thirtybees/blob/f0dc91ec291cc773c2f30ffa963712f3429c2cbe/install-dev/models/install.php#L722

@Traumflug 
When installing tb with country/lang that is RTL, the default admin css is being setup as standard ltr.
basically the line attached above should be:
````
$employee->bo_css = 'schemes_rtl/admin-theme-thirtybees_rtl.css';
````
wasn't sure whats the proper approach to fix it, so I am just raising an issue.

**Comment by Traumflug** [comment]
Yes, initially it gets set for LTR languages. But when such an employee gets added to the database https://github.com/thirtybees/thirtybees/blob/f0dc91ec291cc773c2f30ffa963712f3429c2cbe/install-dev/models/install.php#L729
this should get fixed:
https://github.com/thirtybees/thirtybees/blob/f0dc91ec291cc773c2f30ffa963712f3429c2cbe/classes/Employee.php#L304

It looks more like this is the problem, `_PS_ADMIN_DIR_` is undefined during installation: https://github.com/thirtybees/thirtybees/blob/f0dc91ec291cc773c2f30ffa963712f3429c2cbe/classes/Employee.php#L368-L373

I'll look up when this part got introduced and what the purpose might be.

**Comment by Traumflug** [comment]
This snippet was introduced before PS 1.5, so no hint on its purpose by the commit message available. No other reasons found either, installations work just fine without it. Accordingly put the removal to branch *1.0.x* to get it into the next release.

Does this fix solve the issue? You probably know better how a RTL back office should look like.

**Comment by Traumflug** [comment]
I see. Needs more work. Apparently `updateTextDirection()` doesn't work as it should.

**Comment by Traumflug** [comment]
Just saving an employee's preferences appears to switch text direction correctly, so there's at least a workaround, no need to mess with the database or CSS files.

**Comment by Traumflug** [comment]
Alright, next round, see branch [*markus*](https://github.com/thirtybees/thirtybees/commits/markus).

This should not only fix text direction on installation, but also allow to switch text direction in other themes than the Bootstrap (formerly default) theme.

As dessert topping, theme selector's *Default* is now actually the default theme, which happens to be the thirty bees theme. And displayed theme names lost their *_rtl* suffix.

**Comment by yaniv14** [comment]
Just checked your changes and everything is working perfect.
