### ISSUE TITLE
Use PrestaShopLogger instead of Logger alias

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/thirtybees#652]
`PrestaShopLogger` class have alias `Logger` implemented in `PrestaShopAutoload` -- [here](https://github.com/thirtybees/thirtybees/blob/e552f32d07ef1bf72c7d21dc8b4cf8916651e9c1/classes/PrestaShopAutoload.php#L53) and [here](https://github.com/thirtybees/thirtybees/blob/e552f32d07ef1bf72c7d21dc8b4cf8916651e9c1/classes/PrestaShopAutoload.php#L221).

Core code uses mainly alias class `Logger` - for example [here](https://github.com/thirtybees/thirtybees/blob/e552f32d07ef1bf72c7d21dc8b4cf8916651e9c1/classes/controller/AdminController.php#L1229). It should use `PrestaShopLogger` instead. 

Using alias `Logger` can lead to strange behaviour when some third party module includes `Logger` class of their own. This problem was reported in this [thread](https://forum.thirtybees.com/topic/2206/fatal-error-call-to-undefined-method-logger-addlog-in-home-shopboot-domains-boottrailers-nl-public_html-boot-classes-controller-admincontroller-php-on-line-1336).

If core code used `PrestaShopLogger::addLog` instead of `Logger::addLog`, this issue would not occur.

There's also a possibility to rename PrestaShopLogger to something more thirtybees, is ThirtybeesLogger, and declare PrestaShopLogger as alias for this class.

**Comment by Traumflug** [comment]
Not too keen on this. Class Logger has a long history, before introduction of this alias in January 2014 (51c29a63a22a140a1ad2015a6360a32da87998ce, PS 1.6.0.3), a class of this name was implemented directly. To me it's unclear how this module ever worked. Maybe in PS before v1.5, I don't have a history reaching further back handy.

If we start to change core code to please broken modules we might raise expectations thirty bees can't fulfill ("My XYZ module doesn't work, thirty bees should fix it").

**Comment by getdatakick** [comment]
When I thing about it, this is actually a generic problem - there's a race condition with class definition. 

For example, if some module declares it's own class `Category`, and this module is loaded soon enough (for example is hooked to `moduleRoutes`), then this custom class will be used by the thirtybees core instead of standard Category class. 

Unfortunately there won't even be `PHP Fatal error:  Cannot declare class` error, because autoloader will just never be used for this class. There will only by cryptic fatal error somewhere down the line, complaining about calling undefined method, etc.

The only thing that comes to mind is to perform some static analysis of module prior it's installation, and warn / block module if it contains class with conflicting name.

**Comment by Traumflug** [comment]
> The only thing that comes to mind is to perform some static analysis of module prior its installation, and warn / block module if it contains class with conflicting name.

True. The oldest enhancement issue here goes into this direction: https://github.com/thirtybees/thirtybees/issues/44

**Comment by Traumflug** [comment]
There's another snippet in the [discussion](https://forum.thirtybees.com/topic/2206/fatal-error-call-to-undefined-method-logger-addlog-in-home-shopboot-domains-boottrailers-nl-public_html-boot-classes-controller-admincontroller-php-on-line-1336/7):

> "I have checked it. The problem relates to TB. TB is using Logger class, but this class and PHP file does not exists. "
>
> I checked the TB core files, they have changed the file : classes/controller/AdminController.php
and changed “Logger” into “PrestaShopLogger”
