### ISSUE TITLE
Copying themes in back office apparently doesn't work

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#655]
Somebody tried and ended up in a mess: https://forum.thirtybees.com/topic/2223-2223/selecting-a-new-theme-copied-from-the-default-doesn-t-work

Options probably include to either fix this or to remove this rarely needed feature. Simple workaround is to copy files by shell/FTP, which every merchant can do.

**Comment by mariusherea** [comment]
The workaround doesn't work. Duplicating the directory and changing the community-theme-default name in config.xml with the new name of the theme and activating it from admin leads to the same problems. All files, except the Docs folder, get deleted.

**Comment by ksimunovic** [comment]
@Traumflug Your latest commit was working great for me file copying wise, but I was still getting the UI error about incorrect config.xml, which this commit fixes

**Comment by Traumflug** [comment]
Good step into the right direction! When copying a theme "Markus" into directory _markus/_ I still get this diff between old and new config.xml (manually tweaked here):
```diff
-<theme version="1.1.0" name="Niara" directory="niara">
+<theme version="1.1.0" name="Markus" directory="niara">
[...]
   <variations>
-    <variation name="Niara" directory="niara" responsive="1"
+    <variation name="Niara" directory="niara" responsive="1"
[...]
```
... which means, directory doesn't get adjusted yet and variation isn't updated either. Yes, this variation is duplicate data. Has to be kept for historical reasons for the time being.

**Comment by Traumflug** [comment]
Found part 2 and added part 3 myself. Which means: @mariusherea, this branch is listed in Core Updater, channel _Bleeding Edge_ now and ready for testing.

**Comment by Traumflug** [comment]
Moved to 1.1.x.

If there's something left, please don't hesitate to re-open this issue.
