### ISSUE TITLE
Module dashtrends date misalignment

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#664]
See https://forum.thirtybees.com/topic/2231-2231/error-in-dashtrends

Obviously, setting a time span from date X to date Y doesn't include date Y, but stops at 0:00 h of date Y. It should stop at 24:00 h of date Y instead.

![](https://i.snag.gy/Dsga4i.jpg)

**Comment by ehohetraw** [comment]
i think this can be closed?
