### ISSUE TITLE
Class ShopMaintenance should learn to clean themes/XXX/cache/

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#771]
See https://forum.thirtybees.com/topic/2243/theme-cache-is-huge

With back office -> *Advanced Parameters* -> *Performance* -> *CCC*: *Keep JS and CSS files * turned on, thirty bees keeps older CCC compilations to satisfy search engines. However, after like a month, they're probably no longer needed, search engine spiders should have visited the shop during this time and recorded the newer compilations.

**Comment by therampagerado** [comment]
This is a very positive enhancement to be implemented. My website is not very popular but in 1 month it generates up to 1 gb of cache there (depending on traffic).

I would love to see a setting where admin can set number of days for which we keep both css and js cache in this folder. If older than xx days delete during manual cache deletion in ShopMaintenance.

**Comment by kintaro1981** [comment]
XX days or a max size
