### ISSUE TITLE
Filesystem abstraction

### ISSUE THREAD

**Issue by guestisp** [thirtybees/thirtybees#775]
Would be possible to use Flysystem to abstract the TB filesystem layer when managing user contents like images and so on?

This allow TB to be scaled horizontallly on any cloud provider.

If there are chance to get this merged, we can work on it as we need a way to make TB 12factor compliant and at least move all user assets to a Cloud storage. Currently Is not possible

**Comment by Traumflug** [comment]
Merge what? Is see neither code not a link to code. Please use thirty bees' forum for questions and discussions: https://forum.thirtybees.com/

**Comment by guestisp** [comment]
Ok

**Comment by Traumflug** [comment]
Discussion see https://forum.thirtybees.com/topic/2255/abstract-filesystem-layer
