### ISSUE TITLE
Dashboard sales stats graph - net profit is wrong

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/thirtybees#779]
When you click on settings and set your average gross margin % the formula is wrong....

If I set 30 % the stats module calculate that the profit is 70%. If I want the graph to show to correct amount I have to imput 70% margin (I hope someday I would be able to sell with such margins but not today... :P )

**Comment by Traumflug** [comment]
Is this on the Dashboard page or on the Statistics page? These are two distinct modules.

**Comment by therampagerado** [comment]
Dashboard graph, the main one.

**Comment by Traumflug** [comment]
Does this happen in demo mode as well? For testing I've set average gross margin to 100%, but sales and profit are quite different:

![grafik](https://user-images.githubusercontent.com/318581/48484188-c44ae500-e815-11e8-89aa-cbc0ad60c391.png)

**Comment by therampagerado** [comment]
![image](https://user-images.githubusercontent.com/11251370/48484832-e34e7480-e81f-11e8-8137-42a8aa093fac.png)
![image](https://user-images.githubusercontent.com/11251370/48484860-f6f9db00-e81f-11e8-9c89-ffae02bd7fa7.png)

Even. This is without additional deductions.

**Comment by therampagerado** [comment]
@Traumflug did you manage to reproduce it?

**Comment by Traumflug** [comment]
Not yet. As you found a workaround other bugs appear to be more important.
