### ISSUE TITLE
Cannot set Favicon metas for each shop on mutistore

### ISSUE THREAD

**Issue by dosbiner** [thirtybees/thirtybees#780]
I want to set PWA on my site using https://www.pwabuilder.com
this can be done by editing favicon metas, but I cannot set for each shop on multistore.
is it posible to improve this for multistore?

**Comment by dosbiner** [comment]
I fix this https://github.com/thirtybees/thirtybees/pull/781

**Comment by Traumflug** [comment]
Kudos for those fixing the issues they report!

Fix found to work just fine, picked to branch *1.0.x*. Thank you very much!
