### ISSUE TITLE
PHP 7.x compatibility in method setWsTags in class Product

### ISSUE THREAD

**Issue by morgan-enetb** [thirtybees/thirtybees#785]
Array to string conversion in methode setWsTags() :

if ($ids) {
$sqlValues = '';
$ids = array_map('intval', $ids);

=> 

if ($ids) {
$sqlValues = [];
$ids = array_map('intval', $ids);

**Comment by Traumflug** [comment]
Thank you very much for the contribution!

Looks plausible, so picked to *1.0.x*.
