### ISSUE TITLE
id_lang field in ObjectModel contains array value

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/thirtybees#786]
ObjectModel class contains `id_lang` field that should either be set to **null**, or to numerical value for specific language id. That's how it always was in ps16. 

Commit a01052733016a11f28c8f20279f87e65fee18909 changed visibility of this field from protected to public. This had unfortunate side effect - when loading translatable fields from database, id_lang field now passes [property_exists condition](https://github.com/thirtybees/thirtybees/blob/13fe22712bf43d0a912cb16fb2625e80740a8f5e/Adapter/Adapter_EntityMapper.php#L89), and therefore is loaded and treated as a translatable field. It can now be array map from number -> number.

For example
```
$idLang = (new Country(1))->id_lang; 
``` 
resolves to `null` on ps16. In thirtybees, the same code resolves to ```array(1 => 1, 2 => 2)```

This issue was discovered later, but it was not fixed properly -- see commit 5ef997fa9cebcb9570e17c527d192ba442250924. That fix only masked the problem, but the issue is still there and causes errors elsewhere. 

Note: this problem is a root cause for a compatibility issue raised in this [forum thread](https://forum.thirtybees.com/topic/2289/think-we-will-have-to-leave-thirty-bees-no-avanced-seach-4-compatability)

**Comment by getdatakick** [comment]
Similar problem is with ```id_shop``` field, if lang table contains this column

**Comment by Traumflug** [comment]
Nice catch!

Thinking of a proper fix makes me scratch my head. For example, I'd consider this part:

> when loading translatable fields from database, id_lang field now passes property_exists condition, and therefore is loaded and treated as a translatable field.

is something I'd recognize not as unfortunate, but as expected. Translatable fields should be treated as translatable fields, obviously.

Also, countries can have multiple languages (Switzerland, Canada, ...), so the given code snippet should be able to deal with an array anyways.

Clearly unfortunate is the incompatibility with PS modules, of course. Do you already have an idea on how to get algorithms into a proper shape while keeping compatibility with PS? Like making such fields non-translatable in the database?

**Comment by getdatakick** [comment]
id_lang are not strings, and as such should definitely not be translatable :)

The behaviour of translatable fields is following:

1. creating object with specific language: all translatable fields are strings, id_lang = number
```php
var_dump(new Country(1, 1));

// output looks like this:
Country Object
(
    [id] => 1
    [name] => Germany,
    [id_lang] => 1
)
```

2. creating object without language: all translatable fields are represented as arrays, id_lang should be null (at the moment it isn't)
```php
var_dump(new Country(1));

// output should look like this:
Country Object
(
    [id] => 1
    [name] => Array
        (
            [1] => Germany
            [2] => Germany
        )
    [id_lang] => null
)

// although due to this bug it looks like this:
Country Object
(
    [id] => 1
    [name] => Array
        (
            [1] => Germany
            [2] => Germany
        )
    [id_lang] => Array
          (
            [1] => 1
            [2] => 2
        )
)
```

**Comment by getdatakick** [comment]
@Traumflug please review the fix. I believe this should work

**Comment by Traumflug** [comment]
Thanks for the explanation. Picture gets clearer now.

**Comment by Traumflug** [comment]
Looks good. Applied my nitpicking and picked it to *1.0.x*. Thank you very much.
