### ISSUE TITLE
Some price rounding issue

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#795]
Lots of description, still unclear which rounding types (back office -> *Preferences* -> *General*) get used:

https://forum.thirtybees.com/topic/2349/wrong-tax-calculation

**Comment by getdatakick** [comment]
### Reprosteps:

1. Preferences > General, set
    * Round mode = Round up away from zero
    * Round Type = Round on each item 
    * Number of decimals = 2

2. Edit some product A and set
    * Pre-tax retail price = 9.55
    * Tax Rule = *any rule with 22% tax*

3. Edit customer group Visitor, and add 5% discount
4. Go to front office, and add product A to cart, quantity = 24
5. Go to Check out

#### Expected results:
* Unit price = 9.07  (9.55 - 5% == 9.0725, round(9.0725) = 9.07)
* Line total = **217.68** (9.07 * 24 == 217.68)
* Total Tax = **47.89** (22% of 217.68)

#### Actual result
* :white_check_mark: Unit price = 9.07
* :x: Line total = **217.74** (9.0725 * 24 == 217.74)
* :x: Total Tax = **48** (24 * round(22% of 9.0725) = 24 * round(1.99595) = 24 * 2 = 48)

### Screenshot:
![image](https://user-images.githubusercontent.com/34651851/49944992-100fad80-feec-11e8-8c97-e6822da85c2f.png)

**Comment by getdatakick** [comment]
The first problem - Line total - can be fixed by using correct rounding precision [here](https://github.com/thirtybees/thirtybees/blob/e0647c10d06b74803c48dcba599fd4022170b292/classes/Cart.php#L513). But first we should investigate why @firstred changed it in the first place (commit 50081cd8c0b57c00f5a7d974d5ed69244e9dba81).

For the second problem I haven't found a solution yet.

**Comment by guestisp** [comment]
> The first problem - Line total - can be fixed by using correct rounding precision here. But first we should investigate why @firstred changed it in the first place (commit 50081cd).

Exactly. Why it was hard-coded to 6 regardless what is choosen from the backoffice ?

**Comment by Traumflug** [comment]
Update:

Over the last two days I reviewed this rounding business. There were lots of hardcoded values rather than usage of constants. Problem with the rounded line was that it rounded to the wrong precision. PS used the same value for `_PS_PRICE_DISPLAY_PRECISION_` and `_PS_PRICE_COMPUTE_PRECISION_`, which led to a number of confusions without being noticed. This part should be done and will get committed before too long.

The tax thing is more tricky. Products store their prices always with high precision. Which means, taxes have to get re-calculated after rounding, depending on what gets displayed. Currently taxes get fetched from the product and rounded after that.

Next task will be a review of orders. They apparently have their own calculations, which isn't ideal. Turning a cart into an order should take prices from the cart as-is, to avoid any potential for deviations from the cart.

**Comment by Traumflug** [comment]
A cigarette and a tomato juice later, there was suddenly this:

![grafik](https://user-images.githubusercontent.com/318581/52678781-2b6e5780-2f33-11e9-97cc-1d0c6370464a.png)
 
:v:

**Comment by Traumflug** [comment]
All commits on branch *1.0.x* now, this issue should be solved.
