### ISSUE TITLE
Priview url shows old product after duplicating product even though ID is different

### ISSUE THREAD

**Issue by gingerling** [thirtybees/thirtybees#799]
I am adding new products by the same manufacturer to my store, so rather than starting from scratch I used the duplicate function. 

I have edited the product name, images, descriptions etc on the duplicate product.

The problem is that the preview buttons on the new product take me to the old product. 

This is the preview url of the original product, which is now published: 

https://www.ethicalpets.co.uk/soopa-raw-chews

This is the preview URL given on the new product which is unpublished.

https://www.ethicalpets.co.uk/soopa-raw-chews?adtoken=be23e1b6e21fe9994a3474eb9b6cd9a7&ad=login&id_employee=2

The new product is called Soopa Dental Sticks and has a different ID number (213, the original product is 210)

**Additional info**

I have re-booted and tried in a private window, I don't believe it's a cache issue.

If I recall I used the duplicate button at the top of the original product page in the back office to create the new product, but there is also a drop-down option on the catalogue page from the edit button.

All three preview buttons (catalogue list, top of product page in back office and button near top of product page in back office) do the same thing.

**Comment by gingerling** [comment]
I briefly published the new product and it seems to work fine on the front of store but the preview link did not update yet.

**Comment by gingerling** [comment]
Using the clear cache button on the performance page did not solve the problem. Over to you guys now! :)

**Comment by Dh42** [comment]
Are you changing the url rewrite? I can see that being an issue if you do not change the rewrite.

**Comment by gingerling** [comment]
Where is that setting? Can't find it

**Comment by Traumflug** [comment]
I just tried and indeed, duplicating a product doesn't change the URL, so a duplicate URL is the result. It should be visible with back office -> *Preferences* -> *Duplicate URLs*. (If you have no such menu item there, see https://github.com/thirtybees/psonesixmigrator/issues/15#issuecomment-433379450 or wait for release *1.0.8* to appear in the update module).

**Comment by Traumflug** [comment]
I think @Dh42 means the *Friendly URL* setting here on the product editing page:

![grafik](https://user-images.githubusercontent.com/318581/50056839-e0b6a600-0162-11e9-98bc-6107806b0080.png)

**Comment by gingerling** [comment]
So to clarify, is editing the friendly url the solution to this problem?

**Comment by Traumflug** [comment]
Likely, yes. Having the same friendly URL twice results in the same URL for two products, which can't be good.

**Comment by gingerling** [comment]
yes, I found clicking the "generate" button next to the friendly url fixes the issue. Suggest that this eventually becomes part of the duplicate process or part of the product renaming process (like with a wordpress page/posts) but in the mean time a popup info box saying:

"Don't forget to change the friendly url" when you either clone a product or change the product name"

perhaps? Sorry I'm not a developer so I can't fix this myself :) Would if I could guys! :)

**Comment by Traumflug** [comment]
I've recorded an enhancement request as issue #801, so this issue is solved?

**Comment by gingerling** [comment]
Yep! Great, thanks!
