### ISSUE TITLE
Return number in Return Merchandise Authorization (RMA)

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#804]
The Return number only has the number, for instance # 000002 instead RE#000002 or #RE000002 or RE000002.

Please check the attached pdf.

[ReturnNumberInRMA.pdf](https://github.com/thirtybees/thirtybees/files/2688465/ReturnNumberInRMA.pdf)

**Comment by NemoPS** [comment]
Fixed: https://github.com/thirtybees/thirtybees/commit/ea8b09d9f7bdf67bef7c0ddaee223e61ef29ecf7
