### ISSUE TITLE
Configuration - incorrect escaping 

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/thirtybees#807]
This is injection by commit 12d2d6c5f9f8c6d821603fba011e9de03eb1f70d

Basically, this commit broke following assumption:

```
Configuration::updateValue($key, $value);
$value == Configuration::get($key);
```

as demonstrated in this [test](https://github.com/thirtybees/thirtybees/blob/e03617e6fce78298dfd08865d199bce436271e95/tests/integration/ConfigurationCoreTest.php). I've deliberately submitted the test even though it's failing, as this issue should be addressed promptly. 

@Traumflug, I'll keep the fix on you, since I don't know much about the reasons behind this change.

**Comment by Traumflug** [comment]
Hmm. This commit fixed another case, so a simple revert won't work. It's not all to obvious, the actual change of this commit is that `Configuration::set()` gets called with a `pSQL()'d` value.

**Comment by Traumflug** [comment]
Moved the new test to topic branch *configuration*.

**Comment by Traumflug** [comment]
Without having time to investigate this, I think the commit found guilty just uncovered other behavior. This assumption:
```php
Configuration::updateValue($key, $value);
$value == Configuration::get($key);
```
was only true on the same request before the commit, but not on the next request. Which means, just reloading a page using a setting subject to `pSQL()` changed the displayed data. With the commit, this change happens immediately.

**Comment by getdatakick** [comment]
pSQL function do:
1. escape value to prevent sql injection, ie: `let's escape this` ---> `let\'s escape this`. This escaping has no impact on the value when read back from db. 
2. sanitize value - strips tags, replacing new lines with <br> (unless the $html = true)

The escaping aspect is the reason why we can't call `Configuration::set` on value processed by this function. 

Example:
```php
$input = "<h1>It's a test</h1>";
$val1 = pSQL($input);                    // It\'s a test
...
$val2 = Configuration::get($key);        // It's a test
```

Fix should be like this: 
1) sanitize value in Configuration::updateValue function before calling pSQL --> these values should be passed to Configuration::set
2) call pSQL with $html = true to avoid further sanitization ---> these values should be used to update values in db
