### ISSUE TITLE
Favicon and phone icon

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#818]
Preferences => Themes => YOUR CURRENT THEME => ICONS
In Version 1.0.8 the expression “Favicon and phone icon” it is duplicate. Please check the attach pdf.
I think in the second “Favicon and phone icon” missed the TB icon.

[Favicon and phone icon.pdf](https://github.com/thirtybees/thirtybees/files/2777186/Favicon.and.phone.icon.pdf)

**Comment by eschiendorfer** [comment]
I can't confirm this bug anymore. Maybe it the favicon was deleted during an update in the past.
I have recently uploaded new icons and this problem doesn't arise for me.

**Comment by therampagerado** [comment]
Same here, unable to replicate this.
