### ISSUE TITLE
Test email and PHP 7.3 

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#820]
Thirty Bees version 1.0.8 on PHP 7.3 when we do “Advanced Parameters/E-mail/Test your email configuration” we get the: 
“Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/classes/Tools.php on line 5303”.
We didn’t receive the email.

Our temporary solution was decreases from PHP 7.3 to PHP 7.2 and after we did “Advanced Parameters/E-mail/Test your email configuration” we got:
“A test email has been sent to the email address you provided.”
And we received the test email.

**Comment by getdatakick** [comment]
fixed by 990d56934009843a96b9d60a8b62d7645e090128
