### ISSUE TITLE
Shop email configuration 

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#826]
The TB only have one shop email to send the emails.
This is configured in two places “Preferences/Store Contacts/Shop email” and “Advanced Parameters/Email”.

Problem: At “Advanced Parameters/Email” when select “Set my own SMTP parameters (for advanced users ONLY)” the “SMTP username” is a blank field to complete by user but I think this is wrong because the field is the same of the shop email in the “Advanced Parameters/Email”. If the client set different emails, the smtp email don’t work. 

Solution: The “SMTP username” not be a blank field but be fielded with a link to the shop email. 
Please check the attach.

[Shop email configuration.pdf](https://github.com/thirtybees/thirtybees/files/2799627/Shop.email.configuration.pdf)

**Comment by Traumflug** [comment]
Uhm. An email address and a SMTP user name are two different things. While many email providers (like Yahoo) use an address also as SMTP user name (easy to remember!), just as many don't. For example, all the ~10 email addresses at jump-ing.com use the same SMTP account and hence the same SMTP user name (which matches none of the email addresses).

**Comment by Dh42** [comment]
AWS and every other api system like Mandrill use a api user name that is not remotely like the address too. So that would not work.

**Comment by Jorgemgm** [comment]
Ok, so close the post.
