### ISSUE TITLE
Geolocation updating to new free database type

### ISSUE THREAD

**Issue by toplakd** [thirtybees/thirtybees#828]
As known, Maxmind discontinued the free legacy Databases, and is now offering GeoLite2 Free Downloadable Databases.

Can this changes be adopted to thirty bees rewriting the old geolocation or with help of a new module that would read the new database files?

Datakick is leaning towards removing this from core, and replacing it by set of hooks and new module for GeoLite2 free databases so one can choose if would use the thirty bees geolocation or geolocation from some other modules/providers.

Thank you. Dejan

**Comment by therampagerado** [comment]
What are you using geolocation for with TB/PS?

**Comment by toplakd** [comment]
As I do have to display prices with Tax included for European Union customers, as my shop is based in Europe. But main sales go outside EU and therefore they should see prices without tax.

**Comment by therampagerado** [comment]
Can this be acheived with the inbuild geolocation? I'm doing the same but the prices change only when the customer registers shipping address outside EU.

**Comment by toplakd** [comment]
This is working with inbuilt geolocation. But the Free legacy databases were just discontinued.
Maxmind is now offering new free GeoLite2 databases for Country resolving.

**Comment by toplakd** [comment]
The Old Legacy Databases are not available for download anymore, and they will soon be outdated.

**Comment by Traumflug** [comment]
As a workaround, there's a tool to convert newer databases to the old format:

https://forum.thirtybees.com/topic/3097-old-maxmind-geo-db/?tab=comments#comment-28129

**Comment by Traumflug** [comment]
Googling around a bit I found two free databases:
- [IP2Location](https://lite.ip2location.com/ip2location-lite)
- [DB-IP](https://db-ip.com/db/lite.php)
- - -
- Both are static, not requiring to contact some online service, so they're fine with privacy.
- Both require to display a backlink with some text, which should be doable.
- Both allow to upgrade to more accurate, paid versions.

It looks like a solution without requiring merchants to buy some license is at least possible.

**Comment by toplakd** [comment]
Maxmind GeoLite2 are also free, but are in different format than old ones.

**Comment by Traumflug** [comment]
True, GeoLite2 databases are another option. I read this "discontinued" header, but this applies only to GeoLite, without '2'.

**Comment by Traumflug** [comment]
Now we just have to find somebody writing the code :-)
