### ISSUE TITLE
.htacces woff2 fonts

### ISSUE THREAD

**Issue by toplakd** [thirtybees/thirtybees#830]
Generate .htaccess creates:
     ExpiresByType font/woff2 "access plus 1 year" 
Google marks Cache TTL for that as 0

But following does work with google:
     ExpiresByType application/font-woff2 "access plus 1 year"

**Comment by Dh42** [comment]
This is actually correct, unfortunately it is a server set up issue you have. You can find more information here, https://stackoverflow.com/questions/28235550/proper-mime-type-for-woff2-fonts But basically you need to change the mime type on your server.
