### ISSUE TITLE
Deal with empty tags on CSV import

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#833]
See https://forum.thirtybees.com/topic/2537-update-stock-tags-and-weight-from-csv/?tab=comments#comment-25000

> Add this code to the \controllers\admin\AdminImportController.php
```
else{
    unset($product->tags[$key]);
}
```

![](https://forum.thirtybees.com/uploads/monthly_2019_01/Screenshot00874.jpg.11714af9bfe079a29caeb0ce16d4c3df.jpg)

**Comment by getdatakick** [comment]
closed by commit 0206045535ca5b6f98947e8244b5c913da854004
