### ISSUE TITLE
Sign up for our newsletter

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#835]
Preferences => Customers => Enable newsletter registration => NO

The field "Sign up for our newsletter!” still displayed in front office when the client creates an account. Please check the attach pdf.

[Sign up for our newsletter.pdf](https://github.com/thirtybees/thirtybees/files/2827873/Sign.up.for.our.newsletter.pdf)

**Comment by SLiCK-303** [comment]
Open controllers/front/AuthController, find these two lines:
        $newsletter = Configuration::get('PS_CUSTOMER_NWSL') || (Module::isInstalled('blocknewsletter') && Module::getInstanceByName('blocknewsletter')->active);
        $this->context->smarty->assign('newsletter', $newsletter);

and replace with this line.
        $this->context->smarty->assign('newsletter', (bool) Configuration::get('PS_CUSTOMER_NWSL'));

**Comment by NemoPS** [comment]
Fixed https://github.com/thirtybees/thirtybees/commit/a34c564782aa2632c2a7d8194f28b0043a2763e5
And https://github.com/thirtybees/thirtybees/commit/8f41864b3fcb28407a8f54f07dda06e637536b71
