### ISSUE TITLE
OPC Login does not refresh NAV User info

### ISSUE THREAD

**Issue by toplakd** [thirtybees/thirtybees#836]
When login/register is made from OPC, the User information in header is not refreshed and stil shows Sign in until new page is visited or f5/refresh is made.

**Comment by toplakd** [comment]
Adding the verry bottom line to order-opc.js seems to solve the problem in all the browsers i have available to test.

            // update token
            static_token = jsonData.token;
            updateNewAccountToAddressBlock(that.attr('data-adv-api'));
            $("#header-navbar-right-nav").load(" #header-navbar-right-nav > *");

**Comment by NemoPS** [comment]
Implemented https://github.com/thirtybees/community-theme-default/commit/a4b9dffa6c411a6151caf311bdf63bd8d12dba5a

Thanks!
