### ISSUE TITLE
When the admin disables one state

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#838]
Before the customer create an account:
- If the customer come from a disable country, the costumer can’t register*.
- If the customer come from a enable country and disable state, the costumer can’t register*.

After the customer create an account:
- If the admin disables the country of customer, the customer can’t buy without change his address for one enabled country*.
- If admin disable the state of customer and keep country enabled, the customer can buy for the disabled state (we think the customer shouldn’t be allowed buy for the disabled state).

* Please check the attach pdf.

[When the admin disables one state.pdf](https://github.com/thirtybees/thirtybees/files/2831155/When.the.admin.disables.one.state.pdf)

**Comment by getdatakick** [comment]
Fix adds check also for zone active status.
