### ISSUE TITLE
States when we install TB

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#840]
When we install TB with country UK and go to Localization => States we have states from Argentina, Canada, Indonesia, Italy, Japan, Mexico, United Kingdom, United States.

We think it’s good idea if we have only states of United Kingdom (the country store).

**Comment by Dh42** [comment]
The reason that it installs the states that it does, is that those are the countries that paypal always requires states from.

**Comment by toplakd** [comment]
It's same for Thailand. Paypal requires states for it, so one can not place order if state is missing.

**Comment by Traumflug** [comment]
This doesn't appear to be a bug.
