### ISSUE TITLE
Module "Mail Alerts"

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#844]
When we fill “Tracking number” (on Orders => Orders =>select the order => Shipping => Tracking number), the TB send one email.

After that we disable the “customer notifications” => “Order edit” on module "Mail Alerts".

The problem it still keeps sending the emails after an order is edited.

This is an old bug from pretashop since 2013, but there is a solution, please check the follow link:
https://www.prestashop.com/forums/topic/255815-how-to-disable-notification-mail-sended-after-order-change-at-bo/

Please check the attached pdf.

[Module Mail Alerts.pdf](https://github.com/thirtybees/thirtybees/files/2858042/Module.Mail.Alerts.pdf)

**Comment by therampagerado** [comment]
Who would like to disable sending the tracking number? It's one of the more vital parts of the CMS which improves first time deliveries.

**Comment by Jorgemgm** [comment]
The issues aren’t disable sending "Tracking number" (note: the information about "Tracking number" it's possible when introduce {shipping_number} in email of "Shipped").

The issues are when TB didn't disable the email after we choose disable the “customer notifications” => “Order edit” on module "Mail Alerts".

With solving the bug TB can add (but not necessary) a new configuration option, and when we have order changes then TB ask us if we want send an email, and let manager decide whether to send email or not, like "would you like customer to be notified by email about this order has changed (its recommended to do this if you now have finished editing the order)?”.

Please check the follow link:
https://www.prestashop.com/forums/topic/255815-how-to-disable-notification-mail-sended-after-order-change-at-bo/
