### ISSUE TITLE
PlusMinus buttons in the cart fail sometimes

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#849]
See https://forum.thirtybees.com/topic/2632-bug-error-when-reducing-product-quantity-in-cart-sporadic/

> When some products are added to the cart and then the '-' button is clicked to reduce quantity of a product, a technical error pops up sporadically.

![](https://forum.thirtybees.com/uploads/monthly_2019_02/error-when-reducing-quantity-in-cart.jpg.e606c9feb1e962ed5a9467664ab9c320.jpg)

> It appears this happens when there is more than one product in the cart. Please see screenshot.

**Comment by NaturePinks** [comment]
I can confirm this is an ngnix setting and not a thirtybees bug. Thanks.
https://forum.thirtybees.com/topic/2632-solved-error-when-reducing-product-quantity-in-cart-sporadic/?do=findComment&comment=25728
