### ISSUE TITLE
Enabled or disabled the Orders Statuses

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#852]
Orders => Statuses

We think it’s a plus TB, if we can enable or disable the different “ORDER STATUSES” and “RETURN STATUSES" of “Orders”, instead of need delete and create again (this way doesn’t display on “UPDATE STATUS” on BO). 

Please check the attach pdf.

[Enable Statuses.pdf](https://github.com/thirtybees/thirtybees/files/2890501/Enable.Statuses.pdf)

**Comment by Traumflug** [comment]
There's a first commit in order to get this implemented: https://github.com/thirtybees/thirtybees/commit/7f4cfbdbde8266651551c017ae6a080b447ffa1f

Good work, but not exactly complete:

1. After applying this commit, all order statuses are disabled:

    ![grafik](https://user-images.githubusercontent.com/318581/54453981-b9b74280-4758-11e9-86f5-59114b99ccb2.png)

2. Clicking such a red cross results in nothing happening. Instead JavaScript Console reports:
    ```
    TypeError: data is null[Weitere Informationen] index.php:883:6
    
        <anonym> http://localhost/thirtybees/admin-dev/index.php?controller=AdminStatuses&token=6aeeac328be054a6da8b637cf9aae4b1:883 j4jQuery
    ```

3. When editing an order, checking _Status is active for orders_ and clicking _Save_, I get this:

    ![grafik](https://user-images.githubusercontent.com/318581/54454443-be302b00-4759-11e9-85bc-8a179ff1a7db.png)

4. An _active_ column for return statuses is missing:

    ![grafik](https://user-images.githubusercontent.com/318581/54454625-2f6fde00-475a-11e9-8b47-8e1833e28c78.png)

**Comment by ziyaindia** [comment]
Fixed all issues. Following are the change log

1 - /var/www/html/thirtybees/classes/order/OrderState.php - Add new database column 

2 - /var/www/html/thirtybees/install-dev/data/db_schema.sql - Add new database column in table tb_order_state

3 - /var/www/html/thirtybees/controllers/admin/AdminOrdersController.php - Check either order statues is enabled or not

4 - Database Changes - ALTER TABLE `tb_order_state` ADD `active` TINYINT(1) NOT NULL DEFAULT '1' AFTER `deleted`; 

5 - /var/www/html/thirtybees/install-dev/data/xml/order_state.xml - Add new field

Order Return Statuses

6 - Database Changess - ALTER TABLE `tb_order_return_state` ADD `active` TINYINT(1) NOT NULL DEFAULT '1' AFTER `color`; 

7 - /var/www/html/thirtybees/classes/order/OrderReturnState.php - Add new database column

8 - /var/www/html/thirtybees/install-dev/data/xml/order_return_state.xml - Add new field

9 - /var/www/html/thirtybees/controllers/admin/AdminStatusesController.php

10 - /var/www/html/thirtybees/admin-dev/themes/default/template/helpers/list/list_header.tpl

**Comment by Traumflug** [comment]
Should be solved with the commits listed here and just pushed to _1.0.x_. Thanks to @ziyaindia, who did most of the work.
