### ISSUE TITLE
PHP Deprecated:  Function create_function()

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/thirtybees#853]
When you have profiling switched on under PHP 7.2 you get the following warning:
PHP Deprecated:  Function create_function() is deprecated in /tools/profiling/Controller.php on line 363

**Comment by doclucas** [comment]
All create_function() code can be easily revised to something like this example:
`        $content = preg_replace_callback('#\{config\}([a-zA-Z0-9_-]*)\{/config\}#', create_function('$matches', 'return Configuration::get($matches[1]);'), $content);
        $content = preg_replace_callback('#\{link\}(.*)\{/link\}#', create_function('$matches', 'return Context::getContext()->link->getAdminLink($matches[1]);'), $content);
        $content = preg_replace_callback('#\{employee\}(.*)\{/employee\}#', create_function('$matches', 'return Context::getContext()->employee->$matches[1];'), $content);
        $content = preg_replace_callback('#\{language\}(.*)\{/language\}#', create_function('$matches', 'return Context::getContext()->language->$matches[1];'), $content);
        $content = preg_replace_callback('#\{country\}(.*)\{/country\}#', create_function('$matches', 'return Context::getContext()->country->$matches[1];'), $content);`

To:

`        $content = preg_replace_callback('#\{config\}([a-zA-Z0-9_-]*)\{/config\}#', function($matches) { return Configuration::get($matches[1]); }, $content);
        $content = preg_replace_callback('#\{link\}(.*)\{/link\}#', function($matches) { return Context::getContext()->link->getAdminLink($matches[1]); }, $content);
        $content = preg_replace_callback('#\{employee\}(.*)\{/employee\}#', function($matches) { return Context::getContext()->employee->$matches[1]; }, $content);
        $content = preg_replace_callback('#\{language\}(.*)\{/language\}#', function($matches) { return Context::getContext()->language->$matches[1]; }, $content);
        $content = preg_replace_callback('#\{country\}(.*)\{/country\}#', function($matches) { return Context::getContext()->country->$matches[1]; }, $content);`
