### ISSUE TITLE
Expand or change icon “Close all fieldsets” to “Expand all fieldsets”

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#854]
Localization => Translations => MODIFY TRANSLATIONS => Modify

The icon is “Close all fieldsets”, but they are closed. We click in “Close all fieldsets” and the icon change for “Expand all fieldsets” and we need click again, in “Expand all fieldsets” to expand.

This happen in “Front office translations”, “Back office translations”, “Installed modules translations” and “Email template translations”. 

The first impression it’s the icon must be “Expand all fieldsets” and not “Close all fieldsets”.

But, after check the “Field name translations” and “PDF translations” where fieldsets came expanded maybe the icon is ok and need expanded the fieldset.

[Close all fieldsets.pdf](https://github.com/thirtybees/thirtybees/files/2894988/Close.all.fieldsets.pdf)

**Comment by Traumflug** [comment]
This should be fixed with 434cb6ecd4c3a2666e27621770e46580361e1558. Thank you for reporting!
