### ISSUE TITLE
Obsolete table 'order_slip_detail_tax'

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#855]
The installer creates a table `order_slip_detail_tax`, which serves no purpose and is always empty. Tax breakdowns of order slips get calculated on the fly.

Not removed immediately, because there's currently no handle to remove it from existing installations.

**Comment by getdatakick** [comment]
The table should be populated with data. Invoice / Credit slips shouldn't use current tax value, because it can change frequently. Historical invoices should remain intact
