### ISSUE TITLE
Saving AdminPPreferences in multistore breaks ASM

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/thirtybees#877]
I am using 1.0.8. If you use multistore and asm at the same time. It's very risk to save AdminPPreferences Controller. It will set the column advanced_stock_management in ps_product and ps_product to 0. This is obviously a bug.

To make things more clear, I took a video: https://streamable.com/pt69k

I dont know, if there is a general problem with multistore saving, as I already reported this one: https://github.com/thirtybees/thirtybees/issues/792

**Comment by Traumflug** [comment]
Fix is available for testing in _Bleeding Edge_ -> _issue-877_ in Core Updater.

**Comment by Traumflug** [comment]
Thanks for testing. Glad to see it works for you as well.

If there's anything left, please don't hesitate to re-open this issue or open another one.
