### ISSUE TITLE
Admin panel login issue (Can't log in into admin panel)

### ISSUE THREAD

**Issue by Bulikus** [thirtybees/thirtybees#888]
I migrate from PrestaShop 1.6. The migration process was ok, and I was working for a day on a new system. Then I log out from the admin panel, and I can't log in. I cleared cache in the browser, tried different browsers, but nothing.
I switched on the debug mode, but unfortunately, it showed nothing. Only the developer mode in a browser showed me an error: 
POST https://a-stuff.com.ua/admin7532/ajax-tab.php?rand=1554073235248 500     VM599:1
P.S: Video of the loading process. https://youtu.be/Am9_U8M9TEk

**Comment by Traumflug** [comment]
A quick 500 response to an Ajax request typically means some error in PHP. With some luck, a file with the error message was created in `log/`. Another place to look up is the web server's error log. Where exactly this is (and whether it exists at all) depends largely on the hoster. On a plain Debian/Ubuntu it's `/var/log/apache2/error.log`.

Such an error is crucial, of course. If you find it yourself, please tell us what needed a change. If you can't find it and if you allow, I'd like to take a look myself tomorrow. I'd need FTP or shell access, then. My email is markus@thirtybees.com (for username/password).

**Comment by Bulikus** [comment]
Thank you Traumflug. In thirty bees log folder, there is a 20190401_exception.log file. And there is an error:  *ERROR* 	2019/04/01 - 04:04:48: Property Logger->message is empty at line 1027 in file classes/ObjectModel.php. I will send you my username and password.

**Comment by Traumflug** [comment]
Bad news: I couldn't trigger the problem with some arbitrary login.

Good news: while trying, I found error messages to be empty and fixed this. See 5fb6b4acd99b4f454d8cefc94bdd91038877de1b, which is also applied to your shop now.

Could you please try again? While class Logger should certainly be able to log an empty message without causing an exception, having error translations now might no longer trigger this problem.

If the problem persists, I'd also need a back office login (user/password, by email) of an account having this problem.

**Comment by Traumflug** [comment]
It also looks a bit like this site is running PHP 7.3, where thirty bees isn't entirely stable, yet. PHP 7.0 and 7.1 are currently the most stable PHP versions for thirty bees. PHP 7.2 works also fine with debug mode turned off.

**Comment by Bulikus** [comment]
Now it's ok. Thank's to datakick from thirty bees forum, and thank's to you. I changed the PHP version to 7.2. The problem with login is gone.  datakick modified core file /controllers/admin/AdminLoginController.php that's helped to fix the problem with login. 
Problem with translation. Should I delete the language to fix this or thank's to you problem is gone now?

**Comment by Traumflug** [comment]
Excellent.

Translations can stay where they are. Russian is actually one of the best translated languages.

**Comment by OXPAHHUK** [comment]
> datakick modified core file /controllers/admin/AdminLoginController.php that's helped to fix the problem with login.
Can you please paste here AdminLoginController.php file?
