### ISSUE TITLE
Regression: cart::getPackageList() returns wrong quantity information

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/thirtybees#896]
Commit 3578ad6c1d8be1dc3e0284ec78801c15ad2f16b9 cased some issues even though the comment in code claims to be for retrocompatibility with ps 1.2.

The problem I know about is with order confirmation email -- it shows current quantity on stock, instead of cart/ordered quantity.

<img width="500" alt="bug" src="https://user-images.githubusercontent.com/34651851/55619517-25f5f680-5799-11e9-8e5f-5bc142ee4348.png">

This **quantity** information is returned when method `$cart->getPackageList()` is called (and possibly many more cart methods). 

This is very public method used by many places in core and third party modules. It is therefore very possible that this change in semantics will break many more things.

I think we should revert this change, and possibly fix the order_confirmation email template to use `cart_quantity` instead of `quantity`

**Comment by Traumflug** [comment]
Well, apparently the comment lied and the solution is to revert this commit without the comment, right?

**Comment by Traumflug** [comment]
Reverted. Thanks for reporting the issue.
