### ISSUE TITLE
not critical exception in category view

### ISSUE THREAD

**Issue by Forforce** [thirtybees/ThirtyBees#9]
debug - true
profiling - true
frontend in any category
http://take.ms/NViB7

**Comment by firstred** [comment]
Thanks for the screenshot. It seems that somehow the temporary table cannot be made, which causes the problem. We'll have to investigate why MySQL doesn't accept the query, it seems.

**Comment by firstred** [comment]
Possible fix: https://github.com/thirtybees/ThirtyBees/pull/12
