### ISSUE TITLE
1.0.8 + latest 1.6 Warehouse theme - unable to save font styles with theme editor

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/thirtybees#911]
I've been running TB for quite some time and up until now I have never found out this issue. Even I think this shop was installed on 1.0.8 and of course the latest theme version.

When I want to use local fonts all URLs '-es get escaped and also the new rows get messed up.

In the field under where we specify font family the single brackets are also escaped.

I don't have this issue on PS 1.6.1.23 running next to this shop on the same hosting.

PHP 7.1
Litespeed server

![image](https://user-images.githubusercontent.com/11251370/56615207-4d671300-6623-11e9-86c5-a621c755661c.png)

**Comment by getdatakick** [comment]
It's very likely this is duplicate of issue #807.

@therampagerado do you have the same issues when you forward your shop to bleeding edge?

**Comment by therampagerado** [comment]
@getdatakick - thank you, I'll test today and check if this sorts out the issue.

This is very strange because I made numerous changes to this config page prior but I can't remember if I build the shop on 1.0.8 for sure (90% yes).

**Comment by therampagerado** [comment]
@getdatakick - finally found some time to test. Updated to edge and....

Yes, the escaping now works correctly so the FO is woring fine. But the formatting in the custom field where I'm pasting the code for my custom fonts is squashed again. Probably some sort of internal minification does it. Which is annoing because if someone wants to make changes it is a hassle.

**Comment by getdatakick** [comment]
Good. Is this minification a new problem, or did this happen before as well?

**Comment by therampagerado** [comment]
Nope, I haven't observed it before.

**Comment by therampagerado** [comment]
Just checked at 1.5 Edge as of February 2023 - the issue is not present.
