### ISSUE TITLE
Multistore: virtual url not working correctly

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/thirtybees#912]
Reported in this [forum thread](https://forum.thirtybees.com/topic/2877-multi-store-issue/)

>I have a problem with multi store functionality after update from Prestashop 1.6.1.23 to 30 Bees 1.0.8. 
Multi stores do not wotking now ((. Before update I has 5 multi-stores, each of them was have a url like domainname.com/shop1 , domainname.com/shop2 etc.
>
> But after migration (no server-side changes was made) no one of multistores are working (( Working only main shop that have not any name after "/" (just domainname.com/)
I tried to modulate this situation in clean instalation and on thirtybees demo-site (on "centre1" shop) - have same result (
>
> It is a big system bug or maybe I need some extra settings? 
Any ideas?

![img1](https://forum.thirtybees.com/uploads/monthly_2019_04/01.png.7e99a1589712ee1177591e6ed9254922.png)

![img2](https://forum.thirtybees.com/uploads/monthly_2019_04/02.png.19c21c74faf3aa78f2c687bc88af531e.png)

**Comment by Traumflug** [comment]
Possible fix see cdb6edfab1cd7633c52380594133d23114905f56

**Comment by getdatakick** [comment]
I can confirm that cdb6edfab1cd7633c52380594133d23114905f56 indeed fixes this issue. Logic behind the fix is solid, no need to keep this one open. Good job @Traumflug
