### ISSUE TITLE
Get rid of the SemVer dependency

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#916]
After SemVer (introduced with #149) turned out to be incompatible with 4 part version numbers (see #915), it's only remaining usage is comparing a module's thirty bees version requirement in `Module::checkCompliancy()`. Allowing slightly more fancy version ranges in one place doesn't justify a whole dependency, IMHO.

Suggested replacement: replace `$this->tb_versions_compliancy` in the module's main file with `$this->tb_min_version`, a simple version string.

No _tb_max_version_, because a module developer can't know when a module becomes incompatible before it actually happens. Looking at the usage of _tb_versions_compliancy_ in all the thirty bees modules, none of them defines an upper version number.

The replacement needs a proper deprecation period, of course.

**Comment by Traumflug** [comment]
As a first step into this direction, _validatemodule.sh_ enforces a `tb_min_version` property now and all the standard modules have this already.

**Comment by getdatakick** [comment]
Commit ddd70fa05ccfda6318c2be3370c14d6ac5228a3f removed the only known usage of bierbergenlars\SemVer library from thirtybees core. It's still possible that this library is used by some modules, though. So I haven't removed it from composer dependencies

**Comment by Traumflug** [comment]
Unless I'm mistaken, remaining part is dealing with field `compatibility` in _all.json_.

**Comment by getdatakick** [comment]
That's correct. But this is responsibility of `tbupdater` module which includes its own version of SemVer library

**Comment by Traumflug** [comment]
_tbupdater_ is deprecated. It still exists because nobody found time to move module installation/updating code back into core yet.
