### ISSUE TITLE
Issue after update to edge yesterday - price tab in Products->Product does not open.

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/thirtybees#917]
EDIT: strangely the text here was not saved... whatever..

Uncaught ReferenceError: displayPriceValue is not defined
    at calcPriceTI (price.js:135)
    at HTMLDocument.eval (eval at <anonymous> (jquery-1.11.0.min.js:2), <anonymous>:4:7)
    at j (jquery-1.11.0.min.js:2)
    at Object.add [as done] (jquery-1.11.0.min.js:2)
    at e.fn.init.n.fn.ready (jquery-1.11.0.min.js:2)
    at eval (eval at <anonymous> (jquery-1.11.0.min.js:2), <anonymous>:2:18)
    at eval (<anonymous>)
    at jquery-1.11.0.min.js:2
    at Function.globalEval (jquery-1.11.0.min.js:2)
    at e.fn.init.domManip (jquery-1.11.0.min.js:3)

**Comment by therampagerado** [comment]
Can somebody help me with this one. I can't work my shop that way and I have tons of products to add... :(

**Comment by Traumflug** [comment]
The obvious workaround is to use another browser until this issue is fixed.

**Comment by therampagerado** [comment]
But do you experience it too?

Thanks for the firefox hint, it works!

**Comment by Traumflug** [comment]
I have neither Edge nor Windows available, so debugging this one is going to be tricky anyways.

**Comment by therampagerado** [comment]
OK Thank you for all your work! Hopefully somebody can reproduce it...

**Comment by getdatakick** [comment]
This [line](https://github.com/thirtybees/thirtybees/blob/469a569f8c98660280e3921ae277fede7d9dedc1/js/admin.js#L1396) is probably the culprit

```
 let formatted;
```

`let` is es6 construct. While most of the [browsers](https://caniuse.com/#feat=let) already supports this, there are still some that don't. The simpliest solution is to change the line to
```
var formatted;
```

**Comment by Traumflug** [comment]
> `let` is es6 construct.

OMG, I thought this is introduced since like 15 years already. Looks like I have to make an audit for this keyword across all JavaScript files tomorrow. Used it quite a number of times.

**Comment by getdatakick** [comment]
We could maybe include [es-check](https://www.npmjs.com/package/es-check) or similar tool to `validate.sh`

**Comment by Traumflug** [comment]
Thought about such a solution, but with JS embedded in templates it might work not too well.

**Comment by getdatakick** [comment]
You are right, I forgot about the infamous javascript inlining.

Anyway, I went over core and fixed all occurrences of `let` statement in js and tpl files. 

There is still need to audit modules, though

**Comment by Traumflug** [comment]
Excellent. Me searched through modules as well and found issues in Core Updater, only.
