### ISSUE TITLE
PDF Prefix translations not saved correctly

### ISSUE THREAD

**Issue by Captain-FLAM** [thirtybees/thirtybees#921]
I don't have time to investigate ...

In controllers/admin :
- AdminSlipController
- AdminReturnController
- AdminInvoicesController
- AdminDeliverySlipController

The translatable fileds for PDF Prefix are always saved in English in database

**Comment by getdatakick** [comment]
I can't reproduce this issue on 1.0.x / 1.0.8 / 1.0.7. 

@Captain-FLAM could you please elaborate more on reprosteps?

**Comment by Captain-FLAM** [comment]
Very simple : If you have 2 languages (1=EN, 2=FR in my case), the 1st crunch the second on save ...

I had the same issue with the module "FreeGDPR", and I solved it but ...

It was in "function updateValue" of "classes/Configuration.php" the use of "&value" crunched in the "foreach", but I saw that you changed it by "updateValueRaw", and now with this new version, it's working !
