### ISSUE TITLE
URL doesn't respect language - MOVED FROM blockfacebook

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#923]
Originally opened in thirtybees/blockfacebook at https://github.com/thirtybees/blockfacebook/issues/1
**ISSUE ID:** 1
**REPOSITORY:** blockfacebook
**ISSUE TITLE:** URL doesn't respect language
**REPORT:**
See here: https://forum.thirtybees.com/topic/2708-block-facebook-hardcoded-english-language/

----
blockfacebook.js has hardcoded English language setting for Facebook block. I've hacked it by hand, but ideal would be fixing it, so it will work well with multilanguage sites. just need  to pass selected language iso code needed to create proper facebook js script link - any suggestions how it could be done?
``` javascript
js.src = "//connect.facebook.net/$ISO_CODE_HERE/sdk.js#xfbml=1&version=v3.2";
```

``` javascript
$(document).ready(function() {
	initfb(document, 'script', 'facebook-jssdk');
});

function initfb(d, s, id)
{
	var js, fjs = d.getElementsByTagName(s)[0];
	if (d.getElementById(id))
		return;
	js = d.createElement(s); js.id = id;
	js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=334341610034299";
	fjs.parentNode.insertBefore(js, fjs);
}
```

**Comment by pjrp** [comment]
There's more than this issue, or maybe i'm missing something?

Using Thirty Bees 1.1.0

- Uninstalled and deleted all modules related to facebook and social sharing. 
- Deleted all 'blockfacebook.js' files i could find in theme and installation folders.
- Cleared TB cache. Forced theme compilation.
- Cleared/disabled browser cache.
- Text search for 'connect.facebook.net' in all code, no results.
- Text & file search for 'blockfacebook.js' only got update logs from 1.0.8 and hits in cache\GitUpdateStorage.php

Still in head section:
`<script type="text/javascript" src="/modules/blockfacebook/blockfacebook.js"></script>`
This file is accessible and is loading.

What else can i try to get rid of this facebook module?
