### ISSUE TITLE
thirty base scans for language files outside its basedir 

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#930]
Copy of https://github.com/thirtybees/thirtybees/issues/362#issue-259060985

![langscanoutsidebasedir](https://user-images.githubusercontent.com/6775736/30630985-0778f9e4-9de3-11e7-8b9f-1b0d981ca15a.png)

**Comment by ziyaindia** [comment]
How can i replicate this issue?

**Comment by Traumflug** [comment]
Good question. As the original reporter is no longer with thirty bees we have to find out ourselfs.

To find out a bit more, I checked out the file from the date when the original issue was opened and compared to current code. It's now line 1141 in `classes/Language.php`, the one with `file_exists()`, in method `getFilesList()`.

However, even after browsing language related stuff a lot, I can't reproduce this. Let's close this issue, it'll undoubtly re-appear if it's still an actual issue.
