### ISSUE TITLE
Package satooshi/php-coveralls is abandoned

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#932]
Running `composer update` results in this:
> Package satooshi/php-coveralls is abandoned, you should avoid using it. Use php-coveralls/php-coveralls instead.

**Comment by NemoPS** [comment]
Updated https://github.com/thirtybees/thirtybees/commit/cd56383e10de889911e6b90b56d65978c44300be

**Comment by Traumflug** [comment]
Closing as per last comment.
