### ISSUE TITLE
Unintentional configuration page - MOVED FROM coreupdater

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#937]
Originally opened in thirtybees/coreupdater at https://github.com/thirtybees/coreupdater/issues/4
**ISSUE ID:** 4
**REPOSITORY:** coreupdater
**ISSUE TITLE:** Unintentional configuration page
**REPORT:**
Intended text on the configuration page doesn't display. Looks like this is a multishop environment.

**Comment by yaniv14** [comment]
I think that configuration page is useless in this module and module should redirect to new AdminCoreUpdater controller after successful installation.

**Comment by Traumflug** [comment]
The configuration page also does some environment tests, so it can't go away without changing the installation strategy.

**Comment by Traumflug** [comment]
Original closed.

**Comment by Traumflug** [comment]
Original reopened.

**Comment by Traumflug** [comment]
Original closed again :-)
