### ISSUE TITLE
Stripe - “this options”

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#939]
On Stripe module, “API SETTINGS”, it’s good replace “this options” for “this option”.

![image](https://user-images.githubusercontent.com/38436949/58270360-7e04ae80-7d81-11e9-9b64-21fb10a2fdd5.png)

**Comment by ziyaindia** [comment]
It's a small fix in following file:
/thirtybees-1/modules/stripe
We have to change “this options” for “this option” on line 1536.
I am unable to commit the code because this module is not available in my repository.
Please aware me how to fetch this module in my repository?

**Comment by Traumflug** [comment]
Modules each have their own repository: https://github.com/thirtybees/stripe
