### ISSUE TITLE
Stripe - Payment methods

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#940]
On Stripe module the Payment methods are iDEAL, Bancontact, Giropay, Sofort, P24, Alipay, but Stripe have more Payment methods like EPS, SEPA Direct Debit, WeChat Pay.

![image](https://user-images.githubusercontent.com/38436949/58349090-44ec3d00-7e5a-11e9-8932-7e0b30eb5a44.png)

https://support.stripe.com/questions/pricing-of-payment-methods-in-the-united-kingdom

**Comment by therampagerado** [comment]
All quoted methods are added - https://github.com/thirtybees/stripe/commits/master/
