### ISSUE TITLE
Stripe - Credit card (last 4 digits)

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#942]
For “Stripe Checkout”. 
![image](https://user-images.githubusercontent.com/38436949/58385710-73018680-7fec-11e9-82ac-5536c0ab6e6a.png)

On Backoffice Orders => Orders => Stripe folder display the Credit card (last 4 digits)

But not for “Stripe Credit Card Form”.
![image](https://user-images.githubusercontent.com/38436949/58385714-87de1a00-7fec-11e9-8c24-d984494ecb36.png)

Like this case:
![image](https://user-images.githubusercontent.com/38436949/58385732-d25f9680-7fec-11e9-9d4f-e6aa5a963ae5.png)

Note: I only did this in testing mode.

**Comment by getdatakick** [comment]
Should be fixed in stripe 1.7.0
