### ISSUE TITLE
Stripe - Debit Card

### ISSUE THREAD

**Issue by Jorgemgm** [thirtybees/thirtybees#943]
When we use test card number 4000058260000005, https://stripe.com/docs/testing#testing-charges , it’s a Visa debit card.

![image](https://user-images.githubusercontent.com/38436949/58437974-4caf1a00-80c4-11e9-868b-2f6af5f7a9c6.png)

but on Order => Order display Credit Card (but it’s Debit Card).
![image](https://user-images.githubusercontent.com/38436949/58437984-5c2e6300-80c4-11e9-88c3-81a7d1af50f4.png)

Note: We only did this in testing mode.

**Comment by Dh42** [comment]
Its because the charge method is actually credit not debit. To do a debit charge you need to enter the pin for the card. Its a complicated system, but the actually method is card not present credit that is being charged.

**Comment by Jorgemgm** [comment]
Ok.
