### ISSUE TITLE
What happened to the website's forums?

### ISSUE THREAD

**Issue by techjp** [thirtybees/thirtybees#967]
Apologies for posting this as an issue but what happened to the website's forums? https://forum.thirtybees.com/ just returns "aaa" now. @Traumflug, @Dh42, hope it's nothing too serious.

**Comment by Dh42** [comment]
This place works. Sorry about that. Our forum needs an update and is normally dead this time of night. I was testing out the update to see what is compatible. I ran into a couple issues and rolled it back. Its online and working now.

**Comment by techjp** [comment]
Thanks @Dh42. Being in on the other side of the world means I sometimes hit service outages like that.

Thanks for all your hard work on the project.
