### ISSUE TITLE
Payment methods not available

### ISSUE THREAD

**Issue by Mirandafdfd** [thirtybees/thirtybees#968]
My sites payment modules are not working for some reason. The Paypal button only comes up on the 1st page of the check out, not on the payment page, and the Stripe module isn't showing up at all. 
![Screen Shot 2019-06-12 at 7 53 12 AM](https://user-images.githubusercontent.com/51746926/59349294-4e452880-8ce7-11e9-86b9-46d571d09583.png)
![Screen Shot 2019-06-12 at 7 53 39 AM](https://user-images.githubusercontent.com/51746926/59349295-4e452880-8ce7-11e9-9596-27440f55ac7b.png)

**Comment by therampagerado** [comment]
Do you have them enabled for the selected currency and the customer address?

**Comment by Dh42** [comment]
Also, when you go to Modules -> Payment at the very bottom the page do you have them selected for the carrirs too, https://i.imgur.com/g22BPID.png

**Comment by Traumflug** [comment]
Silent with open questions for over a month, assuming this to be solved.

If not, please don't hesitate to re-open this issue.
