### ISSUE TITLE
Carrier free shipping option disables zone checkboxes

### ISSUE THREAD

**Issue by HeinCorbet** [thirtybees/thirtybees#984]
The 'free shipping' option disables the checkboxes for zones. On saving the carrier the checkboxes are not send to the server. The carrier will not show up anymore in the back-office manual order creation form as available carrier, because no zone is defined for this carrier. On re-opening the carrier all zone checkboxes will show as deselected.
The issues caused by the function hideFees in the js/admin/carrier_wizard.js file.

**Comment by Traumflug** [comment]
This "Free shipping" switch is planned to go away anyways, see #947.

The obvious workaround is to not use this switch. Setting carrier fees to zero should give the same results.

**Comment by HeinCorbet** [comment]
That might be the case, but in the meantime while it is still there, it should not be broken functionality. 
See what you want to do with it. I think it will prevent some users from searching why it is not working.

**Comment by Traumflug** [comment]
Thanks for the pull request, works just fine. Nevertheless I couldn't resist to simplify this with another commit, cde3145fb92ba89d681467a7857ec5f1708be16d.

This should solve the issue, please don't hesitate to re-open this issue in case it doesn't.
