### ISSUE TITLE
Personalize the prices based in sizes

### ISSUE THREAD

**Issue by mauroagr** [thirtybees/thirtybees#992]
Dear,
I will make a personalized products, that the customers can select some parameters (size, material, color, etc), and then calculate the price. But this price are not related to an product specific, but i will only change the price and add some parameters to the product and close the order.
One idea is use a voucher to increase the price, but the voucher work only to reduce the price, not the increasing.
Have some ideia, or module that i can add it?
Thanks

**Comment by Traumflug** [comment]
Sounds much like a description of Combinations. There one can provide parameters and define a price impact for each.

**Comment by mauroagr** [comment]
The problem is that i can't define all combinations....example:
Order 1: 10.2cm x 11cm
Order 2: 10.1.cm x 11cm, the sizes is similar, but the prices can increase a little.
The combination is not a solution to my problem.
I was checking if i can change in ps_cart the product price, but not...they only finalize when validation the order.
