### ISSUE TITLE
Error in CMS category pagination

### ISSUE THREAD

**Issue by Rubben1985** [thirtybees/thirtybees#993]
Hi,

There is an error when trying to access any cms listing page inside of a CMS category.

Entering a CMS category.: click on page 2 or 3 for example. Instead of going to the correct page, it goes back to the CMS home page.

I recorded a video:
https://www.loom.com/share/832353c193b647de9c5e0b94e157ed02

It seems the formed URL is wrong because introducing manually the parameters &submitFiltercms=2#cms at the end of URL works to see page 2 of the cms category

**Comment by ksimunovic** [comment]
@Rubben1985 I got the error you described and recorded and I think I found out why is this happening. In the commit is a simple fix which pagination available again and I was wondering if you could please test it and report back if it's working now.

What I noticed is that in the whole request (GET/POST) the id_category_cms is missing, therefore it never reaches controllers which makes category id variable always empty, hence the main categories screen on pagination.
To fix this I added the output of category in the template file as hidden input and then also I added processing of this hidden field to append category id in the URL, much like you described using it.

**Comment by Traumflug** [comment]
Thanks for looking into this.

@ksimunovic, don't bother to make a pull request, a link to a commit is entirely sufficient.

**Comment by Traumflug** [comment]
Here's the issue branch with this commit applied (and whitespace nitpicked) https://github.com/thirtybees/thirtybees/commits/issue-993

**Comment by Rubben1985** [comment]
thanks @ksimunovic . For me it works!!

**Comment by Rubben1985** [comment]
sorry, new in Github. Should I mark it as solved? Is not me but an admin?

**Comment by Traumflug** [comment]
It's not entirely solved yet, as it's not yet on _1.1.x_ :-)

I wonder a bit how PS could get away with something requiring a change in such a fundamental place. But studying this even more is probably a waste of time, so I'll simply move it to the development branch (and then close this issue). Thanks for fixing, @ksimunovic, thanks for testing, @Rubben1985!

**Comment by Traumflug** [comment]
Done: 844f9ec4d028d385c90f192c6b14a020165d54b6
