### ISSUE TITLE
Shop objects don't get stored in an all shops context

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#997]
A few snippets from a developer chat:

![image](https://user-images.githubusercontent.com/318581/61555794-7d765480-aa60-11e9-8c77-b92fadaeabcd.png)
(it should also save to table _ps_product_shop_)

![image](https://user-images.githubusercontent.com/318581/61555919-c29a8680-aa60-11e9-9942-17c74f37f70e.png)

![image](https://user-images.githubusercontent.com/318581/61555653-296b7000-aa60-11e9-8d0e-c9075d65bf60.png)

Key is to use multishop and to be in an all shops context. The last snipped talks about code in `ObjectModel->update()`.

**Comment by getdatakick** [comment]
commit 905af0d47e67feb27b7ebdc279eb2f8d8d198c1c is an attempt to fix this issue.

**Comment by getdatakick** [comment]
closed by fda6560a074a7a78c83f1eb9295c0c9503fa477f
