### ISSUE TITLE
Module installation chokes on Bleeding Edge

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/thirtybees#998]
Module installation does a version comparison before installing a module. This apparently doesn't work in Bleeding Edge versions. See

https://forum.thirtybees.com/topic/3311-tb-108-10x-and-tb-vat-exemption-module-v231

> In Order to use the VAT Exemption Module do we have to roll back from 1.0.8 Bleeding Edge to TB 1.0.8? 

>  That's probably a Yes.
>
> Changing _TB_VERSION_ in config/settings.inc.php should be sufficient. It can get restored after the installation. 

> Thank you @Traumflug, Changing the TB_Version worked.

This should work without editing _settings.inc.php_, of course. Probably a matter of the algorithm used for version comparison.

**Comment by getdatakick** [comment]
This is related to #916 - SemVer doesn't properly parse version `1.0.8-1.0.x`. 
```php
if (isset($this->tb_versions_compliancy) && $this->tb_versions_compliancy) {
    $range = new Expression($this->tb_versions_compliancy);
    if (! $range->satisfiedBy(new Version(_TB_VERSION_))) {
        return false;
    }
}
```
